// Steema.TeeChart.VCL.xxx packages.
// Common assembly attributes

[assembly: AssemblyTitle('TeeChart Pro')]
[assembly: AssemblyDescription('Charting Controls by David Berneda')]
[assembly: AssemblyConfiguration('TeeChart for VCL.NET')]
[assembly: AssemblyCompany('Steema Software')]
[assembly: AssemblyProduct('TeeChart')]
[assembly: AssemblyCopyright('2003-2004 by Steema Software. All Rights Reserved.')]
[assembly: AssemblyTrademark('')]
[assembly: AssemblyCulture('')]
[assembly: AssemblyVersion('7.0.*')]
[assembly: AssemblyDelaySign(false)]

{$IFDEF TEEKEYS}
[assembly: AssemblyKeyFile('Keys\\TeeChart.snk')]
{$ENDIF}

[assembly: AssemblyKeyName('')]

