unit TeeChinese;
{$I TeeDefs.inc}

interface

Uses Classes;

Var TeeChineseLanguage:TStringList=nil;

Procedure TeeSetChinese;
Procedure TeeCreateChinese;

implementation

Uses SysUtils, TeeTranslate, TeeConst, TeeProCo {$IFNDEF D5},TeCanvas{$ENDIF};

Procedure TeeChineseConstants;
begin
  { TeeConst }
  TeeMsg_Copyright          :='(C) 1995-2004 by David Berneda';
  TeeMsg_LegendFirstValue   :='²Ä¤@­Ó¹Ï¨Ò­È¥²¶·¤j©ó 0';
  TeeMsg_LegendColorWidth   :='¹Ï¨ÒªºÃC¦â¼e«×¥²¶·¤j©ó 0%';
  TeeMsg_SeriesSetDataSource:='¨S¦³¥D¹Ïªí¨Ó½T»{¸ê®Æ¨Ó·½';
  TeeMsg_SeriesInvDataSource:='¤£¥¿½Tªº¸ê®Æ¨Ó·½: %s';
  TeeMsg_FillSample         :='FillSampleValues ªº NumValues ¥²¶·¤j©ó 0';
  TeeMsg_AxisLogDateTime    :='¤é´Á®É¶¡ªº¶b¤£¯à¬O¹ï¼Æ';
  TeeMsg_AxisLogNotPositive :='¹ï¼Æ¶bªº³Ì¤j³Ì¤p­È¥²¶·¤j©ó©Îµ¥©ó 0';
  TeeMsg_AxisLabelSep       :='¼ÐÅÒªº¶¡¹j¦Ê¤À¤ñ¥²¶·¤j©ó 0';
  TeeMsg_AxisIncrementNeg   :='¶bªº»¼¼W­È¥²¶·¤j©ó©Îµ¥©ó 0';
  TeeMsg_AxisMinMax         :='¶bªº³Ì¤p­È¥²¶·¤p©ó©Îµ¥©ó³Ì¤j­È';
  TeeMsg_AxisMaxMin         :='¶bªº³Ì¤j­È¥²¶·¤j©ó©Îµ¥©ó³Ì¤p­È';
  TeeMsg_AxisLogBase        :='¶bªº¹ï¼Æ°ò¼Æ¥²¶·¤j©ó©Îµ¥©ó 2';
  TeeMsg_MaxPointsPerPage   :='¨C­¶ªºÁ`¼ÐÂI¼Æ¥²¶·¤j©ó©Îµ¥©ó 0';
  TeeMsg_3dPercent          :='3D ®ÄªGªº¦Ê¤À¤ñ¥²¶·¦ì©ó %d ¨ì %d ¤§¶¡';
  TeeMsg_CircularSeries     :='°é§Îªº§Ç¦C¤£¥i¦³´`Àô¬ÛÃö©Ê';
  TeeMsg_WarningHiColor     :='»Ý­n 16k ©Î¥H¤Wªº¦â±m¨Ó±o¨ì¨}¦nªº®ÄªG';

  TeeMsg_DefaultPercentOf   :='%s ¤§ %s';
  TeeMsg_DefaultPercentOf2  :='%s'+#13+'¤§ %s';
  TeeMsg_DefPercentFormat   :='##0.## %';
  TeeMsg_DefValueFormat     :='#,##0.###';
  TeeMsg_DefLogValueFormat  :='#.0 "x10" E+0';
  TeeMsg_AxisTitle          :='¶bªº¼ÐÃD';
  TeeMsg_AxisLabels         :='¶bªº¼ÐÅÒ';
  TeeMsg_RefreshInterval    :='§ó·s®É¶¡¥²¶·¦ì©ó 0 ¨ì 60 ¤§¶¡';
  TeeMsg_SeriesParentNoSelf :='Series.ParentChart ¤£¬O¦Û¤v!';
  TeeMsg_GalleryLine        :='½u±ø¹Ï';
  TeeMsg_GalleryPoint       :='¼ÐÂI';
  TeeMsg_GalleryArea        :='­±¿n¹Ï';
  TeeMsg_GalleryBar         :='´Î§Î¹Ï';
  TeeMsg_GalleryHorizBar    :='¾î¦V´Î§Î¹Ï';
  TeeMsg_Stack              :='°ïúê¹Ï';
  TeeMsg_GalleryPie         :='¹Ï§Î¹Ï';
  TeeMsg_GalleryCircled     :='¶ê°é';
  TeeMsg_GalleryFastLine    :='§Ö³t½u±ø¹Ï';
  TeeMsg_GalleryHorizLine   :='¥­¦æ½u±ø¹Ï';

  TeeMsg_PieSample1         :='¨T¨®';
  TeeMsg_PieSample2         :='¹q¸Ü';
  TeeMsg_PieSample3         :='®à¤l';
  TeeMsg_PieSample4         :='Åã¥Ü¾¹';
  TeeMsg_PieSample5         :='Âi¿O';
  TeeMsg_PieSample6         :='Áä½L';
  TeeMsg_PieSample7         :='¸}½ñ¨®';
  TeeMsg_PieSample8         :='´È¤l';

  TeeMsg_GalleryLogoFont    :='·s²Ó©úÅé';
  TeeMsg_Editing            :='½s¿è %s';

  TeeMsg_GalleryStandard    :='¼Ð·Ç';
  TeeMsg_GalleryExtended    :='©µ¦ù';
  TeeMsg_GalleryFunctions   :='¨ç¼Æ';

  TeeMsg_EditChart          :='½s¿è¹Ïªí(&D)...';
  TeeMsg_PrintPreview       :='¹wÄý¦C¦L(&P)...';
  TeeMsg_ExportChart        :='¶×¥X¹Ïªí(&X)...';
  TeeMsg_CustomAxes         :='¦Û©w¶b...';

  TeeMsg_InvalidEditorClass :='%s: ¤£¥¿½Tªº½s¿è¾¹ª«¥ó: %s';
  TeeMsg_MissingEditorClass :='%s: ¨S¦³½s¿è¹ï¸Üµøµ¡';

  TeeMsg_GalleryArrow       :='½bÀY';

  TeeMsg_ExpFinish          :='§¹¦¨(&F)';
  TeeMsg_ExpNext            :='¤U¤@¨B(&N) >';

  TeeMsg_GalleryGantt       :='¶i«×¹Ï(¥Ì¯S)';

  TeeMsg_GanttSample1       :='³]­p';
  TeeMsg_GanttSample2       :='»s§@¼Ë«~';
  TeeMsg_GanttSample3       :='¶}µo';
  TeeMsg_GanttSample4       :='¾P°â';
  TeeMsg_GanttSample5       :='¶}µoÉ]³õ';
  TeeMsg_GanttSample6       :='´ú¸Õ';
  TeeMsg_GanttSample7       :='¥Í²£';
  TeeMsg_GanttSample8       :='°£¿ù';
  TeeMsg_GanttSample9       :='·sª©¥»';
  TeeMsg_GanttSample10      :='»È¦æªA°È';

  TeeMsg_ChangeSeriesTitle  :='ÅÜ§ó§Ç¦Cªº¼ÐÃD';
  TeeMsg_NewSeriesTitle     :='·sªº§Ç¦C¼ÐÃD:';
  TeeMsg_DateTime           :='¤é´Á®É¶¡';
  TeeMsg_TopAxis            :='¤W¶b';
  TeeMsg_BottomAxis         :='¤U¶b';
  TeeMsg_LeftAxis           :='¥ª¶b';
  TeeMsg_RightAxis          :='¥k¶b';

  TeeMsg_SureToDelete       :='²¾°£ %s ?';
  TeeMsg_DateTimeFormat     :='¤é´Á®É¶¡®æ¦¡(&M):';
  TeeMsg_Default            :='¹w³]';
  TeeMsg_ValuesFormat       :='¼Æ­È®æ¦¡(&M):';
  TeeMsg_Maximum            :='³Ì¤j';
  TeeMsg_Minimum            :='³Ì¤p';
  TeeMsg_DesiredIncrement   :='»Ý¨Dªº %s »¼¼W';

  TeeMsg_IncorrectMaxMinValue:='¿ù»~¼Æ­È¡C­ì¦]¡G%s';
  TeeMsg_EnterDateTime      :='¿é¤J [Á`¤Ñ¼Æ] '+TeeMsg_HHNNSS;

  TeeMsg_SureToApply        :='®M¥ÎÅÜ§ó?';
  TeeMsg_SelectedSeries     :='(¤w¿ïªº§Ç¦C)';
  TeeMsg_RefreshData        :='§ó·s¸ê®Æ(&R)';

  TeeMsg_DefaultFontSize    :={$IFDEF LINUX}'10'{$ELSE}'8'{$ENDIF};
  TeeMsg_FunctionAdd        :='¥[';
  TeeMsg_FunctionSubtract   :='´î';
  TeeMsg_FunctionMultiply   :='­¼';
  TeeMsg_FunctionDivide     :='°£';
  TeeMsg_FunctionHigh       :='³Ì°ª­È';
  TeeMsg_FunctionLow        :='³Ì§C­È';
  TeeMsg_FunctionAverage    :='¥­§¡';

  TeeMsg_GalleryShape       :='§Îª¬¹Ï';
  TeeMsg_GalleryBubble      :='ªwªw¹Ï';
  TeeMsg_FunctionNone       :='½Æ»s';

  TeeMsg_None               :='(µL)';

  TeeMsg_PrivateDeclarations:='{ Private «Å§i }';
  TeeMsg_PublicDeclarations :='{ Public «Å§i }';

  TeeMsg_DefaultFontName    :=TeeMsg_DefaultEngFontName;

  TeeMsg_CheckPointerSize   :='«ü¼Ð¤j¤p¥²¶·¤j©ó¹s';
  TeeMsg_About              :='¦³Ãö TeeChart(&U)...';

  TeeMsg_DataSet            :='¸ê®Æ²Õ';
  TeeMsg_AskDataSet         :='¸ê®Æ²Õ(&D):';

  TeeMsg_SingleRecord       :='³æµ§¸ê®Æ';
  TeeMsg_AskDataSource      :='¸ê®Æ¨Ó·½(&D):';

  TeeMsg_Summary            :='ºK­n';

  TeeMsg_FunctionPeriod     :='¨ç¼Æªº©P´Á­È¥²¶·¤j©ó©Îµ¥©ó¹s';

  TeeMsg_ClearImage         :='²M°£(&r)';
  TeeMsg_BrowseImage        :='ÂsÄý(&R)...';

  TeeMsg_WizardSureToClose  :='½T©w­nÃö³¬ TeeChart ºëÆF¡H';
  TeeMsg_FieldNotFound      :='Äæ¦ì %s ¤£¦s¦b';

  TeeMsg_DepthAxis          :='²`«×¶b';
  TeeMsg_PieOther           :='¨ä¥L';
  TeeMsg_ShapeGallery1      :='abc';
  TeeMsg_ShapeGallery2      :='123';
  TeeMsg_ValuesX            :='X';
  TeeMsg_ValuesY            :='Y';
  TeeMsg_ValuesPie          :='»æª¬';
  TeeMsg_ValuesBar          :='ªø±ø';
  TeeMsg_ValuesAngle        :='¨¤«×';
  TeeMsg_ValuesGanttStart   :='¶}©l';
  TeeMsg_ValuesGanttEnd     :='µ²§ô';
  TeeMsg_ValuesGanttNextTask:='¤U­Ó¤u§@';
  TeeMsg_ValuesBubbleRadius :='¥b®|';
  TeeMsg_ValuesArrowEndX    :='µ²§ôX';
  TeeMsg_ValuesArrowEndY    :='µ²§ôY';
  TeeMsg_Legend             :='¹Ï¨Ò';
  TeeMsg_Title              :='¼ÐÃD';
  TeeMsg_Foot               :='¼Ð§À';
  TeeMsg_Period		    :='©P´Á';
  TeeMsg_PeriodRange        :='©P´Áªº½d³ò';
  TeeMsg_CalcPeriod         :='­pºâ %s ©ó¨C­Ó:';
  TeeMsg_SmallDotsPen       :='¤pÂI';

  TeeMsg_InvalidTeeFile     :='*.'+TeeMsg_TeeExtension+' ÀÉ®×ªº¹Ïªí¤£¥¿½T';
  TeeMsg_WrongTeeFileFormat :='*.'+TeeMsg_TeeExtension+' ÀÉ®×®æ¦¡¿ù»~';
  TeeMsg_EmptyTeeFile       :='ªÅ¥Õªº *.'+TeeMsg_TeeExtension+' ÀÉ®×';  { 5.01 }

  {$IFDEF D5}
  TeeMsg_ChartAxesCategoryName   :='¹Ïªí¶b';
  TeeMsg_ChartAxesCategoryDesc   :='¹Ïªí¶bªºÄÝ©Ê»P¨Æ¥ó';
  TeeMsg_ChartWallsCategoryName  :='¹Ïªí¾ÀªO';
  TeeMsg_ChartWallsCategoryDesc  :='¹Ïªí¾ÀªOªºÄÝ©Ê»P¨Æ¥ó';
  TeeMsg_ChartTitlesCategoryName :='¹Ïªí¼ÐÃD';
  TeeMsg_ChartTitlesCategoryDesc :='¹Ïªí¼ÐÃDªºÄÝ©Ê»P¨Æ¥ó';
  TeeMsg_Chart3DCategoryName     :='3D ¹Ïªí';
  TeeMsg_Chart3DCategoryDesc     :='3D ¹ÏªíªºÄÝ©Ê»P¨Æ¥ó';
  {$ENDIF}

  TeeMsg_CustomAxesEditor       :='¦Û©w ';
  TeeMsg_Series                 :='§Ç¦C';
  TeeMsg_SeriesList             :='§Ç¦C...';

  TeeMsg_PageOfPages            :='²Ä %d­¶,¦@ %d­¶';
  TeeMsg_FileSize               :='%d ­Ó¦ì¤¸²Õ';

  TeeMsg_First  :='³Ìªì';
  TeeMsg_Prior  :='¤§«e';
  TeeMsg_Next   :='¤§«á';
  TeeMsg_Last   :='³Ì«á';
  TeeMsg_Insert :='´¡¤J';
  TeeMsg_Delete :='²¾°£';
  TeeMsg_Edit   :='½s¿è';
  TeeMsg_Post   :='¶Ç±H';
  TeeMsg_Cancel :='¨ú®ø';

  TeeMsg_All    :='(¥þ³¡)';
  TeeMsg_Index  :='¯Á¤Þ';
  TeeMsg_Text   :='¤å¦r';

  TeeMsg_AsBMP        :='ÂI°}¹Ï(&B)';
  TeeMsg_BMPFilter    :='ÂI°}¹ÏÀÉ (*.bmp)|*.bmp';
  TeeMsg_AsEMF        :='&Metafile';
  TeeMsg_EMFFilter    :='Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  TeeMsg_ExportPanelNotSet :='¶×¥X®æ¦¡¤¤¥¼¦³³]©w­±ªOÄÝ©Ê';

  TeeMsg_Normal    :='¥¿±`';
  TeeMsg_NoBorder  :='µLÃä½t';
  TeeMsg_Dotted    :='ÂI½u';
  TeeMsg_Colors    :='ÃC¦â';
  TeeMsg_Filled    :='¶ñº¡';
  TeeMsg_Marks     :='¼Ð»x';
  TeeMsg_Stairs    :='¶¥±è';
  TeeMsg_Points    :='¼ÐÂI';
  TeeMsg_Height    :='°ª«×';
  TeeMsg_Hollow    :='ªÅ¤ß';
  TeeMsg_Point2D   :='2D ¼ÐÂI';
  TeeMsg_Triangle  :='¤T¨¤§Î';
  TeeMsg_Star      :='¬P§Î';
  TeeMsg_Circle    :='¶ê§Î';
  TeeMsg_DownTri   :='¤Ï¤T¨¤§Î';
  TeeMsg_Cross     :='¤Q¦r§Î';
  TeeMsg_Diamond   :='µÙ§Î';
  TeeMsg_NoLines   :='µL½u±ø';
  TeeMsg_Stack100  :='°ï¿n 100%';
  TeeMsg_Pyramid   :='¨¤À@§Î';
  TeeMsg_Ellipse   :='¾ò¶ê§Î';
  TeeMsg_InvPyramid:='¤Ï¨¤À@§Î';
  TeeMsg_Sides     :='°¼Ãä';
  TeeMsg_SideAll   :='¥þ³¡°¼Ãä';
  TeeMsg_Patterns  :='¼Ë¦¡';
  TeeMsg_Exploded  :='Ãz¥X';
  TeeMsg_Shadow    :='³±¼v';
  TeeMsg_SemiPie   :='¥b»æª¬';
  TeeMsg_Rectangle :='¯x§Î';
  TeeMsg_VertLine  :='ª½½u';
  TeeMsg_HorizLine :='¾î½u';
  TeeMsg_Line      :='½u±ø';
  TeeMsg_Cube      :='¥ß¤èÅé';
  TeeMsg_DiagCross :='¤e§Î';

  TeeMsg_CanNotFindTempPath    :='µLªk§ä¨ì Temp ¸ê®Æ§¨';
  TeeMsg_CanNotCreateTempChart :='µLªk¶}·s¼È¦sÀÉ®×';
  TeeMsg_CanNotEmailChart      :='µLªk¥H¹q¤l¶l¥ó¶Ç°e TeeChart¡CMapi ¿ù»~¡G%d';

  TeeMsg_SeriesDelete :='²¾°£§Ç¦C¡GValueIndex %d ¶W¥X½d³ò (0 ¨ì %d).';

  { TeeProCo }
  TeeMsg_GalleryPolar       :='·¥½u¹Ï';
  TeeMsg_GalleryCandle      :='Àë¥ú¹Ï';
  TeeMsg_GalleryVolume      :='®e¶q¹Ï';
  TeeMsg_GallerySurface     :='ªí­±¹Ï';
  TeeMsg_GalleryContour     :='½ü¹ø¹Ï';
  TeeMsg_GalleryBezier      :='Bezier¹Ï';
  TeeMsg_GalleryPoint3D     :='3D¼ÐÂI¹Ï';
  TeeMsg_GalleryRadar       :='¹p¹F¹Ï';
  TeeMsg_GalleryDonut       :='Àôª¬¹Ï';
  TeeMsg_GalleryCursor      :='´å¼Ð¹Ï';
  TeeMsg_GalleryBar3D       :='3Dªø±ø¹Ï';
  TeeMsg_GalleryBigCandle   :='¤jÀë¥ú¹Ï';
  TeeMsg_GalleryLinePoint   :='¼ÐÂI½u¹Ï';
  TeeMsg_GalleryHistogram   :='ª½¤è¹Ï';
  TeeMsg_GalleryWaterFall   :='Âr¥¬¹Ï';
  TeeMsg_GalleryWindRose    :='­·¦V¹Ï';
  TeeMsg_GalleryClock       :='¥¢¶q¶ê¹Ï';
  TeeMsg_GalleryColorGrid   :='±m¦â®æ¹Ï';
  TeeMsg_GalleryBoxPlot     :='¼Ð²°¹Ï';
  TeeMsg_GalleryHorizBoxPlot:='¾î¼Ð²°¹Ï';
  TeeMsg_GalleryBarJoin     :='ªø±ø³s±µ¹Ï';
  TeeMsg_GallerySmith       :='¥v±K´µ¹Ï';
  TeeMsg_GalleryPyramid     :='¨¤À@¹Ï';
  TeeMsg_GalleryMap         :='¦a¹Ï';

  TeeMsg_PolyDegreeRange    :='Polynomial degree ¥²¶·¦ì©ó 1 ¨ì 20 ¤§¶¡';
  TeeMsg_AnswerVectorIndex   :='Answer Vector ¯Á¤Þ­È¥²¶·¦ì©ó 1 ¨ì %d ¤§¶¡';
  TeeMsg_FittingError        :='µLªk¹ï¦ì';
  TeeMsg_PeriodRange         :='©P´Á¥²¶·¤j©ó©Îµ¥©ó¹s';
  TeeMsg_ExpAverageWeight    :='ExpAverage Weight ¥²¶·¦ì©ó 0 ¨ì 1 ¤§¶¡';
  TeeMsg_GalleryErrorBar     :='»~®t±ø¹Ï';
  TeeMsg_GalleryError        :='»~®t¹Ï';
  TeeMsg_GalleryHighLow      :='°ª§C¹Ï';
  TeeMsg_FunctionMomentum    :='Momentum';
  TeeMsg_FunctionMomentumDiv :='MomentumÊ Div.';
  TeeMsg_FunctionExpAverage  :='Exp. Avg.';
  TeeMsg_FunctionMovingAverage:='Moving Avg.';
  TeeMsg_FunctionExpMovAve   :='Exp. Mov. Avg.';
  TeeMsg_FunctionRSI         :='R.S.I.';
  TeeMsg_FunctionCurveFitting:='Curve Fitting';
  TeeMsg_FunctionTrend       :='Trend';
  TeeMsg_FunctionExpTrend    :='Exp. Trend';
  TeeMsg_FunctionLogTrend    :='Log. Trend';
  TeeMsg_FunctionCumulative  :='Cumulative';
  TeeMsg_FunctionStdDeviation:='StdDeviation';
  TeeMsg_FunctionBollinger   :='Bollinger';
  TeeMsg_FunctionRMS         :='Root Mean Sq.';
  TeeMsg_FunctionMACD        :='MACD';
  TeeMsg_FunctionStochastic  :='Stochastic';
  TeeMsg_FunctionADX         :='ADX';

  TeeMsg_FunctionCount       :='¼Æ¶q';
  TeeMsg_LoadChart           :='¶}±Ò TeeChart...';
  TeeMsg_SaveChart           :='Àx¦s TeeChart...';
  TeeMsg_TeeFiles            :='TeeChart Pro ÀÉ®×';

  TeeMsg_GallerySamples      :='¨ä¥¦';
  TeeMsg_GalleryStats        :='²Î­p';

  TeeMsg_CannotFindEditor    :='µLªk§ä¨ì§Ç¦Cªº½s¿èµøµ¡: %s';


  TeeMsg_CannotLoadChartFromURL:='¿ù»~½X: %d ±q¥H¤Uºô§}¤U¸ü¹Ïªí: %s';
  TeeMsg_CannotLoadSeriesDataFromURL:='¿ù»~½X: %d ±q¥H¤Uºô§}¤U¸ü§Ç¦C¸ê®Æ: %s';

  TeeMsg_Test                :='´ú¸Õ...';

  TeeMsg_ValuesDate          :='¤é´Á';
  TeeMsg_ValuesOpen          :='¶}±Ò';
  TeeMsg_ValuesHigh          :='°ª';
  TeeMsg_ValuesLow           :='§C';
  TeeMsg_ValuesClose         :='Ãö³¬';
  TeeMsg_ValuesOffset        :='°¾²¾';
  TeeMsg_ValuesStdError      :='¼Ð·Ç»~®t';

  TeeMsg_Grid3D              :='3Dªí®æ';

  TeeMsg_LowBezierPoints     :='BezierªºÂI¼Æ¥²¶·¤j©ó 1';

  { TeeCommander component... }

  TeeCommanMsg_Normal   :='¥¿±`';
  TeeCommanMsg_Edit     :='½s¿è';
  TeeCommanMsg_Print    :='¦C¦L';
  TeeCommanMsg_Copy     :='½Æ»s';
  TeeCommanMsg_Save     :='Àx¦s';
  TeeCommanMsg_3D       :='3D';

  TeeCommanMsg_Rotating :='±ÛÂà: %d° ¤W¤É´T«×: %d°';
  TeeCommanMsg_Rotate   :='±ÛÂà';

  TeeCommanMsg_Moving   :='¤ô¥­°¾²¾: %d ««ª½°¾²¾: %d';
  TeeCommanMsg_Move     :='²¾°Ê';

  TeeCommanMsg_Zooming  :='ÁY©ñ: %d %%';
  TeeCommanMsg_Zoom     :='ÁY©ñ';

  TeeCommanMsg_Depthing :='3D: %d %%';
  TeeCommanMsg_Depth    :='²`«×';

  TeeCommanMsg_Chart    :='¹Ïªí';
  TeeCommanMsg_Panel    :='­±ªO';

  TeeCommanMsg_RotateLabel:='©ì¦² %s ¨Ó±ÛÂà';
  TeeCommanMsg_MoveLabel  :='©ì¦² %s ¨Ó²¾°Ê';
  TeeCommanMsg_ZoomLabel  :='©ì¦² %s ¨ÓÁY©ñ';
  TeeCommanMsg_DepthLabel :='©ì¦² %s ¨ÓÅÜ§ó 3D ¤j¤p';

  TeeCommanMsg_NormalLabel:='©ì¦²¥ªÁä¨ÓÁY©ñ, ¥kÁä¨ÓÂà°Ê';
  TeeCommanMsg_NormalPieLabel:='©ì¦²»æª¬¤ºªº¤ù¶ô¨Ó±N¥¦¤À¸Ñ';

  TeeCommanMsg_PieExploding :='¤ù¶ô: %d ¤À¸Ñ: %d %%';

  TeeMsg_TriSurfaceLess:='¼ÐÂI¼Æ¶q¥²¶·¤j©ó©Îµ¥©ó 4';
  TeeMsg_TriSurfaceAllColinear:='¥þ³¡¦@¦P©Ê¸ê®Æªº¼ÐÂI';
  TeeMsg_TriSurfaceSimilar:='¬ÛªñÂI - µLªk°õ¦æ';
  TeeMsg_GalleryTriSurface:='¤T¨¤­±';

  TeeMsg_AllSeries :='¥þ³¡§Ç¦C';
  TeeMsg_Edit      :='½s¿è';

  TeeMsg_GalleryFinancial    :='°]¸g';

  TeeMsg_CursorTool    :='«ü¼Ð';
  TeeMsg_DragMarksTool :='©ì¦²¼Ð»x';
  TeeMsg_AxisArrowTool :='¶b½bÀY';
  TeeMsg_DrawLineTool  :='µe½u';
  TeeMsg_NearestTool   :='³ÌªñÂI';
  TeeMsg_ColorBandTool :='ÃC¦â±a';
  TeeMsg_ColorLineTool :='ÃC¦â½u';
  TeeMsg_RotateTool    :='±ÛÂà';
  TeeMsg_ImageTool     :='¹Ï®×';
  TeeMsg_MarksTipTool  :='¼Ð»x»¡©ú';

  TeeMsg_CantDeleteAncestor  :='µLªk²¾°£­ì©lª«¥ó';

  TeeMsg_Load	         :='Åª¨ú...';
  TeeMsg_NoSeriesSelected:='¨Ã¥¼¿ï¨ú¥ô¦ó§Ç¦C';

  { TeeChart Actions }
  TeeMsg_CategoryChartActions  :='¹Ïªí';
  TeeMsg_CategorySeriesActions :='¹Ïªíªº§Ç¦C';

  TeeMsg_Action3D               :='&3D';
  TeeMsg_Action3DHint           :='¤Á´« 2D / 3D';
  TeeMsg_ActionSeriesActive     :='°_°Ê(&A)';
  TeeMsg_ActionSeriesActiveHint :='Åã¥Ü / ÁôÂÃ §Ç¦C';
  TeeMsg_ActionEditHint         :='½s¿è¹Ïªí';
  TeeMsg_ActionEdit             :='½s¿è(&E)...';
  TeeMsg_ActionCopyHint         :='½Æ»s¨ì°Å¶KÃ¯';
  TeeMsg_ActionCopy             :='½Æ»s(&C)';
  TeeMsg_ActionPrintHint        :='¹wÄý¦C¦L¹Ïªí';
  TeeMsg_ActionPrint            :='¦C¦L(&P)...';
  TeeMsg_ActionAxesHint         :='Åã¥Ü / ÁôÂÃ ¶b';
  TeeMsg_ActionAxes             :='¶b(&A)';
  TeeMsg_ActionGridsHint        :='Åã¥Ü / ÁôÂÃ ªí®æ';
  TeeMsg_ActionGrids            :='ªí®æ(&G)';
  TeeMsg_ActionLegendHint       :='Åã¥Ü / ÁôÂÃ ¹Ï¨Ò';
  TeeMsg_ActionLegend           :='¹Ï¨Ò(&L)';
  TeeMsg_ActionSeriesEditHint   :='½s¿è¹Ï¨Ò';
  TeeMsg_ActionSeriesMarksHint  :='Åã¥Ü / ÁôÂÃ §Ç¦C¼Ð»x';
  TeeMsg_ActionSeriesMarks      :='¼Ð»x(&M)';
  TeeMsg_ActionSaveHint         :='Àx¦s¹Ïªí';
  TeeMsg_ActionSave             :='Àx¦s(&S)...';

  TeeMsg_CandleBar              :='ªø±ø';
  TeeMsg_CandleNoOpen           :='µL¶}±Ò';
  TeeMsg_CandleNoClose          :='µLÃö³¬';
  TeeMsg_NoLines                :='µL½u±ø';
  TeeMsg_NoHigh                 :='µL°ª';
  TeeMsg_NoLow                  :='µL§C';
  TeeMsg_ColorRange             :='ÃC¦â½d³ò';
  TeeMsg_WireFrame              :='®Ø¬[½u';
  TeeMsg_DotFrame               :='®Ø¬[ÂI';
  TeeMsg_Positions              :='¦ì¸m';
  TeeMsg_NoGrid                 :='µLªí®æ';
  TeeMsg_NoPoint                :='µL¼ÐÂI';
  TeeMsg_NoLine                 :='µL½u±ø';
  TeeMsg_Labels                 :='¼ÐÅÒ';
  TeeMsg_NoCircle               :='µL¶ê°é';
  TeeMsg_Lines                  :='½u±ø';
  TeeMsg_Border                 :='Ãä½t';

  TeeMsg_SmithResistance      :='ªý¤O';
  TeeMsg_SmithReactance       :='¤O§Ü';
  
  TeeMsg_Column               :='Äæ¦ì';

  { 5.01 }
  TeeMsg_Separator            :='¤À¹j²Å¸¹';
  TeeMsg_FunnelSegment        :='¤ù¬q ';
  TeeMsg_FunnelSeries         :='º|¤æ¹Ï';
  TeeMsg_FunnelPercent        :='0.00 %';
  TeeMsg_FunnelExceed         :='¶W¥X­­ÃB';
  TeeMsg_FunnelWithin         :=' ¦b­­ÃB¤§¤º';
  TeeMsg_FunnelBelow          :=' ©Î§ó§C©ó­­ÃB';
  TeeMsg_CalendarSeries       :='¤ë¾ä';
  TeeMsg_DeltaPointSeries     :='¤T¸}¼ÐÂI(Delta)';
  TeeMsg_ImagePointSeries     :='¹Ï®×¼ÐÂI';
  TeeMsg_ImageBarSeries       :='¹Ï®×ªø±ø';
  TeeMsg_SeriesTextFieldZero  :='SeriesText: Field index ¥²¶·¤j¶· 0';

  {OCX 5.0.4}
  TeeMsg_ActiveXVersion      := 'ActiveX ª©¥» ' + AXVer;
  TeeMsg_ActiveXCannotImport := 'µLªk±q %s ¸ü¤JTeeChart ';
  TeeMsg_ActiveXVerbPrint    := '¹wÄý¦C¦L(&P)...';
  TeeMsg_ActiveXVerbExport   := '¶×¥X(&x)...';
  TeeMsg_ActiveXVerbImport   := '¶×¤J(&I)...';
  TeeMsg_ActiveXVerbHelp     := '»¡©ú(&H)...';
  TeeMsg_ActiveXVerbAbout    := 'Ãö©ó TeeChart(&A) ...';
  TeeMsg_ActiveXError        := 'TeeChart: ¿ù»~¥N½X: %d ¤U¸ü: %s';
//To do-->
  TeeMsg_DatasourceError     := 'TeeChart DataSource is not a Series or RecordSet';
  TeeMsg_SeriesTextSrcError  := 'Invalid Series type';
  TeeMsg_AxisTextSrcError    := 'Invalid Axis type';
  TeeMsg_DelSeriesDatasource := 'Are you sure you want to delete %s ?';
  TeeMsg_OCXNoPrinter        := 'No default printer installed.';
  TeeMsg_ActiveXPictureNotValid:='Picture not valid';

end;

Procedure TeeCreateChinese;
begin
  if not Assigned(TeeChineseLanguage) then
  begin
    TeeChineseLanguage:=TStringList.Create;
    TeeChineseLanguage.Text:=

'GRADIENT EDITOR=º¥±m½s¿è¾¹'#13+
'GRADIENT=º¥±m'#13+
'DIRECTION=¤è¦V'#13+
'VISIBLE=Åã¥Ü'#13+
'TOP BOTTOM=¤W¦Ü¤U'#13+
'BOTTOM TOP=¤U¦Ü¤W'#13+
'LEFT RIGHT=¥ª¦Ü¥k'#13+
'RIGHT LEFT=¥k¦Ü¥ª'#13+
'FROM CENTER=±q¤¤¥¡'#13+
'FROM TOP LEFT=±q¥ª¤W'#13+
'FROM BOTTOM LEFT=±q¥ª¤U'#13+
'OK=½T©w'#13+
'CANCEL=¨ú®ø'#13+
'COLORS=ÃC¦â'#13+
'START=¶}©l'#13+
'MIDDLE=¤¤¶¡'#13+
'END=µ²§ô'#13+
'SWAP=´À´«'#13+
'NO MIDDLE=µL¤¤¶¡'#13+
'TEEFONT EDITOR=TeeFont ½s¿è'#13+
'INTER-CHAR SPACING=¦r¥À¶¡¹j'#13+
'FONT=¦r«¬'#13+
'SHADOW=³±¼v'#13+
'HORIZ. SIZE=¤ô¥­¤j¤p'#13+
'VERT. SIZE=««ª½¤j¤p'#13+
'COLOR=ÃC¦â'#13+
'OUTLINE=½ü¹ø'#13+
'OPTIONS=¿ï¶µ'#13+
'FORMAT=®æ¦¡'#13+
'TEXT=¤å¦r'#13+
'TEXT=¤å¦r'#13+
'POSITION=¦ì¸m'#13+
'LEFT=¥ª'#13+
'TOP=¤W'#13+
'AUTO=¦Û°Ê'#13+
'CUSTOM=¦Û©w'#13+
'LEFT TOP=¥ª¤W'#13+
'LEFT BOTTOM=¥ª¤U'#13+
'RIGHT TOP=¥k¤W'#13+
'RIGHT BOTTOM=¥k¤U'#13+
'MULTIPLE AREAS=¦h­±¿n'#13+
'NONE=µL'#13+
'STACKED=°ï¿n'#13+
'STACKED 100%=°ï¿n 100%'#13+
'AREA=­±¿n'#13+
'PATTERN=ªá¯¾'#13+
'STAIRS=¶¥±è'#13+
'SOLID=¹ê½u'#13+
'CLEAR=³z©ú'#13+
'HORIZONTAL=¾î½u'#13+
'VERTICAL=ª½½u'#13+
'DIAGONAL=±×½u'#13+
'B.DIAGONAL=¤Ï±×½u'#13+
'CROSS=¤Q¦r'#13+
'DIAG.CROSS=¤e½u'#13+
'AREA LINES=­±¿n½u±ø'#13+
'BORDER=Ãä½t'#13+
'INVERTED=ÄA­Ë'#13+
'COLOR=ÃC¦â'#13+
'COLOR EACH=¦U§O¦â'#13+
'ORIGIN=¤¤¤ßÂI'#13+
'USE ORIGIN=¨Ï¥Î¤¤¤ßÂI'#13+
'WIDTH=¼e«×'#13+
'HEIGHT=°ª«×'#13+
'AXIS=¶b'#13+
'LENGTH=ªø«×'#13+
'POSITION=¦ì¸m'#13+
'SCROLL=±²°Ê'#13+
'START=¶}©l'#13+
'END=µ²§ô'#13+
'BOTH=¨âªÌ'#13+
'AXIS INCREMENT=¶bªº»¼¼W­È'#13+
'INCREMENT=Increment'#13+
'INCREMENT=»¼¼W'#13+
'STANDARD=¼Ð·Ç'#13+
'ONE MILLISECOND=¤@²@¬í'#13+
'ONE SECOND=¤@¬í'#13+
'FIVE SECONDS=¤­¬í'#13+
'TEN SECONDS=¤Q¬í'#13+
'FIFTEEN SECONDS=¤Q¤­¬í'#13+
'THIRTY SECONDS=¤T¤Q¬í'#13+
'ONE MINUTE=¤@¤ÀÄÁ'#13+
'FIVE MINUTES=¤­¤ÀÄÁ'#13+
'TEN MINUTES=¤Q¤ÀÄÁ'#13+
'FIFTEEN MINUTES=¤Q¤­¤ÀÄÁ'#13+
'THIRTY MINUTES=¤T¤Q¤ÀÄÁ'#13+
'ONE HOUR=¤@¤p®É'#13+
'TWO HOURS=¨â¤p®É'#13+
'SIX HOURS=¤»¤p®É'#13+
'TWELVE HOURS=¤Q¤G¤p®É'#13+
'ONE DAY=¤@¤Ñ'#13+
'TWO DAYS=¨â¤Ñ'#13+
'THREE DAYS=¤T¤Ñ'#13+
'ONE WEEK=¤@Â§«ô'#13+
'HALF MONTH=¥b­Ó¤ë'#13+
'ONE MONTH=¤@­Ó¤ë'#13+
'TWO MONTHS=¨â­Ó¤ë'#13+
'THREE MONTHS=¤T­Ó¤ë'#13+
'FOUR MONTHS=¥|­Ó¤ë'#13+
'SIX MONTHS=¤»­Ó¤ë'#13+
'ONE YEAR=¤@¦~'#13+
'EXACT DATE TIME=ºë½T¤é´Á®É¶¡'#13+
'AXIS MAXIMUM AND MINIMUM=¶bªº³Ì¤j³Ì¤p­È'#13+
'VALUE=¼Æ­È'#13+
'TIME=®É¶¡'#13+
'LEFT AXIS=¥ª¶b'#13+
'RIGHT AXIS=¥k¶b'#13+
'TOP AXIS=¤W¶b'#13+
'BOTTOM AXIS=¤U¶b'#13+
'% BAR WIDTH=% ªø±ø¼e«×'#13+
'STYLE=¼Ë¦¡'#13+
'% BAR OFFSET=% ªø±ø°¾²¾'#13+
'RECTANGLE=¯x§Î'#13+
'PYRAMID=¨¤À@§Î'#13+
'INVERT. PYRAMID=¤Ï¨¤À@§Î'#13+
'CYLINDER=¶ê¬W§Î'#13+
'ELLIPSE=¾ò¶ê§Î'#13+
'ARROW=½bÀY'#13+
'RECT. GRADIENT=º¥±m¯x§Î'#13+
'CONE=¶êÀ@§Î'#13+
'DARK BAR 3D SIDES=3D ©ú·tªø±ø'#13+
'BAR SIDE MARGINS=ªø±ø­±ªºÃä¬É'#13+
'AUTO MARK POSITION=¦Û°Ê¼Ð»x¦ì¸m'#13+
'GRADIENT=º¥±m'#13+
'JOIN=³s±µ'#13+
'DATASET=¸ê®Æ²Õ'#13+
'APPLY=®M¥Î'#13+
'SOURCE=¨Ó·½'#13+
'COLORS=ÃC¦â'#13+
'MONOCHROME=³æ¦â'#13+
'DEFAULT=¹w³]'#13+
'2 (1 BIT)=Âù¦â (1¦ì¤¸)'#13+
'16 (4 BIT)=16¦â (4¦ì¤¸)'#13+
'256 (8 BIT)=256¦â (8¦ì¤¸)'#13+
'32768 (15 BIT)=32768¦â (15¦ì¤¸)'#13+
'65536 (16 BIT)=65536¦â (16¦ì¤¸)'#13+
'16M (24 BIT)=16M¦â (24¦ì¤¸)'#13+
'16M (32 BIT)=16M¦â (32¦ì¤¸)'#13+
'MEDIAN=¤¤¥¡½u'#13+
'WHISKER=Ä²Å½½u'#13+
'PATTERN COLOR EDITOR=ªá¯¾ÃC¦â½s¿è'#13+
'IMAGE=¹Ï®×'#13+
'IMAGE=¹Ï®×'#13+
'SOLID=¹ê¦â'#13+
'NONE=³z©ú'#13+
'BACK DIAGONAL=¤Ï±×½u'#13+
'DIAGONAL CROSS=¤e½u'#13+
'FILL 80%=¶ñº¡ 80%'#13+
'FILL 60%=¶ñº¡ 60%'#13+
'FILL 40%=¶ñº¡ 40%'#13+
'FILL 20%=¶ñº¡ 20%'#13+
'FILL 10%=¶ñº¡ 10%'#13+
'ZIG ZAG=¿÷¾¦ª¬'#13+
'VERTICAL SMALL=¤pª½½u'#13+
'HORIZ. SMALL=¤p¾î½u'#13+
'DIAG. SMALL=¤p±×½u'#13+
'BACK DIAG. SMALL=¤p¤Ï±×½u'#13+
'CROSS SMALL=¤p¤Q¦r'#13+
'DIAG. CROSS SMALL=¤p¤e½u'#13+
'DAYS=¤Ñ¼Æ'#13+
'WEEKDAYS=¤u§@¤é'#13+
'TODAY=¤µ¤Ñ'#13+
'SUNDAY=¬P´Á¤é'#13+
'TRAILING=¤§«á'#13+
'MONTHS=¤ë¥÷'#13+
'LINES=½u±ø'#13+
'SHOW WEEKDAYS=Åã¥Ü¤u§@¤é'#13+
'UPPERCASE=¤j¼g'#13+
'TRAILING DAYS=¤§«á¤Ñ¼Æ'#13+
'SHOW TODAY=Åã¥Ü¤µ¤Ñ'#13+
'SHOW MONTHS=Åã¥Ü¤ë¥÷'#13+
'UPPERCASE=¤j¼g'#13+
'CANDLE WIDTH=Àë¥ú¼e«×'#13+
'STYLE=¼Ë¦¡'#13+
'STICK=´Îª¬'#13+
'BAR=±øª¬'#13+
'OPEN CLOSE=¶}±ÒÃö³¬'#13+
'UP CLOSE=Ãö³¬¤W¤è'#13+
'DOWN CLOSE=Ãö³¬¤U¤è'#13+
'SHOW OPEN=Åã¥Ü¶}¤f'#13+
'SHOW CLOSE=Åã¥ÜÃö¤f'#13+
'BORDER=Ãä½t'#13+
'DRAW 3D=3D Ã¸µe'#13+
'DARK 3D=3D ©ú·t'#13+
'EDITING=½s¿è'#13+
'CHART=¹Ïªí'#13+
'SERIES=§Ç¦C'#13+
'DATA=¸ê®Æ'#13+
'TOOLS=¤u¨ã'#13+
'EXPORT=¶×¥X'#13+
'PRINT=¦C¦L'#13+
'GENERAL=¤@¯ë'#13+
'AXIS=¶b'#13+
'TITLES=¼ÐÃD'#13+
'LEGEND=¹Ï¨Ò'#13+
'PANEL=­±ªO'#13+
'PAGING=¤À­¶'#13+
'WALLS=¾ÀªO'#13+
'3D=3D'#13+
'ADD=·s¼W'#13+
'DELETE=²¾°£'#13+
'TITLE=¼ÐÃD'#13+
'CLONE=½Æ»s'#13+
'CHANGE=ÅÜ§ó'#13+
'HELP=»¡©ú'#13+
'CLOSE=Ãö³¬'#13+
'SERIES=§Ç¦C'#13+
'TEECHART PRINT PREVIEW=TeeChart ¹wÄý¦C¦L'#13+
'PRINTER=¦Lªí¾÷'#13+
'SETUP=³]©w'#13+
'PRINT=¦C¦L'#13+
'ORIENTATION=¤è¦V'#13+
'PORTRAIT=Áa¦V'#13+
'LANDSCAPE=¾î¦V'#13+
'MARGINS (%)=Ãä¬É (%)'#13+
'DETAIL=²Ó¸`'#13+
'MORE=¦h'#13+
'NORMAL=¥¿±`'#13+
'RESET MARGINS=­«³]Ãä¬É'#13+
'VIEW MARGINS=Åã¥ÜÃä¬É'#13+
'PROPORTIONAL=¦¨¥¿¤ñ'#13+
'TEECHART PRINT PREVIEW=TeeChart ¹wÄý¦C¦L'#13+
'STYLE=¼Ë¦¡'#13+
'TEXT=¤å¦r'#13+
'CIRCLE=¶ê§Î'#13+
'VERTICAL LINE=ª½½u'#13+
'HORIZ. LINE=¾î½u'#13+
'TRIANGLE=¤T¨¤§Î'#13+
'INVERT. TRIANGLE=¤Ï¤T¨¤§Î'#13+
'LINE=½u±ø'#13+
'DIAMOND=µÙ§Î'#13+
'CUBE=¥ß¤èÅé'#13+
'DIAGONAL CROSS=¥æ¤e'#13+
'STAR=¬P§Î'#13+
'BORDER=Ãä½t'#13+
'TRANSPARENT=³z©ú'#13+
'HORIZ. ALIGNMENT=¤ô¥­¹ï»ô'#13+
'LEFT=¦V¥ª'#13+
'CENTER=¸m¤¤'#13+
'RIGHT=¦V¥k'#13+
'ROUND RECTANGLE=¶ê¨¤¯x§Î'#13+
'ALIGNMENT=¹ï»ô'#13+
'TOP=¦V¤W'#13+
'BOTTOM=¦V¤U'#13+
'LEFT=¥ª'#13+
'RIGHT=:¥k'#13+
'TOP=¤W'#13+
'BOTTOM=¤U'#13+
'UNITS=³æ¦ì'#13+
'PIXELS=¹³¯À'#13+
'AXIS ORIGIN=¶b¤¤¤ßÂI'#13+
'ROTATION=±ÛÂà'#13+
'CIRCLED=¥¿¶ê§Î'#13+
'3 DIMENSIONS=3D ®ÄªG'#13+
'RADIUS=¥b®|'#13+
'HORIZONTAL=¤ô¥­'#13+
'VERTICAL=««ª½'#13+
'COLOR=ÃC¦â'#13+
'ANGLE INCREMENT=¨¤«×»¼¼W'#13+
'RADIUS INCREMENT=¥b®|»¼¼W'#13+
'CLOSE CIRCLE=Ãö³¬¶ê§Î'#13+
'PEN=Ã¸µ§'#13+
'CIRCLE=¶ê§Î'#13+
'PATTERN=ªá¯¾'#13+
'LABELS=¼ÐÅÒ'#13+
'ROTATED=±ÛÂà'#13+
'CLOCKWISE=¶¶®ÉÄÁ'#13+
'INSIDE=¤º³¡'#13+
'ROMAN=Ã¹°¨'#13+
'HOURS=¤p®É'#13+
'MINUTES=¤ÀÄÁ'#13+
'SECONDS=¬í¼Æ'#13+
'RADIUS=¥b®|'#13+
'START VALUE=¶}©l­È'#13+
'END VALUE=µ²§ô­È'#13+
'TRANSPARENCY=³z©ú'#13+
'DRAW BEHIND=µe¦b¤U¼h'#13+
'COLOR MODE=ÃC¦â¼Ò¦¡'#13+
'STEPS=°Ï¬q'#13+
'STYLE=ºØÃþ'#13+
'RANGE=½d³ò'#13+
'PALETTE=½Õ¦â½L'#13+
'PALE=²L²H'#13+
'STRONG=±j¯P'#13+
'GRID SIZE=®æ¤l¤j¤p'#13+
'X=X'#13+
'Z=Z'#13+
'DEPTH=²`«×'#13+
'IRREGULAR=¤£³W«hªº'#13+
'GRID=ªí®æ'#13+
'VALUE=¼Æ­È'#13+
'ALLOW DRAG=¥i©ì¦²'#13+
'VERTICAL POSITION=««ª½¦ì¸m'#13+
'LEVELS POSITION=¼h¦¸¦ì¸m'#13+
'LEVELS=¼h¦¸'#13+
'NUMBER=¼Æ¦r'#13+
'LEVEL=¼h¦¸'#13+
'AUTOMATIC=¦Û°Ê'#13+
'COLOR EACH=¦U§O¦â'#13+
'STYLE=¼Ë¦¡'#13+
'HORIZONTAL=¤ô¥­'#13+
'VERTICAL=««ª½'#13+
'SNAP=¶¡¹j²¾°Ê'#13+
'FOLLOW MOUSE=¸òÀH·Æ¹«'#13+
'STACK=°ï¿n'#13+
'HEIGHT 3D=3D °ª«×'#13+
'LINE MODE=½u±ø¼Ò¦¡'#13+
'INVERTED=ÄA­Ë'#13+
'DARK 3D=3D ©ú·t'#13+
'OVERLAP=­«Å|'#13+
'STACK=°ï¿n'#13+
'STACK 100%=°ï¿n 100%'#13+
'CLICKABLE=¥iÂI¿ï'#13+
'LABELS=¼ÐÅÒ'#13+
'AVAILABLE=¦³Ãö¶µ¥Ø'#13+
'SELECTED=¤w¿ï¶µ¥Ø'#13+
'DATASOURCE=¸ê®Æ¨Ó·½'#13+
'GROUP BY=¤ÀÃþ'#13+
'CALC=­pºâ'#13+
'OF=¤§'#13+
'SUM=Á`­p'#13+
'COUNT=¼Æ¶q'#13+
'HIGH=³Ì°ª'#13+
'LOW=³Ì§C'#13+
'AVG=¥­§¡'#13+
'HOUR=¤p®É'#13+
'DAY=¤Ñ'#13+
'WEEK=Â§«ô'#13+
'WEEKDAY=¤u§@¤é'#13+
'MONTH=¤ë'#13+
'QUARTER=©u'#13+
'YEAR=¦~'#13+
'HOLE %=¬} %'#13+
'RESET POSITIONS=­«³]¦ì¸m'#13+
'MOUSE BUTTON=·Æ¹««öÁä'#13+
'LEFT=¥ªÁä'#13+
'RIGHT=¥kÁä'#13+
'MIDDLE=¤¤Áä'#13+
'ENABLE DRAWING=±Ò¥ÎÃ¸µe'#13+
'ENABLE SELECT=±Ò¥Î¿ï¾Ü'#13+
'ENHANCED=¼W±j®æ¦¡'#13+
'ERROR WIDTH=»~®t¼e«×'#13+
'WIDTH UNITS=¼e«×³æ¦ì'#13+
'PERCENT=¦Ê¤À¤ñ'#13+
'PIXELS=¹³¯À'#13+
'RIGHT=¥k'#13+
'LEFT AND RIGHT=¥ª»P¥k'#13+
'TOP AND BOTTOM=¤W»P¤U'#13+
'BORDER EDITOR=Ã¸µ§½s¿è'#13+
'DASH=¹ê½u'#13+
'DOT=µê½u'#13+
'DASH DOT=ÂI½u'#13+
'DASH DOT DOT=µêÂI½u'#13+
'DASH=µê½u'#13+
'DOT=ÂI½u'#13+
'DASH DOT=µêÂI½u'#13+
'DASH DOT DOT=µêÂIÂI½u'#13+
'CALCULATE EVERY=­pºâ¨C­Ó'#13+
'ALL POINTS=©Ò¦³¼ÐÂI'#13+
'NUMBER OF POINTS=¼ÐÂI¼Æ¶q'#13+
'RANGE OF VALUES=¼Æ­È½d³ò'#13+
'ALIGNMENT=¹ï»ô'#13+
'FIRST=³Ìªì'#13+
'CENTER=¤¤¶¡'#13+
'LAST=³Ì«á'#13+
'TEEPREVIEW EDITOR=¹wÄý½s¿è'#13+
'ALLOW MOVE=¥i²¾°Ê'#13+
'ALLOW RESIZE=¥iÁY©ñ'#13+
'DRAG IMAGE=©ì¦²¹Ï®×'#13+
'AS BITMAP=¬°ÂI°}¹Ï'#13+
'SHOW IMAGE=Åã¥Ü¹Ï®×'#13+
'PORTRAIT=Áa¦V'#13+
'LANDSCAPE=¾î¦V'#13+
'MARGINS=Ãä¬É'#13+
'SIZE=¤j¤p'#13+
'3D %=3D %'#13+
'ZOOM=ÁY©ñ'#13+
'ELEVATION=¤É«×'#13+
'100%=100%'#13+
'HORIZ. OFFSET=¤ô¥­°¾²¾'#13+
'VERT. OFFSET=««ª½°¾²¾'#13+
'PERSPECTIVE=³zµø²`«×'#13+
'ANGLE=¨¤«×'#13+
'ORTHOGONAL=ª½¨¤¹Ï'#13+
'ZOOM TEXT=ÁY©ñ¤å¦r'#13+
'SCALES=¨è«×'#13+
'TITLE=¼ÐÃD'#13+
'TICKS=°O¸¹'#13+
'MINOR=¦¸­n'#13+
'MAXIMUM=³Ì¤j­È'#13+
'MINIMUM=³Ì¤p­È'#13+
'(MAX)=(max)'#13+
'(MIN)=(min)'#13+
'DESIRED INCREMENT=»Ý¨Dªº»¼¼W­È'#13+
'(INCREMENT)=(increment)'#13+
'LOG BASE=¹ï¼Æ©³'#13+
'LOGARITHMIC=±Ò¥Î¹ï¼Æ(Log)'#13+
'AUTO=¦Û°Ê'#13+
'AUTO=¦Û°Ê'#13+
'CHANGE=ÅÜ§ó'#13+
'CHANGE=ÅÜ§ó'#13+
'TITLE=¼ÐÃD'#13+
'ANGLE=¨¤«×'#13+
'MIN. SEPARATION %=³Ì¤p¤ÀÂ÷ %'#13+
'VISIBLE=Åã¥Ü'#13+
'MULTI-LINE=¦h¦æ'#13+
'LABEL ON AXIS=¦b¶b¤W'#13+
'ROUND FIRST=¥ý±Ë¤J­È'#13+
'AUTO=¦Û°Ê'#13+
'MARK=°O¸¹'#13+
'LABELS FORMAT=¼ÐÅÒ®æ¦¡'#13+
'EXPONENTIAL=«ü¼Æ(Exponential)'#13+
'DEFAULT ALIGNMENT=¹w³]¹ï»ô'#13+
'LEN=ªø«×'#13+
'TICKS=°O¸¹'#13+
'INNER=¤º³¡'#13+
'AT LABELS ONLY=¥u¦b¼ÐÅÒ'#13+
'CENTERED=¸m¤¤'#13+
'COUNT=¼Æ¶q'#13+
'TICKS=°O¸¹'#13+
'POSITION %=¦ì¸m %'#13+
'START %=¶}©l %'#13+
'END %=µ²§ô %'#13+
'OTHER SIDE=¥t¤@­±'#13+
'AXES=¶b'#13+
'VISIBLE=Åã¥Ü'#13+
'BEHIND=¤U¼h'#13+
'CLIP POINTS=Åã¥Ü½d³ò¤º'#13+
'PRINT PREVIEW=¹wÄý¦C¦L'#13+
'ZOOM=ÁY©ñ'#13+
'SCROLL=±²°Ê'#13+
'STEPS=°Ï¬q'#13+
'MINIMUM PIXELS=³Ì¤ÖÂI¼Æ'#13+
'DIRECTION=¤è¦ì'#13+
'MOUSE BUTTON=·Æ¹«Áä'#13+
'ALLOW=¤¹³\'#13+
'ANIMATED=°Êµe'#13+
'PEN=Ã¸µ§'#13+
'PATTERN=ªá¯¾'#13+
'ALLOW SCROLL=¤¹³\±²°Ê'#13+
'NONE=µL'#13+
'BOTH=¨âªÌ'#13+
'TEEOPENGL EDITOR=TeeOpenGL ½s¿è'#13+
'AMBIENT LIGHT=Àô¹Ò«G«×'#13+
'SHININESS=¥ú¿A'#13+
'FONT 3D DEPTH=3D ¦r«¬²`«×'#13+
'ACTIVE=¦³®Ä'#13+
'FONT OUTLINES=¦r«¬½ü¹ø'#13+
'SMOOTH SHADING=¥­·Æ´yÃ¸³±¼v'#13+
'LIGHT=¿O¥ú'#13+
'Y=Y'#13+
'INTENSITY=±j¯P«×'#13+
'BEVEL=±×­±'#13+
'SIZE=¤j¤p'#13+
'FRAME=®Ø¬['#13+
'ROUND FRAME=¶ê¨¤¥~®Ø'#13+
'TRANSPARENT=³z©ú'#13+
'LOWERED=³´¤J'#13+
'RAISED=¯B°_'#13+
'SYMBOLS=²Å¸¹'#13+
'TEXT STYLE=¤å¦r¼Ë¦¡'#13+
'LEGEND STYLE=¹Ï¨Ò¼Ë¦¡'#13+
'VERT. SPACING=««ª½ªÅ¶¡'#13+
'AUTOMATIC=¦Û°Ê'#13+
'SERIES NAMES=§Ç¦C¦WºÙ'#13+
'SERIES VALUES=§Ç¦C¼Æ­È'#13+
'LAST VALUES=³Ì«á¼Æ­È'#13+
'PLAIN=´¶³q'#13+
'LEFT VALUE=¥ª¼Æ­È'#13+
'RIGHT VALUE=¥k¼Æ­È'#13+
'LEFT PERCENT=¥ª¦Ê¤À¤ñ'#13+
'RIGHT PERCENT=¥k¦Ê¤À¤ñ'#13+
'X VALUE=X ¼Æ­È'#13+
'VALUE=¼Æ´Ó'#13+
'PERCENT=¦Ê¤À¤ñ'#13+
'X AND VALUE=X »P ¼Æ­È'#13+
'X AND PERCENT=X »P ¦Ê¤À¤ñ'#13+
'CHECK BOXES=¤Ä¿ï¶µ¥Ø'#13+
'DIVIDING LINES=¤À¹j½u'#13+
'FONT SERIES COLOR=§Ç¦C¦r«¬ÃC¦â'#13+
'POSITION OFFSET %=¦ì¸m°¾²¾ %'#13+
'MARGIN=Ãä¬É'#13+
'RESIZE CHART=ÅÜ§ó¹Ïªí¤j¤p'#13+
'WIDTH UNITS=¼e«×³æ¦ì'#13+
'LEFT=¥ª'#13+
'RIGHT=¥k'#13+
'CONTINUOUS=³sÄòªº'#13+
'POINTS PER PAGE=¨C­¶ªº¼ÐÂI¼Æ'#13+
'SCALE LAST PAGE=ÁY©ñ³Ì«á¤@­¶'#13+
'CURRENT PAGE LEGEND=¥»­¶Åã¥Ü¹Ï¨Ò'#13+
'PANEL EDITOR=­±ªO½s¿è'#13+
'BACKGROUND=­I´º'#13+
'BORDERS=Ãä½t'#13+
'COLOR=­±ªOÃC¦â'#13+
'BACK IMAGE=­I´º¹Ï®×'#13+
'STRETCH=®i¶}'#13+
'TILE=¨Ö¦C'#13+
'INSIDE=½d³ò¤§¤º'#13+
'WIDTH=¼e'#13+
'WIDTH=¼e'#13+
'BEVEL INNER=¤º±×­±'#13+
'BEVEL OUTER=¥~±×­±'#13+
'MARKS=¼Ð»x'#13+
'DATA SOURCE=¸ê®Æ¨Ó·½'#13+
'SORT=±Æ§Ç'#13+
'CURSOR=«ü¼Ð'#13+
'SHOW IN LEGEND=Åã¥Ü¦b¹Ï¼Ð'#13+
'FORMATS=®æ¦¡'#13+
'VALUES=¼Æ­È'#13+
'PERCENTS=¦Ê¤À¤ñ'#13+
'HORIZONTAL AXIS=¾î¶b'#13+
'TOP=¤W'#13+
'BOTTOM=¤U'#13+
'TOP AND BOTTOM=¤W»P¤U'#13+
'DATETIME=¤é´Á®É¶¡'#13+
'VERTICAL AXIS=ª½¶b'#13+
'LEFT AND RIGHT=¥ª»P¥k'#13+
'DATETIME=¤é´Á®É¶¡'#13+
'ASCENDING=»¼¼W'#13+
'DESCENDING=»¼´î'#13+
'DRAW EVERY=µe¨C­Ó'#13+
'CLIPPED=­×°Å'#13+
'ARROWS=½bÀY'#13+
'MULTI LINE=¦h¦æ'#13+
'ALL SERIES VISIBLE=Åã¥Ü©Ò¦³§Ç¦C'#13+
'LABEL=¼ÐÅÒ'#13+
'LABEL AND PERCENT=¼ÐÅÒ»P¦Ê¤À¤ñ'#13+
'LABEL AND VALUE=¼ÐÅÒ»P¼Æ­È'#13+
'LEGEND=¹Ï¼Ð'#13+
'PERCENT TOTAL=Á`¦Ê¤À¤ñ'#13+
'X AND Y VALUES=X ©M Y ¼Æ­È'#13+
'MANUAL=¤â°Ê'#13+
'RANDOM=¶Ã¼Æ'#13+
'FUNCTION=¨ç¼Æ'#13+
'NEW=·s¼W'#13+
'EDIT=­×§ï'#13+
'PERSISTENT=«O¯d'#13+
'ADJUST FRAME=½Õ¾ã®Ø¬['#13+
'LEFT=¦V¥ª'#13+
'CENTER=¸m¤¤'#13+
'RIGHT=¦V¥k'#13+
'TOP=¤W'#13+
'SUBTITLE=¤l¼ÐÃD'#13+
'SUBFOOT=¤l¼Ð§À'#13+
'FOOT=¼Ð§À'#13+
'ACTIVE=¦³®Ä'#13+
'VISIBLE WALLS=Åã¥Ü¾ÀªO'#13+
'LEFT=¥ª­±'#13+
'RIGHT=¥k­±'#13+
'BOTTOM=¤U­±'#13+
'BACK=«á¤è'#13+
'BORDER=Ãä½t'#13+
'DIF. LIMIT=¬Û®t­­'#13+
'LINES=½u±ø.'#13+
'ABOVE=°ª©ó'#13+
'WITHIN=¤§¤º'#13+
'BELOW=§C©ó'#13+
'CONNECTING LINES=³s±µ½u±ø'#13+
'HIGH=°ª'#13+
'LOW=§C'#13+
'BROWSE=ÂsÄý'#13+
'TILED=¨Ö¦CÅã¥Ü'#13+
'INFLATE MARGINS=º¦¤jÃä¬É '#13+
'SQUARE=¥¿¤è§Î'#13+
'DOWN TRIANGLE=¤Ï¤T¨¤§Î'#13+
'SMALL DOT=¤pÂI'#13+
'DEFAULT=¹w³]'#13+
'GLOBAL=¾ãÅé'#13+
'SHAPES=§Îª¬'#13+
'BRUSH=µ§¨ê'#13+
'GLOBAL=¾ãÅé'#13+
'BRUSH=µ§¨ê'#13+
'GLOBAL=¾ãÅé'#13+
'BORDER=Ãä½t'#13+
'DELAY=©µ¿ð'#13+
'MSEC.=·L¬í'#13+
'LABEL AND PERCENT TOTAL=¼ÐÅÒ»PÁ`¦Ê¤À¤ñ'#13+
'MOUSE ACTION=·Æ¹«°Ê§@'#13+
'MOVE=²¾°Ê'#13+
'CLICK=ÂI¿ï'#13+
'SIZE=¤j¤p'#13+
'BRUSH=µ§¨ê'#13+
'DRAW LINE=µe½u'#13+
'EXPLODE BIGGEST=¤À¸Ñ³Ì¤j'#13+
'TOTAL ANGLE=Á`¨¤«×'#13+
'GROUP SLICES=¤ÀÃþ'#13+
'VALUE=¼Æ­È'#13+
'LABEL=¼ÐÅÒ'#13+
'BELOW %=¦Ê¤À¤ñ¤§¤U'#13+
'BELOW VALUE=¼Æ­È¤§¤U'#13+
'OTHER=Other'#13+
'PATTERNS=ªá¯¾'#13+
'DEPTH=²`«×'#13+
'LINE=½u±ø'#13+
'SIZE %=¤j¤p %'#13+
'SERIES DATASOURCE TEXT EDITOR=¹Ïªí¸ê®Æ¨Ó½t¤å¦r½s¿è'#13+
'FIELDS=Fields'#13+
'SOURCE=¨Ó·½'#13+
'NUMBER OF HEADER LINES=¼ÐÀYÁ`¦æ¼Æ'#13+
'SEPARATOR=¤À¹j²Å¸¹'#13+
'SERIES=§Ç¦C'#13+
'COMMA=³rÂI'#13+
'SPACE=ªÅ¥Õ'#13+
'TAB=Tab'#13+
'FILE=ÀÉ®×'#13+
'C:\TEST.TXT=c:\test.txt'#13+
'WEB URL=ºô§}'#13+
'LOAD=Åª¨ú'#13+
'C LABELS=C ¼ÐÅÒ'#13+
'R LABELS=R ¼ÐÅÒ'#13+
'C PEN=C Ã¸µ§'#13+
'R PEN=R Ã¸µ§'#13+
'CIRCLE=¶ê°é'#13+
'COLOR EACH=¦U§O¦â'#13+
'FONT=¦r«¬'#13+
'STACK GROUP=°ï©ñ²Õ¼Æ'#13+
'USE ORIGIN=¨Ï¥Î¤¤¤ßÂI'#13+
'MULTIPLE BAR=¦hªø±ø¹Ï'#13+
'SIDE=°¼©ñ'#13+
'SIDE ALL=¥þ°¼©ñ'#13+
'DRAWING MODE=Ã¸¹Ï¼Ò¦¡'#13+
'SOLID=¹êÅé'#13+
'WIREFRAME=¥~®Ø½u'#13+
'DOTFRAME=¥~®ØÂI'#13+
'SMOOTH PALETTE=¥­·Æ¦â¿A'#13+
'SIDE BRUSH=°¼­±µ§¨ê'#13+
'ABOUT TEECHART PRO V7.0=¦³Ãö TeeChart Pro v7.0'#13+
'TEECHART PRO V5.03=TeeChart Pro v5.03'#13+
'ALL RIGHTS RESERVED.=All Rights Reserved.'#13+
'VISIT OUR WEB SITE !=Visit our Web site !'#13+
'TEECHART WIZARD=TeeChart ºëÆF'#13+
'SELECT A CHART STYLE=Select a Chart style'#13+
'DATABASE CHART=Database Chart'#13+
'NON DATABASE CHART=Non Database Chart'#13+
'SELECT A DATABASE TABLE=Select a Database Table'#13+
'ALIAS=Alias'#13+
'TABLE=Table'#13+
'SOURCE=Source'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'MICROSOFT ADO=Microsoft ADO'#13+
'SELECT THE DESIRED FIELDS TO CHART=Select the desired Fields to Chart'#13+
'SELECT A TEXT LABELS FIELD=Select a text labels Field'#13+
'CHOOSE THE DESIRED CHART TYPE=Choose the desired Chart type'#13+
'2D=2D'#13+
'CHART PREVIEW=¹Ïªí¹wÄý'#13+
'SHOW LEGEND=Åã¥Ü¹Ï¨Ò'#13+
'SHOW MARKS=Åã¥Ü¼Ð»x'#13+
'COLOR EACH=­Ó§O¦â'#13+
'< BACK=< ¤W¤@¨B'#13+
'SELECT A CHART STYLE=Select a Chart style'#13+
'NON DATABASE CHART=Non Database Chart'#13+
'SELECT A DATABASE TABLE=Select a Database Table'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'SELECT THE DESIRED FIELDS TO CHART=Select the desired Fields to Chart'#13+
'SELECT A TEXT LABELS FIELD=Select a text labels Field'#13+
'CHOOSE THE DESIRED CHART TYPE=Choose the desired Chart type'#13+
'EXPORT CHART=¶×¥X¹Ïªí'#13+
'PICTURE=¹Ï¤ù'#13+
'NATIVE=­ì©l'#13+
'FORMAT=®æ¦¡'#13+
'SIZE=¤j¤p'#13+
'HEIGHT=°ª'#13+
'KEEP ASPECT RATIO=«O¯d¤j¤p¤ñ¨Ò'#13+
'INCLUDE SERIES DATA=¥[¤J§Ç¦C¸ê®Æ'#13+
'FILE SIZE=ÀÉ®×¤j¤p'#13+
'SERIES=§Ç¦C'#13+
'DELIMITER=¤À¹j½X'#13+
'XML=XML'#13+
'HTML TABLE=HTML ªí®æ'#13+
'EXCEL=Excel'#13+
'COMMA=³r¸¹'#13+
'COLON=«_¸¹'#13+
'CUSTOM=¦Û©w'#13+
'INCLUDE=¥[¤J'#13+
'POINT LABELS=¼ÐÂI¼ÐÅÒ'#13+
'POINT INDEX=¼ÐÂI¯Á¤Þ'#13+
'HEADER=ªíÀY'#13+
'COPY=½Æ»s'#13+
'SAVE=Àx¦s'#13+
'SEND=¶Ç°e'#13+
'FUNCTIONS=¨ç¼Æ'#13+
'ADD=´î'#13+
'ADX=¥['#13+
'AVERAGE=¥­§¡'#13+
'BOLLINGER=§C'#13+
'COPY=°£'#13+
'DIVIDE=°ª'#13+
'EXP. AVERAGE=­¼'#13+
'EXP.MOV.AVRG.=½Æ»s'#13+
'HIGH=ADX'#13+
'LOW=Bollinger'#13+
'MACD=Exp. Avg.'#13+
'MOMENTUM=Exp. Mov. Avg.'#13+
'MOMENTUM DIV=MACD'#13+
'MOVING AVRG.=Momentum'#13+
'MULTIPLY=Momentum Div.'#13+
'R.S.I.=Moving Avg.'#13+
'ROOT MEAN SQ.=R.S.I.'#13+
'STD.DEVIATION=Root Mean Sq.'#13+
'STOCHASTIC=StdDeviation'#13+
'SUBTRACT=Stochastic'#13+
'SOURCE SERIES=¨Ó·½§Ç¦C'#13+
'TEECHART GALLERY=TeeChart ³¯¦C«Ç'#13+
'FUNCTIONS=¨ç¼Æ'#13+
'DITHER=¦â½Õ'#13+
'REDUCTION=Âà´«'#13+
'COMPRESSION=À£ÁY®æ¦¡'#13+
'LZW=LZW'#13+
'RLE=RLE'#13+
'NEAREST=Nearest'#13+
'FLOYD STEINBERG=Floyd Steinberg'#13+
'STUCKI=Stucki'#13+
'SIERRA=Sierra'#13+
'JAJUNI=JaJuNI'#13+
'STEVE ARCHE=Steve Arche'#13+
'BURKES=Burkes'#13+
'WINDOWS 20=Windows 20'#13+
'WINDOWS 256=Windows 256'#13+
'WINDOWS GRAY=Windows Gray'#13+
'MONOCHROME=³æ¦â'#13+
'GRAY SCALE=º¥¦Ç«×'#13+
'NETSCAPE=Netscape'#13+
'QUANTIZE=Quantize'#13+
'QUANTIZE 256=Quantize 256'#13+
'% QUALITY=% «~½è'#13+
'GRAY SCALE=¦Ç¶¥'#13+
'PERFORMANCE=®Ä¯à'#13+
'QUALITY=«~½è'#13+
'SPEED=³t«×'#13+
'COMPRESSION LEVEL=À£ÁYµ{«×'#13+
'CHART TOOLS GALLERY=¹Ïªí¤u¨ã³¯¦C«Ç'#13+
'ANNOTATION=±ÛÂà'#13+
'AXIS ARROWS=«ü¼Ð'#13+
'COLOR BAND=©ì¦²¼Ð»x'#13+
'COLOR LINE=µe½u'#13+
'CURSOR=¶b½bÀY'#13+
'DRAG MARKS=¼Ð»x»¡©ú'#13+
'DRAW LINE=¹Ï®×'#13+
'IMAGE=³ÌªñÂI'#13+
'MARK TIPS=ÃC¦â±a'#13+
'NEAREST POINT=ÃC¦â½u'#13+
'ROTATE=±ÛÂà'#13
;
  end;
end;

Procedure TeeSetChinese;
begin
  TeeCreateChinese;
  TeeLanguage:=TeeChineseLanguage;
  TeeChineseConstants;
  TeeLanguageHotKeyAtEnd:=True;
  TeeLanguageCanUpper:=False;
end;

initialization
finalization
  FreeAndNil(TeeChineseLanguage);
end.
