unit TeeLithuanian;
{$I TeeDefs.inc}

interface

Uses Classes;

Var TeeLithuanianLanguage:TStringList=nil;

Procedure TeeSetLithuanian;
Procedure TeeCreateLithuanian;

implementation

Uses SysUtils, TeeConst, TeeProCo {$IFNDEF D5},TeCanvas{$ENDIF};

Procedure TeeLithuanianConstants;
begin
  TeeMsg_Copyright          :='© 1995-2004 by David Berneda';
  TeeMsg_LegendFirstValue   :='First Legend Value must be > 0';
  TeeMsg_LegendColorWidth   :='Legend Color Width must be > 0%';
  TeeMsg_SeriesSetDataSource:='No ParentChart to validate DataSource';
  TeeMsg_SeriesInvDataSource:='No valid DataSource: %s';
  TeeMsg_FillSample         :='FillSampleValues NumValues must be > 0';
  TeeMsg_AxisLogDateTime    :='DateTime Axis cannot be Logarithmic';
  TeeMsg_AxisLogNotPositive :='Logarithmic Axis Min and Max values should be >= 0';
  TeeMsg_AxisLabelSep       :='Labels Separation % must be greater than 0';
  TeeMsg_AxisIncrementNeg   :='Axis increment must be >= 0';
  TeeMsg_AxisMinMax         :='Axis Minimum Value must be <= Maximum';
  TeeMsg_AxisMaxMin         :='Axis Maximum Value must be >= Minimum';
  TeeMsg_AxisLogBase        :='Axis Logarithmic Base should be >= 2';
  TeeMsg_MaxPointsPerPage   :='MaxPointsPerPage must be >= 0';
  TeeMsg_3dPercent          :='3D effect percent must be between %d and %d';
  TeeMsg_CircularSeries     :='Circular Series dependences are not allowed';
  TeeMsg_WarningHiColor     :='16k Color or greater required to get better look';

  TeeMsg_DefaultPercentOf   :='%s of %s';
  TeeMsg_DefaultPercentOf2  :='%s'+#13+'of %s';
  TeeMsg_DefPercentFormat   :='##0.## %';
  TeeMsg_DefValueFormat     :='#,##0.###';
  TeeMsg_DefLogValueFormat  :='#.0 "x10" E+0';
  TeeMsg_AxisTitle          :='Axis Title';
  TeeMsg_AxisLabels         :='Axis Labels';
  TeeMsg_RefreshInterval    :='Refresh Interval must be between 0 and 60';
  TeeMsg_SeriesParentNoSelf :='Series.ParentChart is not myself!';
  TeeMsg_GalleryLine        :='Line';
  TeeMsg_GalleryPoint       :='Point';
  TeeMsg_GalleryArea        :='Area';
  TeeMsg_GalleryBar         :='Bar';
  TeeMsg_GalleryHorizBar    :='Horiz. Bar';
  TeeMsg_Stack              :='Stack';
  TeeMsg_GalleryPie         :='Pie';
  TeeMsg_GalleryCircled     :='Circled';
  TeeMsg_GalleryFastLine    :='Fast Line';
  TeeMsg_GalleryHorizLine   :='Horiz Line';

  TeeMsg_PieSample1         :='Cars';
  TeeMsg_PieSample2         :='Phones';
  TeeMsg_PieSample3         :='Tables';
  TeeMsg_PieSample4         :='Monitors';
  TeeMsg_PieSample5         :='Lamps';
  TeeMsg_PieSample6         :='Keyboards';
  TeeMsg_PieSample7         :='Bikes';
  TeeMsg_PieSample8         :='Chairs';

  TeeMsg_GalleryLogoFont    :='Courier New';
  TeeMsg_Editing            :='Editing %s';

  TeeMsg_GalleryStandard    :='Standard';
  TeeMsg_GalleryExtended    :='Extended';
  TeeMsg_GalleryFunctions   :='Functions';

  TeeMsg_EditChart          :='E&dit Chart...';
  TeeMsg_PrintPreview       :='&Print Preview...';
  TeeMsg_ExportChart        :='E&xport Chart...';
  TeeMsg_CustomAxes         :='Custom Axes...';

  TeeMsg_InvalidEditorClass :='%s: Invalid Editor Class: %s';
  TeeMsg_MissingEditorClass :='%s: has no Editor Dialog';

  TeeMsg_GalleryArrow       :='Arrow';

  TeeMsg_ExpFinish          :='&Finish';
  TeeMsg_ExpNext            :='&Next >';

  TeeMsg_GalleryGantt       :='Gantt';

  TeeMsg_GanttSample1       :='Design';
  TeeMsg_GanttSample2       :='Prototyping';
  TeeMsg_GanttSample3       :='Development';
  TeeMsg_GanttSample4       :='Sales';
  TeeMsg_GanttSample5       :='Marketing';
  TeeMsg_GanttSample6       :='Testing';
  TeeMsg_GanttSample7       :='Manufac.';
  TeeMsg_GanttSample8       :='Debugging';
  TeeMsg_GanttSample9       :='New Version';
  TeeMsg_GanttSample10      :='Banking';

  TeeMsg_ChangeSeriesTitle  :='Change Series Title';
  TeeMsg_NewSeriesTitle     :='New Series Title:';
  TeeMsg_DateTime           :='DateTime';
  TeeMsg_TopAxis            :='Top Axis';
  TeeMsg_BottomAxis         :='Bottom Axis';
  TeeMsg_LeftAxis           :='Left Axis';
  TeeMsg_RightAxis          :='Right Axis';

  TeeMsg_SureToDelete       :='Delete %s ?';
  TeeMsg_DateTimeFormat     :='DateTime For&mat:';
  TeeMsg_Default            :='Default: ';
  TeeMsg_ValuesFormat       :='Values For&mat:';
  TeeMsg_Maximum            :='Maximum';
  TeeMsg_Minimum            :='Minimum';
  TeeMsg_DesiredIncrement   :='Desired %s Increment';

  TeeMsg_IncorrectMaxMinValue:='Incorrect value. Reason: %s';
  TeeMsg_EnterDateTime      :='Enter [Number of Days] [hh:mm:ss]';

  TeeMsg_SureToApply        :='Apply Changes ?';
  TeeMsg_SelectedSeries     :='(Selected Series)';
  TeeMsg_RefreshData        :='&Refresh Data';

  TeeMsg_DefaultFontSize    :={$IFDEF LINUX}'10'{$ELSE}'8'{$ENDIF};
  TeeMsg_DefaultEditorSize  :='414';
  TeeMsg_FunctionAdd        :='Add';
  TeeMsg_FunctionSubtract   :='Subtract';
  TeeMsg_FunctionMultiply   :='Multiply';
  TeeMsg_FunctionDivide     :='Divide';
  TeeMsg_FunctionHigh       :='High';
  TeeMsg_FunctionLow        :='Low';
  TeeMsg_FunctionAverage    :='Average';

  TeeMsg_GalleryShape       :='Shape';
  TeeMsg_GalleryBubble      :='Bubble';
  TeeMsg_FunctionNone       :='Copy';

  TeeMsg_None               :='(none)';

  TeeMsg_PrivateDeclarations:='{ Private declarations }';
  TeeMsg_PublicDeclarations :='{ Public declarations }';
  TeeMsg_DefaultFontName    :={$IFDEF CLX}'Helvetica'{$ELSE}'Arial'{$ENDIF};

  TeeMsg_CheckPointerSize   :='Pointer size must be greater than zero';
  TeeMsg_About              :='Abo&ut TeeChart...';

  tcAdditional              :='Additional';
  tcDControls               :='Data Controls';
  tcQReport                 :='QReport';

  TeeMsg_DataSet            :='Dataset';
  TeeMsg_AskDataSet         :='&Dataset:';

  TeeMsg_SingleRecord       :='Single Record';
  TeeMsg_AskDataSource      :='&DataSource:';

  TeeMsg_Summary            :='Summary';

  TeeMsg_FunctionPeriod     :='Function Period should be >= 0';

  TeeMsg_WizardTab          :='Business';
  TeeMsg_TeeChartWizard     :='TeeChart Wizard';

  TeeMsg_ClearImage         :='Clea&r';
  TeeMsg_BrowseImage        :='B&rowse...';

  TeeMsg_WizardSureToClose  :='Are you sure that you want to close the TeeChart Wizard ?';
  TeeMsg_FieldNotFound      :='Field %s does not exist';

  TeeMsg_DepthAxis          :='Depth Axis';
  TeeMsg_PieOther           :='Other';
  TeeMsg_ShapeGallery1      :='abc';
  TeeMsg_ShapeGallery2      :='123';
  TeeMsg_ValuesX            :='X';
  TeeMsg_ValuesY            :='Y';
  TeeMsg_ValuesPie          :='Pie';
  TeeMsg_ValuesBar          :='Bar';
  TeeMsg_ValuesAngle        :='Angle';
  TeeMsg_ValuesGanttStart   :='Start';
  TeeMsg_ValuesGanttEnd     :='End';
  TeeMsg_ValuesGanttNextTask:='NextTask';
  TeeMsg_ValuesBubbleRadius :='Radius';
  TeeMsg_ValuesArrowEndX    :='EndX';
  TeeMsg_ValuesArrowEndY    :='EndY';
  TeeMsg_Legend             :='Legend';
  TeeMsg_Title              :='Title';
  TeeMsg_Foot               :='Footer';
  TeeMsg_Period		    :='Period';
  TeeMsg_PeriodRange        :='Period range';
  TeeMsg_CalcPeriod         :='Calculate %s every:';
  TeeMsg_SmallDotsPen       :='Small Dots';

  TeeMsg_InvalidTeeFile     :='Invalid Chart in *.tee file';
  TeeMsg_WrongTeeFileFormat :='Wrong *.tee file format';
  TeeMsg_EmptyTeeFile       :='Empty *.tee file';  { 5.01 }

  {$IFDEF D5}
  TeeMsg_ChartAxesCategoryName   := 'Chart Axes';
  TeeMsg_ChartAxesCategoryDesc   := 'Chart Axes properties and events';
  TeeMsg_ChartWallsCategoryName  := 'Chart Walls';
  TeeMsg_ChartWallsCategoryDesc  := 'Chart Walls properties and events';
  TeeMsg_ChartTitlesCategoryName := 'Chart Titles';
  TeeMsg_ChartTitlesCategoryDesc := 'Chart Titles properties and events';
  TeeMsg_Chart3DCategoryName     := 'Chart 3D';
  TeeMsg_Chart3DCategoryDesc     := 'Chart 3D properties and events';
  {$ENDIF}

  TeeMsg_CustomAxesEditor       :='Custom ';
  TeeMsg_Series                 :='Series';
  TeeMsg_SeriesList             :='Series...';

  TeeMsg_PageOfPages            :='Page %d of %d';
  TeeMsg_FileSize               :='%d bytes';

  TeeMsg_First  :='First';
  TeeMsg_Prior  :='Prior';
  TeeMsg_Next   :='Next';
  TeeMsg_Last   :='Last';
  TeeMsg_Insert :='Insert';
  TeeMsg_Delete :='Delete';
  TeeMsg_Edit   :='Edit';
  TeeMsg_Post   :='Post';
  TeeMsg_Cancel :='Cancel';

  TeeMsg_All    :='(all)';
  TeeMsg_Index  :='Index';
  TeeMsg_Text   :='Text';

  TeeMsg_AsBMP        :='as &Bitmap';
  TeeMsg_BMPFilter    :='Bitmaps (*.bmp)|*.bmp';
  TeeMsg_AsEMF        :='as &Metafile';
  TeeMsg_EMFFilter    :='Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  TeeMsg_ExportPanelNotSet := 'Panel property is not set in Export format';

  TeeMsg_Normal    :='Normal';
  TeeMsg_NoBorder  :='No Border';
  TeeMsg_Dotted    :='Dotted';
  TeeMsg_Colors    :='Colors';
  TeeMsg_Filled    :='Filled';
  TeeMsg_Marks     :='Marks';
  TeeMsg_Stairs    :='Stairs';
  TeeMsg_Points    :='Points';
  TeeMsg_Height    :='Height';
  TeeMsg_Hollow    :='Hollow';
  TeeMsg_Point2D   :='Point 2D';
  TeeMsg_Triangle  :='Triangle';
  TeeMsg_Star      :='Star';
  TeeMsg_Circle    :='Circle';
  TeeMsg_DownTri   :='Down Tri.';
  TeeMsg_Cross     :='Cross';
  TeeMsg_Diamond   :='Diamond';
  TeeMsg_NoLines   :='No Lines';
  TeeMsg_Stack100  :='Stack 100%';
  TeeMsg_Pyramid   :='Pyramid';
  TeeMsg_Ellipse   :='Ellipse';
  TeeMsg_InvPyramid:='Inv. Pyramid';
  TeeMsg_Sides     :='Sides';
  TeeMsg_SideAll   :='Side All';
  TeeMsg_Patterns  :='Patterns';
  TeeMsg_Exploded  :='Exploded';
  TeeMsg_Shadow    :='Shadow';
  TeeMsg_SemiPie   :='Semi Pie';
  TeeMsg_Rectangle :='Rectangle';
  TeeMsg_VertLine  :='Vert.Line';
  TeeMsg_HorizLine :='Horiz.Line';
  TeeMsg_Line      :='Line';
  TeeMsg_Cube      :='Cube';
  TeeMsg_DiagCross :='Diag.Cross';

  TeeMsg_CanNotFindTempPath    :='Can not find Temp folder';
  TeeMsg_CanNotCreateTempChart :='Can not create Temp file';
  TeeMsg_CanNotEmailChart      :='Can not email TeeChart. Mapi Error: %d';

  TeeMsg_SeriesDelete :='Series Delete: ValueIndex %d out of bounds (0 to %d).';

  { 5.02 } { Moved from TeeImageConstants.pas unit }

  TeeMsg_AsJPEG        :='as &JPEG';
  TeeMsg_JPEGFilter    :='JPEG files (*.jpg)|*.jpg';
  TeeMsg_AsGIF         :='as &GIF';
  TeeMsg_GIFFilter     :='GIF files (*.gif)|*.gif';
  TeeMsg_AsPNG         :='as &PNG';
  TeeMsg_PNGFilter     :='PNG files (*.png)|*.png';
  TeeMsg_AsPCX         :='as PC&X';
  TeeMsg_PCXFilter     :='PCX files (*.pcx)|*.pcx';
  TeeMsg_AsVML         :='as &VML (HTM)';
  TeeMsg_VMLFilter     :='VML files (*.htm)|*.htm';

  { 5.02 }
  TeeMsg_AskLanguage  :='&Language...';
  
  { TeeProCo }
  TeeMsg_GalleryPolar       :='Polar';
  TeeMsg_GalleryCandle      :='Candle';
  TeeMsg_GalleryVolume      :='Volume';
  TeeMsg_GallerySurface     :='Surface';
  TeeMsg_GalleryContour     :='Contour';
  TeeMsg_GalleryBezier      :='Bezier';
  TeeMsg_GalleryPoint3D     :='Point 3D';
  TeeMsg_GalleryRadar       :='Radar';
  TeeMsg_GalleryDonut       :='Donut';
  TeeMsg_GalleryCursor      :='Cursor';
  TeeMsg_GalleryBar3D       :='Bar 3D';
  TeeMsg_GalleryBigCandle   :='Big Candle';
  TeeMsg_GalleryLinePoint   :='Line Point';
  TeeMsg_GalleryHistogram   :='Histogram';
  TeeMsg_GalleryWaterFall   :='Water Fall';
  TeeMsg_GalleryWindRose    :='Wind Rose';
  TeeMsg_GalleryClock       :='Clock';
  TeeMsg_GalleryColorGrid   :='ColorGrid';
  TeeMsg_GalleryBoxPlot     :='BoxPlot';
  TeeMsg_GalleryHorizBoxPlot:='Horiz.BoxPlot';
  TeeMsg_GalleryBarJoin     :='Bar Join';
  TeeMsg_GallerySmith       :='Smith';
  TeeMsg_GalleryPyramid     :='Pyramid';
  TeeMsg_GalleryMap         :='Map';

  TeeMsg_PolyDegreeRange    :='Polynomial degree must be between 1 and 20';
  TeeMsg_AnswerVectorIndex   :='Answer Vector index must be between 1 and %d';
  TeeMsg_FittingError        :='Cannot process fitting';
  TeeMsg_PeriodRange         :='Period must be >= 0';
  TeeMsg_ExpAverageWeight    :='ExpAverage Weight must be between 0 and 1';
  TeeMsg_GalleryErrorBar     :='Error Bar';
  TeeMsg_GalleryError        :='Error';
  TeeMsg_GalleryHighLow      :='High-Low';
  TeeMsg_FunctionMomentum    :='Momentum';
  TeeMsg_FunctionMomentumDiv :='Momentum Div';
  TeeMsg_FunctionExpAverage  :='Exp. Average';
  TeeMsg_FunctionMovingAverage:='Moving Avrg.';
  TeeMsg_FunctionExpMovAve   :='Exp.Mov.Avrg.';
  TeeMsg_FunctionRSI         :='R.S.I.';
  TeeMsg_FunctionCurveFitting:='Curve Fitting';
  TeeMsg_FunctionTrend       :='Trend';
  TeeMsg_FunctionExpTrend    :='Exp.Trend';
  TeeMsg_FunctionLogTrend    :='Log.Trend';
  TeeMsg_FunctionCumulative  :='Cumulative';
  TeeMsg_FunctionStdDeviation:='Std.Deviation';
  TeeMsg_FunctionBollinger   :='Bollinger';
  TeeMsg_FunctionRMS         :='Root Mean Sq.';
  TeeMsg_FunctionMACD        :='MACD';
  TeeMsg_FunctionStochastic  :='Stochastic';
  TeeMsg_FunctionADX         :='ADX';

  TeeMsg_FunctionCount       :='Count';
  TeeMsg_LoadChart           :='Open TeeChart...';
  TeeMsg_SaveChart           :='Save TeeChart...';
  TeeMsg_TeeFiles            :='TeeChart Pro files';

  TeeMsg_GallerySamples      :='Other';
  TeeMsg_GalleryStats        :='Stats';

  TeeMsg_CannotFindEditor    :='Cannot find Series editor Form: %s';


  TeeMsg_CannotLoadChartFromURL:='Error code: %d downloading Chart from URL: %s';
  TeeMsg_CannotLoadSeriesDataFromURL:='Error code: %d downloading Series data from URL: %s';

  TeeMsg_Test                :='Test...';

  TeeMsg_ValuesDate          :='Date';
  TeeMsg_ValuesOpen          :='Open';
  TeeMsg_ValuesHigh          :='High';
  TeeMsg_ValuesLow           :='Low';
  TeeMsg_ValuesClose         :='Close';
  TeeMsg_ValuesOffset        :='Offset';
  TeeMsg_ValuesStdError      :='StdError';

  TeeMsg_Grid3D              :='Grid 3D';

  TeeMsg_LowBezierPoints     :='Number of Bezier points should be > 1';

  { TeeCommander component... }

  TeeCommanMsg_Normal   :='Normal';
  TeeCommanMsg_Edit     :='Edit';
  TeeCommanMsg_Print    :='Print';
  TeeCommanMsg_Copy     :='Copy';
  TeeCommanMsg_Save     :='Save';
  TeeCommanMsg_3D       :='3D';

  TeeCommanMsg_Rotating :='Rotation: %d° Elevation: %d°';
  TeeCommanMsg_Rotate   :='Rotate';

  TeeCommanMsg_Moving   :='Horiz.Offset: %d Vert.Offset: %d';
  TeeCommanMsg_Move     :='Move';

  TeeCommanMsg_Zooming  :='Zoom: %d %%';
  TeeCommanMsg_Zoom     :='Zoom';

  TeeCommanMsg_Depthing :='3D: %d %%';
  TeeCommanMsg_Depth    :='Depth';

  TeeCommanMsg_Chart    :='Chart';
  TeeCommanMsg_Panel    :='Panel';

  TeeCommanMsg_RotateLabel:='Drag %s to Rotate';
  TeeCommanMsg_MoveLabel  :='Drag %s to Move';
  TeeCommanMsg_ZoomLabel  :='Drag %s to Zoom';
  TeeCommanMsg_DepthLabel :='Drag %s to resize 3D';

  TeeCommanMsg_NormalLabel:='Drag Left button to Zoom, Right button to Scroll';
  TeeCommanMsg_NormalPieLabel:='Drag a Pie Slice to Explode it';

  TeeCommanMsg_PieExploding :='Slice: %d Exploded: %d %%';

  TeeMsg_TriSurfaceLess        :='Number of points must be >= 4';
  TeeMsg_TriSurfaceAllColinear :='All colinear data points';
  TeeMsg_TriSurfaceSimilar     :='Similar points - cannot execute';
  TeeMsg_GalleryTriSurface     :='Triangle Surf.';

  TeeMsg_AllSeries :='All Series';
  TeeMsg_Edit      :='Edit';

  TeeMsg_GalleryFinancial    :='Financial';

  TeeMsg_CursorTool    :='Cursor';
  TeeMsg_DragMarksTool :='Drag Marks';
  TeeMsg_AxisArrowTool :='Axis Arrows';
  TeeMsg_DrawLineTool  :='Draw Line';
  TeeMsg_NearestTool   :='Nearest Point';
  TeeMsg_ColorBandTool :='Color Band';
  TeeMsg_ColorLineTool :='Color Line';
  TeeMsg_RotateTool    :='Rotate';
  TeeMsg_ImageTool     :='Image';
  TeeMsg_MarksTipTool  :='Mark Tips';

  TeeMsg_CantDeleteAncestor  :='Can not delete ancestor';

  TeeMsg_Load	          :='Load...';
  TeeMsg_NoSeriesSelected :='No Series selected';

  { TeeChart Actions }
  TeeMsg_CategoryChartActions  :='Chart';
  TeeMsg_CategorySeriesActions :='Chart Series';

  TeeMsg_Action3D               := '&3D';
  TeeMsg_Action3DHint           := 'Switch 2D / 3D';
  TeeMsg_ActionSeriesActive     := '&Active';
  TeeMsg_ActionSeriesActiveHint := 'Show / Hide Series';
  TeeMsg_ActionEditHint         := 'Edit Chart';
  TeeMsg_ActionEdit             := '&Edit...';
  TeeMsg_ActionCopyHint         := 'Copy to Clipboard';
  TeeMsg_ActionCopy             := '&Copy';
  TeeMsg_ActionPrintHint        := 'Print preview Chart';
  TeeMsg_ActionPrint            := '&Print...';
  TeeMsg_ActionAxesHint         := 'Show / Hide Axes';
  TeeMsg_ActionAxes             := '&Axes';
  TeeMsg_ActionGridsHint        := 'Show / Hide Grids';
  TeeMsg_ActionGrids            := '&Grids';
  TeeMsg_ActionLegendHint       := 'Show / Hide Legend';
  TeeMsg_ActionLegend           := '&Legend';
  TeeMsg_ActionSeriesEditHint   := 'Edit Series';
  TeeMsg_ActionSeriesMarksHint  := 'Show / Hide Series Marks';
  TeeMsg_ActionSeriesMarks      := '&Marks';
  TeeMsg_ActionSaveHint         := 'Save Chart';
  TeeMsg_ActionSave             := '&Save...';

  TeeMsg_CandleBar              := 'Bar';
  TeeMsg_CandleNoOpen           := 'No Open';
  TeeMsg_CandleNoClose          := 'No Close';
  TeeMsg_NoLines                := 'No Lines';
  TeeMsg_NoHigh                 := 'No High';
  TeeMsg_NoLow                  := 'No Low';
  TeeMsg_ColorRange             := 'Color Range';
  TeeMsg_WireFrame              := 'Wireframe';
  TeeMsg_DotFrame               := 'Dot Frame';
  TeeMsg_Positions              := 'Positions';
  TeeMsg_NoGrid                 := 'No Grid';
  TeeMsg_NoPoint                := 'No Point';
  TeeMsg_NoLine                 := 'No Line';
  TeeMsg_Labels                 := 'Labels';
  TeeMsg_NoCircle               := 'No Circle';
  TeeMsg_Lines                  := 'Lines';
  TeeMsg_Border                 := 'Border';

  TeeMsg_SmithResistance      := 'Resistance';
  TeeMsg_SmithReactance       := 'Reactance';

  TeeMsg_Column               := 'Column';

  { 5.01 }
  TeeMsg_Separator            := 'Separator';
  TeeMsg_FunnelSegment        := 'Segment ';
  TeeMsg_FunnelSeries         := 'Funnel';
  TeeMsg_FunnelPercent        := '0.00 %';
  TeeMsg_FunnelExceed         := 'Exceeds quota';
  TeeMsg_FunnelWithin         := ' within quota';
  TeeMsg_FunnelBelow          := ' or more below quota';
  TeeMsg_CalendarSeries       := 'Calendar';
  TeeMsg_DeltaPointSeries     := 'DeltaPoint';
  TeeMsg_ImagePointSeries     := 'ImagePoint';
  TeeMsg_ImageBarSeries       := 'ImageBar';
  TeeMsg_SeriesTextFieldZero  := 'SeriesText: Field index should be greater than zero.';

  { 5.02 }
  TeeMsg_Origin               := 'Origin';
  TeeMsg_Transparency         := 'Transparency';
  TeeMsg_Box		      := 'Box';
  TeeMsg_ExtrOut	      := 'ExtrOut';
  TeeMsg_MildOut	      := 'MildOut';
  TeeMsg_PageNumber	      := 'Page Number';
  TeeMsg_TextFile             := 'Text File';


  { 5.03 }
  TeeMsg_DragPoint            := 'Drag Point';
  TeeMsg_OpportunityValues    := 'OpportunityValues';
  TeeMsg_QuoteValues          := 'QuoteValues';

  {AX 5.0.4}
  TeeMsg_ActiveXVersion      := 'ActiveX Release ' + AXVer;
  TeeMsg_ActiveXCannotImport := 'Cannot import TeeChart from %s';
  TeeMsg_ActiveXVerbPrint    := '&Print Preview...';
  TeeMsg_ActiveXVerbExport   := 'E&xport...';
  TeeMsg_ActiveXVerbImport   := '&Import...';
  TeeMsg_ActiveXVerbHelp     := '&Help...';
  TeeMsg_ActiveXVerbAbout    := '&About TeeChart...';
  TeeMsg_ActiveXError        := 'TeeChart: Error code: %d downloading: %s';
  TeeMsg_DatasourceError     := 'TeeChart DataSource is not a Series or RecordSet';
  TeeMsg_SeriesTextSrcError  := 'Invalid Series type';
  TeeMsg_AxisTextSrcError    := 'Invalid Axis type';
  TeeMsg_DelSeriesDatasource := 'Are you sure you want to delete %s ?';
  TeeMsg_OCXNoPrinter        := 'No default printer installed.';
  TeeMsg_ActiveXPictureNotValid :='Picture not valid';

  { 6.0 }
  TeeMsg_FunctionCustom   :='y = f(x)';
  TeeMsg_AsPDF            :='as &PDF';
  TeeMsg_PDFFilter        :='PDF files (*.pdf)|*.pdf';
  TeeMsg_AsPS             :='as PostScript';
  TeeMsg_PSFilter         :='PostScript files (*.eps)|*.eps';
  TeeMsg_GalleryHorizArea :='Horizontal'#13'Area';
  TeeMsg_SelfStack        :='Self Stacked';
  TeeMsg_DarkPen          :='Dark Border';
  TeeMsg_SelectFolder     :='Select database folder';
  TeeMsg_BDEAlias         :='&Alias:';
  TeeMsg_ADOConnection    :='&Connection:';

  // 6.02
  TeeMsg_Apply            :='&Apply';
  TeeMsg_AddNewGroup      :='Add new group';
  TeeMsg_ChangeGroupName  :='Change group name';
  TeeMsg_GroupName        :='Group name:';
  TeeMsg_FunctionMedian   :='Median';
  TeeMsg_FunctionMode     :='Mode';
  TeeMsg_Options          :='&Options...';
  TeeMsg_DepthTopAxis     :='Depth Top';


  { 6.0 }
  TeeMsg_FunctionSmooth       :='Smoothing';
  TeeMsg_FunctionCross        :='Cross Points';
  TeeMsg_GridTranspose        :='3D Grid Transpose';
  TeeMsg_FunctionCompress     :='Compression';
  TeeMsg_ExtraLegendTool      :='Extra Legend';
  TeeMsg_FunctionCLV          :='Close Location'#13'Value';
  TeeMsg_FunctionOBV          :='On Balance'#13'Volume';
  TeeMsg_FunctionCCI          :='Commodity'#13'Channel Index';
  TeeMsg_FunctionPVO          :='Volume'#13'Oscillator';
  TeeMsg_SeriesAnimTool       :='Series Animation';
  TeeMsg_GalleryPointFigure   :='Point & Figure';
  TeeMsg_Up                   :='Up';
  TeeMsg_Down                 :='Down';
  TeeMsg_GanttTool            :='Gantt Drag';
  TeeMsg_XMLFile              :='XML file';
  TeeMsg_GridBandTool         :='Grid Band';
  TeeMsg_FunctionPerf         :='Performance';
  TeeMsg_GalleryGauge         :='Gauge';
  TeeMsg_GalleryGauges        :='Gauges';
  TeeMsg_ValuesVectorEndZ     :='EndZ';
  TeeMsg_GalleryVector3D      :='Vector 3D';
  TeeMsg_Gallery3D            :='3D';
  TeeMsg_GalleryTower         :='Tower';
  TeeMsg_SingleColor          :='Single Color';
  TeeMsg_Cover                :='Cover';
  TeeMsg_Cone                 :='Cone';
  TeeMsg_PieTool              :='Pie Slices';

  // 7.0
  TeeMsg_Stop                 :='Stop';
  TeeMsg_Execute              :='Execute !';
  TeeMsg_Themes               :='Themes';
  TeeMsg_LightTool            :='2D Lighting';
  TeeMsg_Current              :='Current';
  TeeMsg_FunctionCorrelation  :='Correlation';
  TeeMsg_FunctionVariance     :='Variance';
  TeeMsg_GalleryBubble3D      :='Bubble 3D';
  TeeMsg_GalleryHorizHistogram:='Horizontal'#13'Histogram';
  TeeMsg_FunctionPerimeter    :='Perimeter';
  TeeMsg_SurfaceNearestTool   :='Surface Nearest';
end;

Procedure TeeCreateLithuanian;
begin
  if not Assigned(TeeLithuanianLanguage) then
  begin
    TeeLithuanianLanguage:=TStringList.Create;
    TeeLithuanianLanguage.Text:=

'GRADIENT EDITOR=Gradient editor'#13+
'GRADIENT=Gradient'#13+
'DIRECTION=Direction'#13+
'VISIBLE=Visible'#13+
'TOP BOTTOM=Top Bottom'#13+
'BOTTOM TOP=Bottom Top'#13+
'LEFT RIGHT=Left Right'#13+
'RIGHT LEFT=Right Left'#13+
'FROM CENTER=From Center'#13+
'FROM TOP LEFT=From Top Left'#13+
'FROM BOTTOM LEFT=From Bottom Left'#13+
'OK=Ok'#13+
'CANCEL=Cancel'#13+
'COLORS=Colors'#13+
'START=Start'#13+
'MIDDLE=Middle'#13+
'END=End'#13+
'SWAP=Swap'#13+
'NO MIDDLE=No middle'#13+
'TEEFONT EDITOR=Font Editor'#13+
'INTER-CHAR SPACING=Inter-Chart spacing'#13+
'FONT=Font'#13+
'SHADOW=Shadow'#13+
'HORIZ. SIZE=Horiz. size'#13+
'VERT. SIZE=Vert. size'#13+
'COLOR=Color'#13+
'OUTLINE=Outline'#13+
'OPTIONS=Options'#13+
'FORMAT=Format'#13+
'TEXT=Text'#13+
'GRADIENT=Gradient'#13+
'POSITION=Position'#13+
'LEFT=Left'#13+
'TOP=Top'#13+
'AUTO=Auto'#13+
'CUSTOM=Custom'#13+
'LEFT TOP=Left top'#13+
'LEFT BOTTOM=Left bottom'#13+
'RIGHT TOP=Right top'#13+
'RIGHT BOTTOM=Right bottom'#13+
'MULTIPLE AREAS=Mehrere Flächen'#13+
'NONE=None'#13+
'STACKED=Stacked'#13+
'STACKED 100%=Stacked 100%'#13+
'AREA=Area'#13+
'PATTERN=Pattern'#13+
'STAIRS=Stairs'#13+
'SOLID=Solid'#13+
'CLEAR=Clear'#13+
'HORIZONTAL=Horizontal'#13+
'VERTICAL=Vertical'#13+
'DIAGONAL=Diagonal'#13+
'B.DIAGONAL=B.Diagonal'#13+
'CROSS=Cross'#13+
'DIAG.CROSS=Diag.Cross'#13+
'AREA LINES=Area lines'#13+
'BORDER=Border'#13+
'INVERTED=Inverted'#13+
'INVERTED SCROLL=Inverted Scroll'#13+
'COLOR EACH=Color each'#13+
'ORIGIN=Origin'#13+
'USE ORIGIN=Use origin'#13+
'WIDTH=Width'#13+
'HEIGHT=Height'#13+
'AXIS=Axis'#13+
'LENGTH=Length'#13+
'SCROLL=Scroll'#13+
'PATTERN=Pattern'#13+
'START=Start'#13+
'END=End'#13+
'BOTH=Both'#13+
'AXIS INCREMENT=Axis increnent'#13+
'INCREMENT=Increment'#13+
'STANDARD=Standard'#13+
'CUSTOM=Custom'#13+
'ONE MILLISECOND=One Millisecond'#13+
'ONE SECOND=One Second'#13+
'FIVE SECONDS=Five Seconds'#13+
'TEN SECONDS=Ten Seconds'#13+
'FIFTEEN SECONDS=Fifteen Seconds'#13+
'THIRTY SECONDS=Thirty Seconds'#13+
'ONE MINUTE=One Minute'#13+
'FIVE MINUTES=Five Minutes'#13+
'TEN MINUTES=Ten Minutes'#13+
'FIFTEEN MINUTES=Fifteen Minutes'#13+
'THIRTY MINUTES=Thirty Minutes'#13+
'ONE HOUR=One Hour'#13+
'TWO HOURS=Two Hours'#13+
'SIX HOURS=Six Hours'#13+
'TWELVE HOURS=Twelve Hours'#13+
'ONE DAY=One Day'#13+
'TWO DAYS=Two Days'#13+
'THREE DAYS=Three Days'#13+
'ONE WEEK=One Week'#13+
'HALF MONTH=Half Month'#13+
'ONE MONTH=One Month'#13+
'TWO MONTHS=Two Months'#13+
'THREE MONTHS=Three Months'#13+
'FOUR MONTHS=Four Months'#13+
'SIX MONTHS=Six Months'#13+
'ONE YEAR=One Year'#13+
'EXACT DATE TIME=Exact date time'#13+
'AXIS MAXIMUM AND MINIMUM=Axis maximum and minimum'#13+
'VALUE=Value'#13+
'TIME=Time'#13+
'LEFT AXIS=Left axis'#13+
'RIGHT AXIS=Right axis'#13+
'TOP AXIS=Top axis'#13+
'BOTTOM AXIS=Bottom axis'#13+
'% BAR WIDTH=% Bar Width'#13+
'STYLE=Style'#13+
'% BAR OFFSET=% Bar offset'#13+
'RECTANGLE=Rectangle'#13+
'PYRAMID=Pyramid'#13+
'INVERT. PYRAMID=Invert. Pyramid'#13+
'CYLINDER=Cylinder'#13+
'ELLIPSE=Ellipse'#13+
'ARROW=Arrow'#13+
'RECT. GRADIENT=Rect. Gradient'#13+
'CONE=Cone'#13+
'DARK BAR 3D SIDES=Dark bar 3D Sides'#13+
'BAR SIDE MARGINS=Bar Side Margins'#13+
'AUTO MARK POSITION=Auto Mark Position'#13+
'BORDER=Border'#13+
'JOIN=Join'#13+
'BAR SIDE MARGINS=Bar Side Margins'#13+
'DATASET=Dataset'#13+
'APPLY=Apply'#13+
'SOURCE=Source'#13+
'MONOCHROME=Monochrome'#13+
'DEFAULT=Default'#13+
'2 (1 BIT)=2 (1 bit)'#13+
'16 (4 BIT)=16 (4 bit)'#13+
'256 (8 BIT)=256 (8 bit)'#13+
'32768 (15 BIT)=32768 (15 bit)'#13+
'65536 (16 BIT)=65536 (16 bit)'#13+
'16M (24 BIT)=16M (24 bit)'#13+
'16M (32 BIT)=16M (32 bit)'#13+
'LENGTH=Length'#13+
'MEDIAN=Median'#13+
'WHISKER=Whisker'#13+
'PATTERN COLOR EDITOR=Pattern Color Editor'#13+
'IMAGE=Image'#13+
'NONE=None'#13+
'BACK DIAGONAL=Back Diagonal'#13+
'CROSS=Cross'#13+
'DIAGONAL CROSS=Diagonal Cross'#13+
'FILL 80%=Fill 80%'#13+
'FILL 60%=Fill 60%'#13+
'FILL 40%=Fill 40%'#13+
'FILL 20%=Fill 20%'#13+
'FILL 10%=Fill 10%'#13+
'ZIG ZAG=Zig Zag'#13+
'VERTICAL SMALL=Vertical small'#13+
'HORIZ. SMALL=Horiz. small'#13+
'DIAG. SMALL=Diag. small'#13+
'BACK DIAG. SMALL=Back Diag.'#13+
'CROSS SMALL=Cross small'#13+
'DIAG. CROSS SMALL=Diag. Cross'#13+
'PATTERN COLOR EDITOR=Pattern Color Editor'#13+
'OPTIONS=Options'#13+
'DAYS=Days'#13+
'WEEKDAYS=Weekdays'#13+
'TODAY=Today'#13+
'SUNDAY=Sunday'#13+
'TRAILING=Trailing'#13+
'MONTHS=Months'#13+
'LINES=Lines'#13+
'SHOW WEEKDAYS=Show Weekdays'#13+
'UPPERCASE=Uppercase'#13+
'TRAILING DAYS=Trailing days'#13+
'SHOW TODAY=Show today'#13+
'SHOW MONTHS=Show Months'#13+
'CANDLE WIDTH=Candle Width'#13+
'STICK=Stick'#13+
'BAR=Bar'#13+
'OPEN CLOSE=Open Close'#13+
'UP CLOSE=Farbe Steigend'#13+
'DOWN CLOSE=Farbe Fallend'#13+
'SHOW OPEN=Eröffnung'#13+
'SHOW CLOSE=Schluß'#13+
'DRAW 3D=3D'#13+
'DARK 3D=3D Dunkel'#13+
'EDITING=Bearbeiten'#13+
'CHART=Chart'#13+
'SERIES=Reihe'#13+
'DATA=Daten'#13+
'TOOLS=Tools'#13+
'EXPORT=Exportieren'#13+
'PRINT=Drucken'#13+
'GENERAL=Allgemein'#13+
'TITLES=Titel'#13+
'LEGEND=Legende'#13+
'PANEL=Rand'#13+
'PAGING=Seite'#13+
'WALLS=Wand'#13+
'3D=3D'#13+
'ADD=Hinzufügen'#13+
'DELETE=Entfernen'#13+
'TITLE=Name'#13+
'CLONE=Dublizieren'#13+
'CHANGE=Ändern'#13+
'HELP=Hilfe'#13+
'CLOSE=Schließen'#13+
'IMAGE=Bild'#13+
'TEECHART PRINT PREVIEW=TeeChart Druckansicht'#13+
'PRINTER=Drucker'#13+
'SETUP=Eigenscha.'#13+
'ORIENTATION=Ausrichtung'#13+
'PORTRAIT=Hochformat'#13+
'LANDSCAPE=Querformat'#13+
'MARGINS (%)=Rand (%)'#13+
'DETAIL=Detail'#13+
'MORE=Mehr'#13+
'NORMAL=Normal'#13+
'RESET MARGINS=Zurücksetzen'#13+
'VIEW MARGINS=Rand anzeigen'#13+
'PROPORTIONAL=Proportional'#13+
'TEECHART PRINT PREVIEW=TeeChart Druckansicht'#13+
'RECTANGLE=Rectangle'#13+
'CIRCLE=Circle'#13+
'VERTICAL LINE=Vert. Linie'#13+
'HORIZ. LINE=Horiz. Linie'#13+
'TRIANGLE=Dreieck'#13+
'INVERT. TRIANGLE=Kopfst. Dreieck'#13+
'LINE=Linie'#13+
'DIAMOND=Diamant'#13+
'CUBE=Würfel'#13+
'DIAGONAL CROSS=Diagonal Kreuz'#13+
'STAR=Stern'#13+
'TRANSPARENT=Transparent'#13+
'HORIZ. ALIGNMENT=Horiz. Ausrichtung'#13+
'LEFT=Links'#13+
'CENTER=Mitte'#13+
'RIGHT=Rechts'#13+
'ROUND RECTANGLE=Rechteck abrunden'#13+
'ALIGNMENT=Ausrichtung'#13+
'TOP=Oben'#13+
'BOTTOM=Unten'#13+
'RIGHT=:Right'#13+
'BOTTOM=Bottom'#13+
'UNITS=Units'#13+
'PIXELS=Pixels'#13+
'AXIS=Axis'#13+
'AXIS ORIGIN=Axis Origin'#13+
'ROTATION=Drehung'#13+
'CIRCLED=Rund'#13+
'3 DIMENSIONS=3 Dimensional'#13+
'RADIUS=Radius'#13+
'ANGLE INCREMENT=Schrittweite Winkel'#13+
'RADIUS INCREMENT=Schrittweite Radius'#13+
'CLOSE CIRCLE=Kreisrund'#13+
'PEN=Stift'#13+
'CIRCLE=Kreis'#13+
'LABELS=Beschriftung'#13+
'VISIBLE=Anzeig.'#13+
'ROTATED=Gedreht'#13+
'CLOCKWISE=Uhrzeigersinn'#13+
'INSIDE=Innen'#13+
'ROMAN=Roman'#13+
'HOURS=Stunden'#13+
'MINUTES=Minuten'#13+
'SECONDS=Sekunden'#13+
'START VALUE=Startwert'#13+
'END VALUE=Endwert'#13+
'TRANSPARENCY=Transparenz'#13+
'DRAW BEHIND=Dahinter zeichnen'#13+
'COLOR MODE=Farbmodus'#13+
'STEPS=Schritte'#13+
'RANGE=Bereich'#13+
'PALETTE=Palette'#13+
'PALE=Blaß'#13+
'STRONG=Stark'#13+
'GRID SIZE=Gittergröße'#13+
'X=X'#13+
'Z=Z'#13+
'DEPTH=Tiefe'#13+
'IRREGULAR=Irregulär'#13+
'GRID=Gitter'#13+
'VALUE=Wert'#13+
'ALLOW DRAG=Ziehen erlauben'#13+
'VERTICAL POSITION=Vertikale Position'#13+
'PEN=Linien'#13+
'LEVELS POSITION=Ebenen Position'#13+
'LEVELS=Ebenen'#13+
'NUMBER=Anzahl'#13+
'LEVEL=Ebenen'#13+
'AUTOMATIC=Automatisch'#13+
'BOTH=Beide'#13+
'SNAP=Snap'#13+
'FOLLOW MOUSE=Maus folgen'#13+
'STACK=Stapel'#13+
'HEIGHT 3D=3D Höhe'#13+
'LINE MODE=Linien Modus'#13+
'STAIRS=Stufen'#13+
'NONE=None'#13+
'OVERLAP=Overlap'#13+
'STACK=Stack'#13+
'STACK 100%=Stack 100%'#13+
'CLICKABLE=Mausclick'#13+
'LABELS=Labels'#13+
'AVAILABLE=Vorhanden'#13+
'SELECTED=Ausgewählt'#13+
'DATASOURCE=Datenquelle'#13+
'GROUP BY=Group by'#13+
'CALC=Calc'#13+
'OF=of'#13+
'SUM=Sum'#13+
'COUNT=Count'#13+
'HIGH=High'#13+
'LOW=Low'#13+
'AVG=Avg'#13+
'HOUR=Hour'#13+
'DAY=Day'#13+
'WEEK=Week'#13+
'WEEKDAY=WeekDay'#13+
'MONTH=Month'#13+
'QUARTER=Quarter'#13+
'YEAR=Year'#13+
'HOLE %=Loch %'#13+
'RESET POSITIONS=Positionen rücksetzen'#13+
'MOUSE BUTTON=Maustaste'#13+
'ENABLE DRAWING=Zeichnung erlauben'#13+
'ENABLE SELECT=Auswahl erlauben'#13+
'ENHANCED=Erhöht'#13+
'ERROR WIDTH=Fehler T Breite'#13+
'WIDTH UNITS=T Breite'#13+
'PERCENT=Prozent'#13+
'PIXELS=Pixel'#13+
'LEFT AND RIGHT=Links und Rechts'#13+
'TOP AND BOTTOM=Oben und Unten'#13+
'BORDER=Fehler Linie'#13+
'BORDER EDITOR=Grenz Editor'#13+
'DASH=Durchgezogen'#13+
'DOT=Gestrichelt'#13+
'DASH DOT=Punkt'#13+
'DASH DOT DOT=Strich Punkt'#13+
'CALCULATE EVERY=Jede berechnen'#13+
'ALL POINTS=Alle Werte'#13+
'NUMBER OF POINTS=Anzahl der Werte'#13+
'RANGE OF VALUES=Wertereihe'#13+
'FIRST=Erster'#13+
'CENTER=Mittlerer'#13+
'LAST=Letzter'#13+
'TEEPREVIEW EDITOR=TeeVorschau Editor'#13+
'ALLOW MOVE=Bewegung erlauben'#13+
'ALLOW RESIZE=Resize erlauben'#13+
'DRAG IMAGE=Grafik ziehen'#13+
'AS BITMAP=Als Bitmap'#13+
'SHOW IMAGE=Grafik anzeigen'#13+
'DEFAULT=Voreinstellung'#13+
'MARGINS=Abstände'#13+
'SIZE=Größe'#13+
'3D %=3D %'#13+
'ZOOM=Zoom'#13+
'ROTATION=Rotation'#13+
'ELEVATION=Blickwinkel'#13+
'100%=100%'#13+
'HORIZ. OFFSET=Horiz. Offset'#13+
'VERT. OFFSET=Vert. Offset'#13+
'PERSPECTIVE=Perspektive'#13+
'ANGLE=Winkel'#13+
'ORTHOGONAL=Orthogonal'#13+
'ZOOM TEXT=Zoom Text'#13+
'SCALES=Skalierung'#13+
'TITLE=Title'#13+
'TICKS=Ticks'#13+
'MINOR=Unterticks'#13+
'MAXIMUM=Maximum'#13+
'MINIMUM=Minimum'#13+
'(MAX)=(max)'#13+
'(MIN)=(min)'#13+
'DESIRED INCREMENT=Schrittweite'#13+
'(INCREMENT)=(increment)'#13+
'LOG BASE=Log Basis'#13+
'LOGARITHMIC=Logarithmisch'#13+
'TITLE=Titel'#13+
'MIN. SEPARATION %=Min. Abstand %'#13+
'MULTI-LINE=Multi-linie'#13+
'LABEL ON AXIS=Beschriftung auf Achsen'#13+
'ROUND FIRST=Ersten Runden'#13+
'MARK=Mark.'#13+
'LABELS FORMAT=Beschrift.- Format'#13+
'EXPONENTIAL=Exponential'#13+
'DEFAULT ALIGNMENT=Voreinstellung Abstand'#13+
'LEN=Länge'#13+
'LENGTH=Länge'#13+
'AXIS=Achsgrenzen'#13+
'INNER=Inner'#13+
'GRID=Gitternetz'#13+
'AT LABELS ONLY=Nur Beschriftung'#13+
'CENTERED=Mittig'#13+
'COUNT=Anzahl'#13+
'TICKS=Unterticks'#13+
'POSITION %=Position %'#13+
'START %=Beginn %'#13+
'END %=Ende %'#13+
'OTHER SIDE=Andere Seite'#13+
'AXES=Achsen'#13+
'BEHIND=Hinten'#13+
'CLIP POINTS=Clip Points'#13+
'PRINT PREVIEW=Seitenansicht'#13+
'MINIMUM PIXELS=Minimum Pixel'#13+
'MOUSE BUTTON=Maus-Click'#13+
'ALLOW=Zoom Ein/Aus'#13+
'ANIMATED=Gleitend'#13+
'VERTICAL=Vertical'#13+
'RIGHT=Right'#13+
'MIDDLE=Middle'#13+
'ALLOW SCROLL=Scroll'#13+
'TEEOPENGL EDITOR=TeeOpenGL Editor'#13+
'AMBIENT LIGHT=Umgebung'#13+
'SHININESS=Beleuchtung'#13+
'FONT 3D DEPTH=3D Schrift-Tiefe'#13+
'ACTIVE=Aktiv'#13+
'FONT OUTLINES=Umriß Schrift'#13+
'SMOOTH SHADING=Fließender Schatten'#13+
'LIGHT=Licht'#13+
'Y=Y'#13+
'INTENSITY=Intensität'#13+
'BEVEL=Schräge'#13+
'FRAME=Rahmen'#13+
'ROUND FRAME=Runder Rahmen'#13+
'LOWERED=Hinter'#13+
'RAISED=Hervor'#13+
'POSITION=Ausrichtung'#13+
'SYMBOLS=Symbole'#13+
'TEXT STYLE=Textstil'#13+
'LEGEND STYLE=Legendenstil'#13+
'VERT. SPACING=Vert. Abstand'#13+
'AUTOMATIC=Automatic'#13+
'SERIES NAMES=Series Names'#13+
'SERIES VALUES=Series Values'#13+
'LAST VALUES=Last Values'#13+
'PLAIN=Plain'#13+
'LEFT VALUE=Left Value'#13+
'RIGHT VALUE=Right Value'#13+
'LEFT PERCENT=Left Percent'#13+
'RIGHT PERCENT=Right Percent'#13+
'X VALUE=X Value'#13+
'VALUE=Value'#13+
'PERCENT=Percent'#13+
'X AND VALUE=X and Value'#13+
'X AND PERCENT=X and Percent'#13+
'CHECK BOXES=Check-Boxen'#13+
'DIVIDING LINES=Trennlinie'#13+
'FONT SERIES COLOR=Chart-Farbe'#13+
'POSITION OFFSET %=Abstand Oben %'#13+
'MARGIN=Rand'#13+
'RESIZE CHART=Originalgröße'#13+
'CUSTOM=Benutzerdef.'#13+
'WIDTH UNITS=Einheit'#13+
'CONTINUOUS=Fortlaufend'#13+
'POINTS PER PAGE=Werte pro Seite'#13+
'SCALE LAST PAGE=Letzte Seite Einteilen'#13+
'CURRENT PAGE LEGEND=Aktuelle Legende'#13+
'PANEL EDITOR=Hintergrund Editor'#13+
'BACKGROUND=Hintergrund'#13+
'BORDERS=Rand'#13+
'BACK IMAGE=Hintergrund'#13+
'STRETCH=Dehnen'#13+
'TILE=Ausfüllen'#13+
'CENTER=Mittig'#13+
'BEVEL INNER=Innen'#13+
'LOWERED=Hinten'#13+
'RAISED=Vorn'#13+
'BEVEL OUTER=Außen'#13+
'MARKS=Marks'#13+
'DATA SOURCE=Datei'#13+
'SORT=Sortieren'#13+
'CURSOR=Cursor'#13+
'SHOW IN LEGEND=In Legende Anzeigen'#13+
'FORMATS=Formate'#13+
'VALUES=Werte'#13+
'PERCENTS=Prozente'#13+
'HORIZONTAL AXIS=Horizontale Achse'#13+
'TOP AND BOTTOM=Beide'#13+
'DATETIME=Datum/Uhrzeit'#13+
'VERTICAL AXIS=Vertikale Achse'#13+
'LEFT=Oben'#13+
'RIGHT=Unten'#13+
'LEFT AND RIGHT=Beide'#13+
'ASCENDING=Aufsteigend'#13+
'DESCENDING=Absteigend'#13+
'DRAW EVERY=Alle zeichnen'#13+
'CLIPPED=Schneiden'#13+
'ARROWS=Pfeile'#13+
'MULTI LINE=Multi-linie'#13+
'ALL SERIES VISIBLE=Alle Reihen anzeigen'#13+
'LABEL=Label'#13+
'LABEL AND PERCENT=Label und Prozent'#13+
'LABEL AND VALUE=Label und Wert'#13+
'PERCENT TOTAL=Prozent Total'#13+
'LABEL & PERCENT TOTAL=Label & Prozent Total'#13+
'X VALUE=X Wert'#13+
'X AND Y VALUES=X und Y Werte'#13+
'MANUAL=Manuell'#13+
'RANDOM=Zufall'#13+
'FUNCTION=Funktion'#13+
'NEW=Neu'#13+
'EDIT=Bearbeiten'#13+
'DELETE=Löschung'#13+
'PERSISTENT=Ständig'#13+
'ADJUST FRAME=Rahmen fest'#13+
'SUBTITLE=Untertitel'#13+
'SUBFOOT=Fußzeile'#13+
'FOOT=2. Fußzeile'#13+
'DELETE=Löschen'#13+
'VISIBLE WALLS=Wände Anzeigen'#13+
'BACK=Hinten'#13+
'DIF. LIMIT=Dif. Limit'#13+
'LINES=Trennlinien'#13+
'ABOVE=Über'#13+
'WITHIN=Innerhalb'#13+
'BELOW=Unter'#13+
'CONNECTING LINES=Verknüpfungslinien'#13+
'SERIES=Konstant'#13+
'PALE=Pale'#13+
'STRONG=Strong'#13+
'HIGH=Oben'#13+
'LOW=Unten'#13+
'BROWSE=Suchen in'#13+
'TILED=Ausgefüllt'#13+
'INFLATE MARGINS=Randabstand'#13+
'SQUARE=Quadrat'#13+
'DOWN TRIANGLE=Kopfst. Dreieck'#13+
'SMALL DOT=Kleine Punkte'#13+
'DEFAULT=Voreinst.'#13+
'GLOBAL=Global'#13+
'SHAPES=Formen'#13+
'BRUSH=Pinsel'#13+
'BRUSH=Brush'#13+
'BORDER=Border'#13+
'COLOR=Color'#13+
'DELAY=Verzögerung'#13+
'MSEC.=msec.'#13+
'MOUSE ACTION=Mausaktion'#13+
'MOVE=Bewegen'#13+
'CLICK=Click'#13+
'BRUSH=Hintergrund'#13+
'DRAW LINE=Linie zeichnen'#13+
'BORDER EDITOR=Grenz Farben Editor'#13+
'DASH=Solid'#13+
'DOT=Dash'#13+
'DASH DOT=Dot'#13+
'DASH DOT DOT=Dash Dot'#13+
'EXPLODE BIGGEST=Größter Extra'#13+
'TOTAL ANGLE=Gesamtwinkel'#13+
'GROUP SLICES=Gruppierung'#13+
'BELOW %=Below %'#13+
'BELOW VALUE=Below Value'#13+
'OTHER=Other'#13+
'PATTERNS=Muster'#13+
'CLOSE CIRCLE=Schließen'#13+
'VISIBLE=Zeigen'#13+
'CLOCKWISE=Uhrwärts'#13+
'SIZE %=Größe %'#13+
'PATTERN=Hintergrund'#13+
'DEFAULT=Vorher'#13+
'SERIES DATASOURCE TEXT EDITOR=DatenquellenText Editor'#13+
'FIELDS=Felder'#13+
'NUMBER OF HEADER LINES=Anzahl der  Titelzeilen'#13+
'SEPARATOR=Teilung'#13+
'COMMA=Komma'#13+
'SPACE=Space'#13+
'TAB=Tabulator'#13+
'FILE=File'#13+
'WEB URL=Web URL'#13+
'LOAD=Laden'#13+
'C LABELS=C Labels'#13+
'R LABELS=R Labels'#13+
'C PEN=C Stift'#13+
'R PEN=R Stift'#13+
'STACK GROUP=Stapel gruppieren'#13+
'USE ORIGIN=Ursprung'#13+
'MULTIPLE BAR=Mehrere Säulen'#13+
'SIDE=Nebeneinander'#13+
'STACKED 100%=Stacked 100%'#13+
'SIDE ALL=Alle Nebeneinander'#13+
'BRUSH=Muster..'#13+
'DRAWING MODE=Zeichnungsmodus'#13+
'SOLID=Voll'#13+
'WIREFRAME=Gitternetz'#13+
'DOTFRAME=Punktnetz'#13+
'SMOOTH PALETTE=Weicher Übergang'#13+
'SIDE BRUSH=Seitenmuster'#13+
'ABOUT TEECHART PRO V7.0=Info TeeChart Pro v7.0'#13+
'ALL RIGHTS RESERVED.=All Rights Reserved.'#13+
'VISIT OUR WEB SITE !=Visit our Web site !'#13+
'TEECHART WIZARD=TeeChart Wizard'#13+
'SELECT A CHART STYLE=Chart Stil auswählen'#13+
'DATABASE CHART=Datenbank-Chart'#13+
'NON DATABASE CHART=Kein Datenbank-Chart'#13+
'SELECT A DATABASE TABLE=Select a Database Table'#13+
'ALIAS=Alias'#13+
'TABLE=Table'#13+
'SOURCE=Source'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'MICROSOFT ADO=Microsoft ADO'#13+
'SELECT THE DESIRED FIELDS TO CHART=Select the desired Fields to Chart'#13+
'SELECT A TEXT LABELS FIELD=Select a text labels Field'#13+
'CHOOSE THE DESIRED CHART TYPE=Choose the desired Chart type'#13+
'2D=2D'#13+
'CHART PREVIEW=Chart Preview'#13+
'SHOW LEGEND=Show Legend'#13+
'SHOW MARKS=Show Marks'#13+
'< BACK=< Vorheriger'#13+
'SELECT A CHART STYLE=Chart Stil auswählen'#13+
'NON DATABASE CHART=Kein Datenbank-Chart'#13+
'SELECT A DATABASE TABLE=Select a Database Table'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'SELECT THE DESIRED FIELDS TO CHART=Select the desired Fields to Chart'#13+
'SELECT A TEXT LABELS FIELD=Select a text labels Field'#13+
'CHOOSE THE DESIRED CHART TYPE=Choose the desired Chart type'#13+
'EXPORT CHART=Chart Exportieren'#13+
'PICTURE=Bild'#13+
'NATIVE=TeeFile'#13+
'KEEP ASPECT RATIO=Verhältnis beibehalten'#13+
'INCLUDE SERIES DATA=Inklusive Reihendaten'#13+
'FILE SIZE=File-Größe'#13+
'DELIMITER=Abgrenzung'#13+
'XML=XML'#13+
'HTML TABLE=HTML Table'#13+
'EXCEL=Excel'#13+
'TAB=Tab'#13+
'COLON=Doppelpunkt'#13+
'INCLUDE=Inklusive'#13+
'POINT LABELS=Labels anzeigen'#13+
'POINT INDEX=Index anzeigen'#13+
'HEADER=Kopfzeile'#13+
'COPY=Kopieren'#13+
'SAVE=Speichern'#13+
'SEND=Senden'#13+
'KEEP ASPECT RATIO=Verhältnis beibehalten'#13+
'INCLUDE SERIES DATA=Inklusive Reihendaten'#13+
'FUNCTIONS=Funktionen'#13+
'ADD=Addieren'#13+
'ADX=ADX'#13+
'AVERAGE=Bollinger'#13+
'BOLLINGER=Dividieren'#13+
'COPY=Durchschnitt'#13+
'DIVIDE=Exp.Durchschn.'#13+
'EXP. AVERAGE=Exp.Gleit.Durchschn.'#13+
'EXP.MOV.AVRG.=Gleit.Durchschn.'#13+
'HIGH=Hoch'#13+
'LOW=Kopie'#13+
'MACD=MACD'#13+
'MOMENTUM=Momentum'#13+
'MOMENTUM DIV=Momentum Div'#13+
'MOVING AVRG.=Multiplizieren'#13+
'MULTIPLY=R.S.I.'#13+
'R.S.I.=Std.-Abweichung'#13+
'ROOT MEAN SQ.=Stochastik'#13+
'STD.DEVIATION=Subtrahieren'#13+
'STOCHASTIC=Tief'#13+
'SUBTRACT=Wurzel Mean Sq.'#13+
'APPLY=Hinzufügen'#13+
'SOURCE SERIES=Quellreihe'#13+
'TEECHART GALLERY=TeeChart Gallerie'#13+
'FUNCTIONS=Funktion'#13+
'DITHER=Dither'#13+
'REDUCTION=Reduction'#13+
'COMPRESSION=Compression'#13+
'LZW=LZW'#13+
'RLE=RLE'#13+
'NEAREST=Nearest'#13+
'FLOYD STEINBERG=Floyd Steinberg'#13+
'STUCKI=Stucki'#13+
'SIERRA=Sierra'#13+
'JAJUNI=JaJuNI'#13+
'STEVE ARCHE=Steve Arche'#13+
'BURKES=Burkes'#13+
'WINDOWS 20=Windows 20'#13+
'WINDOWS 256=Windows 256'#13+
'WINDOWS GRAY=Windows Gray'#13+
'MONOCHROME=Monochrome'#13+
'GRAY SCALE=Gray Scale'#13+
'NETSCAPE=Netscape'#13+
'QUANTIZE=Quantize'#13+
'QUANTIZE 256=Quantize 256'#13+
'% QUALITY=% Qualität'#13+
'GRAY SCALE=Graustufe'#13+
'PERFORMANCE=Erscheinung'#13+
'QUALITY=Qualität'#13+
'SPEED=Schnell'#13+
'COMPRESSION LEVEL=Kompressionsgrad'#13+
'CHART TOOLS GALLERY=Chart Tools Gallerie'#13+
'ANNOTATION=Achspfeile'#13+
'AXIS ARROWS=Annotation'#13+
'COLOR BAND=Bild'#13+
'COLOR LINE=Cursor'#13+
'CURSOR=Drehen'#13+
'DRAG MARKS=Farbbreite'#13+
'DRAW LINE=Farbige Linie'#13+
'IMAGE=Linie zeichnen'#13+
'MARK TIPS=Markiere Tips'#13+
'NEAREST POINT=Nächster Punkt'#13+
'ROTATE=Zieh Marks'#13+
'CHART TOOLS GALLERY=Chart Tools Gallerie'#13+
'BRUSH=Schraffur'#13+
'DRAWING MODE=Zeichenmodus'#13+
'WIREFRAME=Drahtnetz'#13+
'SMOOTH PALETTE=Farbfluß'#13+
'SIDE BRUSH=Schraffur Seiten'#13+
'YES=Ja'#13+
'SIDE=Al lado'+#13+
'SIDE ALL=Lateral'+#13+
'ROTATE=Rotar'+#13+
'SMOOTH PALETTE=Paleta suavizada'+#13+
'CHART TOOLS GALLERY=Galería de Herramientas'+#13+
'ADD=Añadir'+#13+
'BORDER EDITOR=Editor de Borde'+#13+
'DRAWING MODE=Modo de Dibujo'+#13+
'CLOSE CIRCLE=Cerrar Círculo'+#13+
'PICTURE=Imagen'+#13+
'NATIVE=Nativo'+#13+
'DATA=Datos'+#13+
'KEEP ASPECT RATIO=Mantener proporción'+#13+
'COPY=Copiar'+#13+
'SAVE=Guardar'+#13+
'SEND=Enviar'+#13+
'INCLUDE SERIES DATA=Incluir Datos de Series'+#13+
'FILE SIZE=Tamaño del Archivo'+#13+
'INCLUDE=Incluir'+#13+
'POINT INDEX=Indice de Puntos'+#13+
'POINT LABELS=Etiquetas de Puntos'+#13+
'DELIMITER=Delimitador'+#13+
'DEPTH=Profund.'+#13+
'COMPRESSION LEVEL=Nivel Compresión'+#13+
'COMPRESSION=Compresión'+#13+
'PATTERNS=Tramas'+#13+
'LABEL=Etiqueta'+#13+
'GROUP SLICES=Agrupar porciones'+#13+
'EXPLODE BIGGEST=Separar Porción'+#13+
'TOTAL ANGLE=Angulo Total'+#13+
'HORIZ. SIZE=Tamaño Horiz.'+#13+
'VERT. SIZE=Tamaño Vert.'+#13+
'SHAPES=Formas'+#13+
'INFLATE MARGINS=Ampliar Márgenes'+#13+
'QUALITY=Calidad'+#13+
'SPEED=Velocidad'+#13+
'% QUALITY=% Calidad'+#13+
'GRAY SCALE=Escala de Grises'+#13+
'PERFORMANCE=Mejor'+#13+
'BROWSE=Seleccionar'+#13+
'TILED=Mosaico'+#13+
'HIGH=Alto'+#13+
'LOW=Bajo'+#13+
'DATABASE CHART=Gráfico con Base de Datos'+#13+
'NON DATABASE CHART=Gráfico sin Base de Datos'+#13+
'HELP=Ayuda'+#13+
'NEXT >=Siguiente >'+#13+
'< BACK=< Anterior'+#13+
'TEECHART WIZARD=Asistente de TeeChart'+#13+
'PERCENT=Porcentual'+#13+
'PIXELS=Pixels'+#13+
'ERROR WIDTH=Ancho Error'+#13+
'ENHANCED=Mejorado'+#13+
'VISIBLE WALLS=Ver Paredes'+#13+
'ACTIVE=Activo'+#13+
'DELETE=Borrar'+#13+
'ALIGNMENT=Alineación'+#13+
'ADJUST FRAME=Ajustar Marco'+#13+
'HORIZONTAL=Horizontal'+#13+
'VERTICAL=Vertical'+#13+
'VERTICAL POSITION=Posición Vertical'+#13+
'NUMBER=Número'+#13+
'LEVELS=Niveles'+#13+
'OVERLAP=Sobreponer'+#13+
'STACK 100%=Apilar 100%'+#13+
'MOVE=Mover'+#13+
'CLICK=Clic'+#13+
'DELAY=Retraso'+#13+
'DRAW LINE=Dibujar Línea'+#13+
'FUNCTIONS=Funciones'+#13+
'SOURCE SERIES=Series Origen'+#13+
'ABOVE=Arriba'+#13+
'BELOW=Abajo'+#13+
'Dif. Limit=Límite Dif.'+#13+
'WITHIN=Dentro'+#13+
'EXTENDED=Extendidas'+#13+
'STANDARD=Estandard'+#13+
'STATS=Estadística'+#13+
'FINANCIAL=Financieras'+#13+
'OTHER=Otras'+#13+
'TEECHART GALLERY=Galería de Gráficos TeeChart'+#13+
'CONNECTING LINES=Líneas de Conexión'+#13+
'REDUCTION=Reducción'+#13+
'LIGHT=Luz'+#13+
'INTENSITY=Intensidad'+#13+
'FONT OUTLINES=Borde Fuentes'+#13+
'SMOOTH SHADING=Sombras suaves'+#13+
'AMBIENT LIGHT=Luz Ambiente'+#13+
'MOUSE ACTION=Acción del Ratón'+#13+
'CLOCKWISE=Segun horario'+#13+
'ANGLE INCREMENT=Incremento Angulo'+#13+
'RADIUS INCREMENT=Incremento Radio'+#13+
'PRINTER=Impresora'+#13+
'SETUP=Opciones'+#13+
'ORIENTATION=Orientación'+#13+
'PORTRAIT=Vertical'+#13+
'LANDSCAPE=Horizontal'+#13+
'MARGINS (%)=Márgenes (%)'+#13+
'MARGINS=Márgenes'+#13+
'DETAIL=Detalle'+#13+
'MORE=Más'+#13+
'PROPORTIONAL=Proporcional'+#13+
'VIEW MARGINS=Ver Márgenes'+#13+
'RESET MARGINS=Márg. Defecto'+#13+
'PRINT=Imprimir'+#13+
'TEEPREVIEW EDITOR=Editor Impresión Preliminar'+#13+
'ALLOW MOVE=Permitir Mover'+#13+
'ALLOW RESIZE=Permitir Redimensionar'+#13+
'SHOW IMAGE=Ver Imagen'+#13+
'DRAG IMAGE=Arrastrar Imagen'+#13+
'AS BITMAP=Como mapa de bits'+#13+
'SIZE %=Tamaño %'+#13+
'FIELDS=Campos'+#13+
'SOURCE=Origen'+#13+
'SEPARATOR=Separador'+#13+
'NUMBER OF HEADER LINES=Líneas de cabecera'+#13+
'COMMA=Coma'+#13+
'EDITING=Editando'+#13+
'TAB=Tabulación'+#13+
'SPACE=Espacio'+#13+
'ROUND RECTANGLE=Rectáng. Redondeado'+#13+
'BOTTOM=Abajo'+#13+
'RIGHT=Derecha'+#13+
'C PEN=Lápiz C'+#13+
'R PEN=Lápiz R'+#13+
'C LABELS=Textos C'+#13+
'R LABELS=Textos R'+#13+
'MULTIPLE BAR=Barras Múltiples'+#13+
'MULTIPLE AREAS=Areas Múltiples'+#13+
'STACK GROUP=Grupo de Apilado'+#13+
'BOTH=Ambos'+#13+
'BACK DIAGONAL=Diagonal Invertida'+#13+
'B.DIAGONAL=Diagonal Invertida'+#13+
'DIAG.CROSS=Cruz en Diagonal'+#13+
'WHISKER=Whisker'+#13+
'CROSS=Cruz'+#13+
'DIAGONAL CROSS=Cruz en Diagonal'+#13+
'LEFT RIGHT=Izquierda Derecha'+#13+
'RIGHT LEFT=Derecha Izquierda'+#13+
'FROM CENTER=Desde el centro'+#13+
'FROM TOP LEFT=Desde Izq. Arriba'+#13+
'FROM BOTTOM LEFT=Desde Izq. Abajo'+#13+
'SHOW WEEKDAYS=Ver Laborables'+#13+
'SHOW MONTHS=Ver Meses'+#13+
'SHOW PREVIOUS BUTTON=Ver Botón Anterior'#13+
'SHOW NEXT BUTTON=Ver Botón Siguiente'#13+
'TRAILING DAYS=Ver otros Días'+#13+
'SHOW TODAY=Ver Hoy'+#13+
'TRAILING=Otros Días'+#13+
'LOWERED=Hundido'+#13+
'RAISED=Elevado'+#13+
'HORIZ. OFFSET=Desplaz. Horiz.'+#13+
'VERT. OFFSET=Desplaz. Vert.'+#13+
'INNER=Dentro'+#13+
'LEN=Long.'+#13+
'AT LABELS ONLY=Sólo en etiquetas'+#13+
'MAXIMUM=Máximo'+#13+
'MINIMUM=Mínimo'+#13+
'CHANGE=Cambiar'+#13+
'LOGARITHMIC=Logarítmico'+#13+
'LOG BASE=Base Log.'+#13+
'DESIRED INCREMENT=Incremento'+#13+
'(INCREMENT)=(Incremento)'+#13+
'MULTI-LINE=Multi-Línea'+#13+
'MULTI LINE=Multilínea'+#13+
'RESIZE CHART=Redim. Gráfico'+#13+
'X AND PERCENT=X y Porcentaje'+#13+
'X AND VALUE=X y Valor'+#13+
'RIGHT PERCENT=Porcentaje derecha'+#13+
'LEFT PERCENT=Porcentaje izquierda'+#13+
'LEFT VALUE=Valor izquierda'+#13+
'RIGHT VALUE=Valor derecha'+#13+
'PLAIN=Texto'+#13+
'LAST VALUES=Ultimos Valores'+#13+
'SERIES VALUES=Valores de Series'+#13+
'SERIES NAMES=Nombres de Series'+#13+
'NEW=Nuevo'+#13+
'EDIT=Editar'+#13+
'PANEL COLOR=Color de fondo'+#13+
'TOP BOTTOM=Arriba Abajo'+#13+
'BOTTOM TOP=Abajo Arriba'+#13+
'DEFAULT ALIGNMENT=Alineación defecto'+#13+
'EXPONENTIAL=Exponencial'+#13+
'LABELS FORMAT=Formato Etiquetas'+#13+
'MIN. SEPARATION %=Min. Separación %'+#13+
'YEAR=Año'+#13+
'MONTH=Mes'+#13+
'WEEK=Semana'+#13+
'WEEKDAY=Dia Laborable'+#13+
'MARK=Marcas'+#13+
'ROUND FIRST=Redondear primera'+#13+
'LABEL ON AXIS=Etiqueta en eje'+#13+
'COUNT=Número'+#13+
'POSITION %=Posición %'+#13+
'START %=Empieza %'+#13+
'END %=Termina %'+#13+
'OTHER SIDE=Lado opuesto'+#13+
'INTER-CHAR SPACING=Espacio entre caracteres'+#13+
'VERT. SPACING=Espaciado Vertical'+#13+
'POSITION OFFSET %=Desplazamiento %'+#13+
'GENERAL=General'+#13+
'MANUAL=Manual'+#13+
'PERSISTENT=Persistente'+#13+
'PANEL=Panel'+#13+
'ALIAS=Alias'+#13+
'2D=2D'+#13+
'ADX=ADX'+#13+
'BOLLINGER=Bollinger'+#13+
'TEEOPENGL EDITOR=Editor de OpenGL'+#13+
'FONT 3D DEPTH=Profund. Fuentes'+#13+
'NORMAL=Normal'+#13+
'TEEFONT EDITOR=Editor de Fuente'+#13+
'CLIP POINTS=Ocultar'+#13+
'CLIPPED=Oculta'+#13+
'3D %=3D %'+#13+
'QUANTIZE=Cuantifica'+#13+
'QUANTIZE 256=Cuantifica 256'+#13+
'DITHER=Reduce'+#13+
'VERTICAL SMALL=Vertical Pequeño'+#13+
'HORIZ. SMALL=Horizontal Pequeño'+#13+
'DIAG. SMALL=Diagonal Pequeño'+#13+
'BACK DIAG. SMALL=Diagonal Invert. Peq.'+#13+
'DIAG. CROSS SMALL=Cruz Diagonal Peq.'+#13+
'MINIMUM PIXELS=Mínimos pixels'+#13+
'ALLOW SCROLL=Permitir Desplaz.'+#13+
'SWAP=Cambiar'+#13+
'GRADIENT EDITOR=Editor de Gradiente'+#13+
'TEXT STYLE=Estilo de textos'+#13+
'DIVIDING LINES=Líneas de División'+#13+
'SYMBOLS=Símbolos'+#13+
'CHECK BOXES=Casillas'+#13+
'FONT SERIES COLOR=Color de Series'+#13+
'LEGEND STYLE=Estilo de Leyenda'+#13+
'POINTS PER PAGE=Puntos por página'+#13+
'SCALE LAST PAGE=Escalar última página'+#13+
'CURRENT PAGE LEGEND=Leyenda con página actual'+#13+
'BACKGROUND=Fondo'+#13+
'BACK IMAGE=Imagen fondo'+#13+
'STRETCH=Ajustar'+#13+
'TILE=Mosaico'+#13+
'BORDERS=Bordes'+#13+
'CALCULATE EVERY=Calcular cada'+#13+
'NUMBER OF POINTS=Número puntos'+#13+
'RANGE OF VALUES=Rango de valores'+#13+
'FIRST=Primero'+#13+
'LAST=Ultimo'+#13+
'ALL POINTS=Todos los puntos'+#13+
'DATA SOURCE=Origen de Datos'+#13+
'WALLS=Pared'+#13+
'PAGING=Página'+#13+
'CLONE=Duplicar'+#13+
'TITLES=Título'+#13+
'TOOLS=Herramientas'+#13+
'EXPORT=Exportar'+#13+
'CHART=Gráfico'+#13+
'BACK=Fondo'+#13+
'LEFT AND RIGHT=Izq. y Derecha'+#13+
'SELECT A CHART STYLE=Seleccione tipo de Gráfico'+#13+
'SELECT A DATABASE TABLE=Seleccione una Tabla'+#13+
'TABLE=Tabla'+#13+
'SELECT THE DESIRED FIELDS TO CHART=Seleccione los campos a graficar'+#13+
'SELECT A TEXT LABELS FIELD=Campo de etiquetas'+#13+
'CHOOSE THE DESIRED CHART TYPE=Seleccione el tipo deseado'+#13+
'CHART PREVIEW=Visión Preliminar'+#13+
'SHOW LEGEND=Ver Leyenda'+#13+
'SHOW MARKS=Ver Marcas'+#13+
'FINISH=Terminar'+#13+
'RANDOM=Aleatorio'+#13+
'DRAW EVERY=Dibujar cada'+#13+
'ARROWS=Flechas'+#13+
'ASCENDING=Ascendente'+#13+
'DESCENDING=Descendente'+#13+
'VERTICAL AXIS=Eje Vertical'+#13+
'DATETIME=Fecha/Hora'+#13+
'TOP AND BOTTOM=Superior e Inferior'+#13+
'HORIZONTAL AXIS=Eje Horizontal'+#13+
'PERCENTS=Porcentajes'+#13+
'VALUES=Valores'+#13+
'FORMATS=Formatos'+#13+
'SHOW IN LEGEND=Ver en Leyenda'+#13+
'SORT=Orden'+#13+
'MARKS=Marcas'+#13+
'BEVEL INNER=Marco interior'+#13+
'BEVEL OUTER=Marco exterior'+#13+
'PANEL EDITOR=Editor de Panel'+#13+
'CONTINUOUS=Continuos'+#13+
'HORIZ. ALIGNMENT=Alineación Horiz.'+#13+
'EXPORT CHART=Exportar Gráfico'+#13+
'BELOW %=Inferior a %'+#13+
'BELOW VALUE=Inferior a Valor'+#13+
'NEAREST POINT=Punto cercano'+#13+
'DRAG MARKS=Mover Marcas'+#13+
'TEECHART PRINT PREVIEW=Impresión Preliminar'+#13+
'X VALUE=Valor X'+#13+
'X AND Y VALUES=Valores X Y'+#13+
'SHININESS=Brillo'+#13+
'ALL SERIES VISIBLE=Todas las Series Visible'+#13+
'MARGIN=Margen'+#13+
'DIAGONAL=Diagonal'+#13+
'LEFT TOP=Izquierda Arriba'+#13+
'LEFT BOTTOM=Izquierda Abajo'+#13+
'RIGHT TOP=Derecha Arriba'+#13+
'RIGHT BOTTOM=Derecha Abajo'+#13+
'EXACT DATE TIME=Fecha/Hora Exacta'+#13+
'RECT. GRADIENT=Gradiente'+#13+
'CROSS SMALL=Cruz pequeña'+#13+
'AVG=Media'+#13+
'FUNCTION=Función'+#13+
'AUTO=Auto'+#13+
'ONE MILLISECOND=Un milisegundo'+#13+
'ONE SECOND=Un segundo'+#13+
'FIVE SECONDS=Cinco segundos'+#13+
'TEN SECONDS=Diez segundos'+#13+
'FIFTEEN SECONDS=Quince segundos'+#13+
'THIRTY SECONDS=Trenta segundos'+#13+
'ONE MINUTE=Un minuto'+#13+
'FIVE MINUTES=Cinco minutos'+#13+
'TEN MINUTES=Diez minutos'+#13+
'FIFTEEN MINUTES=Quince minutos'+#13+
'THIRTY MINUTES=Trenta minutos'+#13+
'TWO HOURS=Dos horas'+#13+
'SIX HOURS=Seis horas'+#13+
'TWELVE HOURS=Doce horas'+#13+
'ONE DAY=Un dia'+#13+
'TWO DAYS=Dos dias'+#13+
'THREE DAYS=Tres dias'+#13+
'ONE WEEK=Una semana'+#13+
'HALF MONTH=Medio mes'+#13+
'ONE MONTH=Un mes'+#13+
'TWO MONTHS=Dos meses'+#13+
'THREE MONTHS=Tres meses'+#13+
'FOUR MONTHS=Cuatro meses'+#13+
'SIX MONTHS=Seis meses'+#13+
'IRREGULAR=Irregular'+#13+
'CLICKABLE=Clicable'+#13+
'ROUND=Redondo'+#13+
'FLAT=Plano'+#13+
'PIE=Pastel'+#13+
'HORIZ. BAR=Barra Horiz.'+#13+
'BUBBLE=Burbuja'+#13+
'SHAPE=Forma'+#13+
'POINT=Puntos'+#13+
'FAST LINE=Línea Rápida'+#13+
'CANDLE=Vela'+#13+
'VOLUME=Volumen'+#13+
'HORIZ LINE=Línea Horiz.'+#13+
'SURFACE=Superfície'+#13+
'LEFT AXIS=Eje Izquierdo'+#13+
'RIGHT AXIS=Eje Derecho'+#13+
'TOP AXIS=Eje Superior'+#13+
'BOTTOM AXIS=Eje Inferior'+#13+
'CHANGE SERIES TITLE=Cambiar Título de Series'+#13+
'DELETE %S ?=Eliminar %s ?'+#13+
'DESIRED %S INCREMENT=Incremento %s deseado'+#13+
'INCORRECT VALUE. REASON: %S=Valor incorrecto. Razón: %s'+#13+
'FillSampleValues NumValues must be > 0=FillSampleValues. Número de valores debe ser > 0.'#13+
'VISIT OUR WEB SITE !=Visite nuestra Web !'#13+
'SHOW PAGE NUMBER=Ver Número de Página'#13+
'PAGE NUMBER=Número de Página'#13+
'PAGE %D OF %D=Pág. %d de %d'#13+
'TEECHART LANGUAGES=Lenguajes de TeeChart'#13+
'CHOOSE A LANGUAGE=Escoja un idioma'+#13+
'SELECT ALL=Seleccionar Todas'#13+
'MOVE UP=Mover Arriba'#13+
'MOVE DOWN=Mover Abajo'#13+
'DRAW ALL=Dibujar todo'#13+
'TEXT FILE=Archivo de Texto'#13+
'IMAG. SYMBOL=Símbolo Imag.'#13+
'DRAG REPAINT=Repinta todo'#13+
'NO LIMIT DRAG=Sin límites arrastre'#13+
'AVAILABLE LANGUAGES=Lenguajes disponibles'#13+
'PERIOD=Periodo'#13+
'FILL 80%=Relleno 80%'#13+
'FILL 60%=Relleno 60%'#13+
'FILL 40%=Relleno 40%'#13+
'FILL 20%=Relleno 20%'#13+
'FILL 10%=Relleno 10%'#13+
'ZIG ZAG=Zig-Zag'#13+
'IGNORE NULLS=Ignorar nulos'#13+
'LIGHT 0=Luz 0'#13+
'LIGHT 1=Luz 1'#13+
'LIGHT 2=Luz 2'#13+
'DRAW STYLE=Estilo'#13+
'POINTS=Puntos'#13+
'EXPORT DIALOG=Diálogo de Exportación'#13+
'POINT COLORS=Color de puntos'#13+
'OUTLINE GRADIENT=Gradiente en borde'#13+
'GAUGES=Indicadores'#13+
'RADIAL=Radial'#13+
'RADIAL OFFSET=Desplaz. Radial'#13+
'SHADOW EDITOR=Editor de Sombra'#13+
'3D GRID TRANSPOSE=Invertir matriz 3D'#13+
'EXTRA LEGEND=Leyenda Extra'#13+
'GANTT DRAG=Arrastra Gantt'#13+
'GRID BAND TOOL=Bandas en rejilla'#13+
'SERIES ANIMATION=Animación de Series'#13+
'UP=Arriba'#13+
'DOWN=Abajo'#13+
'CALLOUT=Enlace'#13+
'TEXT ALIGNMENT=Alineación texto'#13+
'DISTANCE=Distancia'#13+
'ARROW HEAD=Cabeza flecha'#13+
'POINTER=Puntero'#13+
'CALCULATE USING=Calcular usando'#13+
'EVERY NUMBER OF POINTS=Cada num. puntos'#13+
'EVERY RANGE=Cada rango'#13+
'INCLUDE NULL VALUES=Incluir nulos'#13+
'DATE=Fecha'#13+
'ENTER DATE=Entrar fecha'#13+
'ENTER TIME=Entrar hora'#13+
'CYLINDER=Cilindro'#13+
'DEVIATION=Desviación'#13+
'UPPER=Superior'#13+
'LOWER=Inferior'#13+
'CONSTANT=Constante'#13+
'SHOW LABELS=Ver textos'#13+
'SHOW COLORS=Ver colores'#13+
'XYZ SERIES=Series xyz'#13+
'SHOW X VALUES=Ver valores X'#13+
'ACCUMULATE=Acumular'#13+
'SMOOTH=Suave'#13+
'INTERPOLATE=Interpolar'#13+
'START X=Inicio X'#13+
'STEP=Paso'#13+
'NUM. POINTS=Num. puntos'#13+
'COLOR EACH LINE=Color cada linea'#13+
'SORT BY=Ordenar por'#13+
'CALCULATION=Cálculo'#13+
'GROUP=Grupo'#13+
'WEIGHT=Ponderar'#13+
'EDIT LEGEND=Editar Leyenda'#13+
'OFFSET=Desplaz.'#13+
'DEFAULT BORDER=Borde defecto'#13+
'SEPARATION=Separación'#13+
'ROUND BORDER=Borde redondo'#13+
'NUMBER OF SAMPLE VALUES=Num. muestras'#13+
'DIF. LIMIT=Limite dif.'#13+
'RESIZE PIXELS TOLERANCE=Tolerancia pixels'#13+
'FULL REPAINT=Repintar todo'#13+
'END POINT=Punto final'#13+
'BAND 1=Banda 1'#13+
'BAND 2=Banda 2'#13+
'TRANSPOSE NOW=Invertir'#13+
'NOTHING=Nada'#13+
'LEFT TRIANGLE=Triángulo Izq.'#13+
'RIGHT TRIANGLE=Triángulo Der.'#13+
'PERIOD 1=Periodo 1'#13+
'PERIOD 2=Periodo 2'#13+
'PERIOD 3=Periodo 3'#13+
'HISTOGRAM=Histograma'#13+
'EXP. LINE=Linea Exp.'#13+
'WEIGHTED=Ponderado'#13+
'WEIGHTED BY INDEX=Ponderar indices'#13+
'BOX SIZE=Tamaño caja'#13+
'REVERSAL AMOUNT=Valor inversión'#13+
'PERCENTAGE=Porcentaje'#13+
'COMPLETE R.M.S.=RMS completa'#13+
'BUTTON=Botón'#13+
'ALL=Todo'#13+
'START AT MIN. VALUE=Empezar en valor mín.'#13+
'EXECUTE !=Ejecutar !'#13+
'WEB URL=Dirección web'#13+
'SELF STACK=Apilado sí mismo'#13+
'SIDE LINES=Lineas laterales'#13+
'COVER=Cubierta'#13+
'VALUE SOURCE=Fuente valores'#13+

// 6.0
'BEVEL SIZE=Tam. Marco'#13+
'DELETE ROW=Eliminar fila'#13+
'VOLUME SERIES=Serie Volumen'#13+
'SINGLE=Unico'#13+
'REMOVE CUSTOM COLORS=Eliminar colores'#13+
'USE PALETTE MINIMUM=Usar mínimo paleta'#13+
'AXIS MAXIMUM=Máximo eje'#13+
'AXIS CENTER=Centro eje'#13+
'AXIS MINIMUM=Mínimo eje'#13+
'DAILY (NONE)=Diario'#13+
'WEEKLY=Semanal'#13+
'MONTHLY=Mensual'#13+
'BI-MONTHLY=Bimensual'#13+
'QUARTERLY=Trimestral'#13+
'YEARLY=Anual'#13+
'DATETIME PERIOD=Periodo fecha/hora'#13+
'CASE SENSITIVE=Mayusc./Minusc.'#13+
'DRAG STYLE=Estilo arrastre'#13+
'SQUARED=Cuadrado'#13+
'GRID 3D SERIES=Serie 3D'#13+
'DARK BORDER=Borde oscuro'#13+
'PIE SERIES=Serie Pastel'#13+
'FOCUS=Marcar'#13+
'EXPLODE=Expandir'#13+
'FACTOR=Factor'#13+
'CHART FROM TEMPLATE (*.TEE FILE)=Desde archivo plantilla (*.tee)'#13+
'OPEN TEECHART TEMPLATE FILE FROM=Abrir plantilla desde'#13+
'BINARY=Binario'#13+
'VOLUME OSCILLATOR=Oscilador Volumen'#13+
'PIE SLICES=Porciones pastel'#13+
'ARROW WIDTH=Ancho flecha'#13+
'ARROW HEIGHT=Alto flecha'#13+
'DEFAULT COLOR=Color defecto'#13+
'BALANCE=Balance'
;
  end;
end;

Procedure TeeSetLithuanian;
begin
  TeeCreateLithuanian;
  TeeLanguage:=TeeLithuanianLanguage;
  TeeLithuanianConstants;
end;

initialization
finalization
  FreeAndNil(TeeLithuanianLanguage);
end.
