unit TeeSlovak;
{$I TeeDefs.inc}

interface

Uses Classes;

Var TeeSlovakLanguage:TStringList=nil;

Procedure TeeSetSlovak;
Procedure TeeCreateSlovak;

implementation

Uses SysUtils, TeeConst, TeeProCo {$IFNDEF D5},TeCanvas{$ENDIF};

Procedure TeeSlovakConstants;
begin
  TeeMsg_Copyright          :='© 1995-2004 by David Berneda';
  TeeMsg_LegendFirstValue   :='Prv· hodnota legendy musÌ byù > 0';
  TeeMsg_LegendColorWidth   :='äÌrka farby legendy musÌ byù > 0%';
  TeeMsg_SeriesSetDataSource:='Nie je rodiËovsk˝ graf pre overenie zdroja d·t';
  TeeMsg_SeriesInvDataSource:='Neplatn˝ zdroj d·t: %s';
  TeeMsg_FillSample         :='FillSampleValues NumValues musÌ byù > 0';
  TeeMsg_AxisLogDateTime    :='D·tumov· a Ëasov· os nemÙûe byù logaritmick·';
  TeeMsg_AxisLogNotPositive :='Min a max hodnoty logaritmickej osi musia byù >= 0';
  TeeMsg_AxisLabelSep       :='% vzdialenosù ötÌtkov musÌ byù v‰Ëöia ako 0';
  TeeMsg_AxisIncrementNeg   :='PrÌrastok osi musÌ byù >= 0';
  TeeMsg_AxisMinMax         :='Minim·lna hodnota osi musÌ byù <= ako maxim·lna';
  TeeMsg_AxisMaxMin         :='Maxim·lna hodnota osi musÌ byù >= ako minim·lna';
  TeeMsg_AxisLogBase        :='Logaritmick˝ z·klad osi musÌ byù >= 2';
  TeeMsg_MaxPointsPerPage   :='MaxPointsPerPage musÌ byù >= 0';
  TeeMsg_3dPercent          :='Percento 3D efektu musÌ byù medzi %d a %d';
  TeeMsg_CircularSeries     :='KrÌûovÈ z·vislosti sÈriÌ nie s˙ prÌpustnÈ';
  TeeMsg_WarningHiColor     :='Je poûadovan· 16k farebn· hÂbka kvÙli lepöiemu vzhæadu';

  TeeMsg_DefaultPercentOf   :='%s / %s';
  TeeMsg_DefaultPercentOf2  :='%s'+#13+'/ %s';
  TeeMsg_DefPercentFormat   :='##0.## %';
  TeeMsg_DefValueFormat     :='#,##0.###';
  TeeMsg_DefLogValueFormat  :='#.0 "x10" E+0';
  TeeMsg_AxisTitle          :='Nadpis osi';
  TeeMsg_AxisLabels         :='ätÌtky osi';
  TeeMsg_RefreshInterval    :='Interval obnovovania musÌ byù medzi 0 a 60';
  TeeMsg_SeriesParentNoSelf :='Nie som Series.ParentChart !';
  TeeMsg_GalleryLine        :='»iarov˝';
  TeeMsg_GalleryPoint       :='Bodov˝';
  TeeMsg_GalleryArea        :='Povrchov˝';
  TeeMsg_GalleryBar         :='StÂpcov˝';
  TeeMsg_GalleryHorizBar    :='Horizont·lny'#13'stÂpcov˝';
  TeeMsg_Stack              :='Hromada';
  TeeMsg_GalleryPie         :='Kol·Ëov˝';
  TeeMsg_GalleryCircled     :='Kruhov˝';
  TeeMsg_GalleryFastLine    :='R˝chly Ëiarov˝';
  TeeMsg_GalleryHorizLine   :='Horizont·lny'#13'Ëiarov˝';

  TeeMsg_PieSample1         :='Automobily';
  TeeMsg_PieSample2         :='TelefÛny';
  TeeMsg_PieSample3         :='Stoly';
  TeeMsg_PieSample4         :='Monitory';
  TeeMsg_PieSample5         :='Lampy';
  TeeMsg_PieSample6         :='Kl·vesnice';
  TeeMsg_PieSample7         :='Bicykle';
  TeeMsg_PieSample8         :='StoliËky';

  TeeMsg_GalleryLogoFont    :='Courier New';
  TeeMsg_Editing            :='Upravujem %s';

  TeeMsg_GalleryStandard    :='ätandardnÈ';
  TeeMsg_GalleryExtended    :='RozöÌrenÈ';
  TeeMsg_GalleryFunctions   :='Funkcie';

  TeeMsg_EditChart          :='&Upraviù graf...';
  TeeMsg_PrintPreview       :='U&k·ûka pred tlaËou...';
  TeeMsg_ExportChart        :='E&xport grafu...';
  TeeMsg_CustomAxes         :='äpeci·lne osi...';

  TeeMsg_InvalidEditorClass :='%s: Neplatn· trieda editora: %s';
  TeeMsg_MissingEditorClass :='%s: nem· ûiadne okno editora';

  TeeMsg_GalleryArrow       :='äÌpka';

  TeeMsg_ExpFinish          :='&DokonËiù';
  TeeMsg_ExpNext            :='œ&alej >';

  TeeMsg_GalleryGantt       :='Gantt';

  TeeMsg_GanttSample1       :='Design';
  TeeMsg_GanttSample2       :='Modelovanie';
  TeeMsg_GanttSample3       :='V˝voj';
  TeeMsg_GanttSample4       :='Predaj';
  TeeMsg_GanttSample5       :='Marketing';
  TeeMsg_GanttSample6       :='Testovanie';
  TeeMsg_GanttSample7       :='V˝roba';
  TeeMsg_GanttSample8       :='Ladenie';
  TeeMsg_GanttSample9       :='Nov· verzia';
  TeeMsg_GanttSample10      :='BankovnÌctvo';

  TeeMsg_ChangeSeriesTitle  :='Zmena nadpisu sÈrie';
  TeeMsg_NewSeriesTitle     :='Nov˝ nadpis sÈrie:';
  TeeMsg_DateTime           :='D·tum / Ëas';
  TeeMsg_TopAxis            :='Horn· os';
  TeeMsg_BottomAxis         :='Spodn· os';
  TeeMsg_LeftAxis           :='ºav· os';
  TeeMsg_RightAxis          :='Prav· os';

  TeeMsg_SureToDelete       :='Vymazaù %s ?';
  TeeMsg_DateTimeFormat     :='For&m·t d·tumu a Ëasu:';
  TeeMsg_Default            :='ImplicitnÈ: ';
  TeeMsg_ValuesFormat       :='For&m·t hodnÙt:';
  TeeMsg_Maximum            :='Maximum';
  TeeMsg_Minimum            :='Minimum';
  TeeMsg_DesiredIncrement   :='éiad˙ci %s inkrement';

  TeeMsg_IncorrectMaxMinValue:='Nekorektn· hodnota. DÙvod: %s';
  TeeMsg_EnterDateTime      :='Vloû [PoËet dnÌ] '+TeeMsg_HHNNSS;

  TeeMsg_SureToApply        :='Pouûiù zmeny ?';
  TeeMsg_SelectedSeries     :='(VybranÈ sÈrie)';
  TeeMsg_RefreshData        :='&Obnoviù d·ta';

  TeeMsg_DefaultFontSize    :={$IFDEF LINUX}'10'{$ELSE}'8'{$ENDIF};
  TeeMsg_DefaultEditorSize  :='414';
  TeeMsg_DefaultEditorHeight:='347';
  TeeMsg_FunctionAdd        :='SËÌtaù';
  TeeMsg_FunctionSubtract   :='OdËÌtaù';
  TeeMsg_FunctionMultiply   :='N·sobiù';
  TeeMsg_FunctionDivide     :='Deliù';
  TeeMsg_FunctionHigh       :='Vysoko';
  TeeMsg_FunctionLow        :='NÌzko';
  TeeMsg_FunctionAverage    :='Priemer';

  TeeMsg_GalleryShape       :='Tvary';
  TeeMsg_GalleryBubble      :='Bubliny';
  TeeMsg_FunctionNone       :='KopÌrovaù';

  TeeMsg_None               :='(niË)';

  TeeMsg_PrivateDeclarations:='{ S˙kromnÈ deklar·cie }';
  TeeMsg_PublicDeclarations :='{ VerejnÈ deklar·cie }';
  TeeMsg_DefaultFontName    :=TeeMsg_DefaultEngFontName;

  TeeMsg_CheckPointerSize   :='Veækosù ukazateæa musÌ byù v‰Ëöia ako nula';
  TeeMsg_About              :='&O TeeChart-e...';

  tcAdditional              :='Additional';
  tcDControls               :='Data Controls';
  tcQReport                 :='QReport';

  TeeMsg_DataSet            :='S˙bor d·t';
  TeeMsg_AskDataSet         :='&S˙bor d·t:';

  TeeMsg_SingleRecord       :='Jeden z·znam';
  TeeMsg_AskDataSource      :='&Zdroj d·t:';

  TeeMsg_Summary            :='S˙hrn';

  TeeMsg_FunctionPeriod     :='PeriÛda funkcie musÌ byù >= 0';

  TeeMsg_WizardTab          :='Business';
  TeeMsg_TeeChartWizard     :='Sprievodca TeeChart';

  TeeMsg_ClearImage         :='Odst&r·niù';
  TeeMsg_BrowseImage        :='&Vyhæadaù...';

  TeeMsg_WizardSureToClose  :='Ste si ist˝, ûe chcete zatvoriù sprievodcu TeeChart ?';
  TeeMsg_FieldNotFound      :='Pole %s neexistuje';

  TeeMsg_DepthAxis          :='HÂbkov· os';
  TeeMsg_PieOther           :='OstatnÈ';
  TeeMsg_ShapeGallery1      :='abc';
  TeeMsg_ShapeGallery2      :='123';
  TeeMsg_ValuesX            :='X';
  TeeMsg_ValuesY            :='Y';
  TeeMsg_ValuesPie          :='Kol·Ë';
  TeeMsg_ValuesBar          :='StÂpec';
  TeeMsg_ValuesAngle        :='Uhol';
  TeeMsg_ValuesGanttStart   :='ZaËiatok';
  TeeMsg_ValuesGanttEnd     :='Koniec';
  TeeMsg_ValuesGanttNextTask:='NextTask';
  TeeMsg_ValuesBubbleRadius :='Polomer';
  TeeMsg_ValuesArrowEndX    :='KoniecX';
  TeeMsg_ValuesArrowEndY    :='KoniecY';
  TeeMsg_Legend             :='Legenda';
  TeeMsg_Title              :='Nadpis';
  TeeMsg_Foot               :='Spodok';
  TeeMsg_Period		    :='PeriÛda';
  TeeMsg_PeriodRange        :='Rozsah periÛdy';
  TeeMsg_CalcPeriod         :='PoËÌtaù %s kaûd˝:';
  TeeMsg_SmallDotsPen       :='MalÈ body';

  TeeMsg_InvalidTeeFile     :='Neplatn˝ graf v s˙bore *.'+TeeMsg_TeeExtension;
  TeeMsg_WrongTeeFileFormat :='Chybn˝ form·t s˙boru *.'+TeeMsg_TeeExtension;
  TeeMsg_EmptyTeeFile       :='Pr·zdny s˙bor *.'+TeeMsg_TeeExtension;  { 5.01 }

  {$IFDEF D5}
  TeeMsg_ChartAxesCategoryName   := 'Osi grafu';
  TeeMsg_ChartAxesCategoryDesc   := 'Vlastnosti a udalosti os grafu';
  TeeMsg_ChartWallsCategoryName  := 'Steny grafu';
  TeeMsg_ChartWallsCategoryDesc  := 'Vlastnosti a udalosti stien grafu';
  TeeMsg_ChartTitlesCategoryName := 'Nadpisy grafu';
  TeeMsg_ChartTitlesCategoryDesc := 'Vlastnosti a udalosti nadpisov grafu';
  TeeMsg_Chart3DCategoryName     := '3D graf';
  TeeMsg_Chart3DCategoryDesc     := 'Vlastnosti a udalosti 3D grafu';
  {$ENDIF}

  TeeMsg_CustomAxesEditor       :='Zvl·ötne ';
  TeeMsg_Series                 :='SÈrie';
  TeeMsg_SeriesList             :='SÈrie...';

  TeeMsg_PageOfPages            :='Strana %d / %d';
  TeeMsg_FileSize               :='%d bytov';

  TeeMsg_First  :='Prv·';
  TeeMsg_Prior  :='Predch·dzaj˙ca';
  TeeMsg_Next   :='Nasleduj˙ca';
  TeeMsg_Last   :='Posledn·';
  TeeMsg_Insert :='Vloûiù';
  TeeMsg_Delete :='Vymazaù';
  TeeMsg_Edit   :='Upraviù';
  TeeMsg_Post   :='Uloûiù';
  TeeMsg_Cancel :='Storno';

  TeeMsg_All    :='(vöetko)';
  TeeMsg_Index  :='Index';
  TeeMsg_Text   :='Text';

  TeeMsg_AsBMP        :='ako &Bitov· mapa';
  TeeMsg_BMPFilter    :='BitovÈ mapy (*.bmp)|*.bmp';
  TeeMsg_AsEMF        :='ako &Metafile';
  TeeMsg_EMFFilter    :='Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  TeeMsg_ExportPanelNotSet := 'Vlastnosù Panel vo form·te exportu nie je nastaven·';

  TeeMsg_Normal    :='Norm·lne';
  TeeMsg_NoBorder  :='Bez okraja';
  TeeMsg_Dotted    :='BodkovanÈ';
  TeeMsg_Colors    :='Farby';
  TeeMsg_Filled    :='VyplnenÈ';
  TeeMsg_Marks     :='ZnaËky';
  TeeMsg_Stairs    :='Schody';
  TeeMsg_Points    :='Body';
  TeeMsg_Height    :='V˝öka';
  TeeMsg_Hollow    :='Dutina';
  TeeMsg_Point2D   :='Bod 2D';
  TeeMsg_Triangle  :='TrojuholnÌk';
  TeeMsg_Star      :='Hviezda';
  TeeMsg_Circle    :='Kruh';
  TeeMsg_DownTri   :='Dole troj.';
  TeeMsg_Cross     :='KrÌû';
  TeeMsg_Diamond   :='Diamant';
  TeeMsg_NoLines   :='Bez Ëiar';
  TeeMsg_Stack100  :='Sklad 100%';
  TeeMsg_Pyramid   :='PyramÌda';
  TeeMsg_Ellipse   :='Elipsa';
  TeeMsg_InvPyramid:='Inv. pyramÌda';
  TeeMsg_Sides     :='Strany';
  TeeMsg_SideAll   :='Strana vöet.';
  TeeMsg_Patterns  :='Vzory';
  TeeMsg_Exploded  :='V˝buch';
  TeeMsg_Shadow    :='TieÚ';
  TeeMsg_SemiPie   :='Polokol·Ë';
  TeeMsg_Rectangle :='ObdÂûnik';
  TeeMsg_VertLine  :='Vert. Ëiara';
  TeeMsg_HorizLine :='Horiz. Ëiara';
  TeeMsg_Line      :='»iara';
  TeeMsg_Cube      :='Kocka';
  TeeMsg_DiagCross :='Diag. krÌû';

  TeeMsg_CanNotFindTempPath    :='NemÙûem n·jsù doËasn˝ adres·r';
  TeeMsg_CanNotCreateTempChart :='NemÙûem vytvoriù doËasn˝ s˙bor';
  TeeMsg_CanNotEmailChart      :='NemÙûem poslaù graf e-mailom. Chyba MAPI: %d';

  TeeMsg_SeriesDelete :='Mazanie sÈrie: ValueIndex %d mimo hranice (0 do %d).';
  TeeMsg_NoSeriesSelected :='Nie s˙ vybranÈ ûiadne sÈrie';
  TeeMsg_CannotLoadChartFromURL:='Chybov˝ kÛd: %d pri sùahovanÌ grafu z URL: %s';
  TeeMsg_CannotLoadSeriesDataFromURL:='Chybov˝ kÛd: %d pri sùahovanÌ d·t sÈrie z URL: %s';

  { 5.02 } { Moved from TeeImageConstants.pas unit }

  TeeMsg_AsJPEG        :='ako &JPEG';
  TeeMsg_JPEGFilter    :='JPEG s˙bory (*.jpg)|*.jpg';
  TeeMsg_AsGIF         :='ako &GIF';
  TeeMsg_GIFFilter     :='GIF s˙bory (*.gif)|*.gif';
  TeeMsg_AsPNG         :='ako &PNG';
  TeeMsg_PNGFilter     :='PNG s˙bory (*.png)|*.png';
  TeeMsg_AsPCX         :='ako PC&X';
  TeeMsg_PCXFilter     :='PCX s˙bory (*.pcx)|*.pcx';
  TeeMsg_AsVML         :='ako &VML (HTM)';
  TeeMsg_VMLFilter     :='VML s˙bory (*.htm)|*.htm';

  { 5.02 }
  TeeMsg_AskLanguage  :='&Jazyk...';

  { 5.03 }
  TeeMsg_Gradient     :='Prechod';
  TeeMsg_WantToSave   :='Chcete uloûiù %s?';
  TeeMsg_NativeFilter :='S˙bory TeeChart '+TeeDefaultFilterExtension;

  TeeMsg_Property     :='Vlastnosù';
  TeeMsg_Value        :='Hodnota';
  TeeMsg_Yes          :='¡no';
  TeeMsg_No           :='Nie';
  TeeMsg_Image        :='(obr·zok)';

  {AX 5.0.4}
  TeeMsg_ActiveXVersion      := 'ActiveX Release ' + AXVer;
  TeeMsg_ActiveXCannotImport := 'NemÙûem importovaù TeeChart z %s';
  TeeMsg_ActiveXVerbPrint    := '&Uk·ûka pred tlaËou...';
  TeeMsg_ActiveXVerbExport   := 'E&xport...';
  TeeMsg_ActiveXVerbImport   := '&Import...';
  TeeMsg_ActiveXVerbHelp     := '&Pomoc...';
  TeeMsg_ActiveXVerbAbout    := '&O TeeChart-e...';
  TeeMsg_ActiveXError        := 'TeeChart: Chybov˝ kÛd: %d pri sùahovanÌ: %s';
  TeeMsg_DatasourceError     := 'TeeChart DataSource nie je Series alebo RecordSet';
  TeeMsg_SeriesTextSrcError  := 'Chybn˝ typ sÈrie';
  TeeMsg_AxisTextSrcError    := 'Chybn˝ typ osi';
  TeeMsg_DelSeriesDatasource := 'Naozaj chcete vymazaù %s ?';
  TeeMsg_OCXNoPrinter        := 'Nie je nainötalovan· ûiadna tlaËiareÚ.';
  TeeMsg_ActiveXPictureNotValid :='Obr·zok nie je platn˝';

  { 6.0 }
  TeeMsg_FunctionCustom   :='y = f(x)';
  TeeMsg_AsPDF            :='ako &PDF';
  TeeMsg_PDFFilter        :='PDF s˙bory (*.pdf)|*.pdf';
  TeeMsg_AsPS             :='ako PostScript';
  TeeMsg_PSFilter         :='PostScript s˙bory (*.eps)|*.eps';
  TeeMsg_GalleryHorizArea :='Horizont·lna'#13'oblasù';
  TeeMsg_SelfStack        :='Self Stacked';
  TeeMsg_DarkPen          :='Tmav˝ okraj';
  TeeMsg_SelectFolder     :='Vyberte datab·zov˝ adres·r';
  TeeMsg_BDEAlias         :='&Alias:';
  TeeMsg_ADOConnection    :='&Spojenie:';

  { TeeProCo }
  TeeMsg_GalleryPolar       :='PÛlov˝';
  TeeMsg_GalleryCandle      :='SvieËkov˝';
  TeeMsg_GalleryVolume      :='Objemov˝';
  TeeMsg_GallerySurface     :='Povrchov˝';
  TeeMsg_GalleryContour     :='Obrysov˝';
  TeeMsg_GalleryBezier      :='Bezierov˝';
  TeeMsg_GalleryPoint3D     :='3D bodov˝';
  TeeMsg_GalleryRadar       :='Radar';
  TeeMsg_GalleryDonut       :='Donut';
  TeeMsg_GalleryCursor      :='Kurzorov˝';
  TeeMsg_GalleryBar3D       :='3D stÂpcov˝';
  TeeMsg_GalleryBigCandle   :='VeækÈ svieËky';
  TeeMsg_GalleryLinePoint   :='»iary body';
  TeeMsg_GalleryHistogram   :='Histogram';
  TeeMsg_GalleryWaterFall   :='Vodop·d';
  TeeMsg_GalleryWindRose    :='Vetern· ruûa';
  TeeMsg_GalleryClock       :='Hodiny';
  TeeMsg_GalleryColorGrid   :='Farebn· mrieûka';
  TeeMsg_GalleryBoxPlot     :='BoxPlot';
  TeeMsg_GalleryHorizBoxPlot:='Horiz. boxplot';
  TeeMsg_GalleryBarJoin     :='SpojenÈ stÂpce';
  TeeMsg_GallerySmith       :='Kov·Ë';
  TeeMsg_GalleryPyramid     :='PyramÌda';
  TeeMsg_GalleryMap         :='Mapa';

  TeeMsg_PolyDegreeRange    :='Polynomick˝ stupeÚ musÌ byù medzi 1 a 20';
  TeeMsg_AnswerVectorIndex   :='Index vektora musÌ byù medzi 1 a %d';
  TeeMsg_FittingError        :='NemÙûem vykonaù sk˙öku';
  TeeMsg_PeriodRange         :='PeriÛda musÌ byù >= 0';
  TeeMsg_ExpAverageWeight    :='ExpAverage Weight musÌ byù medzi 0 a 1';
  TeeMsg_GalleryErrorBar     :='Chybov˝ stÂpec';
  TeeMsg_GalleryError        :='Chybov˝';
  TeeMsg_GalleryHighLow      :='Vysok˝-nÌzky';
  TeeMsg_FunctionMomentum    :='Hybnosù';
  TeeMsg_FunctionMomentumDiv :='Rozdelenie'#13'hybnosti';
  TeeMsg_FunctionExpAverage  :='Exponenci·lny'#13'priemer';
  TeeMsg_FunctionMovingAverage:='Pohybliv˝'#13'priemer';
  TeeMsg_FunctionExpMovAve   :='Exp. pohybliv˝'#13'priemer';
  TeeMsg_FunctionRSI         :='R.S.I.';
  TeeMsg_FunctionCurveFitting:='Odpovedaj˙ca'#13'krivka';
  TeeMsg_FunctionTrend       :='Trend';
  TeeMsg_FunctionExpTrend    :='Exp. Trend';
  TeeMsg_FunctionLogTrend    :='Log. Trend';
  TeeMsg_FunctionCumulative  :='KumulatÌvny';
  TeeMsg_FunctionStdDeviation:='ätandardn·'#13'odch˝lka';
  TeeMsg_FunctionBollinger   :='Skupiny'#13'deliteæov';
  TeeMsg_FunctionRMS         :='Root Mean'#13'Square';
  TeeMsg_FunctionMACD        :='MACD';
  TeeMsg_FunctionStochastic  :='Pravdepodobnosù';
  TeeMsg_FunctionADX         :='ADX';

  TeeMsg_FunctionCount       :='PoËet';
  TeeMsg_LoadChart           :='NaËÌtaù TeeChart...';
  TeeMsg_SaveChart           :='Uloûiù TeeChart...';
  TeeMsg_TeeFiles            :='S˙bory TeeChart Pro';

  TeeMsg_GallerySamples      :='OstatnÈ';
  TeeMsg_GalleryStats        :='ätatistiky';

  TeeMsg_CannotFindEditor    :='NemÙûem n·jsù formul·r Editor sÈriÌ: %s';

  TeeMsg_Test                :='Test...';

  TeeMsg_ValuesDate          :='D·tum';
  TeeMsg_ValuesOpen          :='Otvoriù';
  TeeMsg_ValuesHigh          :='Vysoko';
  TeeMsg_ValuesLow           :='NÌzko';
  TeeMsg_ValuesClose         :='Zatvoriù';
  TeeMsg_ValuesOffset        :='Offset';
  TeeMsg_ValuesStdError      :='ätand. chyba';

  TeeMsg_Grid3D              :='3D mrieûka';

  TeeMsg_LowBezierPoints     :='PoËet BÈzierov˝ch bodov musÌ byù > 1';

  { TeeCommander component... }

  TeeCommanMsg_Normal   :='Norm·l';
  TeeCommanMsg_Edit     :='Upraviù';
  TeeCommanMsg_Print    :='TlaË';
  TeeCommanMsg_Copy     :='KopÌrovaù';
  TeeCommanMsg_Save     :='Uloûiù';
  TeeCommanMsg_3D       :='3D';

  TeeCommanMsg_Rotating :='Rot·cia: %d∞ V˝öka: %d∞';
  TeeCommanMsg_Rotate   :='Rot·cia';

  TeeCommanMsg_Moving   :='Horiz.Offset: %d Vert.Offset: %d';
  TeeCommanMsg_Move     :='Presun';

  TeeCommanMsg_Zooming  :='Zoom: %d %%';
  TeeCommanMsg_Zoom     :='Zoom';

  TeeCommanMsg_Depthing :='3D: %d %%';
  TeeCommanMsg_Depth    :='HÂbka';

  TeeCommanMsg_Chart    :='Graf';
  TeeCommanMsg_Panel    :='Panel';

  TeeCommanMsg_RotateLabel:='Pre rot·ciu ùahajte %s';
  TeeCommanMsg_MoveLabel  :='Pre presun ùahajte %s';
  TeeCommanMsg_ZoomLabel  :='Pre zoom ùahajte %s';
  TeeCommanMsg_DepthLabel :='Pre zmenu 3D ùahajte %s';

  TeeCommanMsg_NormalLabel:='çahajte æav˝m tlaËÌtkom pre Zoom, prav˝m pre rolovanie';
  TeeCommanMsg_NormalPieLabel:='çahajte Ëasù kol·Ëa pre explodovanie';

  TeeCommanMsg_PieExploding :='»asù: %d Explodovan·: %d %%';

  TeeMsg_TriSurfaceLess        :='PoËet bodov musÌ byù >= 4';
  TeeMsg_TriSurfaceAllColinear :='Vöetky koline·rne d·tovÈ body';
  TeeMsg_TriSurfaceSimilar     :='PodobnÈ body - nemÙûem vykonaù';
  TeeMsg_GalleryTriSurface     :='Troj.povrch';

  TeeMsg_AllSeries :='Vöetky sÈrie';
  TeeMsg_Edit      :='Upraviù';

  TeeMsg_GalleryFinancial    :='FinanËnÈ';

  TeeMsg_CursorTool    :='Kurzor';
  TeeMsg_DragMarksTool :='çahaj˙ce znaËky';
  TeeMsg_AxisArrowTool :='äÌpky osi';
  TeeMsg_DrawLineTool  :='Kreslenie Ëiary';
  TeeMsg_NearestTool   :='NajbliûöÌ bod';
  TeeMsg_ColorBandTool :='Farebn˝ p·s';
  TeeMsg_ColorLineTool :='Farebn· Ëiara';
  TeeMsg_RotateTool    :='Rot·cia';
  TeeMsg_ImageTool     :='Obr·zok';
  TeeMsg_MarksTipTool  :='Tipy';
  TeeMsg_AnnotationTool:='Pozn·mka';

  TeeMsg_CantDeleteAncestor  :='NemÙûem vymazaù predchodcu';

  TeeMsg_Load	          :='NaËÌtaù...';

  { TeeChart Actions }
  TeeMsg_CategoryChartActions  :='Graf';
  TeeMsg_CategorySeriesActions :='SÈrie grafu';

  TeeMsg_Action3D               := '&3D';
  TeeMsg_Action3DHint           := 'Zmena 2D / 3D';
  TeeMsg_ActionSeriesActive     := '&AktÌvne';
  TeeMsg_ActionSeriesActiveHint := 'Zobraziù / skryù sÈrie';
  TeeMsg_ActionEditHint         := 'Upraviù graf';
  TeeMsg_ActionEdit             := '&Upraviù...';
  TeeMsg_ActionCopyHint         := 'KopÌrovaù do schr·nky';
  TeeMsg_ActionCopy             := '&KopÌrovaù';
  TeeMsg_ActionPrintHint        := 'Uk·ûka grafu pred tlaËou';
  TeeMsg_ActionPrint            := '&TlaË...';
  TeeMsg_ActionAxesHint         := 'Zobraziù / skryù osi';
  TeeMsg_ActionAxes             := '&Osi';
  TeeMsg_ActionGridsHint        := 'Zobraziù / skryù mrieûky';
  TeeMsg_ActionGrids            := '&Mrieûky';
  TeeMsg_ActionLegendHint       := 'Zobraziù / skryù legendu';
  TeeMsg_ActionLegend           := '&Legenda';
  TeeMsg_ActionSeriesEditHint   := 'Upraviù sÈrie';
  TeeMsg_ActionSeriesMarksHint  := 'Zobraziù / skryù znaËky sÈriÌ';
  TeeMsg_ActionSeriesMarks      := '&ZnaËky';
  TeeMsg_ActionSaveHint         := 'Uloûiù graf';
  TeeMsg_ActionSave             := '&Uloûiù...';

  TeeMsg_CandleBar              := 'StÂpec';
  TeeMsg_CandleNoOpen           := 'Neotvoren˝';
  TeeMsg_CandleNoClose          := 'Nezatvoren˝';
  TeeMsg_NoLines                := 'éiadne Ëiary';
  TeeMsg_NoHigh                 := 'éiadny vrchol';
  TeeMsg_NoLow                  := 'éiadny spodok';
  TeeMsg_ColorRange             := 'Rozsah farieb';
  TeeMsg_WireFrame              := 'DrÙtov˝ model';
  TeeMsg_DotFrame               := 'Bodov˝ model';
  TeeMsg_Positions              := 'Polohy';
  TeeMsg_NoGrid                 := 'éiadna mrieûka';
  TeeMsg_NoPoint                := 'éiadny bod';
  TeeMsg_NoLine                 := 'éiadna Ëiara';
  TeeMsg_Labels                 := 'ätÌtky';
  TeeMsg_NoCircle               := 'éiadny kruh';
  TeeMsg_Lines                  := '»iary';
  TeeMsg_Border                 := 'Okraj';

  TeeMsg_SmithResistance      := 'Odpor';
  TeeMsg_SmithReactance       := 'Jalov˝ odpor';

  TeeMsg_Column               := 'StÂpec';

  { 5.01 }
  TeeMsg_Separator            := 'OddeæovaË';
  TeeMsg_FunnelSegment        := 'Segment ';
  TeeMsg_FunnelSeries         := 'Tunel';
  TeeMsg_FunnelPercent        := '0.00 %';
  TeeMsg_FunnelExceed         := 'Presiahnut· kvÛta';
  TeeMsg_FunnelWithin         := ' v kvÛte';
  TeeMsg_FunnelBelow          := ' alebo viac pod kvÛtou';
  TeeMsg_CalendarSeries       := 'Kalend·r';
  TeeMsg_DeltaPointSeries     := 'Troj bod';
  TeeMsg_ImagePointSeries     := 'Obrazov˝ bod';
  TeeMsg_ImageBarSeries       := 'Obrazov˝ stÂpec';
  TeeMsg_SeriesTextFieldZero  := 'SeriesText: Index poæa musÌ byù v‰ËöÌ ako nula.';

  { 5.02 }
  TeeMsg_Origin               := 'PoËiatok';
  TeeMsg_Transparency         := 'Transparentnosù';
  TeeMsg_Box		      := 'Schr·nka';
  TeeMsg_ExtrOut	      := 'ExtrOut';
  TeeMsg_MildOut	      := 'MildOut';
  TeeMsg_PageNumber	      := '»Ìslo strany';
  TeeMsg_TextFile             := 'Textov˝ s˙bor';

  { 5.03 }
  TeeMsg_Gradient             :='Prechod';
  TeeMsg_WantToSave           :='Uloûiù %s?';

  TeeMsg_Property             :='Vlastnosù';
  TeeMsg_Value                :='Hodnota';
  TeeMsg_Yes                  :='¡no';
  TeeMsg_No                   :='Nie';
  TeeMsg_Image                :='(obr·zok)';

  { 5.03 }
  TeeMsg_DragPoint            := 'çahov˝ bod';
  TeeMsg_OpportunityValues    := 'PrÌleûit.hodnoty';
  TeeMsg_QuoteValues          := 'KvÛt.hodnoty';

  { 6.0 }
  TeeMsg_FunctionSmooth       :='Vyrovnanie';
  TeeMsg_FunctionCross        :='KrÌûovÈ body';
  TeeMsg_GridTranspose        :='Transponovanie 3D mrieûky';
  TeeMsg_FunctionCompress     :='Kompresia';
  TeeMsg_ExtraLegendTool      :='Extra Legenda';
  TeeMsg_FunctionCLV          :='Najbliûöia'#13'hodnota';
  TeeMsg_FunctionOBV          :='On Balance'#13'Volume';
  TeeMsg_FunctionCCI          :='Commodity'#13'Channel Index';
  TeeMsg_FunctionPVO          :='Objemov˝'#13'Oscil·tor';
  TeeMsg_SeriesAnimTool       :='Anim·cia sÈriÌ';
  TeeMsg_GalleryPointFigure   :='Bod a obrazec';
  TeeMsg_Up                   :='Hore';
  TeeMsg_Down                 :='Dole';
  TeeMsg_GanttTool            :='Gantt ùahanie';
  TeeMsg_XMLFile              :='XML s˙bor';
  TeeMsg_GridBandTool         :='Skupina mrieûok';
  TeeMsg_FunctionPerf         :='V˝kon';
  TeeMsg_GalleryGauge         :='MerÌtko';
  TeeMsg_GalleryGauges        :='MerÌtka';
  TeeMsg_ValuesVectorEndZ     :='KoniecZ';
  TeeMsg_GalleryVector3D      :='3D vektor';
  TeeMsg_Gallery3D            :='3D';
  TeeMsg_GalleryTower         :='Veûa';
  TeeMsg_SingleColor          :='Jedna farba';
  TeeMsg_Cover                :='Pokrytie';
  TeeMsg_Cone                 :='Kuûeæ';
  TeeMsg_PieTool              :='K˙sky kol·Ëa';
end;

Procedure TeeCreateSlovak;
begin
  if not Assigned(TeeSlovakLanguage) then
  begin
    TeeSlovakLanguage:=TStringList.Create;
    TeeSlovakLanguage.Text:=

'GRADIENT EDITOR=Editor prechodov'#13+
'GRADIENT=Prechod'#13+
'DIRECTION=Smer'#13+
'VISIBLE=ViditeænÈ'#13+
'TOP BOTTOM=Hore Dole'#13+
'BOTTOM TOP=Dole Hore'#13+
'LEFT RIGHT=Væavo Vpravo'#13+
'RIGHT LEFT=Vpravo Væavo'#13+
'FROM CENTER=Od stredu'#13+
'FROM TOP LEFT=Od æava hore'#13+
'FROM BOTTOM LEFT=Od æava dole'#13+
'OK=OK'#13+
'CANCEL=Storno'#13+
'COLORS=Farby'#13+
'START=ZaËiatok'#13+
'MIDDLE=Stred'#13+
'END=Koniec'#13+
'SWAP=V˝mena'#13+
'NO MIDDLE=Bez stredu'#13+
'TEEFONT EDITOR=TeeFont editor'#13+
'INTER-CHAR SPACING=Medzery medzi znakmi'#13+
'FONT=Font'#13+
'SHADOW=TieÚ'#13+
'HORIZ. SIZE=Horiz. veækosù'#13+
'VERT. SIZE=Vert. veækosù'#13+
'COLOR=Farba'#13+
'OUTLINE=Obrys'#13+
'OPTIONS=Moûnosti'#13+
'FORMAT=Form·t'#13+
'TEXT=Text'#13+
'GRADIENT=Prechod'#13+
'POSITION=PozÌcia'#13+
'LEFT=Væavo'#13+
'TOP=Hore'#13+
'AUTO=Auto'#13+
'CUSTOM=VlastnÈ'#13+
'LEFT TOP=Væavo hore'#13+
'LEFT BOTTOM=Væavo dole'#13+
'RIGHT TOP=Vpravo hore'#13+
'RIGHT BOTTOM=Vpravo dole'#13+
'MULTIPLE AREAS=Viac povrchov'#13+
'NONE=NiË'#13+
'STACKED=NakopenÈ'#13+
'STACKED 100%=NakopenÈ 100%'#13+
'AREA=Povrch'#13+
'PATTERN=Vzor'#13+
'STAIRS=Schody'#13+
'SOLID=Pln˝'#13+
'CLEAR=»ist˝'#13+
'HORIZONTAL=Horizont·lny'#13+
'VERTICAL=Vertik·lny'#13+
'DIAGONAL=Diagon·lny'#13+
'B.DIAGONAL=B.Diagon·lny'#13+
'CROSS=KrÌû'#13+
'DIAG.CROSS=Diag. krÌû'#13+
'AREA LINES=PloönÈ Ëiary'#13+
'BORDER=Okraj'#13+
'INVERTED=InverznÈ'#13+
'INVERTED SCROLL=Inverzn˝ posun'#13+
'COLOR EACH=Ofarbi vöetky'#13+
'ORIGIN=PoËiatok'#13+
'USE ORIGIN=Pouûi poËiatok'#13+
'WIDTH=äÌrka'#13+
'HEIGHT=V˝öka'#13+
'AXIS=Osi'#13+
'LENGTH=DÂûka'#13+
'SCROLL=Rolovanie'#13+
'PATTERN=Vzor'#13+
'START=ZaËiatok'#13+
'END=Koniec'#13+
'BOTH=Oboje'#13+
'AXIS INCREMENT=PrÌrastok osi'#13+
'INCREMENT=PrÌrastok'#13+
'STANDARD=ätandard'#13+
'CUSTOM=VlastnÈ'#13+
'ONE MILLISECOND=Jedna milisekunda'#13+
'ONE SECOND=Jedna sekunda'#13+
'FIVE SECONDS=P‰ù sek˙nd'#13+
'TEN SECONDS=Desaù sek˙nd'#13+
'FIFTEEN SECONDS=P‰tn·sù sek˙nd'#13+
'THIRTY SECONDS=Tridsaù sek˙nd'#13+
'ONE MINUTE=Jedna min˙ta'#13+
'FIVE MINUTES=P‰ù min˙t'#13+
'TEN MINUTES=Desaù min˙t'#13+
'FIFTEEN MINUTES=P‰tn·sù min˙t'#13+
'THIRTY MINUTES=Tridsaù min˙t'#13+
'ONE HOUR=Jedna hodina'#13+
'TWO HOURS=Dve hodiny'#13+
'SIX HOURS=äesù hodÌn'#13+
'TWELVE HOURS=Dvan·sù hodÌn'#13+
'ONE DAY=Jeden deÚ'#13+
'TWO DAYS=Dva dni'#13+
'THREE DAYS=Tri dni'#13+
'ONE WEEK=Jeden t˝ûdeÚ'#13+
'HALF MONTH=Pol mesiaca'#13+
'ONE MONTH=Jeden mesiac'#13+
'TWO MONTHS=Dva mesiace'#13+
'THREE MONTHS=Tri mesiace'#13+
'FOUR MONTHS=ätyri mesiace'#13+
'SIX MONTHS=äesù mesiacov'#13+
'ONE YEAR=Jeden rok'#13+
'EXACT DATE TIME=Presn˝ d·tum a Ëas'#13+
'AXIS MAXIMUM AND MINIMUM=Minimum a maximum osi'#13+
'VALUE=Hodnota'#13+
'TIME=»as'#13+
'LEFT AXIS=ºav· os'#13+
'RIGHT AXIS=Prav· os'#13+
'TOP AXIS=Horn· os'#13+
'BOTTOM AXIS=Spodn· os'#13+
'% BAR WIDTH=% äÌrka stÂpca'#13+
'STYLE=ät˝l'#13+
'% BAR OFFSET=% Offset stÂpca'#13+
'RECTANGLE=ObdÂûnik'#13+
'PYRAMID=PyramÌda'#13+
'INVERT. PYRAMID=Inverzn· pyramÌda'#13+
'CYLINDER=Valec'#13+
'ELLIPSE=Elipsa'#13+
'ARROW=äÌpka'#13+
'RECT. GRADIENT=Prav. prechod'#13+
'CONE=Kuûeæ'#13+
'DARK BAR 3D SIDES=Tmav˝ stÂpec 3D strany'#13+
'BAR SIDE MARGINS=Okraje strany stÂpca'#13+
'AUTO MARK POSITION=Automaticky oznaËiù pozÌciu'#13+
'BORDER=Okraj'#13+
'JOIN=Spojiù'#13+
'BAR SIDE MARGINS=Okraje strany stÂpca'#13+
'DATASET=Dataset'#13+
'APPLY=Pouûiù'#13+
'SOURCE=Zdroj'#13+
'MONOCHROME=Monochrom'#13+
'DEFAULT=ImplicitnÈ'#13+
'2 (1 BIT)=2 (1 bit)'#13+
'16 (4 BIT)=16 (4 bit)'#13+
'256 (8 BIT)=256 (8 bit)'#13+
'32768 (15 BIT)=32768 (15 bit)'#13+
'65536 (16 BIT)=65536 (16 bit)'#13+
'16M (24 BIT)=16M (24 bit)'#13+
'16M (32 BIT)=16M (32 bit)'#13+
'LENGTH=DÂûka'#13+
'MEDIAN=Stred'#13+
'WHISKER=Tykadlo'#13+
'PATTERN COLOR EDITOR=Editor farby vzoru'#13+
'IMAGE=Obr·zok'#13+
'NONE=NiË'#13+
'BACK DIAGONAL=Sp‰tn· diagon·la'#13+
'CROSS=KrÌû'#13+
'DIAGONAL CROSS=Diagon·lny krÌû'#13+
'FILL 80%=Vyplniù 80%'#13+
'FILL 60%=Vyplniù 60%'#13+
'FILL 40%=Vyplniù 40%'#13+
'FILL 20%=Vyplniù 20%'#13+
'FILL 10%=Vyplniù 10%'#13+
'ZIG ZAG=Cik Cak'#13+
'VERTICAL SMALL=Vertik·lne malÈ'#13+
'HORIZ. SMALL=Horizont·lne malÈ'#13+
'DIAG. SMALL=Diagon·lne malÈ'#13+
'BACK DIAG. SMALL=Sp‰tnÈ diag. malÈ'#13+
'CROSS SMALL=KrÌû mal˝'#13+
'DIAG. CROSS SMALL=Diag. krÌû mal˝'#13+
'PATTERN COLOR EDITOR=Editor farby vzoru'#13+
'OPTIONS=Moûnosti'#13+
'DAYS=Dni'#13+
'WEEKDAYS=Dni v t˝ûdni'#13+
'TODAY=Dnes'#13+
'SUNDAY=Nedeæa'#13+
'TRAILING=SledovanÈ'#13+
'MONTHS=Mesiace'#13+
'LINES=»iary'#13+
'SHOW WEEKDAYS=Zobraz dni v t˝ûdni'#13+
'UPPERCASE=VeækÈ pÌsmen·'#13+
'TRAILING DAYS=SledovanÈ dni'#13+
'SHOW TODAY=Zobraz dnes'#13+
'SHOW MONTHS=Zobraz mesiace'#13+
'CANDLE WIDTH=äÌrka svieËky'#13+
'STICK=Palica'#13+
'BAR=StÂpec'#13+
'OPEN CLOSE=Otvoriù Zatvoriù'#13+
'UP CLOSE=Hore Zatvoriù'#13+
'DOWN CLOSE=Dole Zatvoriù'#13+
'SHOW OPEN=Otvoriù'#13+
'SHOW CLOSE=Zatvoriù'#13+
'DRAW 3D=Kresliù 3D'#13+
'DARK 3D=TmavÈ 3D'#13+
'EDITING=Upravujem'#13+
'CHART=Graf'#13+
'SERIES=SÈrie'#13+
'DATA=D·ta'#13+
'TOOLS=N·stroje'#13+
'EXPORT=Export'#13+
'PRINT=TlaË'#13+
'GENERAL=VöeobecnÈ'#13+
'TITLES=Nadpisy'#13+
'LEGEND=Legenda'#13+
'PANEL=Panel'#13+
'PAGING=Strany'#13+
'WALLS=Steny'#13+
'3D=3D'#13+
'ADD=Pridaù'#13+
'DELETE=Vymazaù'#13+
'TITLE=Nadpis'#13+
'CLONE=Klon'#13+
'CHANGE=Zmeniù'#13+
'HELP=Pomoc'#13+
'CLOSE=Zatvoriù'#13+
'IMAGE=Obr·zok'#13+
'TEECHART PRINT PREVIEW=Uk·ûka pred tlaËou'#13+
'PRINTER=TlaËiareÚ'#13+
'SETUP=Nastaviù'#13+
'ORIENTATION=Orient·cia'#13+
'PORTRAIT=PortrÈt'#13+
'LANDSCAPE=Naleûato'#13+
'MARGINS (%)=Okraje (%)'#13+
'DETAIL=Detail'#13+
'MORE=Viac'#13+
'NORMAL=Norm·lne'#13+
'RESET MARGINS=Obnoviù okraje'#13+
'VIEW MARGINS=Zobraziù okraje'#13+
'PROPORTIONAL=Proporcion·lne'#13+
'TEECHART PRINT PREVIEW=Uk·ûka pred tlaËou'#13+
'RECTANGLE=ObdÂûnik'#13+
'CIRCLE=Kruh'#13+
'VERTICAL LINE=Vert. Ëiara'#13+
'HORIZ. LINE=Horiz. Ëiara'#13+
'TRIANGLE=TrojuholnÌk'#13+
'INVERT. TRIANGLE=Inv. trojuholnÌk'#13+
'LINE=»iara'#13+
'DIAMOND=Diamant'#13+
'CUBE=Kocka'#13+
'DIAGONAL CROSS=Diagon·lny krÌû'#13+
'STAR=Hviezda'#13+
'TRANSPARENT=Transparentne'#13+
'HORIZ. ALIGNMENT=Horiz. zarovnanie'#13+
'LEFT=Væavo'#13+
'CENTER=Stred'#13+
'RIGHT=Vpravo'#13+
'ROUND RECTANGLE=Zaoblen˝ obdÂûnik'#13+
'ALIGNMENT=Zarovnanie'#13+
'TOP=Hore'#13+
'BOTTOM=Dole'#13+
'RIGHT=Vpravo'#13+
'BOTTOM=Dole'#13+
'UNITS=Jednotky'#13+
'PIXELS=Body'#13+
'AXIS=Osi'#13+
'AXIS ORIGIN=PoËiatok osi'#13+
'ROTATION=Rot·cia'#13+
'CIRCLED=Okr˙hly'#13+
'3 DIMENSIONS=3 rozmery'#13+
'RADIUS=Polomer'#13+
'ANGLE INCREMENT=Inkrement uhla'#13+
'RADIUS INCREMENT=Inkrement polomera'#13+
'CLOSE CIRCLE=BlÌzky krÌû'#13+
'PEN=Pero'#13+
'CIRCLE=Kruh'#13+
'LABELS=ätÌtky'#13+
'VISIBLE=Viditeæn˝'#13+
'ROTATED=Zrotovan˝'#13+
'CLOCKWISE=V smere hod. ruËiËiek'#13+
'INSIDE=Vn˙tri'#13+
'ROMAN=RÌmsky'#13+
'HOURS=Hodiny'#13+
'MINUTES=Min˙ty'#13+
'SECONDS=Sekundy'#13+
'START VALUE=ätartovacia hodnota'#13+
'END VALUE=Koncov· hodnota'#13+
'TRANSPARENCY=Transparentnosù'#13+
'DRAW BEHIND=Kresliù vzadu'#13+
'COLOR MODE=Farebn˝ mÛd'#13+
'STEPS=Kroky'#13+
'RANGE=Rozsah'#13+
'PALETTE=Paleta'#13+
'PALE=Svetl˝'#13+
'STRONG=Siln˝'#13+
'GRID SIZE=Veækosù mrieûky'#13+
'X=X'#13+
'Z=Z'#13+
'DEPTH=HÂbka'#13+
'IRREGULAR=Nepravidelne'#13+
'GRID=Mrieûka'#13+
'VALUE=Hodnota'#13+
'ALLOW DRAG=Povoliù ùahanie'#13+
'VERTICAL POSITION=Vertik·lna pozÌcia'#13+
'PEN=Pero'#13+
'LEVELS POSITION=PozÌcia hladÌn'#13+
'LEVELS=Hladiny'#13+
'NUMBER=»Ìslo'#13+
'LEVEL=Hladina'#13+
'AUTOMATIC=Automaticky'#13+
'BOTH=Oboje'#13+
'SNAP=SnÌmok'#13+
'FOLLOW MOUSE=Sledujte myö'#13+
'STACK=Kopa'#13+
'HEIGHT 3D=V˝öka 3D'#13+
'LINE MODE=»iarov˝ mÛd'#13+
'STAIRS=Schody'#13+
'NONE=NiË'#13+
'OVERLAP=Prekr˝vanie'#13+
'STACK=Kopa'#13+
'STACK 100%=Kopa 100%'#13+
'CLICKABLE=KlikateænÈ'#13+
'LABELS=ätÌtky'#13+
'AVAILABLE=DostupnÈ'#13+
'SELECTED=OznaËenÈ'#13+
'DATASOURCE=Zdroj d·t'#13+
'GROUP BY=Zoskupiù'#13+
'CALC=PoËÌtaù'#13+
'OF=/'#13+
'SUM=S˙Ëet'#13+
'COUNT=PoËet'#13+
'HIGH=Vysoko'#13+
'LOW=NÌzko'#13+
'AVG=Priemer'#13+
'HOUR=Hodina'#13+
'DAY=DeÚ'#13+
'WEEK=T˝ûdeÚ'#13+
'WEEKDAY=DeÚ v t˝ûdni'#13+
'MONTH=Mesiac'#13+
'QUARTER=Kvart·l'#13+
'YEAR=Rok'#13+
'HOLE %=Otvor %'#13+
'RESET POSITIONS=Obnoviù pozÌcie'#13+
'MOUSE BUTTON=TlaËÌtko myöi'#13+
'ENABLE DRAWING=SprÌstupniù kreslenie'#13+
'ENABLE SELECT=SprÌstupniù v˝ber'#13+
'ENHANCED=RozöÌrenÈ'#13+
'ERROR WIDTH=äÌrka chyby'#13+
'WIDTH UNITS=Jednotky öÌrky'#13+
'PERCENT=Percent'#13+
'PIXELS=Body'#13+
'LEFT AND RIGHT=Væavo a vpravo'#13+
'TOP AND BOTTOM=Hore a dole'#13+
'BORDER=Okraj'#13+
'BORDER EDITOR=Editor okraja'#13+
'DASH=»iarka'#13+
'DOT=Bod'#13+
'DASH DOT=»iara bod'#13+
'DASH DOT DOT=»iara bod bod'#13+
'CALCULATE EVERY=SpoËÌtaù kaûdÈ'#13+
'ALL POINTS=Vöetky body'#13+
'NUMBER OF POINTS=PoËet bodov'#13+
'RANGE OF VALUES=Rozsah hodnÙt'#13+
'FIRST=Prv˝'#13+
'CENTER=Stred'#13+
'LAST=Posledn˝'#13+
'TEEPREVIEW EDITOR=Editor uk·ûky'#13+
'ALLOW MOVE=Umoûniù presun'#13+
'ALLOW RESIZE=Umoûniù zmeniù veækosù'#13+
'DRAG IMAGE=çahaù obr·zok'#13+
'AS BITMAP=Ako bitmapa'#13+
'SHOW IMAGE=Zobraziù obr·zok'#13+
'DEFAULT=ImplicitnÈ'#13+
'MARGINS=Okraje'#13+
'SIZE=Veækosù'#13+
'3D %=3D %'#13+
'ZOOM=Zv‰Ëöenie'#13+
'ROTATION=Rot·cia'#13+
'ELEVATION=V˝öka'#13+
'100%=100%'#13+
'HORIZ. OFFSET=Horiz. Offset'#13+
'VERT. OFFSET=Vert. Offset'#13+
'PERSPECTIVE=PerspektÌva'#13+
'ANGLE=Uhol'#13+
'ORTHOGONAL=Ortogon·lny'#13+
'ZOOM TEXT=Zv‰Ëöiù text'#13+
'SCALES=Mierky'#13+
'TITLE=Nadpis'#13+
'TICKS=Tiky'#13+
'MINOR=Menöie'#13+
'MAXIMUM=Maximum'#13+
'MINIMUM=Minimum'#13+
'(MAX)=(max)'#13+
'(MIN)=(min)'#13+
'DESIRED INCREMENT=éiad˙ci prÌrastok'#13+
'(INCREMENT)=(prÌrastok)'#13+
'LOG BASE=Log z·klad'#13+
'LOGARITHMIC=Logaritmick˝'#13+
'TITLE=Nadpis'#13+
'MIN. SEPARATION %=Min. medzera %'#13+
'MULTI-LINE=Viacriadkov˝'#13+
'LABEL ON AXIS=ätÌtok na osi'#13+
'ROUND FIRST=Zaokr˙hliù prv˝'#13+
'MARK=ZnaËka.'#13+
'LABELS FORMAT=Form·t ötÌtkov'#13+
'EXPONENTIAL=Exponenci·lny'#13+
'DEFAULT ALIGNMENT=ImplicitnÈ zoradenie'#13+
'LEN=DÂûka'#13+
'LENGTH=DÂûka'#13+
'AXIS=Os'#13+
'INNER=Vn˙torn˝'#13+
'GRID=Mrieûka'#13+
'AT LABELS ONLY=Iba na ötÌtkoch'#13+
'CENTERED=CentrovanÈ'#13+
'COUNT=PoËet'#13+
'TICKS=Tiky'#13+
'POSITION %=PozÌcia %'#13+
'START %=ZaËiatok %'#13+
'END %=Koniec %'#13+
'OTHER SIDE=Druh· strana'#13+
'AXES=Osi'#13+
'BEHIND=Vzadu'#13+
'CLIP POINTS=OrezanÈ body'#13+
'PRINT PREVIEW=Uk·ûka pred tlaËou'#13+
'MINIMUM PIXELS=Minimum bodov'#13+
'MOUSE BUTTON=TlaËÌtko myöi'#13+
'ALLOW=Povoliù'#13+
'ANIMATED=Animovan˝'#13+
'VERTICAL=Vertik·lny'#13+
'RIGHT=Vpravo'#13+
'MIDDLE=Stred'#13+
'ALLOW SCROLL=Povoliù rolovanie'#13+
'TEEOPENGL EDITOR=TeeOpenGL Editor'#13+
'AMBIENT LIGHT=OkolnÈ svetlo'#13+
'SHININESS=Osvetlenie'#13+
'FONT 3D DEPTH=3D hÂbka fontu'#13+
'ACTIVE=AktÌvne'#13+
'FONT OUTLINES=Obrysy fontu'#13+
'SMOOTH SHADING=JemnÈ tieÚovanie'#13+
'LIGHT=Svetlo'#13+
'Y=Y'#13+
'INTENSITY=Intenzita'#13+
'BEVEL=Pl·tno'#13+
'FRAME=R·m'#13+
'ROUND FRAME=Okr˙hly r·m'#13+
'LOWERED=ZnÌûen˝'#13+
'RAISED=Zv˝öen˝'#13+
'POSITION=PozÌcia'#13+
'SYMBOLS=Symboly'#13+
'TEXT STYLE=ät˝l textu'#13+
'LEGEND STYLE=ät˝l legendy'#13+
'VERT. SPACING=Vert. odstup'#13+
'AUTOMATIC=Automaticky'#13+
'SERIES NAMES=N·zvy sÈriÌ'#13+
'SERIES VALUES=Hodnoty sÈriÌ'#13+
'LAST VALUES=PoslednÈ hodnoty'#13+
'PLAIN=»ist˝'#13+
'LEFT VALUE=ºav· hodnota'#13+
'RIGHT VALUE=Prav· hodnota'#13+
'LEFT PERCENT=ºavÈ percento'#13+
'RIGHT PERCENT=PravÈ percento'#13+
'X VALUE=Hodnota X'#13+
'VALUE=Hodnota'#13+
'PERCENT=Percent'#13+
'X AND VALUE=X a hodnota'#13+
'X AND PERCENT=X a percento'#13+
'CHECK BOXES=Zaökrt·vacie polÌËka'#13+
'DIVIDING LINES=Deliace Ëiary'#13+
'FONT SERIES COLOR=Farba pÌsma sÈriÌ'#13+
'POSITION OFFSET %=Offset pozÌcie %'#13+
'MARGIN=Okraj'#13+
'RESIZE CHART=Upraviù veækosù grafu'#13+
'CUSTOM=äpeci·lny'#13+
'WIDTH UNITS=Jednotky öÌrky'#13+
'CONTINUOUS=S˙visl˝'#13+
'POINTS PER PAGE=Bodov na stranu'#13+
'SCALE LAST PAGE=PrispÙsobiù posledn˙ stranu'#13+
'CURRENT PAGE LEGEND=Legenda aktu·lnej strany'#13+
'PANEL EDITOR=Editor panelu'#13+
'BACKGROUND=Pozadie'#13+
'BORDERS=Okraje'#13+
'BACK IMAGE=Obr·zok v pozadÌ'#13+
'STRETCH=Roztiahnuù'#13+
'TILE=Vydl·ûdiù'#13+
'CENTER=Na stred'#13+
'BEVEL INNER=Vn˙torn· hrana'#13+
'LOWERED=ZnÌûen˝'#13+
'RAISED=Zv˝öen˝'#13+
'BEVEL OUTER=Vonkajöia hrana'#13+
'MARKS=ZnaËky'#13+
'DATA SOURCE=Zdroj d·t'#13+
'SORT=Utriediù'#13+
'CURSOR=Kurzor'#13+
'SHOW IN LEGEND=Zobraziù v legende'#13+
'FORMATS=Form·ty'#13+
'VALUES=Hodnoty'#13+
'PERCENTS=Percent·'#13+
'HORIZONTAL AXIS=Horizont·lna os'#13+
'TOP AND BOTTOM=Vrch a spodok'#13+
'DATETIME=D·tum/»as'#13+
'VERTICAL AXIS=Vertik·lna os'#13+
'LEFT=Væavo'#13+
'RIGHT=Vpravo'#13+
'LEFT AND RIGHT=Væavo a vpravo'#13+
'ASCENDING=Vzostupne'#13+
'DESCENDING=Zostupne'#13+
'DRAW EVERY=Kresli vöetko'#13+
'CLIPPED=Zrezan˝'#13+
'ARROWS=äÌpky'#13+
'MULTI LINE=Viac Ëiar'#13+
'ALL SERIES VISIBLE=Vöetky sÈrie viditeænÈ'#13+
'LABEL=ätÌtok'#13+
'LABEL AND PERCENT=ätÌtok a percento'#13+
'LABEL AND VALUE=ätÌtok a hodnota'#13+
'PERCENT TOTAL=Percent spolu'#13+
'LABEL AND PERCENT TOTAL=ätÌtok a percent spolu'#13+
'X VALUE=Hodnota X'#13+
'X AND Y VALUES=Hodnoty X a Y'#13+
'MANUAL=Manu·lne'#13+
'RANDOM=N·hodne'#13+
'FUNCTION=Funkcia'#13+
'NEW=NovÈ'#13+
'EDIT=Upraviù'#13+
'DELETE=Vymazaù'#13+
'PERSISTENT=Trval˝'#13+
'ADJUST FRAME=Upraviù r·m'#13+
'SUBTITLE=Podnadpis'#13+
'SUBFOOT=Podspodok'#13+
'FOOT=Spodok'#13+
'DELETE=Vymazaù'#13+
'VISIBLE WALLS=ViditeænÈ steny'#13+
'BACK=Sp‰ù'#13+
'DIF. LIMIT=Dif. limit'#13+
'LINES=»iary'#13+
'ABOVE=Nad'#13+
'WITHIN=Vn˙tri'#13+
'BELOW=Pod'#13+
'CONNECTING LINES=SpojenÈ Ëiary'#13+
'SERIES=SÈrie'#13+
'PALE=Bled˝'#13+
'STRONG=Siln˝'#13+
'HIGH=Vysok˝'#13+
'LOW=NÌzky'#13+
'BROWSE=Vyhæadaù'#13+
'TILED=Vydl·ûden˝'#13+
'INFLATE MARGINS=ZhustenÈ okraje'#13+
'SQUARE=ätvorec'#13+
'DOWN TRIANGLE=Doln˝ trojuholnÌk'#13+
'SMALL DOT=Mal˝ bod'#13+
'DEFAULT=Implicitne'#13+
'GLOBAL=Glob·lny'#13+
'SHAPES=Teles·'#13+
'BRUSH=ätetec'#13+
'BRUSH=ätetec'#13+
'BORDER=Okraj'#13+
'COLOR=Farba'#13+
'DELAY=Opozdenie'#13+
'MSEC.=msec.'#13+
'MOUSE ACTION=Akcia myöou'#13+
'MOVE=Presun'#13+
'CLICK=Klik'#13+
'BRUSH=ätetec'#13+
'DRAW LINE=Kresliù Ëiaru'#13+
'BORDER EDITOR=Editor okraja'#13+
'DASH=PomlËka'#13+
'DOT=Bod'#13+
'DASH DOT=PomlËka bod'#13+
'DASH DOT DOT=PomlËka bod bod'#13+
'EXPLODE BIGGEST=Explodovaù najv‰ËöÌ'#13+
'TOTAL ANGLE=Celkov˝ uhol'#13+
'GROUP SLICES=SkupinovÈ rezy'#13+
'BELOW %=Pod %'#13+
'BELOW VALUE=Spodn· hodnota'#13+
'OTHER=OstatnÈ'#13+
'PATTERNS=Vzory'#13+
'CLOSE CIRCLE=Zatvoren˝ kruh'#13+
'VISIBLE=ViditeænÈ'#13+
'CLOCKWISE=V smere hodin. ruËiËiek'#13+
'SIZE %=Veækosù %'#13+
'PATTERN=Vzor'#13+
'DEFAULT=Implicitne'#13+
'SERIES DATASOURCE TEXT EDITOR=Textov˝ editor zdroja d·t sÈriÌ'#13+
'FIELDS=Polia'#13+
'NUMBER OF HEADER LINES=PoËet Ëiar z·hlavia'#13+
'SEPARATOR=OddeæovaË'#13+
'COMMA=»iarka'#13+
'SPACE=Medzera'#13+
'TAB=Tabul·tor'#13+
'FILE=S˙bor'#13+
'WEB URL=WebovÈ URL'#13+
'LOAD=NaËÌtaù'#13+
'C LABELS=C ötÌtky'#13+
'R LABELS=R ötÌtky'#13+
'C PEN=C pero'#13+
'R PEN=R pero'#13+
'STACK GROUP=Skladov· skupina'#13+
'USE ORIGIN=Pouûiù poËiatok'#13+
'MULTIPLE BAR=Zloûen˝ stÂpec'#13+
'SIDE=Strana'#13+
'STACKED 100%=UskladnenÈ 100%'#13+
'SIDE ALL=Straniù vöetko'#13+
'BRUSH=ätetec'#13+
'DRAWING MODE=Kresliaci mÛd'#13+
'SOLID=Pln˝'#13+
'WIREFRAME=DrÙten˝ model'#13+
'DOTFRAME=Bodov˝ model'#13+
'SMOOTH PALETTE=Jemn· paleta'#13+
'SIDE BRUSH=Stranov˝ ötetec'#13+
'ABOUT TEECHART PRO V7.0=O TeeChart Pro v7.0'#13+
'ALL RIGHTS RESERVED.=Vöetky pr·va vyhradenÈ.'#13+
'VISIT OUR WEB SITE !=NavötÌvte naöu web str·nku !'#13+
'TEECHART WIZARD=Sprievodca TeeChart'#13+
'SELECT A CHART STYLE=Vyberte öt˝l grafu'#13+
'DATABASE CHART=Datab·zov˝ graf'#13+
'NON DATABASE CHART=Nedatab·zov˝ graf'#13+
'SELECT A DATABASE TABLE=Vyberte datab·zov˙ tabuæku'#13+
'ALIAS=Alias'#13+
'TABLE=Tabuæka'#13+
'SOURCE=Zdroj'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'MICROSOFT ADO=Microsoft ADO'#13+
'SELECT THE DESIRED FIELDS TO CHART=Vyberte poûadovanÈ polia pre graf'#13+
'SELECT A TEXT LABELS FIELD=Vyberte pole pre textovÈ ötÌtky'#13+
'CHOOSE THE DESIRED CHART TYPE=Vyberte poûadovan˝ typ grafu'#13+
'2D=2D'#13+
'CHART PREVIEW=Uk·ûka grafu'#13+
'SHOW LEGEND=Zobraziù legendu'#13+
'SHOW MARKS=Zobraziù znaËky'#13+
'< BACK=< Sp‰ù'#13+
'SELECT A CHART STYLE=Vyberte öt˝l grafu'#13+
'NON DATABASE CHART=Nedatab·zov˝ graf'#13+
'SELECT A DATABASE TABLE=Vyberte datab·zov˙ tabuæku'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'SELECT THE DESIRED FIELDS TO CHART=Vyberte poûadovanÈ polia pre graf'#13+
'SELECT A TEXT LABELS FIELD=Vyberte pole pre textovÈ ötÌtky'#13+
'CHOOSE THE DESIRED CHART TYPE=Vyberte poûadovan˝ typ grafu'#13+
'EXPORT CHART=Export grafu'#13+
'PICTURE=Obr·zok'#13+
'NATIVE=Vlastn˝'#13+
'KEEP ASPECT RATIO=Zachovaù pomer str·n'#13+
'INCLUDE SERIES DATA=Zahrn˙ù d·ta sÈriÌ'#13+
'FILE SIZE=Veækosù s˙boru'#13+
'DELIMITER=ObmedzovaË'#13+
'XML=XML'#13+
'HTML TABLE=HTML tabuæka'#13+
'EXCEL=Excel'#13+
'TAB=Tabul·tor'#13+
'COLON=Dvojbodka'#13+
'INCLUDE=Vloûiù'#13+
'POINT LABELS=ätÌtky bodu'#13+
'POINT INDEX=Index bodu'#13+
'HEADER=HlaviËka'#13+
'COPY=KopÌrovaù'#13+
'SAVE=Uloûiù'#13+
'SEND=Poslaù'#13+
'KEEP ASPECT RATIO=Zachovaù pomer str·n'#13+
'INCLUDE SERIES DATA=Zahrn˙ù d·ta sÈriÌ'#13+
'FUNCTIONS=Funkcie'#13+
'ADD=Pridaù'#13+
'ADX=ADX'#13+
'AVERAGE=Priemer'#13+
'BOLLINGER=Deliteæ'#13+
'COPY=KopÌrovaù'#13+
'DIVIDE=Deliù'#13+
'EXP. AVERAGE=Exp. priemer'#13+
'EXP.MOV.AVRG.=Exp. pohyb. priemer'#13+
'HIGH=Vysoko'#13+
'LOW=NÌzko'#13+
'MACD=MACD'#13+
'MOMENTUM=Momentum'#13+
'MOMENTUM DIV=Momentum Div'#13+
'MOVING AVRG.=Pohyb. priemer'#13+
'MULTIPLY=N·sobiù'#13+
'R.S.I.=R.S.I.'#13+
'ROOT MEAN SQ.=Root Mean SQ.'#13+
'STD.DEVIATION=ätandardn· odch˝lka'#13+
'STOCHASTIC=N·hodn˝'#13+
'SUBTRACT=OdËÌtaù'#13+
'APPLY=Pouûiù'#13+
'SOURCE SERIES=ZdrojovÈ sÈrie'#13+
'TEECHART GALLERY=TeeChart galÈria'#13+
'FUNCTIONS=Funkcie'#13+
'DITHER=Dither'#13+
'REDUCTION=Redukcia'#13+
'COMPRESSION=Kompresia'#13+
'LZW=LZW'#13+
'RLE=RLE'#13+
'NEAREST=NajbliûöÌ'#13+
'FLOYD STEINBERG=Floyd Steinberg'#13+
'STUCKI=Stucki'#13+
'SIERRA=Sierra'#13+
'JAJUNI=JaJuNI'#13+
'STEVE ARCHE=Steve Arche'#13+
'BURKES=Burkes'#13+
'WINDOWS 20=Windows 20'#13+
'WINDOWS 256=Windows 256'#13+
'WINDOWS GRAY=Windows öedÈ'#13+
'MONOCHROME=MonochromatickÈ'#13+
'GRAY SCALE=Odtiene öedej'#13+
'NETSCAPE=Netscape'#13+
'QUANTIZE=Quantize'#13+
'QUANTIZE 256=Quantize 256'#13+
'% QUALITY=% Kvalita'#13+
'GRAY SCALE=Odtiene öedej'#13+
'PERFORMANCE=V˝kon'#13+
'QUALITY=Kvalita'#13+
'SPEED=R˝chlosù'#13+
'COMPRESSION LEVEL=StupeÚ kompresie'#13+
'CHART TOOLS GALLERY=GalÈria n·strojov grafu'#13+
'ANNOTATION=Pozn·mka'#13+
'AXIS ARROWS=äÌpky osi'#13+
'COLOR BAND=Farebn· skupina'#13+
'COLOR LINE=Farebn· Ëiara'#13+
'CURSOR=Kurzor'#13+
'DRAG MARKS=çahanie znaËky'#13+
'DRAW LINE=Kreslenie Ëiary'#13+
'IMAGE=Obr·zok'#13+
'MARK TIPS=ZnaËkovÈ tipy'#13+
'NEAREST POINT=NajbliûöÌ bod'#13+
'ROTATE=Rot·cia'#13+
'CHART TOOLS GALLERY=GalÈria n·strojov grafu'#13+
'BRUSH=ätetec'#13+
'DRAWING MODE=Kresliaci mÛd'#13+
'WIREFRAME=DrÙten˝ model'#13+
'SMOOTH PALETTE=Jemn· paleta'#13+
'SIDE BRUSH=Stranov˝ ötetec'#13+
'YES=¡no'#13+
'PERIOD=PeriÛda'#13+
'DOWN=Dole'#13+
'ANIMATIONS=Anim·cie'#13+
'ADD TEXT=Pridaù text'#13+
'FONT SIZE=Veækosù pÌsma'#13+
'MOVE TEXT=Presun textu'#13+
'MOVEMENT=Pohyb'#13+
'NODE COLOR=Farba uzla'#13+
'NODE ZOOM=Zv‰Ëöenie uzla'#13+
'TEXT ANGLE=Uhol textu'#13+
'TEXT COLOR=Farba textu'#13+
'TEXT FLASH=Blikanie textu'#13+
'TEXT TRANSP=Transp. text'#13+
'TREE COLOR=Farba stromu'#13+
'PREVIEW=Uk·ûka'#13+
'SHADOW EDITOR=Editor tieÚa'#13+
'CALLOUT=Popis'#13+
'TEXT ALIGNMENT=Zarovnanie textu'#13+
'DISTANCE=Vzdialenosù'#13+
'ARROW HEAD=HlaviËka öÌpky'#13+
'POINTER=Ukazateæ'#13+
'AVAILABLE LANGUAGES=DostupnÈ jazyky'#13+
'CHOOSE A LANGUAGE=Vyberte si jazyk'#13+
'CALCULATE USING=PoËÌtaù pouûitÌm'#13+
'EVERY NUMBER OF POINTS=Kaûd˝ poËet bodov'#13+
'EVERY RANGE=Kaûd˝ rozsah'#13+
'INCLUDE NULL VALUES=Zahrn˙ù nulovÈ hodnoty'#13+
'DATE=D·tum'#13+
'ENTER DATE=Vloûte d·tum'#13+
'ENTER TIME=Vloûte Ëas'#13+
'BEVEL SIZE=Veækosù skosenia'#13+
'DEVIATION=Odch˝lka'#13+
'UPPER=VyööÌ'#13+
'LOWER=NiûöÌ'#13+
'NOTHING=NiË'#13+
'LEFT TRIANGLE=ºav˝ trojuholnÌk'#13+
'RIGHT TRIANGLE=Prav˝ trojuholnÌk'#13+
'SHOW PREVIOUS BUTTON=Zobraziù predch. tlaËÌtko'#13+
'SHOW NEXT BUTTON=Zobraziù nasled. tlaËÌtko'#13+
'CONSTANT=Konötanta'#13+
'SHOW LABELS=Zobraziù ötÌtky'#13+
'SHOW COLORS=Zobraziù farby'#13+
'XYZ SERIES=XYZ sÈrie'#13+
'SHOW X VALUES=Zobraziù X hodnoty'#13+
'DELETE ROW=Vymazaù riadok'#13+
'VOLUME SERIES=ObjemovÈ sÈrie'#13+
'ACCUMULATE=Nazbieraù'#13+
'SINGLE=Jeden'#13+
'REMOVE CUSTOM COLORS=Odstr·niù zvyËajnÈ farby'#13+
'STEP=Krok'#13+
'USE PALETTE MINIMUM=Pouûiù minimum palety'#13+
'AXIS MAXIMUM=Maximum osi'#13+
'AXIS CENTER=Centrovanie osi'#13+
'AXIS MINIMUM=Minimum osi'#13+
'DRAG REPAINT=Prekresliù ùah'#13+
'NO LIMIT DRAG=éiadny limit ùahu'#13+
'DAILY (NONE)=Denne (niË)'#13+
'WEEKLY=T˝ûdenne'#13+
'MONTHLY=MesaËne'#13+
'BI-MONTHLY=DvojmesaËne'#13+
'QUARTERLY=ätvrùroËne'#13+
'YEARLY=RoËne'#13+
'DATETIME PERIOD=PeriÛda d·tumu/Ëasu'#13+
'TREE CONNECTION EDITOR=Editor spojenia stromu'#13+
'ARROW FROM=äÌpka od'#13+
'ARROW TO=äÌpka do'#13+
'POINTS=Body'#13+
'SIDES=Strany'#13+
'INVERTED SIDES=InverznÈ strany'#13+
'CURVE=Krivka'#13+
'POINT=Bod'#13+
'ADD NEW POINT=Pridaù nov˝ bod'#13+
'DELETE POINT=Vymazaù bod'#13+
'FIXED=Nemenn˝'#13+
'RELATIVE FROM=RelatÌvne od'#13+
'PREVIOUS POINT=Predch·dzaj˙ci bod'#13+
'NEXT POINT=œalöÌ bod'#13+
'RELATIVE TO=RelatÌvne do'#13+
'SMOOTH=Hladk˝'#13+
'INTERPOLATE=Interpolovaù'#13+
'START X=ätart X'#13+
'NUM. POINTS=PoËet bodov'#13+
'COLOR EACH LINE=Vyfarbiù kaûd˙ Ëiaru'#13+
'CASE SENSITIVE=Rozliöovaù veækosù pÌsma'#13+
'SORT BY=Triediù podæa'#13+
'(NONE)=(niË)'#13+
'CALCULATION=V˝poËet'#13+
'GROUP=Skupina'#13+
'DRAG STYLE=ät˝l ùahania'#13+
'WEIGHT=V·ha'#13+
'EDIT LEGEND=Upraviù legendu'#13+
'ROUND=Obl˝'#13+
'FLAT=Ploch˝'#13+
'DRAW ALL=Kresliù vöetko'#13+
'IGNORE NULLS=Ignorovaù nuly'#13+
'DATABASE TREE WIZARD=Sprievodca datab·z. stromom'#13+
'SAMPLE DATA=Uk·ûkovÈ d·ta'#13+
'TREE PREVIEW=Uk·ûka stromu'#13+
'CODE FIELD=KÛdovÈ pole'#13+
'PARENT FIELD=RodiËovskÈ pole'#13+
'TEXT FIELDS=TextovÈ polia'#13+
'DETAIL DATASET=Detailn˝ dataset'#13+
'DETAIL FIELDS=DetailnÈ polia'#13+
'MULTI-LINE TEXT=Viacriadkov˝ text'#13+
'NEXT >=œalöie >'#13+
'< PREVIOUS=< Predch.'#13+
'CHOOSE A SITUATION=Vyberte situ·ciu'#13+
'LIGHT 0=Svetlo 0'#13+
'LIGHT 1=Svetlo 1'#13+
'LIGHT 2=Svetlo 2'#13+
'DRAW STYLE=ät˝l kreslenia'#13+
'DEFAULT BORDER=ätandardn˝ okraj'#13+
'SQUARED=ätvorcov˝'#13+
'SHOW PAGE NUMBER=Zobraziù ËÌslo strany'#13+
'SEPARATION=Oddelenie'#13+
'ROUND BORDER=Okr˙hly okraj'#13+
'NUMBER OF SAMPLE VALUES=PoËet uk·ûkov˝ch hodnÙt'#13+
'SPACING=Vzdialenosù'#13+
'RESIZE PIXELS TOLERANCE=Tolerancia zmeny veækosti bodov'#13+
'FULL REPAINT=PlnÈ prekreslenie'#13+
'END POINT=Koncov˝ bod'#13+
'BAND 1=Skupina 1'#13+
'BAND 2=Skupina 2'#13+
'GRID 3D SERIES=3D mrieûka sÈriÌ'#13+
'TRANSPOSE NOW=Transponovaù teraz'#13+
'PERIOD 1=PeriÛda 1'#13+
'PERIOD 2=PeriÛda 2'#13+
'PERIOD 3=PeriÛda 3'#13+
'HISTOGRAM=Histogram'#13+
'EXP. LINE=Exp. Ëiara'#13+
'DRAG TO RESIZE=çahajte pre zmenu veækosti'#13+
'MOVE UP=Presun nahor'#13+
'MOVE DOWN=Presun nadol'#13+
'SERIES MARKS=ZnaËky sÈriÌ'#13+
'WALL=Stena'#13+
'TEXT LABELS=TextovÈ ötÌtky'#13+
'X VALUES=X hodnoty'#13+
'BOLD=TuËnÈ'#13+
'ITALIC=äikmÈ'#13+
'UNDERLINE=PodËiarknutÈ'#13+
'STRIKE OUT=PreËiarknutÈ'#13+
'LEFT JUSTIFY=Zarovnaù væavo'#13+
'RIGHT JUSTIFY=Zarovnaù vpravo'#13+
'FONT COLOR=Farba pÌsma'#13+
'FONT NAME=Meno fontu'#13+
'INTER-CHAR SIZE=Veækosù medzi znakmi'#13+
'ADD ANNOTATION=Pridaù pozn·mku'#13+
'ENABLE ZOOM=Povoliù zv‰Ëöenie'#13+
'ENABLE SCROLL=Povoliù rolovanie'#13+
'DRAW LINES=Kresliù Ëiary'#13+
'SHOW HINTS=Zobraziù rady'#13+
'COLOR EACH POINT=Vyfarbiù kaûd˝ bod'#13+
'SHOW AT LEGEND=Zobraziù v legende'#13+
'SHOW SERIES MARKS=Zobraziù znaËky sÈriÌ'#13+
'BORDER COLOR=Farba okraja'#13+
'BORDER STYLE=ät˝l okraja'#13+
'BORDER WIDTH=äÌrka okraja'#13+
'NEW USING WIZARD=NovÈ pouûitÌm sprievodcu'#13+
'OPEN=Otvoriù'#13+
'SAVE AS=Uloûiù ako'#13+
'REOPEN=Znovu otvoriù'#13+
'SEND BY E-MAIL=Poslaù e-mailom'#13+
'EXIT=Odchod'#13+
'PROPERTIES=Vlastnosti'#13+
'CHART TOOLS=N·stroje grafu'#13+
'VIEW=Zobrazenie'#13+
'OPEN GL=OpenGL'#13+
'SERIES LIST=Zoznam sÈriÌ'#13+
'INSPECTOR=Inöpektor'#13+
'GALLERY=GalÈria'#13+
'STATUS BAR=Stavov˝ riadok'#13+
'AS TAB=Ako tab.'#13+
'AS WINDOW=Ako okno'#13+
'HIDE=Skryù'#13+
'TOOLBARS=N·strojovÈ panely'#13+
'PAGE=Strana'#13+
'LANGUAGE=Jazyk'#13+
'WEB CHARTS GALLERY=GalÈria webov˝ch grafov'#13+
'UPDATE VERSION=Aktualizovan· verzia'#13+
'TEXT MODE=Textov˝ mÛd'#13+
'HELP INDEX=Index pomoci'#13+
'TEECHART WEB=Web TeeChart'#13+
'ONLINE SUPPORT=Online podpora'#13+
'ABOUT=O programe'#13+
'CONFIGURE=Konfigur·cia'#13+
'DUPLICATE=Duplikovaù'#13+
'SELECT ALL=Vybraù vöetko'#13+
'HIDE SERIES LIST=Skryù zoznam sÈriÌ'#13+
'HIDE INSPECTOR=Skryù inöpektora'#13+
'ALIGN TO TOP=Zarovnaù na vrch'#13+
'ALIGN TO BOTTOM=Zarovnaù na spodok'#13+
'VIEW 3D=Zobraziù 3D'#13+
'RIGHT SIDE=Prav· strana'#13+
'CHECK-BOXES=Zaökrt·vacie polÌËka'#13+
'SERIES COLOR=Farba sÈriÌ'#13+
'CONTINOUS=Nepretrûit˝'#13+
'AUTOSIZE=Auto-veækosù'#13+
'CUSTOM POSITION=äpeci·lna pozÌcia'#13+
'GRAY SCALE VISUAL=Vizu·lne stupne öedi'#13+
'INVERTED GRAY SCALE=InverznÈ stupne öedi'#13+
'AUTO SIZE=Auto-veækosù'#13+
'LABEL PERCENT=ätÌtok percento'#13+
'LABEL VALUE=ätÌtok hodnota'#13+
'LABEL PERCENT TOTAL=ätÌtok percento spolu'#13+
'AXIS LINE=»iara osi'#13+
'MINOR GRID=Menöia mrieûka'#13+
'STAIRS INVERTED=InverznÈ schody'#13+
'SIDE MARGINS=Okraje na stran·ch'#13+
'INVERTED PYRAMID=Inverzn· pyramÌda'#13+
'ALIGN GRID=Zarovnan· mrieûka'#13+
'WEIGHTED=V·ûen˝'#13+
'WEIGHTED BY INDEX=V·ûen˝ indexom'#13+
'CREATE NEW DATASET=Vytvoriù nov˝ s˙bor d·t'#13+
'BORLAND BDE=Borland BDE'#13+
'DATASET STYLE=ät˝l s˙boru d·t'#13+
'BDE ALIAS=BDE alias'#13+
'SQL QUERY=SQL prÌkaz'#13+
'SELECT * FROM=select * from'#13+
'CONNECTION=Spojenie'#13+
'BUILD=Stavba'#13+
'TREE NODE EDITOR=Editor stromovÈho uzla'#13+
'CROSS-BOX=KrÌûov˝ box'#13+
'CHILDREN CONNECTIONS=DetskÈ spojenia'#13+
'HORIZONTAL LINE=Horizont·lna Ëiara'#13+
'INVERTED LINE=Inverzn· Ëiara'#13+
'TRIANGLE TOP=TrojuholnÌk hore'#13+
'TRIANGLE BOTTOM=TrojuholnÌk dole'#13+
'TRIANGLE LEFT=TrojuholnÌk væavo'#13+
'TRIANGLE RIGHT=TrojuholnÌk vpravo'#13+
'ALWAYS=Vûdy'#13+
'NEVER=Nikdy'#13+
'CLIP TEXT=Vystrihn˙ù text'#13+
'ALIGN=Zarovnaù'#13+
'DEFAULT IMAGE=ätandardn˝ obr·zok'#13+
'BUTTON5=TlaËÌtko5'#13+
'CLOSED FOLDER=Zatvoren˝ prieËinok'#13+
'OPEN FOLDER=Otvoren˝ prieËinok'#13+
'DESKTOP=Pracovn· plocha'#13+
'MYPC=Moje PC'#13+
'NETWORK=Sieù'#13+
'FLOPPY 3=Disketa 3'#13+
'RECYCLE BIN=Odpadkov˝ kÙö'#13+
'HARD DISK=Pevn˝ disk'#13+
'NET SHARE=SieùovÈ zdieæanie'#13+
'COMPUTER=PoËÌtaË'#13+
'WORLD=Svet'#13+
'FOLDER OPEN AND CLOSE=PrieËinok otvoriù a zatvoriù'#13+
'CHECKED CLOSED FOLDER=Vybran˝ zatvoren˝ prieËinok'#13+
'UNCHECKED CLOSED FOLDER=Nevybran˝ zatvoren˝ prieËinok'#13+
'CHECKED=Vybran˝'#13+
'UNCHECKED=Nevybran˝'#13+
'RADIO CHECKED=Radio vybran˝'#13+
'RADIO UNCHECKED=Radio nevybran˝'#13+
'RADIO CHECKED FOLDER=Radio vybran˝ prieËinok'#13+
'RADIO UNCHECKED FOLDER=Radio nevybran˝ prieËinok'#13+
'HORIZONTAL SIZE=Horizont·lna veækosù'#13+
'VERTICAL SIZE=Vertik·lna veækosù'#13+
'MOVE HORIZ=Presun horiz.'#13+
'MOVE VERT=Presun vert.'#13+
'DARK BORDER=Tmav˝ okraj'#13+
'PIE SERIES=Kol·ËovÈ sÈrie'#13+
'FOCUS=Ohnisko'#13+
'EXPLODE=Explodovaù'#13+
'BOX SIZE=Veækosù polÌËka'#13+
'REVERSAL AMOUNT=Obr·ten˝ rozsah'#13+
'PERCENTAGE=Percento'#13+
'COMPLETE R.M.S.=KompletnÈ R.M.S.'#13+
'BUTTON=TlaËÌtko'#13+
'ALL=Vöetko'#13+
'START AT MIN. VALUE=ätart pri minim·lnej hodnote'#13+
'EXECUTE !=Spustiù !'#13+
'IMAG. SYMBOL=Obr. symbol'#13+
'FACTOR=Faktor'#13+
'SELF STACK=Samokopa'#13+
'SIDE LINES=»iary na strane'#13+
'CHART FROM TEMPLATE (*.TEE FILE)=Graf zo öablÛny (s˙bor *.tee)'#13+
'OPEN TEECHART TEMPLATE FILE FROM=Otvoriù TeeChart öablÛnu zo s˙boru'#13+
'EXPORT DIALOG=Okno exportu'#13+
'BINARY=Bin·rny'#13+
'POINT COLORS=Farby bodu'#13+
'OUTLINE GRADIENT=Obrysov˝ prechod'#13+
'CLOSE LOCATION VALUE=Najbliûöie poloûen· hodnota'#13+
'COMMODITY CHANNEL INDEX=Index tovarovÈho kan·la'#13
;
  end;
end;

Procedure TeeSetSlovak;
begin
  TeeCreateSlovak;
  TeeLanguage:=TeeSlovakLanguage;
  TeeSlovakConstants;
  TeeLanguageHotKeyAtEnd:=False;
  TeeLanguageCanUpper:=True;
end;

initialization
finalization
  FreeAndNil(TeeSlovakLanguage);
end.
