unit TeeSpanish;
{$I TeeDefs.inc}

interface

Uses Classes, TeeTranslate;

Var TeeSpanishLanguage:TLanguageStrings=nil;

Procedure TeeSetSpanish;
Procedure TeeCreateSpanish;

implementation

Uses SysUtils, TeeConst, TeeProCo {$IFNDEF D5},TeCanvas{$ENDIF};

Procedure TeeSpanishConstants;
begin
  { TeeConst }
  TeeMsg_Copyright          :='© 1995-2004 por David Berneda';
  TeeMsg_LegendFirstValue   :='Valor de primera leyenda debe ser > 0';
  TeeMsg_LegendColorWidth   :='Ancho de Color de leyenda > 0%';
  TeeMsg_SeriesSetDataSource:='No hay Gráfico padre para validar DataSource';
  TeeMsg_SeriesInvDataSource:='DataSource no válido: %s';
  TeeMsg_FillSample         :='Rellenar valores ejemplo, número de valores debe ser > 0';
  TeeMsg_AxisLogDateTime    :='Eje Fecha/Hora no puede ser Logarítmico';
  TeeMsg_AxisLogNotPositive :='Valores Min y Max de Eje Logarítmico deben ser >= 0';
  TeeMsg_AxisLabelSep       :='% Separación de etiquetas debe ser > 0';
  TeeMsg_AxisIncrementNeg   :='Incremento de eje debe ser >= 0';
  TeeMsg_AxisMinMax         :='Valor mínimo de eje debe ser <= Mínimo';
  TeeMsg_AxisMaxMin         :='Valor máximo de eje debe ser >= Mínimo';
  TeeMsg_AxisLogBase        :='Base de eje logarítmico debe ser >= 2';
  TeeMsg_MaxPointsPerPage   :='Número de puntos por página debe ser >= 0';
  TeeMsg_3dPercent          :='% Efecto 3D debe estar entre %d y %d';
  TeeMsg_CircularSeries     :='No se permiten referencias circulares de series';
  TeeMsg_WarningHiColor     :='Para una mejor visualización se requiere color de 16k';

  TeeMsg_DefaultPercentOf   :='%s de %s';
  TeeMsg_DefaultPercentOf2  :='%s'+#13+'de %s';
  TeeMsg_DefPercentFormat   :='##0.## %';
  TeeMsg_DefValueFormat     :='#,##0.###';
  TeeMsg_DefLogValueFormat  :='#.0 "x10" E+0';
  TeeMsg_AxisTitle          :='Título Eje';
  TeeMsg_AxisLabels         :='Etiquetas Eje';
  TeeMsg_RefreshInterval    :='Intervalo de refresco debe estar entre 0 y 60';
  TeeMsg_SeriesParentNoSelf :='¡El Series.ParentChart no soy yo!';
  TeeMsg_GalleryLine        :='Línea';
  TeeMsg_GalleryPoint       :='Punto';
  TeeMsg_GalleryArea        :='Area';
  TeeMsg_GalleryBar         :='Barra';
  TeeMsg_GalleryHorizBar    :='Barra Horiz.';
  TeeMsg_Stack              :='Apilado';
  TeeMsg_GalleryPie         :='Pastel';
  TeeMsg_GalleryCircled     :='Circular';
  TeeMsg_GalleryFastLine    :='Línea rápida';
  TeeMsg_GalleryHorizLine   :='Línea Horiz.';

  TeeMsg_PieSample1         :='Coches';
  TeeMsg_PieSample2         :='Teléfonos';
  TeeMsg_PieSample3         :='Tablas';
  TeeMsg_PieSample4         :='Monitores';
  TeeMsg_PieSample5         :='Lámparas';
  TeeMsg_PieSample6         :='Teclados';
  TeeMsg_PieSample7         :='Bicis';
  TeeMsg_PieSample8         :='Sillas';

  TeeMsg_GalleryLogoFont    :='Courier New';
  TeeMsg_Editing            :='Editando %s';

  TeeMsg_GalleryStandard    :='Estandard';
  TeeMsg_GalleryExtended    :='Extendidas';
  TeeMsg_GalleryFunctions   :='Funciones';

  TeeMsg_EditChart          :='E&ditar Gráfico...';
  TeeMsg_PrintPreview       :='&Previsualizar...';
  TeeMsg_ExportChart        :='E&xportar Gráfico...';
  TeeMsg_CustomAxes         :='Ejes Personalizados...';

  TeeMsg_InvalidEditorClass :='%s: Clase Editor no válida: %s';
  TeeMsg_MissingEditorClass :='%s: no tiene cuadro de edición';

  TeeMsg_GalleryArrow       :='Flecha';

  TeeMsg_ExpFinish          :='&Finalizar';
  TeeMsg_ExpNext            :='&Siguiente >';

  TeeMsg_GalleryGantt       :='Gantt';

  TeeMsg_GanttSample1       :='Diseño';
  TeeMsg_GanttSample2       :='Prototipo';
  TeeMsg_GanttSample3       :='Desarrollo';
  TeeMsg_GanttSample4       :='Ventas';
  TeeMsg_GanttSample5       :='Marketing';
  TeeMsg_GanttSample6       :='Testear';
  TeeMsg_GanttSample7       :='Manufac.';
  TeeMsg_GanttSample8       :='Debugando';
  TeeMsg_GanttSample9       :='Nueva Versión';
  TeeMsg_GanttSample10      :='Finanzas';

  TeeMsg_ChangeSeriesTitle  :='Cambiar Título de Series';
  TeeMsg_NewSeriesTitle     :='Nuevo Título de Serie:';
  TeeMsg_DateTime           :='Fecha/Hora';
  TeeMsg_TopAxis            :='Eje superior';
  TeeMsg_BottomAxis         :='Eje inferior';
  TeeMsg_LeftAxis           :='Eje izquierdo';
  TeeMsg_RightAxis          :='Eje derecho';

  TeeMsg_SureToDelete       :='¿Eliminar  %s?';
  TeeMsg_DateTimeFormat     :='For&mato Fecha/Hora:';
  TeeMsg_Default            :='Defecto';
  TeeMsg_ValuesFormat       :='For&mato Valores:';
  TeeMsg_Maximum            :='Máximo';
  TeeMsg_Minimum            :='Mínimo';
  TeeMsg_DesiredIncrement   :='Incremento Deseado %s';

  TeeMsg_IncorrectMaxMinValue:='Valor incorrecto. %s';
  TeeMsg_EnterDateTime      :='Introduzca [Nº de días] '+TeeMsg_HHNNSS;

  TeeMsg_SureToApply        :='¿Aplicar cambios?';
  TeeMsg_SelectedSeries     :='(Series Seleccionadas)';
  TeeMsg_RefreshData        :='&Refrescar datos';

  TeeMsg_DefaultFontSize    :={$IFDEF LINUX}'10'{$ELSE}'8'{$ENDIF};
  TeeMsg_DefaultEditorSize  :='419';
  TeeMsg_FunctionAdd        :='Sumar';
  TeeMsg_FunctionSubtract   :='Restar';
  TeeMsg_FunctionMultiply   :='Multiplicar';
  TeeMsg_FunctionDivide     :='Dividir';
  TeeMsg_FunctionHigh       :='Alto';
  TeeMsg_FunctionLow        :='Bajo';
  TeeMsg_FunctionAverage    :='Media';

  TeeMsg_GalleryShape       :='Forma';
  TeeMsg_GalleryBubble      :='Burbujas';
  TeeMsg_FunctionNone       :='Copiar';

  TeeMsg_None               :='(ninguno)';

  TeeMsg_PrivateDeclarations:='{ Declaraciones privadas }';
  TeeMsg_PublicDeclarations :='{ Declaraciones públicas }';

  TeeMsg_DefaultFontName    :=TeeMsg_DefaultEngFontName;

  TeeMsg_CheckPointerSize   :='Tamaño de puntero debe ser mayor que cero';

  tcAdditional              :='Additional';
  tcDControls               :='Data Controls';
  tcQReport                 :='QReport';

  TeeMsg_About              :='&Acerca de TeeChart...';

  TeeMsg_DataSet            :='Tabla/consulta';
  TeeMsg_AskDataSet         :='&Tabla/consulta:';

  TeeMsg_SingleRecord       :='Registro único';
  TeeMsg_AskDataSource      :='&Fuente de datos:';

  TeeMsg_Summary            :='Sumario';

  TeeMsg_FunctionPeriod     :='El periodo de la función debe ser >= 0';

  TeeMsg_WizardTab          :='Negocios';
  TeeMsg_TeeChartWizard     :='Asistente TeeChart';

  TeeMsg_ClearImage         :='Quita&r';
  TeeMsg_BrowseImage        :='&Abrir...';

  TeeMsg_WizardSureToClose  :='¿Está seguro de cerrar el Asistente TeeChart?';
  TeeMsg_FieldNotFound      :='El campo %s no existe';

  TeeMsg_DepthAxis          :='Eje Prof.';
  TeeMsg_PieOther           :='Otro';
  TeeMsg_ShapeGallery1      :='abc';
  TeeMsg_ShapeGallery2      :='123';
  TeeMsg_ValuesX            :='X';
  TeeMsg_ValuesY            :='Y';
  TeeMsg_ValuesPie          :='Pastel';
  TeeMsg_ValuesBar          :='Barra';
  TeeMsg_ValuesAngle        :='Angulo';
  TeeMsg_ValuesGanttStart   :='Comienzo';
  TeeMsg_ValuesGanttEnd     :='Fin';
  TeeMsg_ValuesGanttNextTask:='ProxTarea';
  TeeMsg_ValuesBubbleRadius :='Radio';
  TeeMsg_ValuesArrowEndX    :='Fin X';
  TeeMsg_ValuesArrowEndY    :='Fin Y';
  TeeMsg_Legend             :='Leyenda';
  TeeMsg_Title              :='Título';
  TeeMsg_Foot               :='Pie';
  TeeMsg_Period		    :='Periodo';
  TeeMsg_PeriodRange        :='Rango Periodo';
  TeeMsg_CalcPeriod         :='Calcular %s cada:';
  TeeMsg_SmallDotsPen       :='Puntitos';

  TeeMsg_InvalidTeeFile     :='Gráfico no válido en archivo *.'+TeeMsg_TeeExtension;
  TeeMsg_WrongTeeFileFormat :='Formato de archivo *.'+TeeMsg_TeeExtension+' incorrecto.';
  TeeMsg_EmptyTeeFile       :='Archivo *.'+TeeMsg_TeeExtension+' vacio.';  { 5.01 }

  {$IFDEF D5}
  TeeMsg_ChartAxesCategoryName   := 'Ejes Gráfico';
  TeeMsg_ChartAxesCategoryDesc   := 'Propiedades y Eventos de Ejes';
  TeeMsg_ChartWallsCategoryName  := 'Paredes del Gráfico';
  TeeMsg_ChartWallsCategoryDesc  := 'Propiedades y Eventos de la pared del gráfico';
  TeeMsg_ChartTitlesCategoryName := 'Títulos del Gráfico';
  TeeMsg_ChartTitlesCategoryDesc := 'Eventos y propiedades del título del gráfico';
  TeeMsg_Chart3DCategoryName     := 'Gráfico 3D';
  TeeMsg_Chart3DCategoryDesc     := 'Propiedades y eventos del gráfico 3D';
  {$ENDIF}

  TeeMsg_CustomAxesEditor       :='Personalizado ';
  TeeMsg_Series                 :='Series';
  TeeMsg_SeriesList             :='Series...';

  TeeMsg_PageOfPages            :='Página %d de %d';
  TeeMsg_FileSize               :='%d bytes';

  TeeMsg_First  :='Primero';
  TeeMsg_Prior  :='Anterior';
  TeeMsg_Next   :='Siguiente';
  TeeMsg_Last   :='Último';
  TeeMsg_Insert :='Insertar';
  TeeMsg_Delete :='Eliminar';
  TeeMsg_Edit   :='Editar';
  TeeMsg_Post   :='Guardar';
  TeeMsg_Cancel :='Cancelar';

  TeeMsg_All    :='(todas)'; {las series}
  TeeMsg_Index  :='Indice';
  TeeMsg_Text   :='Texto';

  TeeMsg_AsBMP        :='como &Bitmap';
  TeeMsg_BMPFilter    :='Bitmaps (*.bmp)|*.bmp';
  TeeMsg_AsEMF        :='como &Metafile';
  TeeMsg_EMFFilter    :='Metafiles mejorados (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  TeeMsg_ExportPanelNotSet := 'La propiedad Panel no está asignada.';

  TeeMsg_Normal    :='Normal';
  TeeMsg_NoBorder  :='Sin Borde';
  TeeMsg_Dotted    :='Puntos';
  TeeMsg_Colors    :='Colores';
  TeeMsg_Filled    :='Relleno';
  TeeMsg_Marks     :='Marcas';
  TeeMsg_Stairs    :='Escaleras';
  TeeMsg_Points    :='Puntos';
  TeeMsg_Height    :='Altura';
  TeeMsg_Hollow    :='Hueco';
  TeeMsg_Point2D   :='Punto 2D';
  TeeMsg_Triangle  :='Triángulos';
  TeeMsg_Star      :='Estrella';
  TeeMsg_Circle    :='Circulo';
  TeeMsg_DownTri   :='Tri. Bajo';
  TeeMsg_Cross     :='Cruz';
  TeeMsg_Diamond   :='Diamante';
  TeeMsg_NoLines   :='Sin líneas';
  TeeMsg_Stack100  :='Apilado 100%';
  TeeMsg_Pyramid   :='Pirámide';
  TeeMsg_Ellipse   :='Elipse';
  TeeMsg_InvPyramid:='Pirámide Inv.';
  TeeMsg_Sides     :='Caras';
  TeeMsg_SideAll   :='Todas las caras';
  TeeMsg_Patterns  :='Patrones';
  TeeMsg_Exploded  :='Expandido';
  TeeMsg_Shadow    :='Sombra';
  TeeMsg_SemiPie   :='Semi Tarta';
  TeeMsg_Rectangle :='Rectángulo';
  TeeMsg_VertLine  :='Lín.Vert.';
  TeeMsg_HorizLine :='Lín.Horiz.';
  TeeMsg_Line      :='Línea';
  TeeMsg_Cube      :='Cubo';
  TeeMsg_DiagCross :='Aspa';

  TeeMsg_CanNotFindTempPath    :='No se puede localizar la carpeta Temp';
  TeeMsg_CanNotCreateTempChart :='No se puede crear archivo Temp';
  TeeMsg_CanNotEmailChart      :='No se puede enviar Gráfico por correo elec. Error Mapi: %d';

  TeeMsg_SeriesDelete :='Borrar Series: Indice de Series fuera de límites %d (0 a %d).';

  { 5.02 }
  TeeMsg_AskLanguage  :='&Lenguaje...';

  { TeeProCo }
  TeeMsg_GalleryPolar       :='Polar';
  TeeMsg_GalleryCandle      :='Vela';
  TeeMsg_GalleryVolume      :='Volumen';
  TeeMsg_GallerySurface     :='Superfície';
  TeeMsg_GalleryContour     :='Contorno';
  TeeMsg_GalleryBezier      :='Bezier';
  TeeMsg_GalleryPoint3D     :='Puntos 3D';
  TeeMsg_GalleryRadar       :='Radar';
  TeeMsg_GalleryDonut       :='Donut';
  TeeMsg_GalleryCursor      :='Cursor';
  TeeMsg_GalleryBar3D       :='Barras 3D';
  TeeMsg_GalleryBigCandle   :='Vela Grande';
  TeeMsg_GalleryLinePoint   :='Punto Línea';
  TeeMsg_GalleryHistogram   :='Histograma';
  TeeMsg_GalleryWaterFall   :='Caida de Agua';
  TeeMsg_GalleryWindRose    :='Rosa de Vientos';
  TeeMsg_GalleryClock       :='Reloj';
  TeeMsg_GalleryColorGrid   :='Rejilla de Color';
  TeeMsg_GalleryBoxPlot     :='Esquema Vertical';
  TeeMsg_GalleryHorizBoxPlot:='Esquema Horizontal';
  TeeMsg_GalleryBarJoin     :='Union de Barras';
  TeeMsg_GallerySmith       :='Smith';
  TeeMsg_GalleryPyramid     :='Pirámide';
  TeeMsg_GalleryMap         :='Mapa';

  TeeMsg_PolyDegreeRange     :='El grado polinomial debe estar entre 1 y 20';
  TeeMsg_AnswerVectorIndex   :='El índice de matriz de vectores debe estar entre 1 y %d';
  TeeMsg_FittingError        :='No es posible calcular el ajuste';
  TeeMsg_PeriodRange         :='El periodo debe ser >= 0';
  TeeMsg_ExpAverageWeight    :='Peso de Promedio Exp. debe estar entre 0 y 1';
  TeeMsg_GalleryErrorBar     :='Barras de Error';
  TeeMsg_GalleryError        :='Error';
  TeeMsg_GalleryHighLow      :='Alto-Bajo';
  TeeMsg_FunctionMomentum    :='Momento';
  TeeMsg_FunctionMomentumDiv :='Mom. División';
  TeeMsg_FunctionExpAverage  :='Promedio Exp.';
  TeeMsg_FunctionMovingAverage:='Media Móvil';
  TeeMsg_FunctionExpMovAve   :='Media Móvil Exp.';
  TeeMsg_FunctionRSI         :='R.S.I.';
  TeeMsg_FunctionCurveFitting:='Ajuste a Curva';
  TeeMsg_FunctionTrend       :='Tendencia';
  TeeMsg_FunctionExpTrend    :='Tendencia Exp.';
  TeeMsg_FunctionLogTrend    :='Tendencia Logarítm.';
  TeeMsg_FunctionCumulative  :='Acumular';
  TeeMsg_FunctionStdDeviation:='Desviación Estand.';
  TeeMsg_FunctionBollinger   :='Bollinger';
  TeeMsg_FunctionRMS         :='Raiz Media Cuad.';
  TeeMsg_FunctionMACD        :='MACD';
  TeeMsg_FunctionStochastic  :='Estocástico';
  TeeMsg_FunctionADX         :='ADX';

  TeeMsg_FunctionCount       :='Contar';
  TeeMsg_LoadChart           :='Abrir TeeChart...';
  TeeMsg_SaveChart           :='Guardar TeeChart...';
  TeeMsg_TeeFiles            :='Archivos TeeChart Pro';

  TeeMsg_GallerySamples      :='Otras';
  TeeMsg_GalleryStats        :='Estadísticas';

  TeeMsg_CannotFindEditor    :='No puedo localizar el formulario %s';

  TeeMsg_CannotLoadChartFromURL:='Código de error: %d descargando gráfico de Web: %s';
  TeeMsg_CannotLoadSeriesDataFromURL:='Código de error: %d descargando datos de series de Web: %s';

  TeeMsg_Test                :='Test...';

  TeeMsg_ValuesDate          :='Fecha';
  TeeMsg_ValuesOpen          :='Apertura';
  TeeMsg_ValuesHigh          :='Alto';
  TeeMsg_ValuesLow           :='Bajo';
  TeeMsg_ValuesClose         :='Cierre';
  TeeMsg_ValuesOffset        :='Desplazar';
  TeeMsg_ValuesStdError      :='Error Est.';

  TeeMsg_Grid3D              :='Rejilla3D';

  TeeMsg_LowBezierPoints     :='Número de puntos Bezier debe ser > 1';

  { TeeCommander component... }

  TeeCommanMsg_Normal   :='Normal';
  TeeCommanMsg_Edit     :='Editar';
  TeeCommanMsg_Print    :='Imprimir';
  TeeCommanMsg_Copy     :='Copiar';
  TeeCommanMsg_Save     :='Guardar';
  TeeCommanMsg_3D       :='3D';

  TeeCommanMsg_Rotating :='Rotación: %d° Elevación: %d°';
  TeeCommanMsg_Rotate   :='Rotar';

  TeeCommanMsg_Moving   :='Desp.Horiz.: %d Desp.Vert.: %d';
  TeeCommanMsg_Move     :='Mover';

  TeeCommanMsg_Zooming  :='Ampliar: %d %%';
  TeeCommanMsg_Zoom     :='Ampliar';

  TeeCommanMsg_Depthing :='3D: %d %%';
  TeeCommanMsg_Depth    :='Profundidad'; { 5.01 }

  TeeCommanMsg_Chart    :='Chart';
  TeeCommanMsg_Panel    :='Panel';

  TeeCommanMsg_RotateLabel:='Arrastrar %s para Rotar'; { 5.01 }
  TeeCommanMsg_MoveLabel  :='Arrastrar %s para Mover'; { 5.01 }
  TeeCommanMsg_ZoomLabel  :='Arrastrar %s para Zoom'; { 5.01 }
  TeeCommanMsg_DepthLabel :='Arrastrar %s para Profundidad 3D'; { 5.01 }

  TeeCommanMsg_NormalLabel:='Arrastrar botón izq. para ampliar, der. para desplazar';
  TeeCommanMsg_NormalPieLabel:='Arrastrar Porción de Pastel para expandir.';

  TeeCommanMsg_PieExploding := 'Porción: %d Expandida: %d %%';

  TeeMsg_TriSurfaceLess:='Número de puntos debe ser >= 4';
  TeeMsg_TriSurfaceAllColinear:='Todos los puntos estan alineados.';
  TeeMsg_TriSurfaceSimilar:='Puntos similares - no se pueden calcular triángulos.';
  TeeMsg_GalleryTriSurface:='Sup. Triáng.';

  TeeMsg_AllSeries := 'Todas las Series';
  TeeMsg_Edit      := 'Editar';

  TeeMsg_GalleryFinancial    :='Financieras';

  TeeMsg_CursorTool    :='Cursor';
  TeeMsg_DragMarksTool :='Arrastrar Marcas'; { 5.01 }
  TeeMsg_AxisArrowTool :='Flechas en Ejes';
  TeeMsg_DrawLineTool  :='Dibujar Líneas';
  TeeMsg_NearestTool   :='Punto más cercano';
  TeeMsg_ColorBandTool :='Bandas de color';
  TeeMsg_ColorLineTool :='Líneas de color';
  TeeMsg_RotateTool    :='Rotar';
  TeeMsg_ImageTool     :='Imagen';
  TeeMsg_MarksTipTool  :='Marcas';
  TeeMsg_AnnotationTool:='Anotación';

  TeeMsg_CantDeleteAncestor  :='No puedo eliminar componente heredado. (Ancestor)';

  TeeMsg_Load	         :='Cargar...';
  TeeMsg_NoSeriesSelected:='No hay Series seleccionadas';

  { TeeChart Actions }
  TeeMsg_CategoryChartActions  :='Chart';
  TeeMsg_CategorySeriesActions :='Chart Series';

  TeeMsg_Action3D               :='&3D';
  TeeMsg_Action3DHint           :='Intercambiar 2D / 3D';
  TeeMsg_ActionSeriesActive     :='&Activo';
  TeeMsg_ActionSeriesActiveHint :='Mostrar / Ocultar Series';
  TeeMsg_ActionEditHint         :='Editar Gráfico';
  TeeMsg_ActionEdit             :='&Editar...';
  TeeMsg_ActionCopyHint         :='Copiar al portapapeles';
  TeeMsg_ActionCopy             :='&Copiar';
  TeeMsg_ActionPrintHint        :='Previsualización de gráfico';
  TeeMsg_ActionPrint            :='&Imprimir...';
  TeeMsg_ActionAxesHint         :='Mostrar / Ocultar Ejes';
  TeeMsg_ActionAxes             :='&Ejes';
  TeeMsg_ActionGridsHint        :='Mostrar / Ocultar rejilla';
  TeeMsg_ActionGrids            :='&Rejillas';
  TeeMsg_ActionLegendHint       :='Mostrar / Ocultar leyenda';
  TeeMsg_ActionLegend           :='&Leyenda';
  TeeMsg_ActionSeriesEditHint   :='Editar Series';
  TeeMsg_ActionSeriesMarksHint  :='Mostrar / Ocultar marcas de series';
  TeeMsg_ActionSeriesMarks      :='&Marcas';
  TeeMsg_ActionSaveHint         :='Guardar Gráfico';
  TeeMsg_ActionSave             :='&Guardar...';

  TeeMsg_CandleBar              :='Barras';
  TeeMsg_CandleNoOpen           :='Sin Apertura';
  TeeMsg_CandleNoClose          :='Sin Cierre';
  TeeMsg_NoLines                :='Sin Líneas';
  TeeMsg_NoHigh                 :='Sin valor Alto';
  TeeMsg_NoLow                  :='Sin valor Bajo';
  TeeMsg_ColorRange             :='Rango de Color';
  TeeMsg_WireFrame              :='Alambres';
  TeeMsg_DotFrame               :='Puntos';
  TeeMsg_Positions              :='Posiciones';
  TeeMsg_NoGrid                 :='Sin rejilla';
  TeeMsg_NoPoint                :='Sin punto';
  TeeMsg_NoLine                 :='Sin línea';
  TeeMsg_Labels                 :='Etiquetas';
  TeeMsg_NoCircle               :='Sin circulo';
  TeeMsg_Lines                  :='Líneas';
  TeeMsg_Border                 :='Borde';

  TeeMsg_SmithResistance      :='Resistencia';
  TeeMsg_SmithReactance       :='Reactancia';

  TeeMsg_Column  :='Columna';

  { 5.01 }
  TeeMsg_Separator            :='Separador';
  TeeMsg_FunnelSegment        :='Segmento ';
  TeeMsg_FunnelSeries         :='Embudo';
  TeeMsg_FunnelPercent        :='0.00 %';
  TeeMsg_FunnelExceed         :='Rebasar cuota';
  TeeMsg_FunnelWithin         :=' entre cuota';
  TeeMsg_FunnelBelow          :=' o debajo de cuota';
  TeeMsg_CalendarSeries       :='Calendario';
  TeeMsg_DeltaPointSeries     :='Tendencias';
  TeeMsg_ImagePointSeries     :='Imagen Punto';
  TeeMsg_ImageBarSeries       :='Imagen Barra';
  TeeMsg_SeriesTextFieldZero  :='SeriesText: El campo debe ser mayor que zero.';

  { 5.02 } { Moved from TeeImageConstants.pas unit }

  TeeMsg_AsJPEG        :='como &JPEG';
  TeeMsg_JPEGFilter    :='Archivos JPEG (*.jpg)|*.jpg';
  TeeMsg_AsGIF         :='como &GIF';
  TeeMsg_GIFFilter     :='Archivos GIF (*.gif)|*.gif';
  TeeMsg_AsPNG         :='como &PNG';
  TeeMsg_PNGFilter     :='Archivos PNG (*.png)|*.png';
  TeeMsg_AsPCX         :='como PC&X';
  TeeMsg_PCXFilter     :='Archivos PCX (*.pcx)|*.pcx';
  TeeMsg_AsVML         :='como &VML (HTM)';
  TeeMsg_VMLFilter     :='Archivos VML (*.htm)|*.htm';

  { 5.02 }
  TeeMsg_Origin               := 'Origen';
  TeeMsg_Transparency         := 'Transparencia';
  TeeMsg_Box		      := 'Caja';
  TeeMsg_ExtrOut	      := 'ExtrOut';
  TeeMsg_MildOut	      := 'MildOut';
  TeeMsg_PageNumber	      := 'Núm Página';
  TeeMsg_TextFile             := 'Archivos Texto';

  { 5.03 }
  TeeMsg_Gradient             :='Gradiente';
  TeeMsg_WantToSave           :='¿Desea guardar %s?';

  TeeMsg_Property            :='Propiedad';
  TeeMsg_Value               :='Valor';
  TeeMsg_Yes                 :='Sí';
  TeeMsg_No                  :='No';
  TeeMsg_Image                :='(imagen)';

  TeeMsg_DragPoint            :='Arrastrar Puntos';
  TeeMsg_OpportunityValues    :='OpportunityValues';
  TeeMsg_QuoteValues          :='QuoteValues';

  {OCX 5.0.4}
  TeeMsg_ActiveXVersion      := 'Versión ActiveX ' + AXVer;
  TeeMsg_ActiveXCannotImport := 'No se puede importar TeeChart desde %s';
  TeeMsg_ActiveXVerbPrint    := 'Vista &Preliminar...';
  TeeMsg_ActiveXVerbExport   := 'E&xportar...';
  TeeMsg_ActiveXVerbImport   := '&Importar...';
  TeeMsg_ActiveXVerbHelp     := 'Ayu&da...';
  TeeMsg_ActiveXVerbAbout    := '&Acerca de TeeChart...';
  TeeMsg_ActiveXError        := 'TeeChart: Codigo error: %d downloading: %s';
  TeeMsg_DatasourceError     := 'El Datsource no es una Series o Recordset';
  TeeMsg_SeriesTextSrcError  := 'Tipo de Series invalido';
  TeeMsg_AxisTextSrcError    := 'Tipo de Eje invalido';
  TeeMsg_DelSeriesDatasource := '¿Esta seguro que quiere borrar %s ?';
  TeeMsg_OCXNoPrinter        := 'No hay una ninguna impresora instalada por omissión';
  TeeMsg_ActiveXPictureNotValid:='Imagen no valida';

  { 6.0 }
  TeeMsg_AsPDF            :='como &PDF';
  TeeMsg_PDFFilter        :='Archivos PDF (*.pdf)|*.pdf';
  TeeMsg_AsPS             :='como PostScript';
  TeeMsg_PSFilter         :='Archivos PostScript (*.eps)|*.eps';
  TeeMsg_GalleryHorizArea :='Area'#13'Horizontal';
  TeeMsg_SelfStack        :='Apilado él mismo';
  TeeMsg_DarkPen          :='Borde oscuro';
  TeeMsg_SelectFolder     :='Seleccione carpeta base datos';
  TeeMsg_BDEAlias         :='&Alias:';
  TeeMsg_ADOConnection    :='&Conexión:';

  TeeMsg_FunctionSmooth       :='Suavizado';
  TeeMsg_FunctionCross        :='Puntos de corte';
  TeeMsg_GridTranspose        :='Invertir matriz 3D';
  TeeMsg_FunctionCompress     :='Compresión';
  TeeMsg_ExtraLegendTool      :='Leyenda Extra';
  TeeMsg_FunctionCLV          :='Close Location'#13'Value';
  TeeMsg_FunctionOBV          :='On Balance'#13'Volume';
  TeeMsg_FunctionCCI          :='Commodity'#13'Channel Index';
  TeeMsg_FunctionPVO          :='Volume'#13'Oscillator';
  TeeMsg_SeriesAnimTool       :='Animación de Series';
  TeeMsg_GalleryPointFigure   :='Punto y Figura';
  TeeMsg_Up                   :='Arriba';
  TeeMsg_Down                 :='Abajo';
  TeeMsg_GanttTool            :='Arrastre Gantt';
  TeeMsg_XMLFile              :='Archivo XML';
  TeeMsg_GridBandTool         :='Bandas de rejilla';
  TeeMsg_FunctionPerf         :='Rendimiento';
  TeeMsg_GalleryGauge         :='Indicador';
  TeeMsg_GalleryGauges        :='Indicadores';
  TeeMsg_GalleryVector3D      :='Vector 3D';
  TeeMsg_Gallery3D            :='3D';
  TeeMsg_GalleryTower         :='Torre';
  TeeMsg_SingleColor          :='Un solo color';
  TeeMsg_Cover                :='Cubierta';
  TeeMsg_Cone                 :='Cono';
  TeeMsg_PieTool              :='Porciones Pastel';

  // 7.0
  TeeMsg_View2D               :='2D';
  TeeMsg_Outline              :='Perfil';

  TeeMsg_Stop                 :='Parar';
  TeeMsg_Execute              :='Executar !';
  TeeMsg_Themes               :='Temas';
  TeeMsg_LightTool            :='Iluminación 2D';
  TeeMsg_Current              :='Actual';
  TeeMsg_FunctionCorrelation  :='Correlación';
  TeeMsg_FunctionVariance     :='Varianza';
  TeeMsg_GalleryBubble3D      :='Burbuja 3D';
  TeeMsg_GalleryHorizHistogram:='Horizontal'#13'Histograma';
  TeeMsg_FunctionPerimeter    :='Perímetro';
  TeeMsg_SurfaceNearestTool   :='Superfície más cercana';
  TeeMsg_AxisScrollTool       :='Arrastre de ejes';
  TeeMsg_RectangleTool        :='Rectángulo';
  TeeMsg_GalleryPolarBar      :='Barra Polar';
  TeeMsg_AsWapBitmap          :='Bitmap WAP';
  TeeMsg_WapBMPFilter         :='Bitmaps WAP (*.wbmp)|*.wbmp';
  TeeMsg_ClipSeries           :='Oculta Series';
  TeeMsg_SeriesBandTool       :='Banda entre Series';

  TeeMsg_Options              :='&Opciones...';
end;

Procedure TeeCreateSpanish;
begin
  if not Assigned(TeeSpanishLanguage) then
  begin
    TeeSpanishLanguage:=TLanguageStrings.Create;
    TeeSpanishLanguage.Text:=

'LABELS=Textos'+#13+
'DATASET=Tabla'+#13+
'ALL RIGHTS RESERVED.=Todos los Derechos Reservados.'+#13+
'APPLY=Aplicar'+#13+
'CLOSE=Cerrar'+#13+
'OK=Aceptar'+#13+
'ABOUT TEECHART PRO V7.0=Acerca de TeeChart Pro v7.0'+#13+
'OPTIONS=Opciones'+#13+
'FORMAT=Formato'+#13+
'TEXT=Texto'+#13+
'GRADIENT=Gradiente'+#13+
'SHADOW=Sombra'+#13+
'POSITION=Posición'+#13+
'LEFT=Izquierda'+#13+
'TOP=Arriba'+#13+
'CUSTOM=Person.'+#13+
'PEN=Lápiz'+#13+
'PATTERN=Trama'+#13+
'SIZE=Tamaño'+#13+
'BEVEL=Marco'+#13+
'INVERTED=Invertido'+#13+
'INVERTED SCROLL=Desplaz. Invertido'+#13+
'BORDER=Borde'+#13+
'ORIGIN=Origen'+#13+
'USE ORIGIN=Usar Origen'+#13+
'AREA LINES=Líneas Area'+#13+
'AREA=Area'+#13+
'COLOR=Color'+#13+
'SERIES=Series'+#13+
'SUM=Suma'+#13+
'DAY=Dia'+#13+
'QUARTER=Trimestre'+#13+
'(MAX)=(max)'+#13+
'(MIN)=(min)'+#13+
'VISIBLE=Visible'+#13+
'CURSOR=Cursor'+#13+
'GLOBAL=Global'+#13+
'X=X'+#13+
'Y=Y'+#13+
'Z=Z'+#13+
'3D=3D'+#13+
'HORIZ. LINE=Línea Horiz.'+#13+
'LABEL AND PERCENT=Etiqueta y Porcentaje'+#13+
'LABEL AND VALUE=Etiqueta y Valor'+#13+
'LABEL AND PERCENT TOTAL=Etiqueta Porc. Total'+#13+
'PERCENT TOTAL=Total Porcentaje'+#13+
'MSEC.=msec.'+#13+
'SUBTRACT=Restar'+#13+
'MULTIPLY=Multiplicar'+#13+
'DIVIDE=Dividir'+#13+
'STAIRS=Escaleras'+#13+
'MOMENTUM=Momento'+#13+
'AVERAGE=Media'+#13+
'XML=XML'+#13+
'HTML TABLE=Tabla HTML'+#13+
'EXCEL=Excel'+#13+
'NONE=Ninguno'+#13+
'(NONE)=Ninguna'#13+
'WIDTH=Ancho'+#13+
'HEIGHT=Alto'+#13+
'COLOR EACH=Colorea Cada'+#13+
'STACK=Apilar'+#13+
'STACKED=Apilado'+#13+
'STACKED 100%=Apilado 100%'+#13+
'AXIS=Eje'+#13+
'LENGTH=Longitud'+#13+
'CANCEL=Cancelar'+#13+
'SCROLL=Desplazamiento'+#13+
'INCREMENT=Incremento'+#13+
'VALUE=Valor'+#13+
'STYLE=Estilo'+#13+
'JOIN=Unión'+#13+
'AXIS INCREMENT=Incremento de Eje'+#13+
'AXIS MAXIMUM AND MINIMUM=Máximo y Mínimo de Eje'+#13+
'% BAR WIDTH=Ancho Barra %'+#13+
'% BAR OFFSET=Desplaz. Barra %'+#13+
'BAR SIDE MARGINS=Márgenes Laterales'+#13+
'AUTO MARK POSITION=Posición Marcas Auto.'+#13+
'DARK BAR 3D SIDES=Lados Barra Oscuros'+#13+
'MONOCHROME=Monocromo'+#13+
'COLORS=Colores'+#13+
'DEFAULT=Defecto'+#13+
'MEDIAN=Mediana'+#13+
'IMAGE=Imagen'+#13+
'DAYS=Dias'+#13+
'WEEKDAYS=Laborables'+#13+
'TODAY=Hoy'+#13+
'SUNDAY=Domingo'+#13+
'MONTHS=Meses'+#13+
'LINES=Líneas'+#13+
'UPPERCASE=Mayúsculas'+#13+
'STICK=Candle'+#13+
'CANDLE WIDTH=Ancho Candle'+#13+
'BAR=Barra'+#13+
'OPEN CLOSE=Aper. Cierre'+#13+
'DRAW 3D=Dibujar 3D'+#13+
'DARK 3D=Oscuro 3D'+#13+
'SHOW OPEN=Ver Apertura'+#13+
'SHOW CLOSE=Ver Cierre'+#13+
'UP CLOSE=Cierre Arriba'+#13+
'DOWN CLOSE=Cierre Abajo'+#13+
'CIRCLED=Circular'+#13+
'CIRCLE=Círculo'+#13+
'3 DIMENSIONS=3 Dimensiones'+#13+
'ROTATION=Rotación'+#13+
'RADIUS=Radios'+#13+
'HOURS=Horas'+#13+
'HOUR=Hora'+#13+
'MINUTES=Minutos'+#13+
'SECONDS=Segundos'+#13+
'FONT=Fuente'+#13+
'INSIDE=Interior'+#13+
'ROTATED=Rotar'+#13+
'ROMAN=Romanos'+#13+
'TRANSPARENCY=Transparencia'+#13+
'DRAW BEHIND=Dibujar Detrás'+#13+
'RANGE=Rango'+#13+
'PALETTE=Paleta'+#13+
'STEPS=Pasos'+#13+
'GRID=Rejilla'+#13+
'GRID SIZE=Tamaño Rejilla'+#13+
'ALLOW DRAG=Permite arrastrar'+#13+
'AUTOMATIC=Automático'+#13+
'LEVEL=Nivel'+#13+
'LEVELS POSITION=Posición Niveles'+#13+
'SNAP=Ajustar'+#13+
'FOLLOW MOUSE=Seguir Ratón'+#13+
'TRANSPARENT=Transparente'+#13+
'ROUND FRAME=Marco Redondo'+#13+
'FRAME=Marco'+#13+
'START=Inicio'+#13+
'END=Final'+#13+
'MIDDLE=Medio'+#13+
'NO MIDDLE=Sin Medio'+#13+
'DIRECTION=Dirección'+#13+
'DATASOURCE=Origen de Datos'+#13+
'AVAILABLE=Disponibles'+#13+
'SELECTED=Seleccionados'+#13+
'CALC=Calcular'+#13+
'GROUP BY=Agrupar por'+#13+
'OF=de'+#13+
'HOLE %=Agujero %'+#13+
'RESET POSITIONS=Posiciones defecto'+#13+
'MOUSE BUTTON=Botón Ratón'+#13+
'ENABLE DRAWING=Permite Dibujar'+#13+
'ENABLE SELECT=Permite Seleccionar'+#13+
'ORTHOGONAL=Ortogonal'+#13+
'ANGLE=Angulo'+#13+
'ZOOM TEXT=Amplia Textos'+#13+
'PERSPECTIVE=Perspectiva'+#13+
'ZOOM=Ampliar'+#13+
'ELEVATION=Elevación'+#13+
'BEHIND=Detrás'+#13+
'AXES=Ejes'+#13+
'SCALES=Escalas'+#13+
'TITLE=Título'+#13+
'TICKS=Marcas'+#13+
'MINOR=Menores'+#13+
'CENTERED=Centrado'+#13+
'CENTER=Centro'+#13+
'PATTERN COLOR EDITOR=Editor de Trama'+#13+
'START VALUE=Valor Inicial'+#13+
'END VALUE=Valor Final'+#13+
'COLOR MODE=Modo de Color'+#13+
'LINE MODE=Modo de Línea'+#13+
'HEIGHT 3D=Alto 3D'+#13+
'OUTLINE=Borde'+#13+
'PRINT PREVIEW=Imprimir'+#13+
'ANIMATED=Animado'+#13+
'ALLOW=Permitir'+#13+
'DASH=Líneas'+#13+
'DOT=Puntos'+#13+
'DASH DOT DOT=Línea Punto Punto'+#13+
'PALE=Suave'+#13+
'STRONG=Fuerte'+#13+
'WIDTH UNITS=Unidades'+#13+
'FOOT=Pie'+#13+
'SUBFOOT=Sub Pie'+#13+
'SUBTITLE=Subtítulo'+#13+
'LEGEND=Leyenda'+#13+
'COLON=Dos puntos'+#13+
'AXIS ORIGIN=Origen Eje'+#13+
'UNITS=Unidades'+#13+
'PYRAMID=Pirámide'+#13+
'DIAMOND=Diamante'+#13+
'CUBE=Cubo'+#13+
'TRIANGLE=Triángulo'+#13+
'STAR=Estrella'+#13+
'SQUARE=Cuadrado'+#13+
'DOWN TRIANGLE=Triángulo Invert.'+#13+
'SMALL DOT=Puntito'+#13+
'LOAD=Cargar'+#13+
'FILE=Archivo'+#13+
'RECTANGLE=Rectángulo'+#13+
'HEADER=Cabecera'+#13+
'CLEAR=Borrar'+#13+
'ONE HOUR=Una Hora'+#13+
'ONE YEAR=Un Año'+#13+
'ELLIPSE=Elipse'+#13+
'CONE=Cono'+#13+
'ARROW=Flecha'+#13+
'CYLLINDER=Cilindro'+#13+
'TIME=Hora'+#13+
'BRUSH=Trama'+#13+
'LINE=Línea'+#13+
'VERTICAL LINE=Línea Vertical'+#13+
'AXIS ARROWS=Flechas en Ejes'+#13+
'MARK TIPS=Sugerencias'+#13+
'DASH DOT=Línea Punto'+#13+
'COLOR BAND=Bandas de Color'+#13+
'COLOR LINE=Linea de Color'+#13+
'INVERT. TRIANGLE=Triángulo Invert.'+#13+
'INVERT. PYRAMID=Pirámide Invert.'+#13+
'INVERTED PYRAMID=Pirámide Invert.'+#13+
'SERIES DATASOURCE TEXT EDITOR=Editor de Origen de Datos de Texto'+#13+
'SOLID=Sólido'+#13+
'WIREFRAME=Alambres'+#13+
'DOTFRAME=Puntos'+#13+
'SIDE BRUSH=Trama Lateral'+#13+
'SIDE=Al lado'+#13+
'SIDE ALL=Lateral'+#13+
'ROTATE=Rotar'+#13+
'SMOOTH PALETTE=Paleta suavizada'+#13+
'CHART TOOLS GALLERY=Galería de Herramientas'+#13+
'ADD=Añadir'+#13+
'BORDER EDITOR=Editor de Borde'+#13+
'DRAWING MODE=Modo de Dibujo'+#13+
'CLOSE CIRCLE=Cerrar Círculo'+#13+
'PICTURE=Imagen'+#13+
'NATIVE=Nativo'+#13+
'DATA=Datos'+#13+
'KEEP ASPECT RATIO=Mantener proporción'+#13+
'COPY=Copiar'+#13+
'SAVE=Guardar'+#13+
'SEND=Enviar'+#13+
'INCLUDE SERIES DATA=Incluir Datos de Series'+#13+
'FILE SIZE=Tamaño del Archivo'+#13+
'INCLUDE=Incluir'+#13+
'POINT INDEX=Indice de Puntos'+#13+
'POINT LABELS=Etiquetas de Puntos'+#13+
'DELIMITER=Delimitador'+#13+
'DEPTH=Profund.'+#13+
'COMPRESSION LEVEL=Nivel Compresión'+#13+
'COMPRESSION=Compresión'+#13+
'PATTERNS=Tramas'+#13+
'LABEL=Etiqueta'+#13+
'GROUP SLICES=Agrupar porciones'+#13+
'EXPLODE BIGGEST=Separar Porción'+#13+
'TOTAL ANGLE=Angulo Total'+#13+
'HORIZ. SIZE=Tamaño Horiz.'+#13+
'VERT. SIZE=Tamaño Vert.'+#13+
'SHAPES=Formas'+#13+
'INFLATE MARGINS=Ampliar Márgenes'+#13+
'QUALITY=Calidad'+#13+
'SPEED=Velocidad'+#13+
'% QUALITY=% Calidad'+#13+
'GRAY SCALE=Escala de Grises'+#13+
'PERFORMANCE=Mejor'+#13+
'BROWSE=Seleccionar'+#13+
'TILED=Mosaico'+#13+
'HIGH=Alto'+#13+
'LOW=Bajo'+#13+
'DATABASE CHART=Gráfico con Base de Datos'+#13+
'NON DATABASE CHART=Gráfico sin Base de Datos'+#13+
'HELP=Ayuda'+#13+
'NEXT >=Siguiente >'+#13+
'< BACK=< Anterior'+#13+
'TEECHART WIZARD=Asistente de TeeChart'+#13+
'PERCENT=Porcentual'+#13+
'PIXELS=Pixels'+#13+
'ERROR WIDTH=Ancho Error'+#13+
'ENHANCED=Mejorado'+#13+
'VISIBLE WALLS=Ver Paredes'+#13+
'ACTIVE=Activo'+#13+
'DELETE=Borrar'+#13+
'ALIGNMENT=Alineación'+#13+
'ADJUST FRAME=Ajustar Marco'+#13+
'HORIZONTAL=Horizontal'+#13+
'VERTICAL=Vertical'+#13+
'VERTICAL POSITION=Posición Vertical'+#13+
'NUMBER=Número'+#13+
'LEVELS=Niveles'+#13+
'OVERLAP=Sobreponer'+#13+
'STACK 100%=Apilar 100%'+#13+
'MOVE=Mover'+#13+
'CLICK=Clic'+#13+
'DELAY=Retraso'+#13+
'DRAW LINE=Dibujar Línea'+#13+
'FUNCTIONS=Funciones'+#13+
'SOURCE SERIES=Series Origen'+#13+
'ABOVE=Arriba'+#13+
'BELOW=Abajo'+#13+
'Dif. Limit=Límite Dif.'+#13+
'WITHIN=Dentro'+#13+
'EXTENDED=Extendidas'+#13+
'STANDARD=Estandard'+#13+
'STATS=Estadística'+#13+
'FINANCIAL=Financieras'+#13+
'OTHER=Otras'+#13+
'TEECHART GALLERY=Galería de Gráficos TeeChart'+#13+
'CONNECTING LINES=Líneas de Conexión'+#13+
'REDUCTION=Reducción'+#13+
'LIGHT=Luz'+#13+
'INTENSITY=Intensidad'+#13+
'FONT OUTLINES=Borde Fuentes'+#13+
'SMOOTH SHADING=Sombras suaves'+#13+
'AMBIENT LIGHT=Luz Ambiente'+#13+
'MOUSE ACTION=Acción del Ratón'+#13+
'CLOCKWISE=Segun horario'+#13+
'ANGLE INCREMENT=Incremento Angulo'+#13+
'RADIUS INCREMENT=Incremento Radio'+#13+
'PRINTER=Impresora'+#13+
'SETUP=Opciones'+#13+
'ORIENTATION=Orientación'+#13+
'PORTRAIT=Vertical'+#13+
'LANDSCAPE=Horizontal'+#13+
'MARGINS (%)=Márgenes (%)'+#13+
'MARGINS=Márgenes'+#13+
'DETAIL=Detalle'+#13+
'MORE=Más'+#13+
'PROPORTIONAL=Proporcional'+#13+
'VIEW MARGINS=Ver Márgenes'+#13+
'RESET MARGINS=Márg. Defecto'+#13+
'PRINT=Imprimir'+#13+
'TEEPREVIEW EDITOR=Editor Impresión Preliminar'+#13+
'ALLOW MOVE=Permitir Mover'+#13+
'ALLOW RESIZE=Permitir Redimensionar'+#13+
'SHOW IMAGE=Ver Imagen'+#13+
'DRAG IMAGE=Arrastrar Imagen'+#13+
'AS BITMAP=Como mapa de bits'+#13+
'SIZE %=Tamaño %'+#13+
'FIELDS=Campos'+#13+
'SOURCE=Origen'+#13+
'SEPARATOR=Separador'+#13+
'NUMBER OF HEADER LINES=Líneas de cabecera'+#13+
'COMMA=Coma'+#13+
'EDITING=Editando'+#13+
'TAB=Tabulación'+#13+
'SPACE=Espacio'+#13+
'ROUND RECTANGLE=Rectáng. Redondeado'+#13+
'BOTTOM=Abajo'+#13+
'RIGHT=Derecha'+#13+
'C PEN=Lápiz C'+#13+
'R PEN=Lápiz R'+#13+
'C LABELS=Textos C'+#13+
'R LABELS=Textos R'+#13+
'MULTIPLE BAR=Barras Múltiples'+#13+
'MULTIPLE AREAS=Areas Múltiples'+#13+
'STACK GROUP=Grupo de Apilado'+#13+
'BOTH=Ambos'+#13+
'BACK DIAGONAL=Diagonal Invertida'+#13+
'B.DIAGONAL=Diagonal Invertida'+#13+
'DIAG.CROSS=Cruz en Diagonal'+#13+
'WHISKER=Whisker'+#13+
'CROSS=Cruz'+#13+
'DIAGONAL CROSS=Cruz en Diagonal'+#13+
'LEFT RIGHT=Izquierda Derecha'+#13+
'RIGHT LEFT=Derecha Izquierda'+#13+
'FROM CENTER=Desde el centro'+#13+
'FROM TOP LEFT=Desde Izq. Arriba'+#13+
'FROM BOTTOM LEFT=Desde Izq. Abajo'+#13+
'SHOW WEEKDAYS=Ver Laborables'+#13+
'SHOW MONTHS=Ver Meses'+#13+
'SHOW PREVIOUS BUTTON=Ver Botón Anterior'#13+
'SHOW NEXT BUTTON=Ver Botón Siguiente'#13+
'TRAILING DAYS=Ver otros Días'+#13+
'SHOW TODAY=Ver Hoy'+#13+
'TRAILING=Otros Días'+#13+
'LOWERED=Hundido'+#13+
'RAISED=Elevado'+#13+
'HORIZ. OFFSET=Desplaz. Horiz.'+#13+
'VERT. OFFSET=Desplaz. Vert.'+#13+
'INNER=Dentro'+#13+
'LEN=Long.'+#13+
'AT LABELS ONLY=Sólo en etiquetas'+#13+
'MAXIMUM=Máximo'+#13+
'MINIMUM=Mínimo'+#13+
'CHANGE=Cambiar'+#13+
'LOGARITHMIC=Logarítmico'+#13+
'LOG BASE=Base Log.'+#13+
'DESIRED INCREMENT=Incremento'+#13+
'(INCREMENT)=(Incremento)'+#13+
'MULTI-LINE=Multi-Línea'+#13+
'MULTI LINE=Multilínea'+#13+
'RESIZE CHART=Redim. Gráfico'+#13+
'X AND PERCENT=X y Porcentaje'+#13+
'X AND VALUE=X y Valor'+#13+
'RIGHT PERCENT=Porcentaje derecha'+#13+
'LEFT PERCENT=Porcentaje izquierda'+#13+
'LEFT VALUE=Valor izquierda'+#13+
'RIGHT VALUE=Valor derecha'+#13+
'PLAIN=Texto'+#13+
'LAST VALUES=Ultimos Valores'+#13+
'SERIES VALUES=Valores de Series'+#13+
'SERIES NAMES=Nombres de Series'+#13+
'NEW=Nuevo'+#13+
'EDIT=Editar'+#13+
'PANEL COLOR=Color de fondo'+#13+
'TOP BOTTOM=Arriba Abajo'+#13+
'BOTTOM TOP=Abajo Arriba'+#13+
'DEFAULT ALIGNMENT=Alineación defecto'+#13+
'EXPONENTIAL=Exponencial'+#13+
'LABELS FORMAT=Formato Etiquetas'+#13+
'MIN. SEPARATION %=Min. Separación %'+#13+
'YEAR=Año'+#13+
'MONTH=Mes'+#13+
'WEEK=Semana'+#13+
'WEEKDAY=Dia Laborable'+#13+
'MARK=Marcas'+#13+
'ROUND FIRST=Redondear primera'+#13+
'LABEL ON AXIS=Etiqueta en eje'+#13+
'COUNT=Número'+#13+
'POSITION %=Posición %'+#13+
'START %=Empieza %'+#13+
'END %=Termina %'+#13+
'OTHER SIDE=Lado opuesto'+#13+
'INTER-CHAR SPACING=Espacio entre caracteres'+#13+
'VERT. SPACING=Espaciado Vertical'+#13+
'POSITION OFFSET %=Desplazamiento %'+#13+
'GENERAL=General'+#13+
'MANUAL=Manual'+#13+
'PERSISTENT=Persistente'+#13+
'PANEL=Panel'+#13+
'ALIAS=Alias'+#13+
'2D=2D'+#13+
'ADX=ADX'+#13+
'BOLLINGER=Bollinger'+#13+
'TEEOPENGL EDITOR=Editor de OpenGL'+#13+
'FONT 3D DEPTH=Profund. Fuentes'+#13+
'NORMAL=Normal'+#13+
'TEEFONT EDITOR=Editor de Fuente'+#13+
'CLIP POINTS=Ocultar'+#13+
'CLIPPED=Oculta'+#13+
'3D %=3D %'+#13+
'QUANTIZE=Cuantifica'+#13+
'QUANTIZE 256=Cuantifica 256'+#13+
'DITHER=Reduce'+#13+
'VERTICAL SMALL=Vertical Pequeño'+#13+
'HORIZ. SMALL=Horizontal Pequeño'+#13+
'DIAG. SMALL=Diagonal Pequeño'+#13+
'BACK DIAG. SMALL=Diagonal Invert. Peq.'+#13+
'DIAG. CROSS SMALL=Cruz Diagonal Peq.'+#13+
'MINIMUM PIXELS=Mínimos pixels'+#13+
'ALLOW SCROLL=Permitir Desplaz.'+#13+
'SWAP=Cambiar'+#13+
'GRADIENT EDITOR=Editor de Gradiente'+#13+
'TEXT STYLE=Estilo de textos'+#13+
'DIVIDING LINES=Líneas de División'+#13+
'SYMBOLS=Símbolos'+#13+
'CHECK BOXES=Casillas'+#13+
'FONT SERIES COLOR=Color de Series'+#13+
'LEGEND STYLE=Estilo de Leyenda'+#13+
'POINTS PER PAGE=Puntos por página'+#13+
'SCALE LAST PAGE=Escalar última página'+#13+
'CURRENT PAGE LEGEND=Leyenda con página actual'+#13+
'BACKGROUND=Fondo'+#13+
'BACK IMAGE=Imagen fondo'+#13+
'STRETCH=Ajustar'+#13+
'TILE=Mosaico'+#13+
'BORDERS=Bordes'+#13+
'CALCULATE EVERY=Calcular cada'+#13+
'NUMBER OF POINTS=Número puntos'+#13+
'RANGE OF VALUES=Rango de valores'+#13+
'FIRST=Primero'+#13+
'LAST=Ultimo'+#13+
'ALL POINTS=Todos los puntos'+#13+
'DATA SOURCE=Origen de Datos'+#13+
'WALLS=Pared'+#13+
'PAGING=Página'+#13+
'CLONE=Duplicar'+#13+
'TITLES=Título'+#13+
'TOOLS=Herramientas'+#13+
'EXPORT=Exportar'+#13+
'CHART=Gráfico'+#13+
'BACK=Fondo'+#13+
'LEFT AND RIGHT=Izq. y Derecha'+#13+
'SELECT A CHART STYLE=Seleccione tipo de Gráfico'+#13+
'SELECT A DATABASE TABLE=Seleccione una Tabla'+#13+
'TABLE=Tabla'+#13+
'SELECT THE DESIRED FIELDS TO CHART=Seleccione los campos a graficar'+#13+
'SELECT A TEXT LABELS FIELD=Campo de etiquetas'+#13+
'CHOOSE THE DESIRED CHART TYPE=Seleccione el tipo deseado'+#13+
'CHART PREVIEW=Visión Preliminar'+#13+
'SHOW LEGEND=Ver Leyenda'+#13+
'SHOW MARKS=Ver Marcas'+#13+
'FINISH=Terminar'+#13+
'RANDOM=Aleatorio'+#13+
'DRAW EVERY=Dibujar cada'+#13+
'ARROWS=Flechas'+#13+
'ASCENDING=Ascendente'+#13+
'DESCENDING=Descendente'+#13+
'VERTICAL AXIS=Eje Vertical'+#13+
'DATETIME=Fecha/Hora'+#13+
'TOP AND BOTTOM=Superior e Inferior'+#13+
'HORIZONTAL AXIS=Eje Horizontal'+#13+
'PERCENTS=Porcentajes'+#13+
'VALUES=Valores'+#13+
'FORMATS=Formatos'+#13+
'SHOW IN LEGEND=Ver en Leyenda'+#13+
'SORT=Orden'+#13+
'MARKS=Marcas'+#13+
'BEVEL INNER=Marco interior'+#13+
'BEVEL OUTER=Marco exterior'+#13+
'PANEL EDITOR=Editor de Panel'+#13+
'CONTINUOUS=Continuos'+#13+
'HORIZ. ALIGNMENT=Alineación Horiz.'+#13+
'EXPORT CHART=Exportar Gráfico'+#13+
'BELOW %=Inferior a %'+#13+
'BELOW VALUE=Inferior a Valor'+#13+
'NEAREST POINT=Punto cercano'+#13+
'DRAG MARKS=Mover Marcas'+#13+
'TEECHART PRINT PREVIEW=Impresión Preliminar'+#13+
'X VALUE=Valor X'+#13+
'X AND Y VALUES=Valores X Y'+#13+
'SHININESS=Brillo'+#13+
'ALL SERIES VISIBLE=Todas las Series Visible'+#13+
'MARGIN=Margen'+#13+
'DIAGONAL=Diagonal'+#13+
'LEFT TOP=Izquierda Arriba'+#13+
'LEFT BOTTOM=Izquierda Abajo'+#13+
'RIGHT TOP=Derecha Arriba'+#13+
'RIGHT BOTTOM=Derecha Abajo'+#13+
'EXACT DATE TIME=Fecha/Hora Exacta'+#13+
'RECT. GRADIENT=Gradiente'+#13+
'CROSS SMALL=Cruz pequeña'+#13+
'AVG=Media'+#13+
'FUNCTION=Función'+#13+
'AUTO=Auto'+#13+
'ONE MILLISECOND=Un milisegundo'+#13+
'ONE SECOND=Un segundo'+#13+
'FIVE SECONDS=Cinco segundos'+#13+
'TEN SECONDS=Diez segundos'+#13+
'FIFTEEN SECONDS=Quince segundos'+#13+
'THIRTY SECONDS=Trenta segundos'+#13+
'ONE MINUTE=Un minuto'+#13+
'FIVE MINUTES=Cinco minutos'+#13+
'TEN MINUTES=Diez minutos'+#13+
'FIFTEEN MINUTES=Quince minutos'+#13+
'THIRTY MINUTES=Trenta minutos'+#13+
'TWO HOURS=Dos horas'+#13+
'SIX HOURS=Seis horas'+#13+
'TWELVE HOURS=Doce horas'+#13+
'ONE DAY=Un dia'+#13+
'TWO DAYS=Dos dias'+#13+
'THREE DAYS=Tres dias'+#13+
'ONE WEEK=Una semana'+#13+
'HALF MONTH=Medio mes'+#13+
'ONE MONTH=Un mes'+#13+
'TWO MONTHS=Dos meses'+#13+
'THREE MONTHS=Tres meses'+#13+
'FOUR MONTHS=Cuatro meses'+#13+
'SIX MONTHS=Seis meses'+#13+
'IRREGULAR=Irregular'+#13+
'CLICKABLE=Clicable'+#13+
'ROUND=Redondo'+#13+
'FLAT=Plano'+#13+
'PIE=Pastel'+#13+
'HORIZ. BAR=Barra Horiz.'+#13+
'BUBBLE=Burbuja'+#13+
'SHAPE=Forma'+#13+
'POINT=Puntos'+#13+
'FAST LINE=Línea Rápida'+#13+
'CANDLE=Vela'+#13+
'VOLUME=Volumen'+#13+
'HORIZ LINE=Línea Horiz.'+#13+
'SURFACE=Superfície'+#13+
'LEFT AXIS=Eje Izquierdo'+#13+
'RIGHT AXIS=Eje Derecho'+#13+
'TOP AXIS=Eje Superior'+#13+
'BOTTOM AXIS=Eje Inferior'+#13+
'CHANGE SERIES TITLE=Cambiar Título de Series'+#13+
'DELETE %S ?=Eliminar %s ?'+#13+
'DESIRED %S INCREMENT=Incremento %s deseado'+#13+
'INCORRECT VALUE. REASON: %S=Valor incorrecto. Razón: %s'+#13+
'FillSampleValues NumValues must be > 0=FillSampleValues. Número de valores debe ser > 0.'#13+
'VISIT OUR WEB SITE !=Visite nuestra Web !'#13+
'SHOW PAGE NUMBER=Ver Número de Página'#13+
'PAGE NUMBER=Número de Página'#13+
'PAGE %D OF %D=Pág. %d de %d'#13+
'TEECHART LANGUAGES=Lenguajes de TeeChart'#13+
'CHOOSE A LANGUAGE=Escoja un idioma'+#13+
'SELECT ALL=Seleccionar Todas'#13+
'MOVE UP=Mover Arriba'#13+
'MOVE DOWN=Mover Abajo'#13+
'DRAW ALL=Dibujar todo'#13+
'TEXT FILE=Archivo de Texto'#13+
'IMAG. SYMBOL=Símbolo Imag.'#13+
'DRAG REPAINT=Repinta todo'#13+
'NO LIMIT DRAG=Sin límites arrastre'#13+
'AVAILABLE LANGUAGES=Lenguajes disponibles'#13+
'PERIOD=Periodo'#13+
'FILL 80%=Relleno 80%'#13+
'FILL 60%=Relleno 60%'#13+
'FILL 40%=Relleno 40%'#13+
'FILL 20%=Relleno 20%'#13+
'FILL 10%=Relleno 10%'#13+
'ZIG ZAG=Zig-Zag'#13+
'IGNORE NULLS=Ignorar nulos'#13+
'LIGHT 0=Luz 0'#13+
'LIGHT 1=Luz 1'#13+
'LIGHT 2=Luz 2'#13+
'DRAW STYLE=Estilo'#13+
'POINTS=Puntos'#13+
'EXPORT DIALOG=Diálogo de Exportación'#13+
'POINT COLORS=Color de puntos'#13+
'OUTLINE GRADIENT=Gradiente en borde'#13+
'GAUGES=Indicadores'#13+
'RADIAL=Radial'#13+
'RADIAL OFFSET=Desplaz. Radial'#13+
'SHADOW EDITOR=Editor de Sombra'#13+
'3D GRID TRANSPOSE=Invertir matriz 3D'#13+
'EXTRA LEGEND=Leyenda Extra'#13+
'GANTT DRAG=Arrastra Gantt'#13+
'GRID BAND TOOL=Bandas en rejilla'#13+
'SERIES ANIMATION=Animación de Series'#13+
'UP=Arriba'#13+
'DOWN=Abajo'#13+
'CALLOUT=Enlace'#13+
'TEXT ALIGNMENT=Alineación texto'#13+
'DISTANCE=Distancia'#13+
'ARROW HEAD=Cabeza flecha'#13+
'POINTER=Puntero'#13+
'CALCULATE USING=Calcular usando'#13+
'EVERY NUMBER OF POINTS=Cada num. puntos'#13+
'EVERY RANGE=Cada rango'#13+
'INCLUDE NULL VALUES=Incluir nulos'#13+
'DATE=Fecha'#13+
'ENTER DATE=Entrar fecha'#13+
'ENTER TIME=Entrar hora'#13+
'CYLINDER=Cilindro'#13+
'DEVIATION=Desviación'#13+
'UPPER=Superior'#13+
'LOWER=Inferior'#13+
'CONSTANT=Constante'#13+
'SHOW LABELS=Ver textos'#13+
'SHOW COLORS=Ver colores'#13+
'XYZ SERIES=Series xyz'#13+
'SHOW X VALUES=Ver valores X'#13+
'ACCUMULATE=Acumular'#13+
'SMOOTH=Suave'#13+
'INTERPOLATE=Interpolar'#13+
'START X=Inicio X'#13+
'STEP=Paso'#13+
'NUM. POINTS=Num. puntos'#13+
'COLOR EACH LINE=Color cada linea'#13+
'SORT BY=Ordenar por'#13+
'CALCULATION=Cálculo'#13+
'GROUP=Grupo'#13+
'WEIGHT=Ponderar'#13+
'EDIT LEGEND=Editar Leyenda'#13+
'OFFSET=Desplaz.'#13+
'DEFAULT BORDER=Borde defecto'#13+
'SEPARATION=Separación'#13+
'ROUND BORDER=Borde redondo'#13+
'NUMBER OF SAMPLE VALUES=Num. muestras'#13+
'DIF. LIMIT=Limite dif.'#13+
'RESIZE PIXELS TOLERANCE=Tolerancia pixels'#13+
'FULL REPAINT=Repintar todo'#13+
'END POINT=Punto final'#13+
'BAND 1=Banda 1'#13+
'BAND 2=Banda 2'#13+
'TRANSPOSE NOW=Invertir'#13+
'NOTHING=Nada'#13+
'LEFT TRIANGLE=Triángulo Izq.'#13+
'RIGHT TRIANGLE=Triángulo Der.'#13+
'PERIOD 1=Periodo 1'#13+
'PERIOD 2=Periodo 2'#13+
'PERIOD 3=Periodo 3'#13+
'HISTOGRAM=Histograma'#13+
'EXP. LINE=Linea Exp.'#13+
'WEIGHTED=Ponderado'#13+
'WEIGHTED BY INDEX=Ponderar indices'#13+
'BOX SIZE=Tamaño caja'#13+
'REVERSAL AMOUNT=Valor inversión'#13+
'PERCENTAGE=Porcentaje'#13+
'COMPLETE R.M.S.=RMS completa'#13+
'BUTTON=Botón'#13+
'ALL=Todo'#13+
'START AT MIN. VALUE=Empezar en valor mín.'#13+
'EXECUTE !=Ejecutar !'#13+
'WEB URL=Dirección web'#13+
'SELF STACK=Apilado sí mismo'#13+
'SIDE LINES=Lineas laterales'#13+
'COVER=Cubierta'#13+
'VALUE SOURCE=Fuente valores'#13+

// 6.0
'BEVEL SIZE=Tam. Marco'#13+
'DELETE ROW=Eliminar fila'#13+
'VOLUME SERIES=Serie Volumen'#13+
'SINGLE=Unico'#13+
'REMOVE CUSTOM COLORS=Eliminar colores'#13+
'USE PALETTE MINIMUM=Usar mínimo paleta'#13+
'AXIS MAXIMUM=Máximo eje'#13+
'AXIS CENTER=Centro eje'#13+
'AXIS MINIMUM=Mínimo eje'#13+
'DAILY (NONE)=Diario'#13+
'WEEKLY=Semanal'#13+
'MONTHLY=Mensual'#13+
'BI-MONTHLY=Bimensual'#13+
'QUARTERLY=Trimestral'#13+
'YEARLY=Anual'#13+
'DATETIME PERIOD=Periodo fecha/hora'#13+
'CASE SENSITIVE=Mayusc./Minusc.'#13+
'DRAG STYLE=Estilo arrastre'#13+
'SQUARED=Cuadrado'#13+
'GRID 3D SERIES=Serie 3D'#13+
'DARK BORDER=Borde oscuro'#13+
'PIE SERIES=Serie Pastel'#13+
'FOCUS=Marcar'#13+
'EXPLODE=Expandir'#13+
'FACTOR=Factor'#13+
'CHART FROM TEMPLATE (*.TEE FILE)=Desde archivo plantilla (*.tee)'#13+
'OPEN TEECHART TEMPLATE FILE FROM=Abrir plantilla desde'#13+
'BINARY=Binario'#13+
'VOLUME OSCILLATOR=Oscilador Volumen'#13+
'PIE SLICES=Porciones pastel'#13+
'ARROW WIDTH=Ancho flecha'#13+
'ARROW HEIGHT=Alto flecha'#13+
'DEFAULT COLOR=Color defecto'#13+
'BALANCE=Balance'#13+
'PERIOD=Periodo'#13+
'UP=Arriba'#13+
'DOWN=Abajo'#13+
'SHADOW EDITOR=Editor de Sombras'#13+
'CALLOUT=Bocadillo'#13+
'TEXT ALIGNMENT=Alineación de Texto'#13+
'DISTANCE=Distancia'#13+
'ARROW HEAD=Punta de Flecha'#13+
'POINTER=Puntero'#13+
'AVAILABLE LANGUAGES=Lenguajes disponibles'#13+
'CALCULATE USING=Calcular usando'#13+
'EVERY NUMBER OF POINTS=Cada numero de puntos'#13+
'EVERY RANGE=Cada rango'#13+
'INCLUDE NULL VALUES=Incluir Valores Nulos'#13+
'DATE=Fecha'#13+
'ENTER DATE=Introduzca Fecha'#13+
'ENTER TIME=Introduzca Hora'#13+
'BEVEL SIZE=Tamaño Bisel'#13+
'CYLINDER=Cilindro'#13+
'SLANT CUBE=Cubo Inclinado'#13+
'TICK LINES=Lineas división'#13+
'% BAR DEPTH=% Profundidad Barra'#13+
'DEVIATION=Desviación'#13+
'UPPER=Superior'#13+
'LOWER=Inferior'#13+
'FILL 80%=Relleno 80%'#13+
'FILL 60%=Relleno 60%'#13+
'FILL 40%=Relleno 40%'#13+
'FILL 20%=Relleno 20%'#13+
'FILL 10%=Relleno 10%'#13+
'ZIG ZAG=Zig Zag'#13+
'METAL=Metal'#13+
'WOOD=Madera'#13+
'STONE=Roca'#13+
'CLOUDS=Nubes'#13+
'GRASS=Cesped'#13+
'FIRE=Fuego'#13+
'SNOW=Nieve'#13+
'NOTHING=Ningun'#13+
'LEFT TRIANGLE=Triángulo Izq.'#13+
'RIGHT TRIANGLE=Triángulo Der.'#13+
'HIGH-LOW=Alto-Bajo'#13+
'CONSTANT=Constante'#13+
'VIEW SERIES NAMES=Mostrar nombres de Series'#13+
'SHOW LABELS=Mostrar Etiquetas'#13+
'SHOW COLORS=Mostrar Colores'#13+
'XYZ SERIES=Series XYZ'#13+
'SHOW X VALUES=Mostrar Valores X'#13+
'EDIT COLOR=Editar Color'#13+
'DEFAULT COLOR=Color por defecto'#13+
'MAKE NULL POINT=Poner punto nulo'#13+
'APPEND ROW=Añadir linea'#13+
'DELETE ROW=Borrar linea'#13+
'TEXT FONT=Fuente de Texto'#13+
'SMOOTH=Suavizar'#13+
'CHART THEME SELECTOR=Selector de tipo de gráfico'#13+
'PREVIEW=Vista Previa'#13+
'THEMES=Temas'#13+
'COLOR PALETTE=Paleta de Colores'#13+
'VIEW 3D=Vista 3D'#13+
'SCALE=Escala'#13+
'MARGIN %=Márgen %'#13+
'VOLUME SERIES=Series Volumen'#13+
'ACCUMULATE=Acumulado'#13+
'DRAW BEHIND AXES=Dibujar detras ejes'#13+
'X GRID EVERY=Rejilla cada X'#13+
'Z GRID EVERY=Rejilla cada Z'#13+
'AXIS MAXIMUM=Máximo eje'#13+
'AXIS CENTER=Centro eje'#13+
'AXIS MINIMUM=Mínimo eje'#13+
'DAILY (NONE)=Diario (ninguno)'#13+
'WEEKLY=Semanal'#13+
'MONTHLY=Mensual'#13+
'BI-MONTHLY=Bi-mensual'#13+
'QUARTERLY=Trimestral'#13+
'YEARLY=Anual'#13+
'DATE PERIOD=Periodo de fecha'#13+
'TIME PERIOD=Periodo de tiempo'#13+
'INTERPOLATE=Interpolar'#13+
'USE SERIES Z=Usar Series Z'#13+
'START X=Inicio X'#13+
'STEP=Paso'#13+
'NUM. POINTS=Num. Puntos'#13+
'COLOR EACH LINE=Colorear cada linea'#13+
'CASE SENSITIVE=Mayu/Minu Sensitivo'#13+
'SORT BY=Ordenar por'#13+
'CALCULATION=Cálculo'#13+
'GROUP=Grupo'#13+
'DRAG STYLE=Estilo de arrastre'#13+
'WEIGHT=Peso'#13+
'EDIT LEGEND=Editar Leyenda'#13+
'IGNORE NULLS=Ignorar nulos'#13+
'NUMERIC FORMAT=Formato numérico'#13+
'DATE TIME=Fecha y hora'#13+
'GEOGRAPHIC=Geográfico'#13+
'DECIMALS=Decimales'#13+
'FIXED=Fijo'#13+
'THOUSANDS=Miles'#13+
'CURRENCY=Moneda'#13+
'VIEWS=Vistas'#13+
'OFFSET=Desplazamiento'#13+
'ALTERNATE=Alternar'#13+
'ZOOM ON UP LEFT DRAG=Arrastre izq-arriba aumenta'#13+
'LIGHT 0=Luz 0'#13+
'LIGHT 1=Luz 1'#13+
'LIGHT 2=Luz 2'#13+
'FIXED POSITION=Posición fija'#13+
'DRAW STYLE=Estilo de dibujo'#13+
'POINTS=Puntos'#13+
'NO CHECK BOXES=Sin Casillas'#13+
'RADIO BUTTONS=Botones de elección'#13+
'DEFAULT BORDER=Borde por defecto'#13+
'SQUARED=Cuadrado'#13+
'SEPARATION=Separación'#13+
'ROUND BORDER=Borde curvado'#13+
'Z DATETIME=Fecha/Hora Z'#13+
'SYMBOL=Símbolo'#13+
'NUMBER OF SAMPLE VALUES=Número de puntos de muestra'#13+
'AUTO HIDE=Auto Ocultar'#13+
'DIF. LIMIT=Límite Dif.'#13+
'RESIZE PIXELS TOLERANCE=Tolerancia tamaño pixels'#13+
'FULL REPAINT=Repintar todo'#13+
'END POINT=Punto final'#13+
'SINGLE=Único'#13+
'REMOVE CUSTOM COLORS=Eliminar colores usuario'#13+
'GALLERY=Galería'#13+
'INVERTED GRAY=Grises Invertido'#13+
'RAINBOW=Arcoiris'#13+
'USE PALETTE MINIMUM=Usar Mínimo Paleta'#13+
'BAND 1=Banda 1'#13+
'BAND 2=Banda 2'#13+
'GRID 3D SERIES=Series Cuadricula 3D'#13+
'TRANSPOSE NOW=Intercambiar ahora'#13+
'TEECHART LIGHTING=Iluminación'#13+
'FACTOR=Factor'#13+
'LINEAR=Lineal'#13+
'SPOTLIGHT=Punto de luz'#13+
'PERIOD 1=Periodo 1'#13+
'PERIOD 2=Periodo 2'#13+
'PERIOD 3=Periodo 3'#13+
'HISTOGRAM=Histograma'#13+
'EXP. LINE=Línea Exp.'#13+
'MACD=MACD'#13+
'SHAPE INDEX=Indice de sombra'#13+
'CLOSED=Cerrado'#13+
'WEIGHTED=Ponderado'#13+
'WEIGHTED BY INDEX=Ponderado por índice'#13+
'DESIGN TIME OPTIONS=Opciones de diseño'#13+
'LANGUAGE=Lenguaje'#13+
'CHART GALLERY=Galería de Gráficos'#13+
'MODE=Modo'#13+
'CHART EDITOR=Editor de Gráfico'#13+
'REMEMBER SIZE=Recordar tamaño'#13+
'REMEMBER POSITION=Recordar posición'#13+
'TREE MODE=Modo Arbol'#13+
'RESET=Resetear'#13+
'NEW CHART=Nuevo Gráfico'#13+
'DEFAULT THEME=Tema por defecto'#13+
'TEECHART DEFAULT=TeeChart Típico'#13+
'CLASSIC=Clásico'#13+
'WEB=Web'#13+
'WINDOWS XP=Windows XP'#13+
'BLUES=Azules'#13+
'DARK BORDER=Borde Oscuro'#13+
'MULTIPLE PIES=Multiples Pasteles'#13+
'3D GRADIENT=Gradiente 3D'#13+
'DISABLE=Desactivar'#13+
'COLOR EACH SLICE=Colorear cada porción'#13+
'PIE SERIES=Series de Pastel'#13+
'FOCUS=Foco'#13+
'EXPLODE=Expander'#13+
'BASE LINE=Linea Base'#13+
'BOX SIZE=Támaño de caja'#13+
'REVERSAL AMOUNT=Valor inversión'#13+
'PERCENTAGE=Porcentaje'#13+
'COMPLETE R.M.S.=R.M.S. Completa'#13+
'BUTTON=Botón'#13+
'ALL=Todo'#13+
'INITIAL DELAY=Pausa inicial'#13+
'THUMB=Caja'#13+
'AUTO-REPEAT=Auto-repetición'#13+
'BACK COLOR=Color de fondo'#13+
'HANDLES=Manejadores'#13+
'ALLOW RESIZE CHART=Permitir cambiar tamaño del gráfico'#13+
'LOOP=Bucle'#13+
'START AT MIN. VALUE=Empezar en valor mínimo'#13+
'EXECUTE !=Ejecutar !'#13+
'ONE WAY=Dirección única'#13+
'DRAW BEHIND SERIES=Dibujar detras de Series'#13+
'WEB URL=Dirección Web'#13+
'SELF STACK=Apilar consigo'#13+
'CELL=Celda'#13+
'ROW=Fila'#13+
'COLUMN=Columna'#13+
'SIDE LINES=Lineas laterales'#13+
'FAST BRUSH=Pintar rápido'#13+
'SVG OPTIONS=Opciones SVG'#13+
'TEXT ANTI-ALIAS=Suavizado de texto'#13+
'CHART FROM TEMPLATE (*.TEE FILE)=Gráfico desde plantilla (archivo *.tee)'#13+
'THEME=Tema'#13+
'OPEN TEECHART TEMPLATE FILE FROM=Abrir plantilla de Gráfico desde'#13+
'EXPORT DIALOG=Diálogo de Exportación'#13+
'BINARY=Binario'#13+
'TEXT QUOTES=Texto comillas'#13+
'POINT COLORS=Colores de puntos'#13+
'OUTLINE GRADIENT=Gradiente del perfil'#13+
'PERIMETER=Perímetro'#13+
'BUSINESS=Comercial'#13+
'CARIBE SUN=Sol Caribeño'#13+
'CLEAR DAY=Dia Claro'#13+
'DESERT=Desierto'#13+
'FARM=Granja'#13+
'FUNKY=Funky'#13+
'GOLF=Golf'#13+
'HOT=Cálido'#13+
'NIGHT=Noche'#13+
'SEA=Mar'#13+
'SEA 2=Mar 2'#13+
'SUNSET=Puesta de Sol'#13+
'TROPICAL=Tropical'#13+
'RADIAL OFFSET=Desplaz. Radial'#13+
'RADIAL=Radial'#13+
'DIAGONAL UP=Diagonal Arriba'#13+
'DIAGONAL DOWN=Diagonal Abajo'#13+
'COVER=Cubierta'#13+
'HIDE TRIANGLES=Ocultar triángulos'#13+
'ARROW WIDTH=Ancho Flecha'#13+
'ARROW HEIGHT=Alto Flecha'#13+
'MIRRORED=Espejo'#13+
'VALUE SOURCE=Origen de valores'#13+
'DRAG=Arrastrar'#13+
'HANDPOINT=Mano'#13+
'HOURGLASS=Reloj de Arena'#13+
'VICTORIAN=Victorianos'#13+
'PASTELS=Pasteles'#13+
'MODERN=Modernos'
;
  end;
end;

Procedure TeeSetSpanish;
begin
  TeeCreateSpanish;
  TeeLanguage:=TeeSpanishLanguage;
  TeeSpanishConstants;
  TeeLanguageHotKeyAtEnd:=False;
  TeeLanguageCanUpper:=True;
end;

initialization
finalization
  FreeAndNil(TeeSpanishLanguage);
end.
