unit TeeUrdu;
{$I TeeDefs.inc}

interface

Uses Classes;

Var TeeUrduLanguage:TStringList=nil;

Procedure TeeSetUrdu;
Procedure TeeCreateUrdu;

implementation

Uses SysUtils, TeeConst, TeeProCo {$IFNDEF D5},TeCanvas{$ENDIF};

Procedure TeeUrduConstants;
begin
  TeeMsg_Copyright          :='© 1995-2004 by David Berneda';
  TeeMsg_LegendFirstValue   :='Pehli Legend Value zero se bari huni chahiye = > 0'; 
  TeeMsg_LegendColorWidth   :='Legend Color width 0% se bari huni chahiye =  > 0%' ;
  TeeMsg_SeriesSetDataSource:='ParentChart Nahein hai jo Datasource ko validate kare';
  TeeMsg_SeriesInvDataSource:='Valid DataSource Nahein hai';
  TeeMsg_FillSample         :='FillSampleValues NumValues zero se bari huni chahiye = > 0';
  TeeMsg_AxisLogDateTime    :='DateTime Axis Logarithmic nahien ho sakte';
  TeeMsg_AxisLogNotPositive :='Logarithmic Axis Min and Max values zero ya zero se bari huni chahiye = >= 0';
  TeeMsg_AxisLabelSep       :='Labels Separation % zero se bari huni chahiye = > 0';
  TeeMsg_AxisIncrementNeg   :='Axis increment zero ya zero se bari huni chahiye = >= 0';
  TeeMsg_AxisMinMax         :='Axis kum se kum Value Ziada se Ziada value ke brabar ya kum honi chahiye = <=Maximum';
  TeeMsg_AxisMaxMin         :='Axis Ziada se Ziada Value kum se kum value ke brabar ya ziada honi chahiye = >=Minimum';
  TeeMsg_AxisLogBase        :='Axis logarithmic Base Do ya Do se ziada hona chahiye = >=2';
  TeeMsg_MaxPointsPerPage   :='MaxPointsPerPage zero ya zero se bari huni chahiye = >= 0';
  TeeMsg_3dPercent          :='3D ke effect fi sud %d aur %d ke darmian hone chahiye ';
  TeeMsg_CircularSeries     :='Circular Series ki dependences ki ijaazat nahien hai';
  TeeMsg_WarningHiColor     :='16k ya ziada ke rangon ke zaroorat hai ta ke achhi lugge';

  TeeMsg_DefaultPercentOf   :='%s of %s';
  TeeMsg_DefaultPercentOf2  :='%s'+#13+'of %s';
  TeeMsg_DefPercentFormat   :='##0.## %';
  TeeMsg_DefValueFormat     :='#,##0.###';
  TeeMsg_DefLogValueFormat  :='#.0 "x10" E+0';
  TeeMsg_AxisTitle          :='Axis Unwaan';
  TeeMsg_AxisLabels         :='Axis Naam';
  TeeMsg_RefreshInterval    :='Refresh ke waqfa zero aur sath ke darmian hoona chahiye = 0 - 60';
  TeeMsg_SeriesParentNoSelf :='Series.ParentChart apnaaap nahein hai';
  TeeMsg_GalleryLine        :='Lakeer';
  TeeMsg_GalleryPoint       :='Nuqta';
  TeeMsg_GalleryArea        :='Hissa';
  TeeMsg_GalleryBar         :='Bar';
  TeeMsg_GalleryHorizBar    :='Tirchi bar';
  TeeMsg_Stack              :='Stack';
  TeeMsg_GalleryPie         :='Pie';
  TeeMsg_GalleryCircled     :='Gooldaira';
  TeeMsg_GalleryFastLine    :='Tez lakeer';
  TeeMsg_GalleryHorizLine   :='Tirchi lakeer';

  TeeMsg_PieSample1         :='Garian';
  TeeMsg_PieSample2         :='Phones';
  TeeMsg_PieSample3         :='Meez';
  TeeMsg_PieSample4         :='Monitors';
  TeeMsg_PieSample5         :='Lamps';
  TeeMsg_PieSample6         :='Keyboards';
  TeeMsg_PieSample7         :='Cycle';
  TeeMsg_PieSample8         :='Kurseian';

  TeeMsg_GalleryLogoFont    :='Courier niyya';
  TeeMsg_Editing            :='sahih karna %s';

  TeeMsg_GalleryStandard    :='miyaar';
  TeeMsg_GalleryExtended    :='lumba kiya hua';
  TeeMsg_GalleryFunctions   :='kaam';

  TeeMsg_EditChart          :='E&dit Chart...';
  TeeMsg_PrintPreview       :='&Print ko dekhna';
  TeeMsg_ExportChart        :='E&xport Chart...';
  TeeMsg_CustomAxes         :='Custom Axes...';

  TeeMsg_InvalidEditorClass :='%s: Editor Class sahih nahein hai: %s';
  TeeMsg_MissingEditorClass :='%s: Editor Dialog nahein hai';

  TeeMsg_GalleryArrow       :='Teer';

  TeeMsg_ExpFinish          :='Khuttum';
  TeeMsg_ExpNext            :='Aglaa';

  TeeMsg_GalleryGantt       :='Gantt';

  TeeMsg_GanttSample1       :='Design';
  TeeMsg_GanttSample2       :='aik model sa banana';
  TeeMsg_GanttSample3       :='banana';
  TeeMsg_GanttSample4       :='beechna';
  TeeMsg_GanttSample5       :='beeche ka tareeqah';
  TeeMsg_GanttSample6       :='test karna';
  TeeMsg_GanttSample7       :='banana';
  TeeMsg_GanttSample8       :='sahih karna';
  TeeMsg_GanttSample9       :='nai version';
  TeeMsg_GanttSample10      :='Banking';

  TeeMsg_ChangeSeriesTitle  :='series ka unwaan badulna';
  TeeMsg_NewSeriesTitle     :='nai series ka unwaan';
  TeeMsg_DateTime           :='Dinwaqt';
  TeeMsg_TopAxis            :='Oopper wali axis';
  TeeMsg_BottomAxis         :='Neeche wali axis';
  TeeMsg_LeftAxis           :='Baain wali axis';
  TeeMsg_RightAxis          :='seedhi wali axis';

  TeeMsg_SureToDelete       :='Mittana %s ?';
  TeeMsg_DateTimeFormat     :='Dinwaqt ko for&mat:';
  TeeMsg_Default            :='Shurrow:';
  TeeMsg_ValuesFormat       :='Values For&mat:';
  TeeMsg_Maximum            :='Ziada se ziada';
  TeeMsg_Minimum            :='Kum se kum';
  TeeMsg_DesiredIncrement   :='Mutloob shuda %s burhana';

  TeeMsg_IncorrectMaxMinValue:='ghult value. Wajjah: %s';
  TeeMsg_EnterDateTime      :='likho [kitne din] [hh:mm:ss]';

  TeeMsg_SureToApply        :='changes ko istamaal karo';
  TeeMsg_SelectedSeries     :='Chunni hoi series';
  TeeMsg_RefreshData        :='&refresh data';

  TeeMsg_DefaultFontSize    :={$IFDEF LINUX}'10'{$ELSE}'8'{$ENDIF};
  TeeMsg_DefaultEditorSize  :='414';
  TeeMsg_FunctionAdd        :='Jumma';
  TeeMsg_FunctionSubtract   :='Tafreeq';
  TeeMsg_FunctionMultiply   :='Zarab daina';
  TeeMsg_FunctionDivide     :='Taqseem karna';
  TeeMsg_FunctionHigh       :='Ooncha';
  TeeMsg_FunctionLow        :='Neecha';
  TeeMsg_FunctionAverage    :='Aust';

  TeeMsg_GalleryShape       :='Jissaamat';
  TeeMsg_GalleryBubble      :='Bulbula';
  TeeMsg_FunctionNone       :='Copy';

  TeeMsg_None               :='(kuch nahein)';

  TeeMsg_PrivateDeclarations:='{ Private declarations }';
  TeeMsg_PublicDeclarations :='{ Public declarations }';
  TeeMsg_DefaultFontName    :={$IFDEF CLX}'Helvetica'{$ELSE}'Arial'{$ENDIF};

  TeeMsg_CheckPointerSize   :='Pionter size zero se bara hona chahiye';
  TeeMsg_About              :='Abo&ut TeeChart...';

  tcAdditional              :='Is ke allawa';
  tcDControls               :='Data controls';
  tcQReport                 :='QReport';

  TeeMsg_DataSet            :='Dataset';
  TeeMsg_AskDataSet         :='&Dataset:';

  TeeMsg_SingleRecord       :='Aik Record';
  TeeMsg_AskDataSource      :='&DataSource:';

  TeeMsg_Summary            :='Tashreeh';

  TeeMsg_FunctionPeriod     :='Function ka waqha zero ya zero se bara hona chahiye = >=0';

  TeeMsg_WizardTab          :='Business';
  TeeMsg_TeeChartWizard     :='TeeChart Jadoo';

  TeeMsg_ClearImage         :='Clea&r';
  TeeMsg_BrowseImage        :='B&rowse...';

  TeeMsg_WizardSureToClose  :='kiya aap ko yakeen hai ke aap TeeChart Wizard ko bund karna chahte hein ?';

  TeeMsg_FieldNotFound      :='Field %s moojud nahein hai ';

  TeeMsg_DepthAxis          :='Gahrhi Axis';
  TeeMsg_PieOther           :='Aur';
  TeeMsg_ShapeGallery1      :='abc';
  TeeMsg_ShapeGallery2      :='123';
  TeeMsg_ValuesX            :='X';
  TeeMsg_ValuesY            :='Y';
  TeeMsg_ValuesPie          :='Pie';
  TeeMsg_ValuesBar          :='Bar';
  TeeMsg_ValuesAngle        :='Zavia';
  TeeMsg_ValuesGanttStart   :='Shurroh';
  TeeMsg_ValuesGanttEnd     :='khuttam';
  TeeMsg_ValuesGanttNextTask:='Aglakam';
  TeeMsg_ValuesBubbleRadius :='Qutar';
  TeeMsg_ValuesArrowEndX    :='KhuttamX';
  TeeMsg_ValuesArrowEndY    :='KhuttamY';
  TeeMsg_Legend             :='Baranaam';
  TeeMsg_Title              :='Unwaan';
  TeeMsg_Foot               :='Nichla hissa';
  TeeMsg_Period		    :='Waqfa';
  TeeMsg_PeriodRange        :='Wafe ka phelao';
  TeeMsg_CalcPeriod         :='Calculate %s saray';
  TeeMsg_SmallDotsPen       :='Chotte Nuqte';

  TeeMsg_InvalidTeeFile     :='Ghult chart in *.tee file';
  TeeMsg_WrongTeeFileFormat :='Ghult *.tee format';
  TeeMsg_EmptyTeeFile       :='Khali *.tee  {  5.01  }';

  {$IFDEF D5}
  TeeMsg_ChartAxesCategoryName   := 'Nuqsha Axes';
  TeeMsg_ChartAxesCategoryDesc   := 'Nuqsha Axes ke properties aur events';
  TeeMsg_ChartWallsCategoryName  := 'Nuqsha ke deewarain';
  TeeMsg_ChartWallsCategoryDesc  := 'Nuqsha deewaroon ke Properties aur events';
  TeeMsg_ChartTitlesCategoryName := 'Nuqsha Unwaan';
  TeeMsg_ChartTitlesCategoryDesc := 'Nuqsha Unwaan ke properties aur events';
  TeeMsg_Chart3DCategoryName     := 'Nuqsha 3D';
  TeeMsg_Chart3DCategoryDesc     := 'Nuqsha 3D ke properties aur unwaan';
  {$ENDIF}

  TeeMsg_CustomAxesEditor       :='Custom ';
  TeeMsg_Series                 :='Series';
  TeeMsg_SeriesList             :='Series...';

  TeeMsg_PageOfPages            :='Saffah %d of %d';
  TeeMsg_FileSize               :='%d bytes';

  TeeMsg_First  :='Pehla';
  TeeMsg_Prior  :='Pichla';
  TeeMsg_Next   :='Agla';
  TeeMsg_Last   :='Aakhir';
  TeeMsg_Insert :='Indraag';
  TeeMsg_Delete :='Mitaana';
  TeeMsg_Edit   :='Theek karna';
  TeeMsg_Post   :='Bheejna';
  TeeMsg_Cancel :='Cancel';

  TeeMsg_All    :='(Saara)';
  TeeMsg_Index  :='Index';
  TeeMsg_Text   :='Likhai';

  TeeMsg_AsBMP        :='as &Bitmap';
  TeeMsg_BMPFilter    :='Bitmaps (*.bmp)|*.bmp';
  TeeMsg_AsEMF        :='as &Metafile';
  TeeMsg_EMFFilter    :='Enhanced Metafiles (*.emf)|*.emf|Metafiles (*.wmf)|*.wmf';
  TeeMsg_ExportPanelNotSet := 'Panel propert ko bahir bhejne wali format mein nahein hai.';

  TeeMsg_Normal    :='Aam';
  TeeMsg_NoBorder  :='Border nahein';
  TeeMsg_Dotted    :='Nuqte dar';
  TeeMsg_Colors    :='Rang';
  TeeMsg_Filled    :='Bhura hua';
  TeeMsg_Marks     :='Nishaan';
  TeeMsg_Stairs    :='Seerian';
  TeeMsg_Points    :='Nuqta';
  TeeMsg_Height    :='Unchai';
  TeeMsg_Hollow    :='Khaali';
  TeeMsg_Point2D   :='Nuqta 2D';
  TeeMsg_Triangle  :='Triangle';
  TeeMsg_Star      :='Taara';
  TeeMsg_Circle    :='GolDaira';
  TeeMsg_DownTri   :='Neecha Tri';
  TeeMsg_Cross     :='Katta hua';
  TeeMsg_Diamond   :='Heera';
  TeeMsg_NoLines   :='Koi lakeer nahein';
  TeeMsg_Stack100  :='Stack 100%';
  TeeMsg_Pyramid   :='Pyramid';
  TeeMsg_Ellipse   :='keencha hua goldaira';
  TeeMsg_InvPyramid:='Ulta Pyramid';
  TeeMsg_Sides     :='Itraaf';
  TeeMsg_SideAll   :='Sarri itraaf';
  TeeMsg_Patterns  :='Nammoone';
  TeeMsg_Exploded  :='Bikhra hua';
  TeeMsg_Shadow    :='Saayah';
  TeeMsg_SemiPie   :='Aadhi Pie';
  TeeMsg_Rectangle :='Rectangle';
  TeeMsg_VertLine  :='Beezve lakeer';
  TeeMsg_HorizLine :='Tirchi Lakeer';
  TeeMsg_Line      :='Lakeer';
  TeeMsg_Cube      :='Cube';
  TeeMsg_DiagCross :='Tircha katta';

  TeeMsg_CanNotFindTempPath    :='Temp folder nahein milla';
  TeeMsg_CanNotCreateTempChart :='Temp File nahein milli';
  TeeMsg_CanNotEmailChart      :='TeeChart email nahein ho sakta';

  TeeMsg_SeriesDelete :='Series Delete: ValueIndex %d apni hadood se bahir hai (0 to %d).';

  { 5.02 } { Moved from TeeImageConstants.pas unit }

  TeeMsg_AsJPEG        :='as &JPEG';
  TeeMsg_JPEGFilter    :='JPEG files (*.jpg)|*.jpg';
  TeeMsg_AsGIF         :='as &GIF';
  TeeMsg_GIFFilter     :='GIF files (*.gif)|*.gif';
  TeeMsg_AsPNG         :='as &PNG';
  TeeMsg_PNGFilter     :='PNG files (*.png)|*.png';
  TeeMsg_AsPCX         :='as PC&X';
  TeeMsg_PCXFilter     :='PCX files (*.pcx)|*.pcx';
  TeeMsg_AsVML         :='as &VML (HTM)';
  TeeMsg_VMLFilter     :='VML files (*.htm)|*.htm';

  { 5.02 }
  TeeMsg_AskLanguage  :='&Language...';
  
  { TeeProCo }
  TeeMsg_GalleryPolar       :='Polar';
  TeeMsg_GalleryCandle      :='MoomBatti';
  TeeMsg_GalleryVolume      :='Awaz';
  TeeMsg_GallerySurface     :='sattah';
  TeeMsg_GalleryContour     :='khuddokhal';
  TeeMsg_GalleryBezier      :='lumbutra';
  TeeMsg_GalleryPoint3D     :='nuqta 3D';
  TeeMsg_GalleryRadar       :='Radar';
  TeeMsg_GalleryDonut       :='Donut';
  TeeMsg_GalleryCursor      :='Cursor';
  TeeMsg_GalleryBar3D       :='Bar 3D';
  TeeMsg_GalleryBigCandle   :='barri MoomBatti';
  TeeMsg_GalleryLinePoint   :='lakeer Nuqta';
  TeeMsg_GalleryHistogram   :='Tareekh';
  TeeMsg_GalleryWaterFall   :='Abshaar';
  TeeMsg_GalleryWindRose    :='Gulab ki Hawwa';
  TeeMsg_GalleryClock       :='Gharri';
  TeeMsg_GalleryColorGrid   :='rangjalli';
  TeeMsg_GalleryBoxPlot     :=';buksaplot';
  TeeMsg_GalleryHorizBoxPlot:='tircha buksaplot';
  TeeMsg_GalleryBarJoin     :='bar Millana';
  TeeMsg_GallerySmith       :='Smith';
  TeeMsg_GalleryPyramid     :='Pyramid';
  TeeMsg_GalleryMap         :='Nuqsha';

  TeeMsg_PolyDegreeRange    :='Polynomial zawiya 1 aur 20 ke dermian hoona lazmi hai';
  TeeMsg_AnswerVectorIndex   :='Jawab vector Index 1 or %d ke dermian hoona lazmi hai';
  TeeMsg_FittingError        :='joorna process nahein ho sakta';
  TeeMsg_PeriodRange         :='waqfa sifar ya sifar se ziada hoona chahiye';
  TeeMsg_ExpAverageWeight    :='ExpAverage wazan sifar aur aik ke dermain hoona chahiye = 0 and 1';
  TeeMsg_GalleryErrorBar     :='Ghulti wali Bar';
  TeeMsg_GalleryError        :='Ghulti';
  TeeMsg_GalleryHighLow      :='ooncha-neecha';
  TeeMsg_FunctionMomentum    :='Momentum';
  TeeMsg_FunctionMomentumDiv :='Momentum Div';
  TeeMsg_FunctionExpAverage  :='Exp. Oost';
  TeeMsg_FunctionMovingAverage:='Chalti hui Oost';
  TeeMsg_FunctionExpMovAve   :='Exp.Mov.Avrg.';
  TeeMsg_FunctionRSI         :='R.S.I.';
  TeeMsg_FunctionCurveFitting:='Moore fitting';
  TeeMsg_FunctionTrend       :='Tareeqa';
  TeeMsg_FunctionExpTrend    :='Exp.Tareeqa';
  TeeMsg_FunctionLogTrend    :='log.Tareeqa';
  TeeMsg_FunctionCumulative  :='jumma kia hua';
  TeeMsg_FunctionStdDeviation:='Std.Deviation';
  TeeMsg_FunctionBollinger   :='Bollinger';
  TeeMsg_FunctionRMS         :='Jur aust sq.';
  TeeMsg_FunctionMACD        :='MACD';
  TeeMsg_FunctionStochastic  :='Stochastic';
  TeeMsg_FunctionADX         :='ADX';

  TeeMsg_FunctionCount       :='Ginntee';
  TeeMsg_LoadChart           :='Khul TeeChart...';
  TeeMsg_SaveChart           :='Bachat TeeChart...';
  TeeMsg_TeeFiles            :='TeeChart Pro files';

  TeeMsg_GallerySamples      :='Aur';
  TeeMsg_GalleryStats        :='Hisabkitab';

  TeeMsg_CannotFindEditor    :='Series editor form nahein milla';


  TeeMsg_CannotLoadChartFromURL:='Ghulti Code: %d neecheuttarna nuqsha URL see: %s';
  TeeMsg_CannotLoadSeriesDataFromURL:='Ghulti Code: %d neecheuttarna series URL see: %s';

  TeeMsg_Test                :='Imtihan';

  TeeMsg_ValuesDate          :='Tareekh';
  TeeMsg_ValuesOpen          :='Khol';
  TeeMsg_ValuesHigh          :='Ooncha';
  TeeMsg_ValuesLow           :='Neecha';
  TeeMsg_ValuesClose         :='Bund';
  TeeMsg_ValuesOffset        :='Offset';
  TeeMsg_ValuesStdError      :='StdError';

  TeeMsg_Grid3D              :='Grid 3D';

  TeeMsg_LowBezierPoints     :='Bezier ke nuqtee ka number 1 se ziada hoona chahiye';

  { TeeCommander component... }

  TeeCommanMsg_Normal   :='Aam';
  TeeCommanMsg_Edit     :='sahih karna';
  TeeCommanMsg_Print    :='print';
  TeeCommanMsg_Copy     :='Copy';
  TeeCommanMsg_Save     :='Save';
  TeeCommanMsg_3D       :='3D';

  TeeCommanMsg_Rotating :='Ghoomna: %d  Elevation: %d';
  TeeCommanMsg_Rotate   :='Ghoomna';

  TeeCommanMsg_Moving   :='Tircha.Offset: %d Vert.Offset';
  TeeCommanMsg_Move     :='Challo';

  TeeCommanMsg_Zooming  :='Zoom: %d %%';
  TeeCommanMsg_Zoom     :='Zoom';

  TeeCommanMsg_Depthing :='3D: %d %%';
  TeeCommanMsg_Depth    :='Gherahi';

  TeeCommanMsg_Chart    :='Chart';
  TeeCommanMsg_Panel    :='Panel';

  TeeCommanMsg_RotateLabel:='Kheencho %s taake Ghoome';
  TeeCommanMsg_MoveLabel  :='Kheencho %s taake Hillee';
  TeeCommanMsg_ZoomLabel  :='Kheencho %s taake Zoom ho';
  TeeCommanMsg_DepthLabel :='Kheencho %s taake size budlee';

  TeeCommanMsg_NormalLabel:='Kheencho Baien button ko Zoom ke liyye, Daen button ko scroll ke liyye';
  TeeCommanMsg_NormalPieLabel:='Pie Slice ko toornee ke liye es ko keenchein';

  TeeCommanMsg_PieExploding :='Tukra: %d Toorna: %d %%';

  TeeMsg_TriSurfaceLess        :='Nuqtee ke number 4 ya 4 se barra huna chahiye';
  TeeMsg_TriSurfaceAllColinear :='tummam colinear data ke nuqtee';
  TeeMsg_TriSurfaceSimilar     :='aik jaisse nuqtee - execute nahein ho sakta';
  TeeMsg_GalleryTriSurface     :='Triangle Surf.';

  TeeMsg_AllSeries :='Tammam series';
  TeeMsg_Edit      :='Sahih Karna';

  TeeMsg_GalleryFinancial    :='Karobari';

  TeeMsg_CursorTool    :='Cursor';
  TeeMsg_DragMarksTool :='Marks ko Keencho';
  TeeMsg_AxisArrowTool :='Axis ke Teer';
  TeeMsg_DrawLineTool  :='Lakeer Kheencho';
  TeeMsg_NearestTool   :='Qareebi Nuqta';
  TeeMsg_ColorBandTool :='Rangoon ka Band';
  TeeMsg_ColorLineTool :='Rangoon ke lakeer';
  TeeMsg_RotateTool    :='Ghumaana';
  TeeMsg_ImageTool     :='Tasveer';
  TeeMsg_MarksTipTool  :='Mark Tips';

  TeeMsg_CantDeleteAncestor  :='ancestor ko khuttam nahein kiya ja sakta';

  TeeMsg_Load	          :='Bharro';
  TeeMsg_NoSeriesSelected :='Koi Kist nahein chunni';

  { TeeChart Actions }
  TeeMsg_CategoryChartActions  :='Chart';
  TeeMsg_CategorySeriesActions :='Chart Kist';

  TeeMsg_Action3D               := '&3D';
  TeeMsg_Action3DHint           := 'Budlu 2D / 3D';
  TeeMsg_ActionSeriesActive     := '&Active';
  TeeMsg_ActionSeriesActiveHint := 'Dekho / Chuppao Kist';
  TeeMsg_ActionEditHint         := 'Chart sahih karo';
  TeeMsg_ActionEdit             := '&Sahih...';
  TeeMsg_ActionCopyHint         := 'Clipboard per copy karo';
  TeeMsg_ActionCopy             := '&Copy';
  TeeMsg_ActionPrintHint        := 'Chart ko print karne se pehle dekho';
  TeeMsg_ActionPrint            := '&Print...';
  TeeMsg_ActionAxesHint         := 'Dekho / Chuppao Axes';
  TeeMsg_ActionAxes             := '&Axes';
  TeeMsg_ActionGridsHint        := 'Dekho / Chuppao Grids';
  TeeMsg_ActionGrids            := '&Grids';
  TeeMsg_ActionLegendHint       := 'Dekho / Chuppao Legend';
  TeeMsg_ActionLegend           := '&Legend';
  TeeMsg_ActionSeriesEditHint   := 'Series ko sahih karo';
  TeeMsg_ActionSeriesMarksHint  := 'Dekho / Chuppao Kist ke Marks';
  TeeMsg_ActionSeriesMarks      := '&Marks';
  TeeMsg_ActionSaveHint         := 'Chart ko Save karo';
  TeeMsg_ActionSave             := '&Save...';

  TeeMsg_CandleBar              := 'Bar';
  TeeMsg_CandleNoOpen           := 'Khulla Nahein';
  TeeMsg_CandleNoClose          := 'Bund Nahein';
  TeeMsg_NoLines                := 'Lakeer Nahein';
  TeeMsg_NoHigh                 := 'Ooncha Nahein';
  TeeMsg_NoLow                  := 'Neecha Nahein';
  TeeMsg_ColorRange             := 'Rangoon ke Range';
  TeeMsg_WireFrame              := 'Wireframe';
  TeeMsg_DotFrame               := 'Dot Frame';
  TeeMsg_Positions              := 'Positions';
  TeeMsg_NoGrid                 := 'Koi Grid Nahein';
  TeeMsg_NoPoint                := 'Koi Nuqta Nahein';
  TeeMsg_NoLine                 := 'Koi Lakeer Nahein';
  TeeMsg_Labels                 := 'Naam';
  TeeMsg_NoCircle               := 'Koi Goldaira Nahein';
  TeeMsg_Lines                  := 'Lakeer';
  TeeMsg_Border                 := 'Koonein';

  TeeMsg_SmithResistance      := 'Muqaabla';
  TeeMsg_SmithReactance       := 'Reactance';

  TeeMsg_Column               := 'Column';

  { 5.01 }
  TeeMsg_Separator            := 'Allug karne wala';
  TeeMsg_FunnelSegment        := 'Hissa';
  TeeMsg_FunnelSeries         := 'Nulki';
  TeeMsg_FunnelPercent        := '0.00 %';
  TeeMsg_FunnelExceed         := 'Muqarrar Hud se ziada';
  TeeMsg_FunnelWithin         := ' Muqarrar Hud ke dermian';
  TeeMsg_FunnelBelow          := 'Ya Muqarrar hud se aur kum';
  TeeMsg_CalendarSeries       := 'Calendar';
  TeeMsg_DeltaPointSeries     := 'DeltaNuqta';
  TeeMsg_ImagePointSeries     := 'TasveerNuqta';
  TeeMsg_ImageBarSeries       := 'TasveerBar';
  TeeMsg_SeriesTextFieldZero  := 'KistText: Field index sifar se barra hoona chahiye';

  { 5.02 }
  TeeMsg_Origin               := 'Ibtaadaijugga';
  TeeMsg_Transparency         := 'Shaffaf';
  TeeMsg_Box		      := 'Buksa';
  TeeMsg_ExtrOut	      := 'ExtrOut';
  TeeMsg_MildOut	      := 'MildOut';
  TeeMsg_PageNumber	      := 'Saffah number';
  TeeMsg_TextFile             := 'Text File';


  { 5.03 }
  TeeMsg_DragPoint            := 'Nuqta Kheencho';
  TeeMsg_OpportunityValues    := 'Mookke ki values';
  TeeMsg_QuoteValues          := 'QuoteValues';

  {AX 5.0.4}
  TeeMsg_ActiveXVersion      := 'ActiveX Release ' + AXVer;
  TeeMsg_ActiveXCannotImport := 'TeeChart ko %s se nahin laya ja sakta';
  TeeMsg_ActiveXVerbPrint    := '&Print Preview...';
  TeeMsg_ActiveXVerbExport   := 'Bahir bhejnat...';
  TeeMsg_ActiveXVerbImport   := 'Andar Laana...';
  TeeMsg_ActiveXVerbHelp     := '&Muddad...';
  TeeMsg_ActiveXVerbAbout    := 'TeeChart &ke muttaliq...';
  TeeMsg_ActiveXError        := 'TeeChart: Ghulti ka code: %d Neeche uttar raha hai: %s';
  TeeMsg_DatasourceError     := 'TeeChart DataSource kist ya RecordSet nahein hai';
  TeeMsg_SeriesTextSrcError  := 'Ghult Series kissam';
  TeeMsg_AxisTextSrcError    := 'Ghult Axis type';
  TeeMsg_DelSeriesDatasource := 'Kiya aap ko mittane ka yaqeen hai %s ?';
  TeeMsg_OCXNoPrinter        := 'Default printer mojud nahein hai.';
  TeeMsg_ActiveXPictureNotValid :='Tasveer sahih nahein hai';

  { 6.0 }
  TeeMsg_FunctionCustom   :='y = f(x)';
  TeeMsg_AsPDF            :='as &PDF';
  TeeMsg_PDFFilter        :='PDF files (*.pdf)|*.pdf';
  TeeMsg_AsPS             :='as PostScript';
  TeeMsg_PSFilter         :='PostScript files (*.eps)|*.eps';
  TeeMsg_GalleryHorizArea :='Tirchi'#13'Illaqa';
  TeeMsg_SelfStack        :='khudhe Stacked';
  TeeMsg_DarkPen          :='Ghera Hashia';
  TeeMsg_SelectFolder     :='Select database folder';
  TeeMsg_BDEAlias         :='&Alias:';
  TeeMsg_ADOConnection    :='&Connection:';

  // 6.02
  TeeMsg_Apply            :='&Apply';
  TeeMsg_AddNewGroup      :='Nai group ka indraaj';
  TeeMsg_ChangeGroupName  :='Group ka naam tabdeel karein';
  TeeMsg_GroupName        :='Group ka naam:';
  TeeMsg_FunctionMedian   :='Median';
  TeeMsg_FunctionMode     :='Mode';
  TeeMsg_Options          :='&Options...';
  TeeMsg_DepthTopAxis     :='Gherai Unchai';


  { 6.0 }
  TeeMsg_FunctionSmooth       :='Narram';
  TeeMsg_FunctionCross        :='Katte hue Nuqtee';
  TeeMsg_GridTranspose        :='3D Jaalli Transpose';
  TeeMsg_FunctionCompress     :='Compression';
  TeeMsg_ExtraLegendTool      :='Faltu Legend';
  TeeMsg_FunctionCLV          :='Bund Jugga'#13'Value';
  TeeMsg_FunctionOBV          :='Baqqaiya per '#13'awaze';
  TeeMsg_FunctionCCI          :='Cheezeen'#13'Channel Index';
  TeeMsg_FunctionPVO          :='Awaz'#13'Oscillator';
  TeeMsg_SeriesAnimTool       :='Kist Animation';
  TeeMsg_GalleryPointFigure   :='Nuqta & Jissamat';
  TeeMsg_Up                   :='Ooper';
  TeeMsg_Down                 :='Neechee';
  TeeMsg_GanttTool            :='Gantt Drag';
  TeeMsg_XMLFile              :='XML file';
  TeeMsg_GridBandTool         :='Jaali Band';
  TeeMsg_FunctionPerf         :='Kargardi';
  TeeMsg_GalleryGauge         :='Gauge';
  TeeMsg_GalleryGauges        :='Gauges';
  TeeMsg_ValuesVectorEndZ     :='KhuttamZ';
  TeeMsg_GalleryVector3D      :='Vector 3D';
  TeeMsg_Gallery3D            :='3D';
  TeeMsg_GalleryTower         :='Minar';
  TeeMsg_SingleColor          :='Aik Rang';
  TeeMsg_Cover                :='Cover';
  TeeMsg_Cone                 :='Cone';
  TeeMsg_PieTool              :='Pie Slices';

  // 7.0
  TeeMsg_Stop                 :='Rukko';
  TeeMsg_Execute              :='Challao!';
  TeeMsg_Themes               :='Themes';
  TeeMsg_LightTool            :='2D Rooshni';
  TeeMsg_Current              :='Moojudda';
  TeeMsg_FunctionCorrelation  :='Correlation';
  TeeMsg_FunctionVariance     :='Variance';
  TeeMsg_GalleryBubble3D      :='Bulbulla 3D';
  TeeMsg_GalleryHorizHistogram:='Tirchi'#13'Histogram';
  TeeMsg_FunctionPerimeter    :='Perimeter';
  TeeMsg_SurfaceNearestTool   :='Nazdeeki sattah';
end;

Procedure TeeCreateUrdu;
begin
  if not Assigned(TeeUrduLanguage) then
  begin
    TeeUrduLanguage:=TStringList.Create;
    TeeUrduLanguage.Text:=

'GRADIENT EDITOR=Gradient Theekkarnewalla'#13+
'GRADIENT=Gradient'#13+
'DIRECTION=Raasta'#13+
'VISIBLE=Nazar annewalla'#13+
'TOP BOTTOM=Ooper Neecha'#13+
'BOTTOM TOP=Neecha Ooper'#13+
'LEFT RIGHT=Bain Dain'#13+
'RIGHT LEFT=Dain Bain'#13+
'FROM CENTER=Beech se'#13+
'FROM TOP LEFT=Ooper Bain se'#13+
'FROM BOTTOM LEFT=Neeche Bain se'#13+
'OK=Ok'#13+
'CANCEL=Cancel'#13+
'COLORS=Rang'#13+
'START=Shurro'#13+
'MIDDLE=Middle'#13+
'END=Khuttam'#13+
'SWAP=Badulna'#13+
'NO MIDDLE=Koi darmian nahein'#13+
'TEEFONT EDITOR=Likhai theek karne wala'#13+
'INTER-CHAR SPACING=Nuqshe ke darmian jugga'#13+
'FONT=Font'#13+
'SHADOW=Saiyya'#13+
'HORIZ. SIZE=Tircha. size'#13+
'VERT. SIZE=Vert. size'#13+
'COLOR=Rang'#13+
'OUTLINE=Bahirki lakeer'#13+
'OPTIONS=Options'#13+
'FORMAT=Format'#13+
'TEXT=Likhai'#13+
'GRADIENT=Gradient'#13+
'POSITION=Position'#13+
'LEFT=Bain'#13+
'TOP=Ooncha'#13+
'AUTO=Khudbakhud'#13+
'CUSTOM=Custom'#13+
'LEFT TOP=Ooper Bain'#13+
'LEFT BOTTOM=Neeche Bain'#13+
'RIGHT TOP=Ooncha Dain'#13+
'RIGHT BOTTOM=Neecha Dain'#13+
'MULTIPLE AREAS=Mukhlalif jugghein'#13+
'NONE=KuchNahien'#13+
'STACKED=Stacked'#13+
'STACKED 100%=Stacked 100%'#13+
'AREA=Jugga'#13+
'PATTERN=Namuuna'#13+
'STAIRS=Serrian'#13+
'SOLID=Mazboot'#13+
'CLEAR=Saaf'#13+
'HORIZONTAL=Tircha'#13+
'VERTICAL=Vertical'#13+
'DIAGONAL=Diagonal'#13+
'B.DIAGONAL=B.Diagonal'#13+
'CROSS=Kanti'#13+
'DIAG.CROSS=Tircha Kanta'#13+
'AREA LINES=Jugga ki lakereen'#13+
'BORDER=Hashia'#13+
'INVERTED=Ultahuvva'#13+
'INVERTED SCROLL=Ulti Scroll'#13+
'COLOR EACH=Her rang'#13+
'ORIGIN=Buniyad'#13+
'USE ORIGIN=Buniyad ka istimaal'#13+
'WIDTH=Chorai'#13+
'HEIGHT=Oonchai'#13+
'AXIS=Axis'#13+
'LENGTH=Lumabai'#13+
'SCROLL=Scroll'#13+
'PATTERN=Namoona'#13+
'START=Shurroo'#13+
'END=Khuttam'#13+
'BOTH=Doono'#13+
'AXIS INCREMENT=Axis Barhana'#13+
'INCREMENT=Barhana'#13+
'STANDARD=Maiiar'#13+
'CUSTOM=Tareeqa'#13+
'ONE MILLISECOND=Aik Millisecond'#13+
'ONE SECOND=Aik Second'#13+
'FIVE SECONDS=Paanch Seconds'#13+
'TEN SECONDS=Das Seconds'#13+
'FIFTEEN SECONDS=Pundhran Seconds'#13+
'THIRTY SECONDS=Tees Seconds'#13+
'ONE MINUTE=Aik Minute'#13+
'FIVE MINUTES=Paanch Minutes'#13+
'TEN MINUTES=Das Minutes'#13+
'FIFTEEN MINUTES=Pundhran Minutes'#13+
'THIRTY MINUTES=Tees Minutes'#13+
'ONE HOUR=Aik Ghanntta'#13+
'TWO HOURS=Doo Ghanttee'#13+
'SIX HOURS=Cheh Ghanttee Hours'#13+
'TWELVE HOURS=Barah Ghanttee'#13+
'ONE DAY=Aik Din'#13+
'TWO DAYS=Doo Din'#13+
'THREE DAYS=Teen Din'#13+
'ONE WEEK=Aik Hafta'#13+
'HALF MONTH=Aadha Maheena'#13+
'ONE MONTH=Aik Maheena'#13+
'TWO MONTHS=Doo Maheene'#13+
'THREE MONTHS=Teen Maheene'#13+
'FOUR MONTHS=Char Maheene'#13+
'SIX MONTHS=Cheh Maheene'#13+
'ONE YEAR=Aik Saal'#13+
'EXACT DATE TIME=Sahih Tarrekh Waqt'#13+
'AXIS MAXIMUM AND MINIMUM=Axis Ziada se Ziada aur Kum se Kum'#13+
'VALUE=Value'#13+
'TIME=Waqt'#13+
'LEFT AXIS=Bain axis'#13+
'RIGHT AXIS=Dain axis'#13+
'TOP AXIS=Ooper axis'#13+
'BOTTOM AXIS=Neechi axis'#13+
'% BAR WIDTH=% Bar Choorai'#13+
'STYLE=Style'#13+
'% BAR OFFSET=% Bar offset'#13+
'RECTANGLE=Rectangle'#13+
'PYRAMID=Pyramid'#13+
'INVERT. PYRAMID=Invert. Pyramid'#13+
'CYLINDER=Cylinder'#13+
'ELLIPSE=Ellipse'#13+
'ARROW=Teer'#13+
'RECT. GRADIENT=Rect. Gradient'#13+
'CONE=Cone'#13+
'DARK BAR 3D SIDES=Gheri bar 3D Itraaf'#13+
'BAR SIDE MARGINS=Bar itraaf waqfa'#13+
'AUTO MARK POSITION=Ghudbukhud Nishaan ki Jugga'#13+
'BORDER=Haashia'#13+
'JOIN=Milna'#13+
'BAR SIDE MARGINS=Bar itraaf waqfa'#13+
'DATASET=Dataset'#13+
'APPLY=Shurroh'#13+
'SOURCE=Source'#13+
'MONOCHROME=aikrang'#13+
'DEFAULT=Ibtadaai'#13+
'2 (1 BIT)=2 (1 bit)'#13+
'16 (4 BIT)=16 (4 bit)'#13+
'256 (8 BIT)=256 (8 bit)'#13+
'32768 (15 BIT)=32768 (15 bit)'#13+
'65536 (16 BIT)=65536 (16 bit)'#13+
'16M (24 BIT)=16M (24 bit)'#13+
'16M (32 BIT)=16M (32 bit)'#13+
'LENGTH=Lumbai'#13+
'MEDIAN=Darmiana'#13+
'WHISKER=Balbrabar'#13+
'PATTERN COLOR EDITOR=Rangon ko sahih karne wala'#13+
'IMAGE=Tasveer'#13+
'NONE=Khuch Nahein'#13+
'BACK DIAGONAL=Pechla Diagonal'#13+
'CROSS=Kanta'#13+
'DIAGONAL CROSS=Diagonal Kanta'#13+
'FILL 80%=Bhurna 80%'#13+
'FILL 60%=Bhurna 60%'#13+
'FILL 40%=Bhurna 40%'#13+
'FILL 20%=Bhurna 20%'#13+
'FILL 10%=Bhurna 10%'#13+
'ZIG ZAG=Terhi Mehri'#13+
'VERTICAL SMALL=Vertical Chotti'#13+
'HORIZ. SMALL=Horiz. Chotti'#13+
'DIAG. SMALL=Diag. Chotti'#13+
'BACK DIAG. SMALL=Pechla Diag.'#13+
'CROSS SMALL=Choota Kanta'#13+
'DIAG. CROSS SMALL=Diag. Kanta'#13+
'PATTERN COLOR EDITOR=Namoone ke rang sahih karne wala'#13+
'OPTIONS=Options'#13+
'DAYS=Din'#13+
'WEEKDAYS=Haftee ki Din'#13+
'TODAY=Aaj'#13+
'SUNDAY=Itwaar'#13+
'TRAILING=Pechla'#13+
'MONTHS=Maheene'#13+
'LINES=Lakeerein'#13+
'SHOW WEEKDAYS=Haftee ke din dikhana'#13+
'UPPERCASE=Uppercase'#13+
'TRAILING DAYS=Guzree hue din'#13+
'SHOW TODAY=Aag ka din dikhao'#13+
'SHOW MONTHS=Maheene Dikhao'#13+
'CANDLE WIDTH=Mombatti ki chorai'#13+
'STICK=Charri'#13+
'BAR=Bar'#13+
'OPEN CLOSE=Khool Bun Karo'#13+
'UP CLOSE=Bahut Nazdeek'#13+
'DOWN CLOSE=Neeche Bund'#13+
'SHOW OPEN=Khulla Dikhao'#13+
'SHOW CLOSE=Bund Dikhao'#13+
'DRAW 3D=3D'#13+
'DARK 3D=3D Ghera'#13+
'EDITING=Sahih Karna'#13+
'CHART=Nuqsha'#13+
'SERIES=Kist'#13+
'DATA=Daten'#13+
'TOOLS=Saaman'#13+
'EXPORT=Bahir Bhaijna'#13+
'PRINT=Printn'#13+
'GENERAL=Aam'#13+
'TITLES=Unwaan'#13+
'LEGEND=Barra'#13+
'PANEL=Panel'#13+
'PAGING=Saffee'#13+
'WALLS=Deewarian'#13+
'3D=3D'#13+
'ADD=Jumma Karna'#13+
'DELETE=Mittana'#13+
'TITLE=Unwaan'#13+
'CLONE=Clone'#13+
'CHANGE=Tabdeel'#13+
'HELP=Maddud'#13+
'CLOSE=Bund'#13+
'IMAGE=Tasveer'#13+
'TEECHART PRINT PREVIEW=TeeChart Print Kehaana'#13+
'PRINTER=Printer'#13+
'SETUP=Setup'#13+
'ORIENTATION=Waqfiat'#13+
'PORTRAIT=Tasveer'#13+
'LANDSCAPE=Landscape'#13+
'MARGINS (%)=Waqfee (%)'#13+
'DETAIL=Tafseel'#13+
'MORE=Ziada'#13+
'NORMAL=Aam'#13+
'RESET MARGINS=Waqfaa doobara set karna'#13+
'VIEW MARGINS=Waqfaa Dekhna'#13+
'PROPORTIONAL=Proportional'#13+
'TEECHART PRINT PREVIEW=TeeChart Print ko Dekhna'#13+
'RECTANGLE=Rectangle'#13+
'CIRCLE=GoolDaira'#13+
'VERTICAL LINE=Vert. Lakeer'#13+
'HORIZ. LINE=Horiz. Lakeer'#13+
'TRIANGLE=Triangle'#13+
'INVERT. TRIANGLE=Invert. Triangle'#13+
'LINE=Lakeer'#13+
'DIAMOND=Heera'#13+
'CUBE=Cube'#13+
'DIAGONAL CROSS=Diagonal Kanta'#13+
'STAR=Sitara'#13+
'TRANSPARENT=Saafshafaf'#13+
'HORIZ. ALIGNMENT=Horiz. Alighnment'#13+
'LEFT=Bain'#13+
'CENTER=Darmian'#13+
'RIGHT=Dain'#13+
'ROUND RECTANGLE=Gool Rectangle'#13+
'ALIGNMENT=Alighnment'#13+
'TOP=Kholna'#13+
'BOTTOM=Neeche'#13+
'RIGHT=:Dain'#13+
'BOTTOM=Neeche'#13+
'UNITS=Units'#13+
'PIXELS=Pixels'#13+
'AXIS=Axis'#13+
'AXIS ORIGIN=Axis Origin'#13+
'ROTATION=Ghumaana'#13+
'CIRCLED=Goldaire ke andar'#13+
'3 DIMENSIONS=3 Itraaf'#13+
'RADIUS=Qutar'#13+
'ANGLE INCREMENT=Zavia ka barhna'#13+
'RADIUS INCREMENT=Qutar ka barhna'#13+
'CLOSE CIRCLE=Bund Daira'#13+
'PEN=Qallum'#13+
'CIRCLE=Daira'#13+
'LABELS=Naam'#13+
'VISIBLE=Dikhta hua.'#13+
'ROTATED=Ghoomta hua'#13+
'CLOCKWISE=Ghariki sooiaon ki tarrah'#13+
'INSIDE=Andhar'#13+
'ROMAN=Roman'#13+
'HOURS=Ghentte'#13+
'MINUTES=Minutes'#13+
'SECONDS=Seconds'#13+
'START VALUE=Shurooh ki value'#13+
'END VALUE=Khuttam ki value'#13+
'TRANSPARENCY=Saafshaffaf'#13+
'DRAW BEHIND=Peeche banana'#13+
'COLOR MODE=Rang ka mode'#13+
'STEPS=Serrian'#13+
'RANGE=Range'#13+
'PALETTE=Palette'#13+
'PALE=Pale'#13+
'STRONG=Mazboot'#13+
'GRID SIZE=Jalli ka size'#13+
'X=X'#13+
'Z=Z'#13+
'DEPTH=Gherahi'#13+
'IRREGULAR=Irregulär'#13+
'GRID=Jalli'#13+
'VALUE=Value'#13+
'ALLOW DRAG=Kheenchne ki ijaazat'#13+
'VERTICAL POSITION=Tirchi Position'#13+
'PEN=Qallum'#13+
'LEVELS POSITION=Darjoon ki Position'#13+
'LEVELS=Darjee'#13+
'NUMBER=Number'#13+
'LEVEL=Durja'#13+
'AUTOMATIC=Khudbakhud'#13+
'BOTH=Doonoo'#13+
'SNAP=Snap'#13+
'FOLLOW MOUSE=Mouse ka Peecha'#13+
'STACK=Stack'#13+
'HEIGHT 3D=3D oonchai'#13+
'LINE MODE=Lakeer ka mode'#13+
'STAIRS=Seerian'#13+
'NONE=Kuchnahein'#13+
'OVERLAP=Ooper charha hua'#13+
'STACK=Ambaar'#13+
'STACK 100%=Ambar 100%'#13+
'CLICKABLE=Clickable'#13+
'LABELS=Unwaan'#13+
'AVAILABLE=Moojud'#13+
'SELECTED=Chunnee Huve'#13+
'DATASOURCE=Datesource'#13+
'GROUP BY=Group by'#13+
'CALC=Calc'#13+
'OF=of'#13+
'SUM=Jummah'#13+
'COUNT=Ginttee'#13+
'HIGH=Oonchai'#13+
'LOW=Neecha'#13+
'AVG=Aust'#13+
'HOUR=Ghentta'#13+
'DAY=Din'#13+
'WEEK=Hufta'#13+
'WEEKDAY=Huftee ke Din'#13+
'MONTH=Maheena'#13+
'QUARTER=Seh Mahi'#13+
'YEAR=Saal'#13+
'HOLE %=Soorakh %'#13+
'RESET POSITIONS=Position dobaara karna'#13+
'MOUSE BUTTON=Choohe ka button'#13+
'ENABLE DRAWING=Enable Drawing'#13+
'ENABLE SELECT=Enable Select'#13+
'ENHANCED=Behter karna'#13+
'ERROR WIDTH=Ghulti ki choorai'#13+
'WIDTH UNITS=Choorai ki units'#13+
'PERCENT=Fi sud'#13+
'PIXELS=Pixel'#13+
'LEFT AND RIGHT=Bain aur Dain'#13+
'TOP AND BOTTOM=Ooncha aur Neecha'#13+
'BORDER=Chardewari'#13+
'BORDER EDITOR=Chardewari ko theek karne wala'#13+
'DASH=Lakeer'#13+
'DOT=Nuqta'#13+
'DASH DOT=Lakeer Nukta'#13+
'DASH DOT DOT=Lakeer Nukta Lakeer'#13+
'CALCULATE EVERY=JeHer aik ko calculate kerna'#13+
'ALL POINTS=Tammam Nuqte'#13+
'NUMBER OF POINTS=Nuqtoon ki taadad'#13+
'RANGE OF VALUES=value ki had'#13+
'FIRST=Pehla'#13+
'CENTER=Dermain'#13+
'LAST=Akhri'#13+
'TEEPREVIEW EDITOR=TeePreview theek karne wala'#13+
'ALLOW MOVE=Ghoomne ki Ijaazat'#13+
'ALLOW RESIZE=Resize ki Ijaazat'#13+
'DRAG IMAGE=Tasveer ko Kheenchna'#13+
'AS BITMAP=Bitmap ki tarrah'#13+
'SHOW IMAGE=Tasveer ko Dikhana'#13+
'DEFAULT=Pehli waali'#13+
'MARGINS=Hashiee'#13+
'SIZE=Jisaamat'#13+
'3D %=3D %'#13+
'ZOOM=Zoom'#13+
'ROTATION=Rotation'#13+
'ELEVATION=Saamne se'#13+
'100%=100%'#13+
'HORIZ. OFFSET=Horiz. Offset'#13+
'VERT. OFFSET=Vert. Offset'#13+
'PERSPECTIVE=Perspective'#13+
'ANGLE=Darja'#13+
'ORTHOGONAL=Orthogonal'#13+
'ZOOM TEXT=Zoom Likhai'#13+
'SCALES=Durji'#13+
'TITLE=Unwaan'#13+
'TICKS=Ticks'#13+
'MINOR=Choote'#13+
'MAXIMUM=Ziada se Ziada'#13+
'MINIMUM=Kum se Kum'#13+
'(MAX)=(Ziada)'#13+
'(MIN)=(Kum)'#13+
'DESIRED INCREMENT=Khuwaish ke muttabiq ziada karna'#13+
'(INCREMENT)=(Ziada karna)'#13+
'LOG BASE=Log Basis'#13+
'LOGARITHMIC=Logarithmic'#13+
'TITLE=Unwaan'#13+
'MIN. SEPARATION %=Kum se kum Juddai %'#13+
'MULTI-LINE=Baht se lakerrien'#13+
'LABEL ON AXIS=Axis ke naam'#13+
'ROUND FIRST=Pehla Daira'#13+
'MARK=Nishaan.'#13+
'LABELS FORMAT=Naam ka format'#13+
'EXPONENTIAL=Exponential'#13+
'DEFAULT ALIGNMENT=Shurro ki alignment'#13+
'LEN=Len'#13+
'LENGTH=Lumbai'#13+
'AXIS=Axis'#13+
'INNER=Anur wala'#13+
'GRID=Jalli'#13+
'AT LABELS ONLY=Siraf Nammon Pe'#13+
'CENTERED=Dermain karna'#13+
'COUNT=Gintee'#13+
'TICKS=Ticks'#13+
'POSITION %=Position %'#13+
'START %=Shuroo %'#13+
'END %=Khuttam %'#13+
'OTHER SIDE=Doosri Taraf'#13+
'AXES=Axis'#13+
'BEHIND=Peeche'#13+
'CLIP POINTS=Clip Nuqtee'#13+
'PRINT PREVIEW=Print Preview'#13+
'MINIMUM PIXELS=Kum se kum Pixel'#13+
'MOUSE BUTTON=Choohe ka button'#13+
'ALLOW=Zoom=zoon ki ijaazat'#13+
'ANIMATED=Animated'#13+
'VERTICAL=Vertical'#13+
'RIGHT=Dain'#13+
'MIDDLE=Dermian'#13+
'ALLOW SCROLL=Scroll i Ijaazat'#13+
'TEEOPENGL EDITOR=TeeOpenGL Saheh karne wala'#13+
'AMBIENT LIGHT=Ambient Rooshni'#13+
'SHININESS=Shininess'#13+
'FONT 3D DEPTH=Font 3D gehrai'#13+
'ACTIVE=Active'#13+
'FONT OUTLINES=Font ki bahir wali lakeerien'#13+
'SMOOTH SHADING=Naram saiee'#13+
'LIGHT=Rooshni'#13+
'Y=Y'#13+
'INTENSITY=Intensity'#13+
'BEVEL=Bevel'#13+
'FRAME=Frame'#13+
'ROUND FRAME=Gool Frame'#13+
'LOWERED=Nechee kia hua'#13+
'RAISED=Ubhra hua '#13+
'POSITION=Position'#13+
'SYMBOLS=Symbol'#13+
'TEXT STYLE=Likhai ke style'#13+
'LEGEND STYLE=Legend style'#13+
'VERT. SPACING=Vert. Spacing'#13+
'AUTOMATIC=Automatic'#13+
'SERIES NAMES=Series ke naam'#13+
'SERIES VALUES=Series Values'#13+
'LAST VALUES=Aakhri Values'#13+
'PLAIN=Plain'#13+
'LEFT VALUE=Bain Value'#13+
'RIGHT VALUE=Dain Value'#13+
'LEFT PERCENT=Bain Fi sad'#13+
'RIGHT PERCENT=Dain Sad'#13+
'X VALUE=X Value'#13+
'VALUE=Value'#13+
'PERCENT=Fi Sad'#13+
'X AND VALUE=X aur Value'#13+
'X AND PERCENT=X aur Fisad'#13+
'CHECK BOXES=Check-Boxes'#13+
'DIVIDING LINES=Taqseem karti hue lakeerain'#13+
'FONT SERIES COLOR=Font series ka rang'#13+
'POSITION OFFSET %=Position Offset %'#13+
'MARGIN=Hashia'#13+
'RESIZE CHART=Nuqshe ka resize karna'#13+
'CUSTOM=Custom.'#13+
'WIDTH UNITS=Choorai ke units'#13+
'CONTINUOUS=Mussalsal'#13+
'POINTS PER PAGE=Nuqtee fi saffa'#13+
'SCALE LAST PAGE=Scale aakhri safaa'#13+
'CURRENT PAGE LEGEND=Moojudah safaa legend'#13+
'PANEL EDITOR=Panel Editor'#13+
'BACKGROUND=Backgroung'#13+
'BORDERS=Chardeewari'#13+
'BACK IMAGE=Pechli Tasveer'#13+
'STRETCH=Kheenchna'#13+
'TILE=Mazmoon'#13+
'CENTER=Dermain'#13+
'BEVEL INNER=Bevel Andruni'#13+
'LOWERED=neeche kia hua'#13+
'RAISED=Ubhra hua'#13+
'BEVEL OUTER=Bevel Outer'#13+
'MARKS=Nishaan'#13+
'DATA SOURCE=Data source'#13+
'SORT=Sort'#13+
'CURSOR=Cursor'#13+
'SHOW IN LEGEND=Legend mei dekhao'#13+
'FORMATS=Formats'#13+
'VALUES=Values'#13+
'PERCENTS=Fi sad'#13+
'HORIZONTAL AXIS=Horizontal Axis'#13+
'TOP AND BOTTOM=Ooncha aur Neecha'#13+
'DATETIME=TarekhWaqt'#13+
'VERTICAL AXIS=Vertical Axis'#13+
'LEFT=Bain'#13+
'RIGHT=Dain'#13+
'LEFT AND RIGHT=Bain aur Dain'#13+
'ASCENDING=Ascending'#13+
'DESCENDING=Descending'#13+
'DRAW EVERY=Hre aik draw karna'#13+
'CLIPPED=Clipped'#13+
'ARROWS=Teer'#13+
'MULTI LINE=Bahut se lakeerain'#13+
'ALL SERIES VISIBLE=Tammam series dikhai detti hui'#13+
'LABEL=Unwaan'#13+
'LABEL AND PERCENT=Naam aur Fisad'#13+
'LABEL AND VALUE=Naam aur value'#13+
'PERCENT TOTAL=Fisad ko total'#13+
'LABEL & PERCENT TOTAL=Naam aur fisad ka total'#13+
'X VALUE=X Value'#13+
'X AND Y VALUES=X aur Y Value'#13+
'MANUAL=Haath se kia hua'#13+
'RANDOM=Random'#13+
'FUNCTION=kaam'#13+
'NEW=Nea'#13+
'EDIT=Theekkarna'#13+
'DELETE=Mittana'#13+
'PERSISTENT=Persistant'#13+
'ADJUST FRAME=Frame ko adjust karna'#13+
'SUBTITLE=Subtitle'#13+
'SUBFOOT=Subfoot'#13+
'FOOT=2. Per = 2'#13+
'DELETE=Mitatna'#13+
'VISIBLE WALLS=Dikhai detti hue deewarain'#13+
'BACK=Peecha'#13+
'DIF. LIMIT=Dif. Limit'#13+
'LINES=Lakeerain'#13+
'ABOVE=Ooper'#13+
'WITHIN=Uske undhar'#13+
'BELOW=Neeche'#13+
'CONNECTING LINES=Jurti hui lakeerain'#13+
'SERIES=Series'#13+
'PALE=Pale'#13+
'STRONG=Mazboot'#13+
'HIGH=Ooncha'#13+
'LOW=Neecha'#13+
'BROWSE=Ghoomna '#13+
'TILED=Tiled'#13+
'INFLATE MARGINS=Hashia ko barra karna'#13+
'SQUARE=Chokoor'#13+
'DOWN TRIANGLE=Nichla triangle'#13+
'SMALL DOT=Chhota Nuqta'#13+
'DEFAULT=Default.'#13+
'GLOBAL=Global'#13+
'SHAPES=Shapes'#13+
'BRUSH=Bursh'#13+
'BRUSH=BUrsh'#13+
'BORDER=Border'#13+
'COLOR=Rang'#13+
'DELAY=Deer'#13+
'MSEC.=msec.'#13+
'MOUSE ACTION=Chooe ka action'#13+
'MOVE=Move'#13+
'CLICK=Click'#13+
'BRUSH=Bursh'#13+
'DRAW LINE=Lakeer Keenchna'#13+
'BORDER EDITOR=Haashia Sahih karne wala'#13+
'DASH=Dash'#13+
'DOT=Nuqta'#13+
'DASH DOT=Lakeer Nuqta'#13+
'DASH DOT DOT=Lakeer Nuqta Nuqta'#13+
'EXPLODE BIGGEST=Sub se bara explode'#13+
'TOTAL ANGLE=Mukammal derja'#13+
'GROUP SLICES=Group slices'#13+
'BELOW %=Neeche %'#13+
'BELOW VALUE=Neeche ki vlaue'#13+
'OTHER=Doosra'#13+
'PATTERNS=Namoone'#13+
'CLOSE CIRCLE=Bund Daira'#13+
'VISIBLE=Dekhai daita hua'#13+
'CLOCKWISE=Gharri ki sooiaon ki tarah'#13+
'SIZE %=size %'#13+
'PATTERN=Namoonee'#13+
'DEFAULT=Default'#13+
'SERIES DATASOURCE TEXT EDITOR=SERIES DATASOURCE Likhai sahih karne wala'#13+
'FIELDS=Fields'#13+
'NUMBER OF HEADER LINES=Headers ki taadad'#13+
'SEPARATOR=Aalaidah karne wala'#13+
'COMMA=Comma'#13+
'SPACE=Juggah'#13+
'TAB=Tabr'#13+
'FILE=File'#13+
'WEB URL=Web URL'#13+
'LOAD=Bahrna'#13+
'C LABELS=C Naam'#13+
'R LABELS=R Naams'#13+
'C PEN=C kallum'#13+
'R PEN=R Kallam'#13+
'STACK GROUP=Stack Group'#13+
'USE ORIGIN=Assal istamall karo'#13+
'MULTIPLE BAR=Bahut se bar'#13+
'SIDE=aik taraf'#13+
'STACKED 100%=Stacked 100%'#13+
'SIDE ALL=tammam taraf'#13+
'BRUSH=Bursh..'#13+
'DRAWING MODE=Drawing Mode'#13+
'SOLID=Bhara hua'#13+
'WIREFRAME=Jaalli'#13+
'DOTFRAME=Dotframe'#13+
'SMOOTH PALETTE=Smooth palette'#13+
'SIDE BRUSH=Side wala bursh'#13+
'ABOUT TEECHART PRO V7.0=TeeChart Pro v7.0 ki muttaliq'#13+
'ALL RIGHTS RESERVED.=Tammam Rights mehfooz hein'#13+
'VISIT OUR WEB SITE !=Hamari web site per jayee !'#13+
'TEECHART WIZARD=TeeChart Wizard'#13+
'SELECT A CHART STYLE=Nuqsha ke style muntakhib keejiye'#13+
'DATABASE CHART=Database-Nuqsha'#13+
'NON DATABASE CHART=Non database nuqsha'#13+
'SELECT A DATABASE TABLE=Database meez ko munthakib kejiye'#13+
'ALIAS=Alias'#13+
'TABLE=meez'#13+
'SOURCE=Source'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'MICROSOFT ADO=Microsoft ADO'#13+
'SELECT THE DESIRED FIELDS TO CHART=Passendeedah fields ko nuqshe mein muntakhib kejiyee'#13+
'SELECT A TEXT LABELS FIELD=Likhai ke neeam wali field ko munthakib kejiyee'#13+
'CHOOSE THE DESIRED CHART TYPE=Passendeedah nuqsha ka type munthakib kejiyee.'#13+
'2D=2D'#13+
'CHART PREVIEW=Chart Preview'#13+
'SHOW LEGEND=Legend Dekhao'#13+
'SHOW MARKS=Nishaan Dikhao'#13+
'< BACK=< Peechee'#13+
'SELECT A CHART STYLE=Nuqshe ka style muntakhib kejiyee'#13+
'NON DATABASE CHART=Non Database Nuqsha'#13+
'SELECT A DATABASE TABLE=Database meez muntakhib karein'#13+
'BORLAND DATABASE ENGINE=Borland Database Engine'#13+
'SELECT THE DESIRED FIELDS TO CHART=Passendeedah fields ko nuqshe mein muntakhib karein'#13+
'SELECT A TEXT LABELS FIELD=Likhai ke namm wali files muntakhib karein'#13+
'CHOOSE THE DESIRED CHART TYPE=Pasendeedah nuqsha muntakhib karein'#13+
'EXPORT CHART=Nuqsha Explosion'#13+
'PICTURE=Tasveer'#13+
'NATIVE=Native'#13+
'KEEP ASPECT RATIO=Aspect Ratio ko aik jaisa rakhin'#13+
'INCLUDE SERIES DATA=Data series ko shaamil karein'#13+
'FILE SIZE=File-size'#13+
'DELIMITER=Delimiter'#13+
'XML=XML'#13+
'HTML TABLE=HTML Meez'#13+
'EXCEL=Excel'#13+
'TAB=Tab'#13+
'COLON=Colon'#13+
'INCLUDE=Shaamil Karna'#13+
'POINT LABELS=Nuqte ke naam'#13+
'POINT INDEX=Nuqte ka index'#13+
'HEADER=Header'#13+
'COPY=Copy'#13+
'SAVE=Bachana'#13+
'SEND=Bhaijna'#13+
'KEEP ASPECT RATIO=Aspect Ratio ko aik jaisa rakhin'#13+
'INCLUDE SERIES DATA=Data series ko shaamil karein'#13+
'FUNCTIONS=Function'#13+
'ADD=Jammah karna'#13+
'ADX=ADX'#13+
'AVERAGE=Aust'#13+
'BOLLINGER=Bollinger'#13+
'COPY=Copy'#13+
'DIVIDE=Taqseem'#13+
'EXP. AVERAGE=Exp. Aust.'#13+
'EXP.MOV.AVRG.=Exp.Mov.Aust.'#13+
'HIGH=Ooncha'#13+
'LOW=Neecha'#13+
'MACD=MACD'#13+
'MOMENTUM=Momentum'#13+
'MOMENTUM DIV=Momentum Div'#13+
'MOVING AVRG.=Moving Aust'#13+
'MULTIPLY=Multiply.'#13+
'R.S.I.=R.S.I'#13+
'ROOT MEAN SQ.=Root Mean Sq.'#13+
'STD.DEVIATION=Std. Deviation'#13+
'STOCHASTIC=Stochastic'#13+
'SUBTRACT=Nafeeh karna'#13+
'APPLY=Apply'#13+
'SOURCE SERIES=Source series'#13+
'TEECHART GALLERY=TeeChart Gallery'#13+
'FUNCTIONS=Funkctions'#13+
'DITHER=Dither'#13+
'REDUCTION=Kam karna'#13+
'COMPRESSION=Compression'#13+
'LZW=LZW'#13+
'RLE=RLE'#13+
'NEAREST=Kareeb ter'#13+
'FLOYD STEINBERG=Floyd Steinberg'#13+
'STUCKI=Stucki'#13+
'SIERRA=Sierra'#13+
'JAJUNI=JaJuNI'#13+
'STEVE ARCHE=Steve Arche'#13+
'BURKES=Burkes'#13+
'WINDOWS 20=Windows 20'#13+
'WINDOWS 256=Windows 256'#13+
'WINDOWS GRAY=Windows Gray'#13+
'MONOCHROME=Monochrome'#13+
'GRAY SCALE=Gray Scale'#13+
'NETSCAPE=Netscape'#13+
'QUANTIZE=Quantize'#13+
'QUANTIZE 256=Quantize 256'#13+
'% QUALITY=% Miyaar'#13+
'GRAY SCALE=Gray schale'#13+
'PERFORMANCE=Kargardegy'#13+
'QUALITY=Miyaar'#13+
'SPEED=Raftar'#13+
'COMPRESSION LEVEL=compression level'#13+
'CHART TOOLS GALLERY=Nuqsha Tools Gallery'#13+
'ANNOTATION=Annotation'#13+
'AXIS ARROWS=Axis teer'#13+
'COLOR BAND=Rang Band'#13+
'COLOR LINE=Cursor lakeer'#13+
'CURSOR=Cursor'#13+
'DRAG MARKS=Kheenchne ke Nishan'#13+
'DRAW LINE=Draw Lakeer'#13+
'IMAGE=Linie zeichnen'#13+
'MARK TIPS=Mark Tips'#13+
'NEAREST POINT=Nazdeek ka Nuqta'#13+
'ROTATE=Ghoomana'#13+
'CHART TOOLS GALLERY=Nuqsha Tools Gallery'#13+
'BRUSH=Bursh'#13+
'DRAWING MODE=Drawing Modes'#13+
'WIREFRAME=Wireframe'#13+
'SMOOTH PALETTE=Smooth pallete'#13+
'SIDE BRUSH=Aik taraf ka bursh'#13+
'YES=Haan'#13+
'SIDE=Aik taraf'+#13+
'SIDE ALL=Tammam Tarafal'+#13+
'ROTATE=Rotate'+#13+
'SMOOTH PALETTE=Smooth Pallete'+#13+
'CHART TOOLS GALLERY=Nuqsha tool gallery'+#13+
'ADD=Jumma'+#13+
'BORDER EDITOR=Border saheh karne wala'+#13+
'DRAWING MODE=Drawing Mode'+#13+
'CLOSE CIRCLE=Bund kia hua daira'+#13+
'PICTURE=Tasveer'+#13+
'NATIVE=Native'+#13+
'DATA=Datos'+#13+
'KEEP ASPECT RATIO=Keep aspect ratio'+#13+
'COPY=Copy'+#13+
'SAVE=Bachao'+#13+
'SEND=Bhejo'+#13+
'INCLUDE SERIES DATA=Series data shamil karo'+#13+
'FILE SIZE=File size'+#13+
'INCLUDE=Shamil karo'+#13+
'POINT INDEX=Point Index'+#13+
'POINT LABELS=nuqtoon ke naam'+#13+
'DELIMITER=Delimitar'+#13+
'DEPTH=Gehrahi.'+#13+
'COMPRESSION LEVEL=Compression level'+#13+
'COMPRESSION=Compresion'+#13+
'PATTERNS=Namoone'+#13+
'LABEL=Naam'+#13+
'GROUP SLICES=Group tukree'+#13+
'EXPLODE BIGGEST=Explode barra'+#13+
'TOTAL ANGLE=Mukkamal Darja'+#13+
'HORIZ. SIZE= Horiz. Size'+#13+
'VERT. SIZE=Vert. Size'+#13+
'SHAPES=Jissamat'+#13+
'INFLATE MARGINS=Hashion ko barhana'+#13+
'QUALITY=Miyar'+#13+
'SPEED=Raftar'+#13+
'% QUALITY=% Miyar'+#13+
'GRAY SCALE=Gray Scale'+#13+
'PERFORMANCE=Kargardegy'+#13+
'BROWSE=Browse'+#13+
'TILED=Tiled'+#13+
'HIGH=Ooncha'+#13+
'LOW=Neecha'+#13+
'DATABASE CHART=Database Nuqsha'+#13+
'NON DATABASE CHART=NON DATABASE Nuqsha'+#13+
'HELP=Maddad'+#13+
'NEXT >=Aglaa >'+#13+
'< BACK=< Peechee'+#13+
'TEECHART WIZARD=TeeChart Wizard'+#13+
'PERCENT=Fisad'+#13+
'PIXELS=Pixels'+#13+
'ERROR WIDTH=Ghalti ki chorai'+#13+
'ENHANCED=Enhanced'+#13+
'VISIBLE WALLS=Dikhti hui dewaar'+#13+
'ACTIVE=Active'+#13+
'DELETE=Mittana'+#13+
'ALIGNMENT=Alighnment'+#13+
'ADJUST FRAME=Adjust frame'+#13+
'HORIZONTAL=Horizontal'+#13+
'VERTICAL=Vertical'+#13+
'VERTICAL POSITION=Position vertical'+#13+
'NUMBER=Hindse'+#13+
'LEVELS=Darje'+#13+
'OVERLAP=Overlap'+#13+
'STACK 100%=Stack 100%'+#13+
'MOVE=Move'+#13+
'CLICK=Click'+#13+
'DELAY=Takheer'+#13+
'DRAW LINE=Lakeer Kheenchna'+#13+
'FUNCTIONS=Functions'+#13+
'SOURCE SERIES=Source Series '+#13+
'ABOVE=Ooper'+#13+
'BELOW=Neeche'+#13+
'Dif. Limit=Dif. Limit'+#13+
'WITHIN=Darmian'+#13+
'EXTENDED=Lamba kia hua'+#13+
'STANDARD=Miyaar'+#13+
'STATS=Aidadoshumar'+#13+
'FINANCIAL=Financial'+#13+
'OTHER=Doosre'+#13+
'TEECHART GALLERY=Teechart Gallery'+#13+
'CONNECTING LINES=Joorti Hui Lakeerein'+#13+
'REDUCTION=Kam Karna'+#13+
'LIGHT=Rooshni'+#13+
'INTENSITY=Intensity'+#13+
'FONT OUTLINES=Font Outlines'+#13+
'SMOOTH SHADING=Smooth shading'+#13+
'AMBIENT LIGHT=Ambient roshni'+#13+
'MOUSE ACTION=Chohe ka action'+#13+
'CLOCKWISE=Clockwise'+#13+
'ANGLE INCREMENT=Darje mein izzaffa'+#13+
'RADIUS INCREMENT=Qutur mein izaafa'+#13+
'PRINTER=Printer'+#13+
'SETUP=Setup'+#13+
'ORIENTATION=Orientation'+#13+
'PORTRAIT=Portrait'+#13+
'LANDSCAPE=Landscape'+#13+
'MARGINS (%)=Hashie (%)'+#13+
'MARGINS=Hashie'+#13+
'DETAIL=Tafseel'+#13+
'MORE=Aur'+#13+
'PROPORTIONAL=Proportional'+#13+
'VIEW MARGINS=Hashie deekhna'+#13+
'RESET MARGINS=Reset Hashie'+#13+
'PRINT=Print'+#13+
'TEEPREVIEW EDITOR=TEEPREVIEW EDITOR'+#13+
'ALLOW MOVE=Move ki ijaazat'+#13+
'ALLOW RESIZE=Resize ki ijaazat'+#13+
'SHOW IMAGE=Tasveer Kekhana'+#13+
'DRAG IMAGE=Tasveer Khhenchna'+#13+
'AS BITMAP=As Bitmap'+#13+
'SIZE %=Size %'+#13+
'FIELDS=Fields'+#13+
'SOURCE=Source'+#13+
'SEPARATOR=Separator'+#13+
'NUMBER OF HEADER LINES=Headlines ki taadad'+#13+
'COMMA=Comma'+#13+
'EDITING=ESaheh karna'+#13+
'TAB=Tab'+#13+
'SPACE=Jugga'+#13+
'ROUND RECTANGLE=Gool rectangle'+#13+
'BOTTOM=Neeche'+#13+
'RIGHT=Dain'+#13+
'C PEN=C Kalam'+#13+
'R PEN=R Kalam'+#13+
'C LABELS=C Naam'+#13+
'R LABELS=R Naam'+#13+
'MULTIPLE BAR=Baut se bar'+#13+
'MULTIPLE AREAS=Bhaut se jugghein'+#13+
'STACK GROUP=Stack Group'+#13+
'BOTH=Doonon'+#13+
'BACK DIAGONAL=Peeche Diagnol'+#13+
'B.DIAGONAL=B. Diagnol'+#13+
'DIAG.CROSS=Diag. Cross'+#13+
'WHISKER=Whisker'+#13+
'CROSS=Kanta'+#13+
'DIAGONAL CROSS=Diagnol Kanta'+#13+
'LEFT RIGHT=Bain Dain'+#13+
'RIGHT LEFT=Dain Bain'+#13+
'FROM CENTER=Dermain se'+#13+
'FROM TOP LEFT=Ooper Bain se'+#13+
'FROM BOTTOM LEFT=Neeche Bain se'+#13+
'SHOW WEEKDAYS=Hafte kie din dikhao'+#13+
'SHOW MONTHS=Ver Meses'+#13+
'SHOW PREVIOUS BUTTON=Pechla button dikhao'#13+
'SHOW NEXT BUTTON=Aglaa button Dikhao'#13+
'TRAILING DAYS=Trailing Din'+#13+
'SHOW TODAY=Aaj ka din Dikhao'+#13+
'TRAILING=trailing'+#13+
'LOWERED=neeche kia hua'+#13+
'RAISED=Ubhra hua'+#13+
'HORIZ. OFFSET=Horiz. offset.'+#13+
'VERT. OFFSET=Vert. Offset.'+#13+
'INNER=Andruni'+#13+
'LEN=LEN'+#13+
'AT LABELS ONLY=Siraf Namoon pe'+#13+
'MAXIMUM=Ziada se ziada'+#13+
'MINIMUM=Kam se kam'+#13+
'CHANGE=Tabdeel'+#13+
'LOGARITHMIC=Logaríthmic'+#13+
'LOG BASE=Log base'+#13+
'DESIRED INCREMENT=Passendedah izaafa'+#13+
'(INCREMENT)=(Izaafa)'+#13+
'MULTI-LINE=Bahut-se-lakeerien'+#13+
'MULTI LINE=Bahut se lakeerien'+#13+
'RESIZE CHART=Nuqshe ko resize karna'+#13+
'X AND PERCENT=X aur fisad'+#13+
'X AND VALUE=X y aur value'+#13+
'RIGHT PERCENT=Dain Fisad'+#13+
'LEFT PERCENT=Bain Fisad'+#13+
'LEFT VALUE=Bain Vlaue'+#13+
'RIGHT VALUE=Dain Value'+#13+
'PLAIN=plain'+#13+
'LAST VALUES=Aakhri value'+#13+
'SERIES VALUES=Kist Values'+#13+
'SERIES NAMES=Kist Naam'+#13+
'NEW=Nea'+#13+
'EDIT=Saheh karne wala'+#13+
'PANEL COLOR=Panel rang'+#13+
'TOP BOTTOM=Ooncha Neecha'+#13+
'BOTTOM TOP=Neecha Ooncha'+#13+
'DEFAULT ALIGNMENT=Default Alignment'+#13+
'EXPONENTIAL=Exponential'+#13+
'LABELS FORMAT=Namoon ka format'+#13+
'MIN. SEPARATION %=Min. Separation %'+#13+
'YEAR=ASaal'+#13+
'MONTH=Maheena'+#13+
'WEEK=Hafta'+#13+
'WEEKDAY=Haftee ke Din'+#13+
'MARK=Nishaan'+#13+
'ROUND FIRST=Pehla Round'+#13+
'LABEL ON AXIS=Axis ka naam'+#13+
'COUNT=Ginti'+#13+
'POSITION %=Position %'+#13+
'START %=Shurro %'+#13+
'END %=Khattam %'+#13+
'OTHER SIDE=Doosri taraf'+#13+
'INTER-CHAR SPACING=Inter-char waqfa'+#13+
'VERT. SPACING=Vert. Waqfa'+#13+
'POSITION OFFSET %=Position offset %'+#13+
'GENERAL=Aam'+#13+
'MANUAL=Hathon se'+#13+
'PERSISTENT=Persistent'+#13+
'PANEL=Panel'+#13+
'ALIAS=Alias'+#13+
'2D=2D'+#13+
'ADX=ADX'+#13+
'BOLLINGER=Bollinger'+#13+
'TEEOPENGL EDITOR=TEEOPENGL saheh karne wala'+#13+
'FONT 3D DEPTH=font 3D Gehrahi'+#13+
'NORMAL=Normal'+#13+
'TEEFONT EDITOR=TEEFONT Saheh karne wala'+#13+
'CLIP POINTS=Clip Nuqtee'+#13+
'CLIPPED=Clipped'+#13+
'3D %=3D %'+#13+
'QUANTIZE=Quantize'+#13+
'QUANTIZE 256=Quantize 256'+#13+
'DITHER=Dither'+#13+
'VERTICAL SMALL=Vertical Choota'+#13+
'HORIZ. SMALL=Horizontal Choota'+#13+
'DIAG. SMALL=Diagonal Choota'+#13+
'BACK DIAG. SMALL=Pechla Diagonal Choota'+#13+
'DIAG. CROSS SMALL=Diagonal Kanta Choota'+#13+
'MINIMUM PIXELS=Kam se kam pixels'+#13+
'ALLOW SCROLL=Scroll ki ijaazat'+#13+
'SWAP=Tabdeel Karna'+#13+
'GRADIENT EDITOR=Gradient saheh karne wala'+#13+
'TEXT STYLE=Likhai ka style'+#13+
'DIVIDING LINES=Taqseem karnee wali lakeerien'+#13+
'SYMBOLS=Nishaan'+#13+
'CHECK BOXES=Check wale baksee'+#13+
'FONT SERIES COLOR=Font kist ke rang'+#13+
'LEGEND STYLE=Legend style'+#13+
'POINTS PER PAGE=Nuqte fi saffah'+#13+
'SCALE LAST PAGE=Scale aakhri safah'+#13+
'CURRENT PAGE LEGEND=Moojoda safah legend'+#13+
'BACKGROUND=Backgroung'+#13+
'BACK IMAGE=Pichli tasveer'+#13+
'STRETCH=Kheenchna'+#13+
'TILE=Unwaan'+#13+
'BORDERS=Hasiee'+#13+
'CALCULATE EVERY=Calculate her aik'+#13+
'NUMBER OF POINTS=Nuqtoon ke number'+#13+
'RANGE OF VALUES=Values ke range'+#13+
'FIRST=Pehla'+#13+
'LAST=Aakhri'+#13+
'ALL POINTS=Saree Nuqtee'+#13+
'DATA SOURCE=Data Source'+#13+
'WALLS=Deewarain'+#13+
'PAGING=Pagina'+#13+
'CLONE=Clone'+#13+
'TITLES=Unwaan'+#13+
'TOOLS=Hathiar'+#13+
'EXPORT=Bahir Bheejna'+#13+
'CHART=Hashia'+#13+
'BACK=Pechla'+#13+
'LEFT AND RIGHT=Bain aur Dain'+#13+
'SELECT A CHART STYLE=Nuqshe ka style muntakhib karna'+#13+
'SELECT A DATABASE TABLE=Database meez ko muntakhib karna '+#13+
'TABLE=Meez'+#13+
'SELECT THE DESIRED FIELDS TO CHART=Passendeedah fields nuqshe ke muntakhib karna'+#13+
'SELECT A TEXT LABELS FIELD=Passendeedah likhai ke naam muntakhib karna'+#13+
'CHOOSE THE DESIRED CHART TYPE=Passendeedah nuqshee ki type muntakhib karna'+#13+
'CHART PREVIEW=Nuqshee ka preview'+#13+
'SHOW LEGEND=Legend ko dikhao'+#13+
'SHOW MARKS=Nishaan Dikhao'+#13+
'FINISH=Khattam'+#13+
'RANDOM=Random'+#13+
'DRAW EVERY=Her aik draw'+#13+
'ARROWS=Teer'+#13+
'ASCENDING=Ascending'+#13+
'DESCENDING=Descending'+#13+
'VERTICAL AXIS=Vertical Axis'+#13+
'DATETIME=Tareekhwaqt'+#13+
'TOP AND BOTTOM=ooncha aur Neecha'+#13+
'HORIZONTAL AXIS=Horizontal Axis'+#13+
'PERCENTS=Fisad'+#13+
'VALUES=Values'+#13+
'FORMATS=Formats'+#13+
'SHOW IN LEGEND=Legend ko dikhao'+#13+
'SORT=Sort'+#13+
'MARKS=Nishaan'+#13+
'BEVEL INNER=Bevel Androoni'+#13+
'BEVEL OUTER=Bevel Berooni'+#13+
'PANEL EDITOR=Panel ko saheh karne wala'+#13+
'CONTINUOUS=Lagataar'+#13+
'HORIZ. ALIGNMENT=Horiz. Alighnment'+#13+
'EXPORT CHART=Nuqsha bahir bheejna'+#13+
'BELOW %=Neeche %'+#13+
'BELOW VALUE=Neeche ki value'+#13+
'NEAREST POINT=Nazdeek tareen nuqta'+#13+
'DRAG MARKS=Nishanoon ko kheenchna'+#13+
'TEECHART PRINT PREVIEW=TEECHART print preview'+#13+
'X VALUE=Value X'+#13+
'X AND Y VALUES=X aur Y values'+#13+
'SHININESS=Shininess'+#13+
'ALL SERIES VISIBLE=Tammam kist dikhai deene wali'+#13+
'MARGIN=Hashiee'+#13+
'DIAGONAL=Diagonal'+#13+
'LEFT TOP=Bain Ooncha'+#13+
'LEFT BOTTOM=Bain Neecha'+#13+
'RIGHT TOP=Dain Oonchaa'+#13+
'RIGHT BOTTOM=Dain Neecha'+#13+
'EXACT DATE TIME=Saheh tareekh waqt'+#13+
'RECT. GRADIENT=Rect. Gradient'+#13+
'CROSS SMALL=Kanta choota'+#13+
'AVG=Aust'+#13+
'FUNCTION=Function'+#13+
'AUTO=Khudbukhud'+#13+
'ONE MILLISECOND=aik milisecond'+#13+
'ONE SECOND=aik SECOND'+#13+
'FIVE SECONDS=Paanch SECOND'+#13+
'TEN SECONDS=Das SECOND'+#13+
'FIFTEEN SECONDS=Pundharan SECONDS'+#13+
'THIRTY SECONDS=Tees SECONDS'+#13+
'ONE MINUTE=aik MINUTE'+#13+
'FIVE MINUTES=Paanch MINUTE'+#13+
'TEN MINUTES=Das MINUTE'+#13+
'FIFTEEN MINUTES=Pundharan  MINUTE'+#13+
'THIRTY MINUTES=Tees MINUTE'+#13+
'TWO HOURS=Do Ghentee'+#13+
'SIX HOURS=cheh Ghentee'+#13+
'TWELVE HOURS=Barah Ghentee'+#13+
'ONE DAY=aik din'+#13+
'TWO DAYS=Do din'+#13+
'THREE DAYS=Teen din'+#13+
'ONE WEEK=aik hafta'+#13+
'HALF MONTH=Aadha maheena'+#13+
'ONE MONTH=aik maheena'+#13+
'TWO MONTHS=Do maheene'+#13+
'THREE MONTHS=Teen maheene'+#13+
'FOUR MONTHS=Char maheene'+#13+
'SIX MONTHS=Cheh maheena'+#13+
'IRREGULAR=betarteeb'+#13+
'CLICKABLE=Clickable'+#13+
'ROUND=Gool'+#13+
'FLAT=Humwar'+#13+
'PIE=Pastel'+#13+
'HORIZ. BAR=Bar Horiz.'+#13+
'BUBBLE=Bulbula'+#13+
'SHAPE=Jissamat'+#13+
'POINT=Nuqtee'+#13+
'FAST LINE=Teez lakeer'+#13+
'CANDLE=Moombatti'+#13+
'VOLUME=Hujjam'+#13+
'HORIZ LINE=Hiriz. Lakeer'+#13+
'SURFACE=Suttah'+#13+
'LEFT AXIS=Bain Axis'+#13+
'RIGHT AXIS=Dain Axis'+#13+
'TOP AXIS=ooper axis'+#13+
'BOTTOM AXIS=Neeche Axis'+#13+
'CHANGE SERIES TITLE=Kist ka Unwaan badalna'+#13+
'DELETE %S ?=Mittana %s ?'+#13+
'DESIRED %S INCREMENT=Passendeedah %S ziada karna'+#13+
'INCORRECT VALUE. REASON: %S=Ghult value ki wajah: %s'+#13+
'FillSampleValues NumValues must be > 0=FillSampleValues. Hindsoon ki value sifar se ziada hooni chahiyee > 0.'#13+
'VISIT OUR WEB SITE !=Hamaari web site pe tashreef layiyee !'#13+
'SHOW PAGE NUMBER=Saffah number dikhao'#13+
'PAGE NUMBER=Safah number'#13+
'PAGE %D OF %D=Páge %d ki %d'#13+
'TEECHART LANGUAGES=TeeChart ki zubannein '#13+
'CHOOSE A LANGUAGE=Zubban Muntakhib karo '+#13+
'SELECT ALL=Sara select karo '#13+
'MOVE UP=Ooper Jao'#13+
'MOVE DOWN=Neeche Jao'#13+
'DRAW ALL=Sara draw karo '#13+
'TEXT FILE=Text ki file'#13+
'IMAG. SYMBOL=Tasveer ka nishaan'#13+
'DRAG REPAINT=Kheench ke dobara paint'#13+
'NO LIMIT DRAG=Koi Hudd Nahein'#13+
'AVAILABLE LANGUAGES=Mojud zubanein'#13+
'PERIOD=Period'#13+
'FILL 80%=Bharo 80%'#13+
'FILL 60%=Bharo 60%'#13+
'FILL 40%=Bharo 40%'#13+
'FILL 20%=Bharo 20%'#13+
'FILL 10%=Bharo 10%'#13+
'ZIG ZAG=Terrimerri'#13+
'IGNORE NULLS=Null ko chor do'#13+
'LIGHT 0=Hulka 0'#13+
'LIGHT 1=Hulka 1'#13+
'LIGHT 2=Hulka 2'#13+
'DRAW STYLE=Draw ka tareeka'#13+
'POINTS=Nuqtee'#13+
'EXPORT DIALOG=Dialog ko bahir bheejna'#13+
'POINT COLORS=Nuqtoon ke rang'#13+
'OUTLINE GRADIENT=Bahir ka gradient'#13+
'GAUGES=Gauges'#13+
'RADIAL=Radial'#13+
'RADIAL OFFSET=Radial Offset'#13+
'SHADOW EDITOR=Saiyee ka sahih karne wala'#13+
'3D GRID TRANSPOSE=3D Jalli transpose'#13+
'EXTRA LEGEND=Faltu legend'#13+
'GANTT DRAG=Gantt ko Kheenchna'#13+
'GRID BAND TOOL=Jalli ka band tool'#13+
'SERIES ANIMATION=Kist ki animation'#13+
'UP=Ooper'#13+
'DOWN=Neeche'#13+
'CALLOUT=Callout'#13+
'TEXT ALIGNMENT=Likhai ki alignment'#13+
'DISTANCE=Faasla'#13+
'ARROW HEAD=Teer ka sar'#13+
'POINTER=Pointer'#13+
'CALCULATE USING=Hissab karo is ko istaamal kar ke'#13+
'EVERY NUMBER OF POINTS=Saray Number'#13+
'EVERY RANGE=Sarry Range'#13+
'INCLUDE NULL VALUES=Null value ko shaamil karo'#13+
'DATE=Tareekh'#13+
'ENTER DATE=Tareekh ka indraaj'#13+
'ENTER TIME=Waqt ka indiraaj'#13+
'CYLINDER=Cylinder'#13+
'DEVIATION=Badulna'#13+
'UPPER=Ooper wala'#13+
'LOWER=Neeche wala'#13+
'CONSTANT=Constant'#13+
'SHOW LABELS=Unwaan Dhikao'#13+
'SHOW COLORS=Rang dhikao'#13+
'XYZ SERIES=XYZ kist'#13+
'SHOW X VALUES=X values dhikao X'#13+
'ACCUMULATE=Jumma Karna'#13+
'SMOOTH=Naram'#13+
'INTERPOLATE=Interpolate'#13+
'START X=Shurooh X'#13+
'STEP=serhi'#13+
'NUM. POINTS=Num. Nuqte'#13+
'COLOR EACH LINE=Her lakeer ko rang karna'#13+
'SORT BY=Sort is per por'#13+
'CALCULATION=Hissab karna'#13+
'GROUP=Group'#13+
'WEIGHT=Wazan'#13+
'EDIT LEGEND=Legend ko sahih karna'#13+
'OFFSET=Desplaz.'#13+
'DEFAULT BORDER=Shurooh ka Haashia'#13+
'SEPARATION=Alaidgi'#13+
'ROUND BORDER=Gool Haashia'#13+
'NUMBER OF SAMPLE VALUES=Missali values ka number'#13+
'DIF. LIMIT=DIF. Hudd'#13+
'RESIZE PIXELS TOLERANCE=Dobara Pixel tolerance'#13+
'FULL REPAINT=Pura dobara rang'#13+
'END POINT=Akhri Nuqta'#13+
'BAND 1=Band 1'#13+
'BAND 2=Band 2'#13+
'TRANSPOSE NOW=Transpose abhi'#13+
'NOTHING=Kuch Nahein'#13+
'LEFT TRIANGLE=Bain Traiangle'#13+
'RIGHT TRIANGLE=Seedha Triangle.'#13+
'PERIOD 1=Pehla Periodo '#13+
'PERIOD 2=Doosra Periodo'#13+
'PERIOD 3=Teesra Period'#13+
'HISTOGRAM=Tareekhinuqsha'#13+
'EXP. LINE=EXP. lakeer'#13+
'WEIGHTED=Wazan ki hoi'#13+
'WEIGHTED BY INDEX=wazan ki index'#13+
'BOX SIZE=Bukse ka size'#13+
'REVERSAL AMOUNT=Ulti keemat'#13+
'PERCENTAGE=Fi sud'#13+
'COMPLETE R.M.S.=RMS complete'#13+
'BUTTON=Buttonn'#13+
'ALL=Sub'#13+
'START AT MIN. VALUE=Sub se choti value se shurroo kare.'#13+
'EXECUTE !=Mukkamul !'#13+
'WEB URL=Web URL'#13+
'SELF STACK=Khudhe stack'#13+
'SIDE LINES=Itraaf ki lakeeren'#13+
'COVER=Cover'#13+
'VALUE SOURCE=Value ka zaria'#13+

// 6.0
'BEVEL SIZE=BevelSize'#13+
'DELETE ROW=Row khuttam karna'#13+
'VOLUME SERIES=Volume Kist'#13+
'SINGLE=Akeela'#13+
'REMOVE CUSTOM COLORS=Rang khatem karna'#13+
'USE PALETTE MINIMUM=Istamaal karo Palette kum se kum'#13+
'AXIS MAXIMUM=Axis Ziada se ziada'#13+
'AXIS CENTER=Axis Center'#13+
'AXIS MINIMUM=Axis Kum se kum'#13+
'DAILY (NONE)=Roozana'#13+
'WEEKLY=Huftawar'#13+
'MONTHLY=Mahana'#13+
'BI-MONTHLY=Maheene me do bar'#13+
'QUARTERLY=Sehmahi'#13+
'YEARLY=Saalana'#13+
'DATETIME PERIOD=TareekhWaqt period'#13+
'CASE SENSITIVE=Case Hassas'#13+
'DRAG STYLE=Kheenchne ka style'#13+
'SQUARED=Cuadrado'#13+
'GRID 3D SERIES=Jaali ki kist 3D'#13+
'DARK BORDER=Gehra Border'#13+
'PIE SERIES=Pie Kist'#13+
'FOCUS=Focus'#13+
'EXPLODE=Tabbah hoona'#13+
'FACTOR=Factor'#13+
'CHART FROM TEMPLATE (*.TEE FILE)=Nuqsha template se (*.tee)'#13+
'OPEN TEECHART TEMPLATE FILE FROM=TeeChart ki template file se kholna'#13+
'BINARY=Binary'#13+
'VOLUME OSCILLATOR=Oscillator Volume'#13+
'PIE SLICES=Pie ke tukree'#13+
'ARROW WIDTH=Teer ki Chorahi'#13+
'ARROW HEIGHT=Teer ki Unchai'#13+
'DEFAULT COLOR=Shoorah ke Rang'#13+
'BALANCE=Baqaia'
;
  end;
end;

Procedure TeeSetUrdu;
begin
  TeeCreateUrdu;
  TeeLanguage:=TeeUrduLanguage;
  TeeUrduConstants;
end;

initialization
finalization
  FreeAndNil(TeeUrduLanguage);
end.

