CREATE TABLE [dbo].[TeShuYangTzsTmp] (
	[prj_no] [varchar] (18) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[stra_no] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[sub_no] [varchar] (4) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[v_id] [char] (1) COLLATE Chinese_PRC_CI_AS NULL ,
	[gygj_pc] [decimal](8, 1) NULL ,
	[gygj_cc] [decimal](8, 4) NULL ,
	[gygj_cs] [decimal](8, 4) NULL ,
	[html] [decimal](8, 1) NULL ,
	[gjxs50_1] [decimal](8, 3) NULL ,
	[gjxs100_1] [decimal](8, 3) NULL ,
	[gjxs200_1] [decimal](8, 3) NULL ,
	[gjxs400_1] [decimal](8, 3) NULL ,
	[gjxs50_2] [decimal](8, 3) NULL ,
	[gjxs100_2] [decimal](8, 3) NULL ,
	[gjxs200_2] [decimal](8, 3) NULL ,
	[gjxs400_2] [decimal](8, 3) NULL ,
	[jcxs_v_005_01] [decimal](8, 2) NULL ,
	[jcxs_v_01_02] [decimal](8, 2) NULL ,
	[jcxs_v_02_04] [decimal](8, 2) NULL ,
	[jcxs_h_005_01] [decimal](8, 2) NULL ,
	[jcxs_h_01_02] [decimal](8, 2) NULL ,
	[jcxs_h_02_04] [decimal](8, 2) NULL ,
	[jzcylxs] [decimal](8, 3) NULL ,
	[wcxkyqd_yz] [decimal](8, 1) NULL ,
	[wcxkyqd_cs] [decimal](8, 1) NULL ,
	[wcxkyqd_lmd] [decimal](8, 2) NULL ,
	[szsy_syff] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL ,
	[szsy_zyl_njl_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_njl_cu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_cu] [decimal](8, 1) NULL ,
	[szsy_yxyl_njl] [decimal](8, 1) NULL ,
	[szsy_yxyl_nmcj] [decimal](8, 1) NULL ,
	[stxs_kv] [decimal](18, 9) NULL ,
	[stxs_kh] [decimal](18, 9) NULL ,
	[trpj_g] [int] NULL ,
	[trpj_sx] [int] NULL ,
	[klzc_li] [decimal](8, 1) NULL ,
	[klzc_sha_2_05] [decimal](8, 1) NULL ,
	[klzc_sha_05_025] [decimal](8, 1) NULL ,
	[klzc_sha_025_0075] [decimal](8, 1) NULL ,
	[klzc_fl] [decimal](8, 1) NULL ,
	[klzc_nl] [decimal](8, 1) NULL ,
	[lj_yxlj] [decimal](8, 3) NULL ,
	[lj_pjlj] [decimal](8, 3) NULL ,
	[lj_xzlj] [decimal](8, 3) NULL ,
	[lj_d70] [decimal](8, 3) NULL ,
	[bjyxs] [decimal](8, 2) NULL ,
	[qlxs] [decimal](8, 2) NULL ,
	[beizhu] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL 
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[TeShuYangTmp] (
	[prj_no] [varchar] (18) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[drl_no] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[s_no] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[s_depth_begin] [decimal](8, 2) NULL ,
	[s_depth_end] [decimal](8, 2) NULL ,
	[gygj_pc] [decimal](8, 1) NULL ,
	[gygj_cc] [decimal](8, 4) NULL ,
	[gygj_cs] [decimal](8, 4) NULL ,
	[html] [decimal](8, 1) NULL ,
	[gjxs50_1] [decimal](8, 3) NULL ,
	[gjxs100_1] [decimal](8, 3) NULL ,
	[gjxs200_1] [decimal](8, 3) NULL ,
	[gjxs400_1] [decimal](8, 3) NULL ,
	[gjxs50_2] [decimal](8, 3) NULL ,
	[gjxs100_2] [decimal](8, 3) NULL ,
	[gjxs200_2] [decimal](8, 3) NULL ,
	[gjxs400_2] [decimal](8, 3) NULL ,
	[jcxs_v_005_01] [decimal](8, 2) NULL ,
	[jcxs_v_01_02] [decimal](8, 2) NULL ,
	[jcxs_v_02_04] [decimal](8, 2) NULL ,
	[jcxs_h_005_01] [decimal](8, 2) NULL ,
	[jcxs_h_01_02] [decimal](8, 2) NULL ,
	[jcxs_h_02_04] [decimal](8, 2) NULL ,
	[jzcylxs] [decimal](8, 3) NULL ,
	[wcxkyqd_yz] [decimal](8, 1) NULL ,
	[wcxkyqd_cs] [decimal](8, 1) NULL ,
	[wcxkyqd_lmd] [decimal](8, 2) NULL ,
	[szsy_syff] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL ,
	[szsy_zyl_njl_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_njl_cu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_cu] [decimal](8, 1) NULL ,
	[szsy_yxyl_njl] [decimal](8, 1) NULL ,
	[szsy_yxyl_nmcj] [decimal](8, 1) NULL ,
	[stxs_kv] [decimal](18, 9) NULL ,
	[stxs_kh] [decimal](18, 9) NULL ,
	[trpj_g] [int] NULL ,
	[trpj_sx] [int] NULL ,
	[klzc_li] [decimal](8, 1) NULL ,
	[klzc_sha_2_05] [decimal](8, 1) NULL ,
	[klzc_sha_05_025] [decimal](8, 1) NULL ,
	[klzc_sha_025_0075] [decimal](8, 1) NULL ,
	[klzc_fl] [decimal](8, 1) NULL ,
	[klzc_nl] [decimal](8, 1) NULL ,
	[lj_yxlj] [decimal](8, 3) NULL ,
	[lj_pjlj] [decimal](8, 3) NULL ,
	[lj_xzlj] [decimal](8, 3) NULL ,
	[lj_d70] [decimal](8, 3) NULL ,
	[bjyxs] [decimal](8, 2) NULL ,
	[qlxs] [decimal](8, 2) NULL ,
	[beizhu] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL ,
	[if_statistic] [bit] NULL ,
	[stra_no] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL ,
	[sub_no] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL ,
	[ea_name] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL 
) ON [PRIMARY]
GO


CREATE TABLE [dbo].[TeShuYang] (
	[prj_no] [varchar] (18) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[drl_no] [varchar] (30) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[s_no] [varchar] (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	[s_depth_begin] [decimal](8, 2) NULL ,
	[s_depth_end] [decimal](8, 2) NULL ,
	[gygj_pc] [decimal](8, 1) NULL ,
	[gygj_cc] [decimal](8, 4) NULL ,
	[gygj_cs] [decimal](8, 4) NULL ,
	[html] [decimal](8, 1) NULL ,
	[gjxs50_1] [decimal](8, 3) NULL ,
	[gjxs100_1] [decimal](8, 3) NULL ,
	[gjxs200_1] [decimal](8, 3) NULL ,
	[gjxs400_1] [decimal](8, 3) NULL ,
	[gjxs50_2] [decimal](8, 3) NULL ,
	[gjxs100_2] [decimal](8, 3) NULL ,
	[gjxs200_2] [decimal](8, 3) NULL ,
	[gjxs400_2] [decimal](8, 3) NULL ,
	[jcxs_v_005_01] [decimal](8, 2) NULL ,
	[jcxs_v_01_02] [decimal](8, 2) NULL ,
	[jcxs_v_02_04] [decimal](8, 2) NULL ,
	[jcxs_h_005_01] [decimal](8, 2) NULL ,
	[jcxs_h_01_02] [decimal](8, 2) NULL ,
	[jcxs_h_02_04] [decimal](8, 2) NULL ,
	[jzcylxs] [decimal](8, 3) NULL ,
	[wcxkyqd_yz] [decimal](8, 1) NULL ,
	[wcxkyqd_cs] [decimal](8, 1) NULL ,
	[wcxkyqd_lmd] [decimal](8, 2) NULL ,
	[szsy_syff] [varchar] (2) COLLATE Chinese_PRC_CI_AS NULL ,
	[szsy_zyl_njl_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_uu] [decimal](8, 1) NULL ,
	[szsy_zyl_njl_cu] [decimal](8, 1) NULL ,
	[szsy_zyl_nmcj_cu] [decimal](8, 1) NULL ,
	[szsy_yxyl_njl] [decimal](8, 1) NULL ,
	[szsy_yxyl_nmcj] [decimal](8, 1) NULL ,
	[stxs_kv] [decimal](18, 9) NULL ,
	[stxs_kh] [decimal](18, 9) NULL ,
	[trpj_g] [int] NULL ,
	[trpj_sx] [int] NULL ,
	[klzc_li] [decimal](8, 1) NULL ,
	[klzc_sha_2_05] [decimal](8, 1) NULL ,
	[klzc_sha_05_025] [decimal](8, 1) NULL ,
	[klzc_sha_025_0075] [decimal](8, 1) NULL ,
	[klzc_fl] [decimal](8, 1) NULL ,
	[klzc_nl] [decimal](8, 1) NULL ,
	[lj_yxlj] [decimal](8, 3) NULL ,
	[lj_pjlj] [decimal](8, 3) NULL ,
	[lj_xzlj] [decimal](8, 3) NULL ,
	[lj_d70] [decimal](8, 3) NULL ,
	[bjyxs] [decimal](8, 2) NULL ,
	[qlxs] [decimal](8, 2) NULL ,
	[beizhu] [varchar] (100) COLLATE Chinese_PRC_CI_AS NULL ,
	[if_statistic] [bit] NULL ,
	[stra_no] [varchar] (10) COLLATE Chinese_PRC_CI_AS NULL ,
	[sub_no] [varchar] (4) COLLATE Chinese_PRC_CI_AS NULL ,
	[ea_name] [varchar] (30) COLLATE Chinese_PRC_CI_AS NULL 
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TeShuYang] ADD 
	CONSTRAINT [PK_TeShuYang] PRIMARY KEY  CLUSTERED 
	(
		[prj_no],
		[drl_no],
		[s_no]
	)  ON [PRIMARY] 
GO

ALTER TABLE [dbo].[TeShuYang] ADD 
	CONSTRAINT [FK_TeShuYang_drills] FOREIGN KEY 
	(
		[prj_no],
		[drl_no]
	) REFERENCES [dbo].[drills] (
		[prj_no],
		[drl_no]
	) ON DELETE CASCADE  ON UPDATE CASCADE 
GO

